// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: ocsf/v1_2_0/events/other/other.proto

//go:build !protoopaque

package other

import (
	enums "github.com/valllabh/ocsf-schema-golang/ocsf/v1_2_0/events/other/enums"
	objects "github.com/valllabh/ocsf-schema-golang/ocsf/v1_2_0/objects"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event: other
// Event UID: 0
// URL: https://schema.ocsf.io/1.2.0/classes/base_event
type BaseEvent struct {
	state          protoimpl.MessageState        `protogen:"hybrid.v1"`
	ActivityId     enums.BASE_EVENT_ACTIVITY_ID  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3,enum=ocsf.v1_2_0.events.other.enums.BASE_EVENT_ACTIVITY_ID" json:"activity_id,omitempty"`     // Caption: Activity ID;
	ActivityName   string                        `protobuf:"bytes,2,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`                                                           // Caption: Activity;
	Api            *objects.Api                  `protobuf:"bytes,3,opt,name=api,proto3" json:"api,omitempty"`                                                                                                 // Caption: API Details; Profile: cloud;
	CategoryName   string                        `protobuf:"bytes,4,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`                                                           // Caption: Category;
	CategoryUid    enums.BASE_EVENT_CATEGORY_UID `protobuf:"varint,5,opt,name=category_uid,json=categoryUid,proto3,enum=ocsf.v1_2_0.events.other.enums.BASE_EVENT_CATEGORY_UID" json:"category_uid,omitempty"` // Caption: Category ID;
	ClassName      string                        `protobuf:"bytes,6,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`                                                                    // Caption: Class;
	ClassUid       enums.BASE_EVENT_CLASS_UID    `protobuf:"varint,7,opt,name=class_uid,json=classUid,proto3,enum=ocsf.v1_2_0.events.other.enums.BASE_EVENT_CLASS_UID" json:"class_uid,omitempty"`             // Caption: Class ID;
	Cloud          *objects.Cloud                `protobuf:"bytes,8,opt,name=cloud,proto3" json:"cloud,omitempty"`                                                                                             // Profile: cloud; Caption: Cloud;
	Count          int32                         `protobuf:"varint,9,opt,name=count,proto3" json:"count,omitempty"`                                                                                            // Caption: Count;
	Duration       int32                         `protobuf:"varint,10,opt,name=duration,proto3" json:"duration,omitempty"`                                                                                     // Caption: Duration;
	EndTime        int64                         `protobuf:"varint,11,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                                                                        // Caption: End Time;
	Enrichments    []*objects.Enrichment         `protobuf:"bytes,12,rep,name=enrichments,proto3" json:"enrichments,omitempty"`                                                                                // Caption: Enrichments;
	Message        string                        `protobuf:"bytes,13,opt,name=message,proto3" json:"message,omitempty"`                                                                                        // Caption: Message;
	Metadata       *objects.Metadata             `protobuf:"bytes,14,opt,name=metadata,proto3" json:"metadata,omitempty"`                                                                                      // Caption: Metadata;
	Observables    []*objects.Observable         `protobuf:"bytes,15,rep,name=observables,proto3" json:"observables,omitempty"`                                                                                // Caption: Observables;
	RawData        string                        `protobuf:"bytes,16,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`                                                                         // Caption: Raw Data;
	Severity       string                        `protobuf:"bytes,17,opt,name=severity,proto3" json:"severity,omitempty"`                                                                                      // Caption: Severity;
	SeverityId     enums.BASE_EVENT_SEVERITY_ID  `protobuf:"varint,18,opt,name=severity_id,json=severityId,proto3,enum=ocsf.v1_2_0.events.other.enums.BASE_EVENT_SEVERITY_ID" json:"severity_id,omitempty"`    // Caption: Severity ID;
	StartTime      int64                         `protobuf:"varint,19,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                                                                  // Caption: Start Time;
	Status         string                        `protobuf:"bytes,20,opt,name=status,proto3" json:"status,omitempty"`                                                                                          // Caption: Status;
	StatusCode     string                        `protobuf:"bytes,21,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                                // Caption: Status Code;
	StatusDetail   string                        `protobuf:"bytes,22,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"`                                                          // Caption: Status Details;
	StatusId       enums.BASE_EVENT_STATUS_ID    `protobuf:"varint,23,opt,name=status_id,json=statusId,proto3,enum=ocsf.v1_2_0.events.other.enums.BASE_EVENT_STATUS_ID" json:"status_id,omitempty"`            // Caption: Status ID;
	Time           int64                         `protobuf:"varint,24,opt,name=time,proto3" json:"time,omitempty"`                                                                                             // Caption: Event Time;
	TimezoneOffset int32                         `protobuf:"varint,25,opt,name=timezone_offset,json=timezoneOffset,proto3" json:"timezone_offset,omitempty"`                                                   // Caption: Timezone Offset;
	TypeName       string                        `protobuf:"bytes,26,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`                                                                      // Caption: Type Name;
	TypeUid        int64                         `protobuf:"varint,27,opt,name=type_uid,json=typeUid,proto3" json:"type_uid,omitempty"`                                                                        // Caption: Type ID;
	Unmapped       *structpb.Struct              `protobuf:"bytes,28,opt,name=unmapped,proto3" json:"unmapped,omitempty"`                                                                                      // Caption: Unmapped Data;
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BaseEvent) Reset() {
	*x = BaseEvent{}
	mi := &file_ocsf_v1_2_0_events_other_other_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseEvent) ProtoMessage() {}

func (x *BaseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ocsf_v1_2_0_events_other_other_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BaseEvent) GetActivityId() enums.BASE_EVENT_ACTIVITY_ID {
	if x != nil {
		return x.ActivityId
	}
	return enums.BASE_EVENT_ACTIVITY_ID(0)
}

func (x *BaseEvent) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *BaseEvent) GetApi() *objects.Api {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *BaseEvent) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *BaseEvent) GetCategoryUid() enums.BASE_EVENT_CATEGORY_UID {
	if x != nil {
		return x.CategoryUid
	}
	return enums.BASE_EVENT_CATEGORY_UID(0)
}

func (x *BaseEvent) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *BaseEvent) GetClassUid() enums.BASE_EVENT_CLASS_UID {
	if x != nil {
		return x.ClassUid
	}
	return enums.BASE_EVENT_CLASS_UID(0)
}

func (x *BaseEvent) GetCloud() *objects.Cloud {
	if x != nil {
		return x.Cloud
	}
	return nil
}

func (x *BaseEvent) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BaseEvent) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *BaseEvent) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *BaseEvent) GetEnrichments() []*objects.Enrichment {
	if x != nil {
		return x.Enrichments
	}
	return nil
}

func (x *BaseEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BaseEvent) GetMetadata() *objects.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BaseEvent) GetObservables() []*objects.Observable {
	if x != nil {
		return x.Observables
	}
	return nil
}

func (x *BaseEvent) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *BaseEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *BaseEvent) GetSeverityId() enums.BASE_EVENT_SEVERITY_ID {
	if x != nil {
		return x.SeverityId
	}
	return enums.BASE_EVENT_SEVERITY_ID(0)
}

func (x *BaseEvent) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *BaseEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BaseEvent) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *BaseEvent) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

func (x *BaseEvent) GetStatusId() enums.BASE_EVENT_STATUS_ID {
	if x != nil {
		return x.StatusId
	}
	return enums.BASE_EVENT_STATUS_ID(0)
}

func (x *BaseEvent) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *BaseEvent) GetTimezoneOffset() int32 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

func (x *BaseEvent) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *BaseEvent) GetTypeUid() int64 {
	if x != nil {
		return x.TypeUid
	}
	return 0
}

func (x *BaseEvent) GetUnmapped() *structpb.Struct {
	if x != nil {
		return x.Unmapped
	}
	return nil
}

func (x *BaseEvent) SetActivityId(v enums.BASE_EVENT_ACTIVITY_ID) {
	x.ActivityId = v
}

func (x *BaseEvent) SetActivityName(v string) {
	x.ActivityName = v
}

func (x *BaseEvent) SetApi(v *objects.Api) {
	x.Api = v
}

func (x *BaseEvent) SetCategoryName(v string) {
	x.CategoryName = v
}

func (x *BaseEvent) SetCategoryUid(v enums.BASE_EVENT_CATEGORY_UID) {
	x.CategoryUid = v
}

func (x *BaseEvent) SetClassName(v string) {
	x.ClassName = v
}

func (x *BaseEvent) SetClassUid(v enums.BASE_EVENT_CLASS_UID) {
	x.ClassUid = v
}

func (x *BaseEvent) SetCloud(v *objects.Cloud) {
	x.Cloud = v
}

func (x *BaseEvent) SetCount(v int32) {
	x.Count = v
}

func (x *BaseEvent) SetDuration(v int32) {
	x.Duration = v
}

func (x *BaseEvent) SetEndTime(v int64) {
	x.EndTime = v
}

func (x *BaseEvent) SetEnrichments(v []*objects.Enrichment) {
	x.Enrichments = v
}

func (x *BaseEvent) SetMessage(v string) {
	x.Message = v
}

func (x *BaseEvent) SetMetadata(v *objects.Metadata) {
	x.Metadata = v
}

func (x *BaseEvent) SetObservables(v []*objects.Observable) {
	x.Observables = v
}

func (x *BaseEvent) SetRawData(v string) {
	x.RawData = v
}

func (x *BaseEvent) SetSeverity(v string) {
	x.Severity = v
}

func (x *BaseEvent) SetSeverityId(v enums.BASE_EVENT_SEVERITY_ID) {
	x.SeverityId = v
}

func (x *BaseEvent) SetStartTime(v int64) {
	x.StartTime = v
}

func (x *BaseEvent) SetStatus(v string) {
	x.Status = v
}

func (x *BaseEvent) SetStatusCode(v string) {
	x.StatusCode = v
}

func (x *BaseEvent) SetStatusDetail(v string) {
	x.StatusDetail = v
}

func (x *BaseEvent) SetStatusId(v enums.BASE_EVENT_STATUS_ID) {
	x.StatusId = v
}

func (x *BaseEvent) SetTime(v int64) {
	x.Time = v
}

func (x *BaseEvent) SetTimezoneOffset(v int32) {
	x.TimezoneOffset = v
}

func (x *BaseEvent) SetTypeName(v string) {
	x.TypeName = v
}

func (x *BaseEvent) SetTypeUid(v int64) {
	x.TypeUid = v
}

func (x *BaseEvent) SetUnmapped(v *structpb.Struct) {
	x.Unmapped = v
}

func (x *BaseEvent) HasApi() bool {
	if x == nil {
		return false
	}
	return x.Api != nil
}

func (x *BaseEvent) HasCloud() bool {
	if x == nil {
		return false
	}
	return x.Cloud != nil
}

func (x *BaseEvent) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *BaseEvent) HasUnmapped() bool {
	if x == nil {
		return false
	}
	return x.Unmapped != nil
}

func (x *BaseEvent) ClearApi() {
	x.Api = nil
}

func (x *BaseEvent) ClearCloud() {
	x.Cloud = nil
}

func (x *BaseEvent) ClearMetadata() {
	x.Metadata = nil
}

func (x *BaseEvent) ClearUnmapped() {
	x.Unmapped = nil
}

type BaseEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ActivityId     enums.BASE_EVENT_ACTIVITY_ID
	ActivityName   string
	Api            *objects.Api
	CategoryName   string
	CategoryUid    enums.BASE_EVENT_CATEGORY_UID
	ClassName      string
	ClassUid       enums.BASE_EVENT_CLASS_UID
	Cloud          *objects.Cloud
	Count          int32
	Duration       int32
	EndTime        int64
	Enrichments    []*objects.Enrichment
	Message        string
	Metadata       *objects.Metadata
	Observables    []*objects.Observable
	RawData        string
	Severity       string
	SeverityId     enums.BASE_EVENT_SEVERITY_ID
	StartTime      int64
	Status         string
	StatusCode     string
	StatusDetail   string
	StatusId       enums.BASE_EVENT_STATUS_ID
	Time           int64
	TimezoneOffset int32
	TypeName       string
	TypeUid        int64
	Unmapped       *structpb.Struct
}

func (b0 BaseEvent_builder) Build() *BaseEvent {
	m0 := &BaseEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.ActivityId = b.ActivityId
	x.ActivityName = b.ActivityName
	x.Api = b.Api
	x.CategoryName = b.CategoryName
	x.CategoryUid = b.CategoryUid
	x.ClassName = b.ClassName
	x.ClassUid = b.ClassUid
	x.Cloud = b.Cloud
	x.Count = b.Count
	x.Duration = b.Duration
	x.EndTime = b.EndTime
	x.Enrichments = b.Enrichments
	x.Message = b.Message
	x.Metadata = b.Metadata
	x.Observables = b.Observables
	x.RawData = b.RawData
	x.Severity = b.Severity
	x.SeverityId = b.SeverityId
	x.StartTime = b.StartTime
	x.Status = b.Status
	x.StatusCode = b.StatusCode
	x.StatusDetail = b.StatusDetail
	x.StatusId = b.StatusId
	x.Time = b.Time
	x.TimezoneOffset = b.TimezoneOffset
	x.TypeName = b.TypeName
	x.TypeUid = b.TypeUid
	x.Unmapped = b.Unmapped
	return m0
}

var File_ocsf_v1_2_0_events_other_other_proto protoreflect.FileDescriptor

const file_ocsf_v1_2_0_events_other_other_proto_rawDesc = "" +
	"\n" +
	"$ocsf/v1_2_0/events/other/other.proto\x12\x18ocsf.v1_2_0.events.other\x1a*ocsf/v1_2_0/events/other/enums/enums.proto\x1a!ocsf/v1_2_0/objects/objects.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x8c\n" +
	"\n" +
	"\tBaseEvent\x12W\n" +
	"\vactivity_id\x18\x01 \x01(\x0e26.ocsf.v1_2_0.events.other.enums.BASE_EVENT_ACTIVITY_IDR\n" +
	"activityId\x12#\n" +
	"\ractivity_name\x18\x02 \x01(\tR\factivityName\x12*\n" +
	"\x03api\x18\x03 \x01(\v2\x18.ocsf.v1_2_0.objects.ApiR\x03api\x12#\n" +
	"\rcategory_name\x18\x04 \x01(\tR\fcategoryName\x12Z\n" +
	"\fcategory_uid\x18\x05 \x01(\x0e27.ocsf.v1_2_0.events.other.enums.BASE_EVENT_CATEGORY_UIDR\vcategoryUid\x12\x1d\n" +
	"\n" +
	"class_name\x18\x06 \x01(\tR\tclassName\x12Q\n" +
	"\tclass_uid\x18\a \x01(\x0e24.ocsf.v1_2_0.events.other.enums.BASE_EVENT_CLASS_UIDR\bclassUid\x120\n" +
	"\x05cloud\x18\b \x01(\v2\x1a.ocsf.v1_2_0.objects.CloudR\x05cloud\x12\x14\n" +
	"\x05count\x18\t \x01(\x05R\x05count\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\x05R\bduration\x12\x19\n" +
	"\bend_time\x18\v \x01(\x03R\aendTime\x12A\n" +
	"\venrichments\x18\f \x03(\v2\x1f.ocsf.v1_2_0.objects.EnrichmentR\venrichments\x12\x18\n" +
	"\amessage\x18\r \x01(\tR\amessage\x129\n" +
	"\bmetadata\x18\x0e \x01(\v2\x1d.ocsf.v1_2_0.objects.MetadataR\bmetadata\x12A\n" +
	"\vobservables\x18\x0f \x03(\v2\x1f.ocsf.v1_2_0.objects.ObservableR\vobservables\x12\x19\n" +
	"\braw_data\x18\x10 \x01(\tR\arawData\x12\x1a\n" +
	"\bseverity\x18\x11 \x01(\tR\bseverity\x12W\n" +
	"\vseverity_id\x18\x12 \x01(\x0e26.ocsf.v1_2_0.events.other.enums.BASE_EVENT_SEVERITY_IDR\n" +
	"severityId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x13 \x01(\x03R\tstartTime\x12\x16\n" +
	"\x06status\x18\x14 \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18\x15 \x01(\tR\n" +
	"statusCode\x12#\n" +
	"\rstatus_detail\x18\x16 \x01(\tR\fstatusDetail\x12Q\n" +
	"\tstatus_id\x18\x17 \x01(\x0e24.ocsf.v1_2_0.events.other.enums.BASE_EVENT_STATUS_IDR\bstatusId\x12\x12\n" +
	"\x04time\x18\x18 \x01(\x03R\x04time\x12'\n" +
	"\x0ftimezone_offset\x18\x19 \x01(\x05R\x0etimezoneOffset\x12\x1b\n" +
	"\ttype_name\x18\x1a \x01(\tR\btypeName\x12\x19\n" +
	"\btype_uid\x18\x1b \x01(\x03R\atypeUid\x123\n" +
	"\bunmapped\x18\x1c \x01(\v2\x17.google.protobuf.StructR\bunmappedB\xe7\x01\n" +
	"\x1ccom.ocsf.v1_2_0.events.otherB\n" +
	"OtherProtoP\x01Z?github.com/valllabh/ocsf-schema-golang/ocsf/v1_2_0/events/other\xa2\x02\x04OVEO\xaa\x02\x16Ocsf.V120.Events.Other\xca\x02\x16Ocsf\\V120\\Events\\Other\xe2\x02\"Ocsf\\V120\\Events\\Other\\GPBMetadata\xea\x02\x19Ocsf::V120::Events::Otherb\x06proto3"

var file_ocsf_v1_2_0_events_other_other_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ocsf_v1_2_0_events_other_other_proto_goTypes = []any{
	(*BaseEvent)(nil),                  // 0: ocsf.v1_2_0.events.other.BaseEvent
	(enums.BASE_EVENT_ACTIVITY_ID)(0),  // 1: ocsf.v1_2_0.events.other.enums.BASE_EVENT_ACTIVITY_ID
	(*objects.Api)(nil),                // 2: ocsf.v1_2_0.objects.Api
	(enums.BASE_EVENT_CATEGORY_UID)(0), // 3: ocsf.v1_2_0.events.other.enums.BASE_EVENT_CATEGORY_UID
	(enums.BASE_EVENT_CLASS_UID)(0),    // 4: ocsf.v1_2_0.events.other.enums.BASE_EVENT_CLASS_UID
	(*objects.Cloud)(nil),              // 5: ocsf.v1_2_0.objects.Cloud
	(*objects.Enrichment)(nil),         // 6: ocsf.v1_2_0.objects.Enrichment
	(*objects.Metadata)(nil),           // 7: ocsf.v1_2_0.objects.Metadata
	(*objects.Observable)(nil),         // 8: ocsf.v1_2_0.objects.Observable
	(enums.BASE_EVENT_SEVERITY_ID)(0),  // 9: ocsf.v1_2_0.events.other.enums.BASE_EVENT_SEVERITY_ID
	(enums.BASE_EVENT_STATUS_ID)(0),    // 10: ocsf.v1_2_0.events.other.enums.BASE_EVENT_STATUS_ID
	(*structpb.Struct)(nil),            // 11: google.protobuf.Struct
}
var file_ocsf_v1_2_0_events_other_other_proto_depIdxs = []int32{
	1,  // 0: ocsf.v1_2_0.events.other.BaseEvent.activity_id:type_name -> ocsf.v1_2_0.events.other.enums.BASE_EVENT_ACTIVITY_ID
	2,  // 1: ocsf.v1_2_0.events.other.BaseEvent.api:type_name -> ocsf.v1_2_0.objects.Api
	3,  // 2: ocsf.v1_2_0.events.other.BaseEvent.category_uid:type_name -> ocsf.v1_2_0.events.other.enums.BASE_EVENT_CATEGORY_UID
	4,  // 3: ocsf.v1_2_0.events.other.BaseEvent.class_uid:type_name -> ocsf.v1_2_0.events.other.enums.BASE_EVENT_CLASS_UID
	5,  // 4: ocsf.v1_2_0.events.other.BaseEvent.cloud:type_name -> ocsf.v1_2_0.objects.Cloud
	6,  // 5: ocsf.v1_2_0.events.other.BaseEvent.enrichments:type_name -> ocsf.v1_2_0.objects.Enrichment
	7,  // 6: ocsf.v1_2_0.events.other.BaseEvent.metadata:type_name -> ocsf.v1_2_0.objects.Metadata
	8,  // 7: ocsf.v1_2_0.events.other.BaseEvent.observables:type_name -> ocsf.v1_2_0.objects.Observable
	9,  // 8: ocsf.v1_2_0.events.other.BaseEvent.severity_id:type_name -> ocsf.v1_2_0.events.other.enums.BASE_EVENT_SEVERITY_ID
	10, // 9: ocsf.v1_2_0.events.other.BaseEvent.status_id:type_name -> ocsf.v1_2_0.events.other.enums.BASE_EVENT_STATUS_ID
	11, // 10: ocsf.v1_2_0.events.other.BaseEvent.unmapped:type_name -> google.protobuf.Struct
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ocsf_v1_2_0_events_other_other_proto_init() }
func file_ocsf_v1_2_0_events_other_other_proto_init() {
	if File_ocsf_v1_2_0_events_other_other_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocsf_v1_2_0_events_other_other_proto_rawDesc), len(file_ocsf_v1_2_0_events_other_other_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocsf_v1_2_0_events_other_other_proto_goTypes,
		DependencyIndexes: file_ocsf_v1_2_0_events_other_other_proto_depIdxs,
		MessageInfos:      file_ocsf_v1_2_0_events_other_other_proto_msgTypes,
	}.Build()
	File_ocsf_v1_2_0_events_other_other_proto = out.File
	file_ocsf_v1_2_0_events_other_other_proto_goTypes = nil
	file_ocsf_v1_2_0_events_other_other_proto_depIdxs = nil
}
