syntax = "proto3";

package ocsf.v1_6_0.events.findings;

option go_package = "/ocsf/v1_6_0/events/findings";

option java_package = "com.your.project.generated.ocsf.v1_6_0.events.findings";

option java_multiple_files = true;

import "ocsf/v1_6_0/events/application/application.proto";

import "ocsf/v1_6_0/events/findings/enums/enums.proto";

import "ocsf/v1_6_0/objects/objects.proto";

import "google/protobuf/struct.proto";

// Event: findings
// Event UID: 7
// URL: https://schema.ocsf.io/1.6.0/classes/application_security_posture_finding
message ApplicationSecurityPostureFinding {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.APPLICATION_SECURITY_POSTURE_FINDING_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.APPLICATION_SECURITY_POSTURE_FINDING_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_6_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_6_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	ocsf.v1_6_0.events.application.Application application = 7; // Caption: Application;
	ocsf.v1_6_0.objects.User assignee = 8; // Caption: Assignee; Profile: incident;
	ocsf.v1_6_0.objects.Group assignee_group = 9; // Caption: Assignee Group; Profile: incident;
	repeated ocsf.v1_6_0.objects.Attack attacks = 10; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_6_0.objects.Authorization authorizations = 11; // Caption: Authorization Information; Profile: security_control;
	string category_name = 12; // Caption: Category;
	ocsf.v1_6_0.events.findings.enums.APPLICATION_SECURITY_POSTURE_FINDING_CATEGORY_UID category_uid = 13; // Caption: Category ID;
	string class_name = 14; // Caption: Class;
	ocsf.v1_6_0.events.findings.enums.APPLICATION_SECURITY_POSTURE_FINDING_CLASS_UID class_uid = 15; // Caption: Class ID;
	ocsf.v1_6_0.objects.Cloud cloud = 16; // Caption: Cloud; Profile: cloud;
	string comment = 17; // Caption: Comment;
	ocsf.v1_6_0.objects.Compliance compliance = 18; // Caption: Compliance;
	string confidence = 19; // Caption: Confidence;
	ocsf.v1_6_0.events.findings.enums.APPLICATION_SECURITY_POSTURE_FINDING_CONFIDENCE_ID confidence_id = 20; // Caption: Confidence ID;
	int32 confidence_score = 21; // Caption: Confidence Score;
	int32 count = 22; // Caption: Count;
	ocsf.v1_6_0.objects.Device device = 23; // Caption: Device;
	string disposition = 24; // Caption: Disposition; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.APPLICATION_SECURITY_POSTURE_FINDING_DISPOSITION_ID disposition_id = 25; // Caption: Disposition ID; Profile: security_control;
	int64 duration = 26; // Caption: Duration Milliseconds;
	int64 end_time = 27; // Caption: End Time;
	repeated ocsf.v1_6_0.objects.Enrichment enrichments = 28; // Caption: Enrichments;
	ocsf.v1_6_0.objects.FindingInfo finding_info = 29; // Caption: Finding Information;
	ocsf.v1_6_0.objects.FirewallRule firewall_rule = 30; // Caption: Firewall Rule; Profile: security_control;
	string impact = 31; // Caption: Impact; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.APPLICATION_SECURITY_POSTURE_FINDING_IMPACT_ID impact_id = 32; // Caption: Impact ID; Profile: incident;
	int32 impact_score = 33; // Caption: Impact Score; Profile: incident;
	bool is_alert = 34; // Caption: Alert; Profile: security_control;
	bool is_suspected_breach = 35; // Caption: Suspected Breach; Profile: incident;
	repeated ocsf.v1_6_0.objects.Malware malware = 36; // Caption: Malware; Profile: security_control;
	ocsf.v1_6_0.objects.MalwareScanInfo malware_scan_info = 37; // Profile: security_control; Caption: Malware Scan Info;
	string message = 38; // Caption: Message;
	ocsf.v1_6_0.objects.Metadata metadata = 39; // Caption: Metadata;
	repeated ocsf.v1_6_0.objects.Observable observables = 40; // Caption: Observables;
	repeated ocsf.v1_6_0.objects.Osint osint = 41; // Caption: OSINT; Profile: osint;
	ocsf.v1_6_0.objects.Policy policy = 42; // Caption: Policy; Profile: security_control;
	string priority = 43; // Caption: Priority; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.APPLICATION_SECURITY_POSTURE_FINDING_PRIORITY_ID priority_id = 44; // Caption: Priority ID; Profile: incident;
	string raw_data = 45; // Caption: Raw Data;
	ocsf.v1_6_0.objects.Fingerprint raw_data_hash = 46; // Caption: Raw Data Hash;
	int64 raw_data_size = 47; // Caption: Raw Data Size;
	ocsf.v1_6_0.objects.Remediation remediation = 48; // Caption: Remediation Guidance;
	repeated ocsf.v1_6_0.objects.ResourceDetails resources = 49; // Caption: Resources Array;
	string risk_details = 50; // Caption: Risk Details; Profile: security_control;
	string risk_level = 51; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.APPLICATION_SECURITY_POSTURE_FINDING_RISK_LEVEL_ID risk_level_id = 52; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 53; // Profile: security_control; Caption: Risk Score;
	string severity = 54; // Caption: Severity;
	ocsf.v1_6_0.events.findings.enums.APPLICATION_SECURITY_POSTURE_FINDING_SEVERITY_ID severity_id = 55; // Caption: Severity ID;
	string src_url = 56; // Caption: Source URL; Profile: incident;
	int64 start_time = 57; // Caption: Start Time;
	string status = 58; // Caption: Status;
	string status_code = 59; // Caption: Status Code;
	string status_detail = 60; // Caption: Status Detail;
	ocsf.v1_6_0.events.findings.enums.APPLICATION_SECURITY_POSTURE_FINDING_STATUS_ID status_id = 61; // Caption: Status ID;
	ocsf.v1_6_0.objects.Ticket ticket = 62; // Caption: Ticket; Profile: incident;
	repeated ocsf.v1_6_0.objects.Ticket tickets = 63; // Caption: Tickets; Profile: incident;
	int64 time = 64; // Caption: Event Time;
	int32 timezone_offset = 65; // Caption: Timezone Offset;
	string type_name = 66; // Caption: Type Name;
	ocsf.v1_6_0.events.findings.enums.APPLICATION_SECURITY_POSTURE_FINDING_TYPE_UID type_uid = 67; // Caption: Type ID;
	google.protobuf.Struct unmapped = 68; // Caption: Unmapped Data;
	ocsf.v1_6_0.objects.VendorAttributes vendor_attributes = 69; // Caption: Vendor Attributes;
	string verdict = 70; // Caption: Verdict; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.APPLICATION_SECURITY_POSTURE_FINDING_VERDICT_ID verdict_id = 71; // Caption: Verdict ID; Profile: incident;
	repeated ocsf.v1_6_0.objects.Vulnerability vulnerabilities = 72; // Caption: Vulnerabilities;
}

// Event: findings
// Event UID: 3
// URL: https://schema.ocsf.io/1.6.0/classes/compliance_finding
message ComplianceFinding {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.COMPLIANCE_FINDING_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.COMPLIANCE_FINDING_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_6_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_6_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	ocsf.v1_6_0.objects.User assignee = 7; // Caption: Assignee; Profile: incident;
	ocsf.v1_6_0.objects.Group assignee_group = 8; // Profile: incident; Caption: Assignee Group;
	repeated ocsf.v1_6_0.objects.Attack attacks = 9; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_6_0.objects.Authorization authorizations = 10; // Caption: Authorization Information; Profile: security_control;
	string category_name = 11; // Caption: Category;
	ocsf.v1_6_0.events.findings.enums.COMPLIANCE_FINDING_CATEGORY_UID category_uid = 12; // Caption: Category ID;
	string class_name = 13; // Caption: Class;
	ocsf.v1_6_0.events.findings.enums.COMPLIANCE_FINDING_CLASS_UID class_uid = 14; // Caption: Class ID;
	ocsf.v1_6_0.objects.Cloud cloud = 15; // Profile: cloud; Caption: Cloud;
	string comment = 16; // Caption: Comment;
	ocsf.v1_6_0.objects.Compliance compliance = 17; // Caption: Compliance;
	string confidence = 18; // Caption: Confidence;
	ocsf.v1_6_0.events.findings.enums.COMPLIANCE_FINDING_CONFIDENCE_ID confidence_id = 19; // Caption: Confidence ID;
	int32 confidence_score = 20; // Caption: Confidence Score;
	int32 count = 21; // Caption: Count;
	ocsf.v1_6_0.objects.Device device = 22; // Caption: Device;
	string disposition = 23; // Caption: Disposition; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.COMPLIANCE_FINDING_DISPOSITION_ID disposition_id = 24; // Caption: Disposition ID; Profile: security_control;
	int64 duration = 25; // Caption: Duration Milliseconds;
	int64 end_time = 26; // Caption: End Time;
	repeated ocsf.v1_6_0.objects.Enrichment enrichments = 27; // Caption: Enrichments;
	repeated ocsf.v1_6_0.objects.Evidences evidences = 28; // Caption: Evidence Artifacts;
	ocsf.v1_6_0.objects.FindingInfo finding_info = 29; // Caption: Finding Information;
	ocsf.v1_6_0.objects.FirewallRule firewall_rule = 30; // Caption: Firewall Rule; Profile: security_control;
	string impact = 31; // Caption: Impact; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.COMPLIANCE_FINDING_IMPACT_ID impact_id = 32; // Caption: Impact ID; Profile: incident;
	int32 impact_score = 33; // Caption: Impact Score; Profile: incident;
	bool is_alert = 34; // Caption: Alert; Profile: security_control;
	bool is_suspected_breach = 35; // Caption: Suspected Breach; Profile: incident;
	repeated ocsf.v1_6_0.objects.Malware malware = 36; // Caption: Malware; Profile: security_control;
	ocsf.v1_6_0.objects.MalwareScanInfo malware_scan_info = 37; // Caption: Malware Scan Info; Profile: security_control;
	string message = 38; // Caption: Message;
	ocsf.v1_6_0.objects.Metadata metadata = 39; // Caption: Metadata;
	repeated ocsf.v1_6_0.objects.Observable observables = 40; // Caption: Observables;
	repeated ocsf.v1_6_0.objects.Osint osint = 41; // Caption: OSINT; Profile: osint;
	ocsf.v1_6_0.objects.Policy policy = 42; // Caption: Policy; Profile: security_control;
	string priority = 43; // Caption: Priority; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.COMPLIANCE_FINDING_PRIORITY_ID priority_id = 44; // Caption: Priority ID; Profile: incident;
	string raw_data = 45; // Caption: Raw Data;
	ocsf.v1_6_0.objects.Fingerprint raw_data_hash = 46; // Caption: Raw Data Hash;
	int64 raw_data_size = 47; // Caption: Raw Data Size;
	ocsf.v1_6_0.objects.Remediation remediation = 48; // Caption: Remediation Guidance;
	ocsf.v1_6_0.objects.ResourceDetails resource = 49; // Caption: Resource;
	repeated ocsf.v1_6_0.objects.ResourceDetails resources = 50; // Caption: Resources Array;
	string risk_details = 51; // Caption: Risk Details; Profile: security_control;
	string risk_level = 52; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.COMPLIANCE_FINDING_RISK_LEVEL_ID risk_level_id = 53; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 54; // Caption: Risk Score; Profile: security_control;
	string severity = 55; // Caption: Severity;
	ocsf.v1_6_0.events.findings.enums.COMPLIANCE_FINDING_SEVERITY_ID severity_id = 56; // Caption: Severity ID;
	string src_url = 57; // Profile: incident; Caption: Source URL;
	int64 start_time = 58; // Caption: Start Time;
	string status = 59; // Caption: Status;
	string status_code = 60; // Caption: Status Code;
	string status_detail = 61; // Caption: Status Detail;
	ocsf.v1_6_0.events.findings.enums.COMPLIANCE_FINDING_STATUS_ID status_id = 62; // Caption: Status ID;
	ocsf.v1_6_0.objects.Ticket ticket = 63; // Caption: Ticket; Profile: incident;
	repeated ocsf.v1_6_0.objects.Ticket tickets = 64; // Caption: Tickets; Profile: incident;
	int64 time = 65; // Caption: Event Time;
	int32 timezone_offset = 66; // Caption: Timezone Offset;
	string type_name = 67; // Caption: Type Name;
	ocsf.v1_6_0.events.findings.enums.COMPLIANCE_FINDING_TYPE_UID type_uid = 68; // Caption: Type ID;
	google.protobuf.Struct unmapped = 69; // Caption: Unmapped Data;
	ocsf.v1_6_0.objects.VendorAttributes vendor_attributes = 70; // Caption: Vendor Attributes;
	string verdict = 71; // Caption: Verdict; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.COMPLIANCE_FINDING_VERDICT_ID verdict_id = 72; // Caption: Verdict ID; Profile: incident;
}

// Event: findings
// Event UID: 6
// URL: https://schema.ocsf.io/1.6.0/classes/data_security_finding
message DataSecurityFinding {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.DATA_SECURITY_FINDING_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.DATA_SECURITY_FINDING_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_6_0.objects.Actor actor = 5; // Caption: Actor;
	ocsf.v1_6_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	ocsf.v1_6_0.objects.User assignee = 7; // Caption: Assignee; Profile: incident;
	ocsf.v1_6_0.objects.Group assignee_group = 8; // Caption: Assignee Group; Profile: incident;
	repeated ocsf.v1_6_0.objects.Attack attacks = 9; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_6_0.objects.Authorization authorizations = 10; // Caption: Authorization Information; Profile: security_control;
	string category_name = 11; // Caption: Category;
	ocsf.v1_6_0.events.findings.enums.DATA_SECURITY_FINDING_CATEGORY_UID category_uid = 12; // Caption: Category ID;
	string class_name = 13; // Caption: Class;
	ocsf.v1_6_0.events.findings.enums.DATA_SECURITY_FINDING_CLASS_UID class_uid = 14; // Caption: Class ID;
	ocsf.v1_6_0.objects.Cloud cloud = 15; // Caption: Cloud; Profile: cloud;
	string comment = 16; // Caption: Comment;
	string confidence = 17; // Caption: Confidence;
	ocsf.v1_6_0.events.findings.enums.DATA_SECURITY_FINDING_CONFIDENCE_ID confidence_id = 18; // Caption: Confidence ID;
	int32 confidence_score = 19; // Caption: Confidence Score;
	int32 count = 20; // Caption: Count;
	ocsf.v1_6_0.objects.DataSecurity data_security = 21; // Caption: Data Security;
	ocsf.v1_6_0.objects.Database database = 22; // Caption: Database;
	ocsf.v1_6_0.objects.Databucket databucket = 23; // Caption: Databucket;
	ocsf.v1_6_0.objects.Device device = 24; // Caption: Device;
	string disposition = 25; // Profile: security_control; Caption: Disposition;
	ocsf.v1_6_0.events.findings.enums.DATA_SECURITY_FINDING_DISPOSITION_ID disposition_id = 26; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_6_0.objects.NetworkEndpoint dst_endpoint = 27; // Caption: Destination Endpoint;
	int64 duration = 28; // Caption: Duration Milliseconds;
	int64 end_time = 29; // Caption: End Time;
	repeated ocsf.v1_6_0.objects.Enrichment enrichments = 30; // Caption: Enrichments;
	ocsf.v1_6_0.objects.File file = 31; // Caption: File;
	ocsf.v1_6_0.objects.FindingInfo finding_info = 32; // Caption: Finding Information;
	ocsf.v1_6_0.objects.FirewallRule firewall_rule = 33; // Caption: Firewall Rule; Profile: security_control;
	string impact = 34; // Caption: Impact;
	ocsf.v1_6_0.events.findings.enums.DATA_SECURITY_FINDING_IMPACT_ID impact_id = 35; // Caption: Impact ID;
	int32 impact_score = 36; // Caption: Impact Score;
	bool is_alert = 37; // Caption: Alert;
	bool is_suspected_breach = 38; // Caption: Suspected Breach; Profile: incident;
	repeated ocsf.v1_6_0.objects.Malware malware = 39; // Caption: Malware; Profile: security_control;
	ocsf.v1_6_0.objects.MalwareScanInfo malware_scan_info = 40; // Caption: Malware Scan Info; Profile: security_control;
	string message = 41; // Caption: Message;
	ocsf.v1_6_0.objects.Metadata metadata = 42; // Caption: Metadata;
	repeated ocsf.v1_6_0.objects.Observable observables = 43; // Caption: Observables;
	repeated ocsf.v1_6_0.objects.Osint osint = 44; // Caption: OSINT; Profile: osint;
	ocsf.v1_6_0.objects.Policy policy = 45; // Caption: Policy; Profile: security_control;
	string priority = 46; // Caption: Priority; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.DATA_SECURITY_FINDING_PRIORITY_ID priority_id = 47; // Caption: Priority ID; Profile: incident;
	string raw_data = 48; // Caption: Raw Data;
	ocsf.v1_6_0.objects.Fingerprint raw_data_hash = 49; // Caption: Raw Data Hash;
	int64 raw_data_size = 50; // Caption: Raw Data Size;
	repeated ocsf.v1_6_0.objects.ResourceDetails resources = 51; // Caption: Resources Array;
	string risk_details = 52; // Caption: Risk Details;
	string risk_level = 53; // Caption: Risk Level;
	ocsf.v1_6_0.events.findings.enums.DATA_SECURITY_FINDING_RISK_LEVEL_ID risk_level_id = 54; // Caption: Risk Level ID;
	int32 risk_score = 55; // Caption: Risk Score;
	string severity = 56; // Caption: Severity;
	ocsf.v1_6_0.events.findings.enums.DATA_SECURITY_FINDING_SEVERITY_ID severity_id = 57; // Caption: Severity ID;
	ocsf.v1_6_0.objects.NetworkEndpoint src_endpoint = 58; // Caption: Source Endpoint;
	string src_url = 59; // Caption: Source URL; Profile: incident;
	int64 start_time = 60; // Caption: Start Time;
	string status = 61; // Caption: Status;
	string status_code = 62; // Caption: Status Code;
	string status_detail = 63; // Caption: Status Detail;
	ocsf.v1_6_0.events.findings.enums.DATA_SECURITY_FINDING_STATUS_ID status_id = 64; // Caption: Status ID;
	ocsf.v1_6_0.objects.Table table = 65; // Caption: Table;
	ocsf.v1_6_0.objects.Ticket ticket = 66; // Caption: Ticket; Profile: incident;
	repeated ocsf.v1_6_0.objects.Ticket tickets = 67; // Caption: Tickets; Profile: incident;
	int64 time = 68; // Caption: Event Time;
	int32 timezone_offset = 69; // Caption: Timezone Offset;
	string type_name = 70; // Caption: Type Name;
	ocsf.v1_6_0.events.findings.enums.DATA_SECURITY_FINDING_TYPE_UID type_uid = 71; // Caption: Type ID;
	google.protobuf.Struct unmapped = 72; // Caption: Unmapped Data;
	ocsf.v1_6_0.objects.VendorAttributes vendor_attributes = 73; // Caption: Vendor Attributes;
	string verdict = 74; // Caption: Verdict; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.DATA_SECURITY_FINDING_VERDICT_ID verdict_id = 75; // Caption: Verdict ID; Profile: incident;
}

// Event: findings
// Event UID: 4
// URL: https://schema.ocsf.io/1.6.0/classes/detection_finding
message DetectionFinding {
	string action = 1; // Profile: security_control; Caption: Action;
	ocsf.v1_6_0.events.findings.enums.DETECTION_FINDING_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.DETECTION_FINDING_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_6_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	repeated ocsf.v1_6_0.objects.AnomalyAnalysis anomaly_analyses = 6; // Caption: Anomaly Analyses;
	ocsf.v1_6_0.objects.Api api = 7; // Caption: API Details; Profile: cloud;
	ocsf.v1_6_0.objects.User assignee = 8; // Caption: Assignee; Profile: incident;
	ocsf.v1_6_0.objects.Group assignee_group = 9; // Caption: Assignee Group; Profile: incident;
	repeated ocsf.v1_6_0.objects.Attack attacks = 10; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_6_0.objects.Authorization authorizations = 11; // Caption: Authorization Information; Profile: security_control;
	string category_name = 12; // Caption: Category;
	ocsf.v1_6_0.events.findings.enums.DETECTION_FINDING_CATEGORY_UID category_uid = 13; // Caption: Category ID;
	string class_name = 14; // Caption: Class;
	ocsf.v1_6_0.events.findings.enums.DETECTION_FINDING_CLASS_UID class_uid = 15; // Caption: Class ID;
	ocsf.v1_6_0.objects.Cloud cloud = 16; // Caption: Cloud; Profile: cloud;
	string comment = 17; // Caption: Comment;
	string confidence = 18; // Caption: Confidence;
	ocsf.v1_6_0.events.findings.enums.DETECTION_FINDING_CONFIDENCE_ID confidence_id = 19; // Caption: Confidence ID;
	int32 confidence_score = 20; // Caption: Confidence Score;
	int32 count = 21; // Caption: Count;
	ocsf.v1_6_0.objects.Device device = 22; // Caption: Device;
	string disposition = 23; // Caption: Disposition; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.DETECTION_FINDING_DISPOSITION_ID disposition_id = 24; // Caption: Disposition ID; Profile: security_control;
	int64 duration = 25; // Caption: Duration Milliseconds;
	int64 end_time = 26; // Caption: End Time;
	repeated ocsf.v1_6_0.objects.Enrichment enrichments = 27; // Caption: Enrichments;
	repeated ocsf.v1_6_0.objects.Evidences evidences = 28; // Caption: Evidence Artifacts;
	ocsf.v1_6_0.objects.FindingInfo finding_info = 29; // Caption: Finding Information;
	ocsf.v1_6_0.objects.FirewallRule firewall_rule = 30; // Caption: Firewall Rule; Profile: security_control;
	string impact = 31; // Caption: Impact;
	ocsf.v1_6_0.events.findings.enums.DETECTION_FINDING_IMPACT_ID impact_id = 32; // Caption: Impact ID;
	int32 impact_score = 33; // Caption: Impact Score;
	bool is_alert = 34; // Caption: Alert;
	bool is_suspected_breach = 35; // Caption: Suspected Breach; Profile: incident;
	repeated ocsf.v1_6_0.objects.Malware malware = 36; // Caption: Malware;
	ocsf.v1_6_0.objects.MalwareScanInfo malware_scan_info = 37; // Caption: Malware Scan Info;
	string message = 38; // Caption: Message;
	ocsf.v1_6_0.objects.Metadata metadata = 39; // Caption: Metadata;
	repeated ocsf.v1_6_0.objects.Observable observables = 40; // Caption: Observables;
	repeated ocsf.v1_6_0.objects.Osint osint = 41; // Caption: OSINT; Profile: osint;
	ocsf.v1_6_0.objects.Policy policy = 42; // Caption: Policy; Profile: security_control;
	string priority = 43; // Caption: Priority; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.DETECTION_FINDING_PRIORITY_ID priority_id = 44; // Caption: Priority ID; Profile: incident;
	string raw_data = 45; // Caption: Raw Data;
	ocsf.v1_6_0.objects.Fingerprint raw_data_hash = 46; // Caption: Raw Data Hash;
	int64 raw_data_size = 47; // Caption: Raw Data Size;
	ocsf.v1_6_0.objects.Remediation remediation = 48; // Caption: Remediation Guidance;
	repeated ocsf.v1_6_0.objects.ResourceDetails resources = 49; // Caption: Resources Array;
	string risk_details = 50; // Caption: Risk Details;
	string risk_level = 51; // Caption: Risk Level;
	ocsf.v1_6_0.events.findings.enums.DETECTION_FINDING_RISK_LEVEL_ID risk_level_id = 52; // Caption: Risk Level ID;
	int32 risk_score = 53; // Caption: Risk Score;
	string severity = 54; // Caption: Severity;
	ocsf.v1_6_0.events.findings.enums.DETECTION_FINDING_SEVERITY_ID severity_id = 55; // Caption: Severity ID;
	string src_url = 56; // Caption: Source URL; Profile: incident;
	int64 start_time = 57; // Caption: Start Time;
	string status = 58; // Caption: Status;
	string status_code = 59; // Caption: Status Code;
	string status_detail = 60; // Caption: Status Detail;
	ocsf.v1_6_0.events.findings.enums.DETECTION_FINDING_STATUS_ID status_id = 61; // Caption: Status ID;
	ocsf.v1_6_0.objects.Ticket ticket = 62; // Profile: incident; Caption: Ticket;
	repeated ocsf.v1_6_0.objects.Ticket tickets = 63; // Caption: Tickets; Profile: incident;
	int64 time = 64; // Caption: Event Time;
	int32 timezone_offset = 65; // Caption: Timezone Offset;
	string type_name = 66; // Caption: Type Name;
	ocsf.v1_6_0.events.findings.enums.DETECTION_FINDING_TYPE_UID type_uid = 67; // Caption: Type ID;
	google.protobuf.Struct unmapped = 68; // Caption: Unmapped Data;
	ocsf.v1_6_0.objects.VendorAttributes vendor_attributes = 69; // Caption: Vendor Attributes;
	string verdict = 70; // Caption: Verdict; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.DETECTION_FINDING_VERDICT_ID verdict_id = 71; // Profile: incident; Caption: Verdict ID;
	repeated ocsf.v1_6_0.objects.Vulnerability vulnerabilities = 72; // Caption: Vulnerabilities;
}

// Event: findings
// Event UID: 0
// URL: https://schema.ocsf.io/1.6.0/classes/finding
message Finding {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.FINDING_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.FINDING_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_6_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_6_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	ocsf.v1_6_0.objects.User assignee = 7; // Caption: Assignee; Profile: incident;
	ocsf.v1_6_0.objects.Group assignee_group = 8; // Caption: Assignee Group; Profile: incident;
	repeated ocsf.v1_6_0.objects.Attack attacks = 9; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_6_0.objects.Authorization authorizations = 10; // Caption: Authorization Information; Profile: security_control;
	string category_name = 11; // Caption: Category;
	ocsf.v1_6_0.events.findings.enums.FINDING_CATEGORY_UID category_uid = 12; // Caption: Category ID;
	string class_name = 13; // Caption: Class;
	ocsf.v1_6_0.events.findings.enums.FINDING_CLASS_UID class_uid = 14; // Caption: Class ID;
	ocsf.v1_6_0.objects.Cloud cloud = 15; // Profile: cloud; Caption: Cloud;
	string comment = 16; // Caption: Comment;
	string confidence = 17; // Caption: Confidence;
	ocsf.v1_6_0.events.findings.enums.FINDING_CONFIDENCE_ID confidence_id = 18; // Caption: Confidence ID;
	int32 confidence_score = 19; // Caption: Confidence Score;
	int32 count = 20; // Caption: Count;
	ocsf.v1_6_0.objects.Device device = 21; // Caption: Device;
	string disposition = 22; // Caption: Disposition; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.FINDING_DISPOSITION_ID disposition_id = 23; // Caption: Disposition ID; Profile: security_control;
	int64 duration = 24; // Caption: Duration Milliseconds;
	int64 end_time = 25; // Caption: End Time;
	repeated ocsf.v1_6_0.objects.Enrichment enrichments = 26; // Caption: Enrichments;
	ocsf.v1_6_0.objects.FindingInfo finding_info = 27; // Caption: Finding Information;
	ocsf.v1_6_0.objects.FirewallRule firewall_rule = 28; // Caption: Firewall Rule; Profile: security_control;
	string impact = 29; // Caption: Impact; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.FINDING_IMPACT_ID impact_id = 30; // Caption: Impact ID; Profile: incident;
	int32 impact_score = 31; // Caption: Impact Score; Profile: incident;
	bool is_alert = 32; // Caption: Alert; Profile: security_control;
	bool is_suspected_breach = 33; // Caption: Suspected Breach; Profile: incident;
	repeated ocsf.v1_6_0.objects.Malware malware = 34; // Caption: Malware; Profile: security_control;
	ocsf.v1_6_0.objects.MalwareScanInfo malware_scan_info = 35; // Caption: Malware Scan Info; Profile: security_control;
	string message = 36; // Caption: Message;
	ocsf.v1_6_0.objects.Metadata metadata = 37; // Caption: Metadata;
	repeated ocsf.v1_6_0.objects.Observable observables = 38; // Caption: Observables;
	repeated ocsf.v1_6_0.objects.Osint osint = 39; // Caption: OSINT; Profile: osint;
	ocsf.v1_6_0.objects.Policy policy = 40; // Profile: security_control; Caption: Policy;
	string priority = 41; // Caption: Priority; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.FINDING_PRIORITY_ID priority_id = 42; // Caption: Priority ID; Profile: incident;
	string raw_data = 43; // Caption: Raw Data;
	ocsf.v1_6_0.objects.Fingerprint raw_data_hash = 44; // Caption: Raw Data Hash;
	int64 raw_data_size = 45; // Caption: Raw Data Size;
	string risk_details = 46; // Caption: Risk Details; Profile: security_control;
	string risk_level = 47; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.FINDING_RISK_LEVEL_ID risk_level_id = 48; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 49; // Caption: Risk Score; Profile: security_control;
	string severity = 50; // Caption: Severity;
	ocsf.v1_6_0.events.findings.enums.FINDING_SEVERITY_ID severity_id = 51; // Caption: Severity ID;
	string src_url = 52; // Caption: Source URL; Profile: incident;
	int64 start_time = 53; // Caption: Start Time;
	string status = 54; // Caption: Status;
	string status_code = 55; // Caption: Status Code;
	string status_detail = 56; // Caption: Status Detail;
	ocsf.v1_6_0.events.findings.enums.FINDING_STATUS_ID status_id = 57; // Caption: Status ID;
	ocsf.v1_6_0.objects.Ticket ticket = 58; // Caption: Ticket; Profile: incident;
	repeated ocsf.v1_6_0.objects.Ticket tickets = 59; // Profile: incident; Caption: Tickets;
	int64 time = 60; // Caption: Event Time;
	int32 timezone_offset = 61; // Caption: Timezone Offset;
	string type_name = 62; // Caption: Type Name;
	ocsf.v1_6_0.events.findings.enums.FINDING_TYPE_UID type_uid = 63; // Caption: Type ID;
	google.protobuf.Struct unmapped = 64; // Caption: Unmapped Data;
	ocsf.v1_6_0.objects.VendorAttributes vendor_attributes = 65; // Caption: Vendor Attributes;
	string verdict = 66; // Caption: Verdict; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.FINDING_VERDICT_ID verdict_id = 67; // Caption: Verdict ID; Profile: incident;
}

// URL: https://schema.ocsf.io/1.6.0/classes/iam_analysis_finding
// Event: findings
// Event UID: 8
message IamAnalysisFinding {
	ocsf.v1_6_0.objects.AccessAnalysisResult access_analysis_result = 1; // Caption: Access Analysis Result;
	string action = 2; // Caption: Action; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.IAM_ANALYSIS_FINDING_ACTION_ID action_id = 3; // Caption: Action ID; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.IAM_ANALYSIS_FINDING_ACTIVITY_ID activity_id = 4; // Caption: Activity ID;
	string activity_name = 5; // Caption: Activity;
	ocsf.v1_6_0.objects.Actor actor = 6; // Caption: Actor; Profile: host;
	ocsf.v1_6_0.objects.Api api = 7; // Caption: API Details; Profile: cloud;
	repeated ocsf.v1_6_0.events.application.Application applications = 8; // Caption: Applications;
	ocsf.v1_6_0.objects.User assignee = 9; // Caption: Assignee; Profile: incident;
	ocsf.v1_6_0.objects.Group assignee_group = 10; // Caption: Assignee Group; Profile: incident;
	repeated ocsf.v1_6_0.objects.Attack attacks = 11; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_6_0.objects.Authorization authorizations = 12; // Caption: Authorization Information; Profile: security_control;
	string category_name = 13; // Caption: Category;
	ocsf.v1_6_0.events.findings.enums.IAM_ANALYSIS_FINDING_CATEGORY_UID category_uid = 14; // Caption: Category ID;
	string class_name = 15; // Caption: Class;
	ocsf.v1_6_0.events.findings.enums.IAM_ANALYSIS_FINDING_CLASS_UID class_uid = 16; // Caption: Class ID;
	ocsf.v1_6_0.objects.Cloud cloud = 17; // Profile: cloud; Caption: Cloud;
	string comment = 18; // Caption: Comment;
	string confidence = 19; // Caption: Confidence;
	ocsf.v1_6_0.events.findings.enums.IAM_ANALYSIS_FINDING_CONFIDENCE_ID confidence_id = 20; // Caption: Confidence ID;
	int32 confidence_score = 21; // Caption: Confidence Score;
	int32 count = 22; // Caption: Count;
	ocsf.v1_6_0.objects.Device device = 23; // Caption: Device;
	string disposition = 24; // Caption: Disposition; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.IAM_ANALYSIS_FINDING_DISPOSITION_ID disposition_id = 25; // Caption: Disposition ID; Profile: security_control;
	int64 duration = 26; // Caption: Duration Milliseconds;
	int64 end_time = 27; // Caption: End Time;
	repeated ocsf.v1_6_0.objects.Enrichment enrichments = 28; // Caption: Enrichments;
	ocsf.v1_6_0.objects.FindingInfo finding_info = 29; // Caption: Finding Information;
	ocsf.v1_6_0.objects.FirewallRule firewall_rule = 30; // Caption: Firewall Rule; Profile: security_control;
	ocsf.v1_6_0.objects.IdentityActivityMetrics identity_activity_metrics = 31; // Caption: Identity Activity Metrics;
	string impact = 32; // Profile: incident; Caption: Impact;
	ocsf.v1_6_0.events.findings.enums.IAM_ANALYSIS_FINDING_IMPACT_ID impact_id = 33; // Caption: Impact ID; Profile: incident;
	int32 impact_score = 34; // Caption: Impact Score; Profile: incident;
	bool is_alert = 35; // Caption: Alert; Profile: security_control;
	bool is_suspected_breach = 36; // Profile: incident; Caption: Suspected Breach;
	repeated ocsf.v1_6_0.objects.Malware malware = 37; // Caption: Malware; Profile: security_control;
	ocsf.v1_6_0.objects.MalwareScanInfo malware_scan_info = 38; // Caption: Malware Scan Info; Profile: security_control;
	string message = 39; // Caption: Message;
	ocsf.v1_6_0.objects.Metadata metadata = 40; // Caption: Metadata;
	repeated ocsf.v1_6_0.objects.Observable observables = 41; // Caption: Observables;
	repeated ocsf.v1_6_0.objects.Osint osint = 42; // Caption: OSINT; Profile: osint;
	repeated ocsf.v1_6_0.objects.PermissionAnalysisResult permission_analysis_results = 43; // Caption: Permission Analysis Results;
	ocsf.v1_6_0.objects.Policy policy = 44; // Caption: Policy; Profile: security_control;
	string priority = 45; // Caption: Priority; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.IAM_ANALYSIS_FINDING_PRIORITY_ID priority_id = 46; // Profile: incident; Caption: Priority ID;
	string raw_data = 47; // Caption: Raw Data;
	ocsf.v1_6_0.objects.Fingerprint raw_data_hash = 48; // Caption: Raw Data Hash;
	int64 raw_data_size = 49; // Caption: Raw Data Size;
	ocsf.v1_6_0.objects.Remediation remediation = 50; // Caption: Remediation Guidance;
	repeated ocsf.v1_6_0.objects.ResourceDetails resources = 51; // Caption: Resources Array;
	string risk_details = 52; // Caption: Risk Details; Profile: security_control;
	string risk_level = 53; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.IAM_ANALYSIS_FINDING_RISK_LEVEL_ID risk_level_id = 54; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 55; // Caption: Risk Score; Profile: security_control;
	string severity = 56; // Caption: Severity;
	ocsf.v1_6_0.events.findings.enums.IAM_ANALYSIS_FINDING_SEVERITY_ID severity_id = 57; // Caption: Severity ID;
	string src_url = 58; // Caption: Source URL; Profile: incident;
	int64 start_time = 59; // Caption: Start Time;
	string status = 60; // Caption: Status;
	string status_code = 61; // Caption: Status Code;
	string status_detail = 62; // Caption: Status Detail;
	ocsf.v1_6_0.events.findings.enums.IAM_ANALYSIS_FINDING_STATUS_ID status_id = 63; // Caption: Status ID;
	ocsf.v1_6_0.objects.Ticket ticket = 64; // Caption: Ticket; Profile: incident;
	repeated ocsf.v1_6_0.objects.Ticket tickets = 65; // Caption: Tickets; Profile: incident;
	int64 time = 66; // Caption: Event Time;
	int32 timezone_offset = 67; // Caption: Timezone Offset;
	string type_name = 68; // Caption: Type Name;
	ocsf.v1_6_0.events.findings.enums.IAM_ANALYSIS_FINDING_TYPE_UID type_uid = 69; // Caption: Type ID;
	google.protobuf.Struct unmapped = 70; // Caption: Unmapped Data;
	ocsf.v1_6_0.objects.User user = 71; // Caption: User;
	ocsf.v1_6_0.objects.VendorAttributes vendor_attributes = 72; // Caption: Vendor Attributes;
	string verdict = 73; // Caption: Verdict; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.IAM_ANALYSIS_FINDING_VERDICT_ID verdict_id = 74; // Profile: incident; Caption: Verdict ID;
}

// Event: findings
// Event UID: 5
// URL: https://schema.ocsf.io/1.6.0/classes/incident_finding
message IncidentFinding {
	string action = 1; // Profile: security_control; Caption: Action;
	ocsf.v1_6_0.events.findings.enums.INCIDENT_FINDING_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.INCIDENT_FINDING_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_6_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_6_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	ocsf.v1_6_0.objects.User assignee = 7; // Caption: Assignee;
	ocsf.v1_6_0.objects.Group assignee_group = 8; // Caption: Assignee Group;
	repeated ocsf.v1_6_0.objects.Attack attacks = 9; // Caption: MITRE ATT&CK® and ATLAS™ Details;
	repeated ocsf.v1_6_0.objects.Authorization authorizations = 10; // Caption: Authorization Information; Profile: security_control;
	string category_name = 11; // Caption: Category;
	ocsf.v1_6_0.events.findings.enums.INCIDENT_FINDING_CATEGORY_UID category_uid = 12; // Caption: Category ID;
	string class_name = 13; // Caption: Class;
	ocsf.v1_6_0.events.findings.enums.INCIDENT_FINDING_CLASS_UID class_uid = 14; // Caption: Class ID;
	ocsf.v1_6_0.objects.Cloud cloud = 15; // Caption: Cloud; Profile: cloud;
	string comment = 16; // Caption: Comment;
	string confidence = 17; // Caption: Confidence;
	ocsf.v1_6_0.events.findings.enums.INCIDENT_FINDING_CONFIDENCE_ID confidence_id = 18; // Caption: Confidence ID;
	int32 confidence_score = 19; // Caption: Confidence Score;
	int32 count = 20; // Caption: Count;
	string desc = 21; // Caption: Description;
	ocsf.v1_6_0.objects.Device device = 22; // Caption: Device; Profile: host;
	string disposition = 23; // Caption: Disposition; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.INCIDENT_FINDING_DISPOSITION_ID disposition_id = 24; // Caption: Disposition ID; Profile: security_control;
	int64 duration = 25; // Caption: Duration Milliseconds;
	int64 end_time = 26; // Caption: End Time;
	repeated ocsf.v1_6_0.objects.Enrichment enrichments = 27; // Caption: Enrichments;
	repeated ocsf.v1_6_0.objects.FindingInfo finding_info_list = 28; // Caption: Finding Information List;
	ocsf.v1_6_0.objects.FirewallRule firewall_rule = 29; // Caption: Firewall Rule; Profile: security_control;
	string impact = 30; // Caption: Impact;
	ocsf.v1_6_0.events.findings.enums.INCIDENT_FINDING_IMPACT_ID impact_id = 31; // Caption: Impact ID;
	int32 impact_score = 32; // Caption: Impact Score;
	bool is_alert = 33; // Caption: Alert; Profile: security_control;
	bool is_suspected_breach = 34; // Caption: Suspected Breach;
	repeated ocsf.v1_6_0.objects.Malware malware = 35; // Caption: Malware; Profile: security_control;
	ocsf.v1_6_0.objects.MalwareScanInfo malware_scan_info = 36; // Caption: Malware Scan Info; Profile: security_control;
	string message = 37; // Caption: Message;
	ocsf.v1_6_0.objects.Metadata metadata = 38; // Caption: Metadata;
	repeated ocsf.v1_6_0.objects.Observable observables = 39; // Caption: Observables;
	repeated ocsf.v1_6_0.objects.Osint osint = 40; // Caption: OSINT; Profile: osint;
	ocsf.v1_6_0.objects.Policy policy = 41; // Caption: Policy; Profile: security_control;
	string priority = 42; // Caption: Priority;
	ocsf.v1_6_0.events.findings.enums.INCIDENT_FINDING_PRIORITY_ID priority_id = 43; // Caption: Priority ID;
	string raw_data = 44; // Caption: Raw Data;
	ocsf.v1_6_0.objects.Fingerprint raw_data_hash = 45; // Caption: Raw Data Hash;
	int64 raw_data_size = 46; // Caption: Raw Data Size;
	string risk_details = 47; // Caption: Risk Details; Profile: security_control;
	string risk_level = 48; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.INCIDENT_FINDING_RISK_LEVEL_ID risk_level_id = 49; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 50; // Caption: Risk Score; Profile: security_control;
	string severity = 51; // Caption: Severity;
	ocsf.v1_6_0.events.findings.enums.INCIDENT_FINDING_SEVERITY_ID severity_id = 52; // Caption: Severity ID;
	string src_url = 53; // Caption: Source URL;
	int64 start_time = 54; // Caption: Start Time;
	string status = 55; // Caption: Status;
	string status_code = 56; // Caption: Status Code;
	string status_detail = 57; // Caption: Status Detail;
	ocsf.v1_6_0.events.findings.enums.INCIDENT_FINDING_STATUS_ID status_id = 58; // Caption: Status ID;
	ocsf.v1_6_0.objects.Ticket ticket = 59; // Caption: Ticket;
	repeated ocsf.v1_6_0.objects.Ticket tickets = 60; // Caption: Tickets;
	int64 time = 61; // Caption: Event Time;
	int32 timezone_offset = 62; // Caption: Timezone Offset;
	string type_name = 63; // Caption: Type Name;
	ocsf.v1_6_0.events.findings.enums.INCIDENT_FINDING_TYPE_UID type_uid = 64; // Caption: Type ID;
	google.protobuf.Struct unmapped = 65; // Caption: Unmapped Data;
	ocsf.v1_6_0.objects.VendorAttributes vendor_attributes = 66; // Caption: Vendor Attributes;
	string verdict = 67; // Caption: Verdict;
	ocsf.v1_6_0.events.findings.enums.INCIDENT_FINDING_VERDICT_ID verdict_id = 68; // Caption: Verdict ID;
}

// Event: findings
// Event UID: 1
// URL: https://schema.ocsf.io/1.6.0/classes/security_finding
message SecurityFinding {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.SECURITY_FINDING_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.SECURITY_FINDING_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_6_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_6_0.objects.Analytic analytic = 6; // Caption: Analytic;
	ocsf.v1_6_0.objects.Api api = 7; // Caption: API Details; Profile: cloud;
	repeated ocsf.v1_6_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® and ATLAS™ Details;
	repeated ocsf.v1_6_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_6_0.events.findings.enums.SECURITY_FINDING_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	repeated ocsf.v1_6_0.objects.CisCsc cis_csc = 12; // Caption: CIS CSC;
	string class_name = 13; // Caption: Class;
	ocsf.v1_6_0.events.findings.enums.SECURITY_FINDING_CLASS_UID class_uid = 14; // Caption: Class ID;
	ocsf.v1_6_0.objects.Cloud cloud = 15; // Caption: Cloud; Profile: cloud;
	ocsf.v1_6_0.objects.Compliance compliance = 16; // Caption: Compliance;
	string confidence = 17; // Caption: Confidence;
	ocsf.v1_6_0.events.findings.enums.SECURITY_FINDING_CONFIDENCE_ID confidence_id = 18; // Caption: Confidence ID;
	int32 confidence_score = 19; // Caption: Confidence Score;
	int32 count = 20; // Caption: Count;
	repeated string data_sources = 21; // Caption: Data Sources;
	ocsf.v1_6_0.objects.Device device = 22; // Caption: Device; Profile: host;
	string disposition = 23; // Caption: Disposition; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.SECURITY_FINDING_DISPOSITION_ID disposition_id = 24; // Caption: Disposition ID; Profile: security_control;
	int64 duration = 25; // Caption: Duration Milliseconds;
	int64 end_time = 26; // Caption: End Time;
	repeated ocsf.v1_6_0.objects.Enrichment enrichments = 27; // Caption: Enrichments;
	google.protobuf.Struct evidence = 28; // Caption: Evidence;
	ocsf.v1_6_0.events.findings.Finding finding = 29; // Caption: Finding;
	ocsf.v1_6_0.objects.FirewallRule firewall_rule = 30; // Profile: security_control; Caption: Firewall Rule;
	string impact = 31; // Caption: Impact;
	ocsf.v1_6_0.events.findings.enums.SECURITY_FINDING_IMPACT_ID impact_id = 32; // Caption: Impact ID;
	int32 impact_score = 33; // Caption: Impact Score;
	bool is_alert = 34; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_6_0.objects.KillChainPhase kill_chain = 35; // Caption: Kill Chain;
	repeated ocsf.v1_6_0.objects.Malware malware = 36; // Caption: Malware;
	ocsf.v1_6_0.objects.MalwareScanInfo malware_scan_info = 37; // Caption: Malware Scan Info; Profile: security_control;
	string message = 38; // Caption: Message;
	ocsf.v1_6_0.objects.Metadata metadata = 39; // Caption: Metadata;
	repeated string nist = 40; // Caption: NIST List;
	repeated ocsf.v1_6_0.objects.Observable observables = 41; // Caption: Observables;
	repeated ocsf.v1_6_0.objects.Osint osint = 42; // Caption: OSINT; Profile: osint;
	ocsf.v1_6_0.objects.Policy policy = 43; // Caption: Policy; Profile: security_control;
	ocsf.v1_6_0.objects.Process process = 44; // Caption: Process;
	string raw_data = 45; // Caption: Raw Data;
	ocsf.v1_6_0.objects.Fingerprint raw_data_hash = 46; // Caption: Raw Data Hash;
	int64 raw_data_size = 47; // Caption: Raw Data Size;
	repeated ocsf.v1_6_0.objects.ResourceDetails resources = 48; // Caption: Resources Array;
	string risk_details = 49; // Profile: security_control; Caption: Risk Details;
	string risk_level = 50; // Caption: Risk Level;
	ocsf.v1_6_0.events.findings.enums.SECURITY_FINDING_RISK_LEVEL_ID risk_level_id = 51; // Caption: Risk Level ID;
	int32 risk_score = 52; // Caption: Risk Score;
	string severity = 53; // Caption: Severity;
	ocsf.v1_6_0.events.findings.enums.SECURITY_FINDING_SEVERITY_ID severity_id = 54; // Caption: Severity ID;
	int64 start_time = 55; // Caption: Start Time;
	string state = 56; // Caption: State;
	ocsf.v1_6_0.events.findings.enums.SECURITY_FINDING_STATE_ID state_id = 57; // Caption: State ID;
	string status = 58; // Caption: Status;
	string status_code = 59; // Caption: Status Code;
	string status_detail = 60; // Caption: Status Detail;
	ocsf.v1_6_0.events.findings.enums.SECURITY_FINDING_STATUS_ID status_id = 61; // Caption: Status ID;
	int64 time = 62; // Caption: Event Time;
	int32 timezone_offset = 63; // Caption: Timezone Offset;
	string type_name = 64; // Caption: Type Name;
	ocsf.v1_6_0.events.findings.enums.SECURITY_FINDING_TYPE_UID type_uid = 65; // Caption: Type ID;
	google.protobuf.Struct unmapped = 66; // Caption: Unmapped Data;
	repeated ocsf.v1_6_0.objects.Vulnerability vulnerabilities = 67; // Caption: Vulnerabilities;
}

// Event: findings
// Event UID: 2
// URL: https://schema.ocsf.io/1.6.0/classes/vulnerability_finding
message VulnerabilityFinding {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.VULNERABILITY_FINDING_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.VULNERABILITY_FINDING_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_6_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_6_0.objects.Api api = 6; // Profile: cloud; Caption: API Details;
	ocsf.v1_6_0.objects.User assignee = 7; // Profile: incident; Caption: Assignee;
	ocsf.v1_6_0.objects.Group assignee_group = 8; // Caption: Assignee Group; Profile: incident;
	repeated ocsf.v1_6_0.objects.Attack attacks = 9; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_6_0.objects.Authorization authorizations = 10; // Caption: Authorization Information; Profile: security_control;
	string category_name = 11; // Caption: Category;
	ocsf.v1_6_0.events.findings.enums.VULNERABILITY_FINDING_CATEGORY_UID category_uid = 12; // Caption: Category ID;
	string class_name = 13; // Caption: Class;
	ocsf.v1_6_0.events.findings.enums.VULNERABILITY_FINDING_CLASS_UID class_uid = 14; // Caption: Class ID;
	ocsf.v1_6_0.objects.Cloud cloud = 15; // Caption: Cloud; Profile: cloud;
	string comment = 16; // Caption: Comment;
	string confidence = 17; // Caption: Confidence;
	ocsf.v1_6_0.events.findings.enums.VULNERABILITY_FINDING_CONFIDENCE_ID confidence_id = 18; // Caption: Confidence ID;
	int32 confidence_score = 19; // Caption: Confidence Score;
	int32 count = 20; // Caption: Count;
	ocsf.v1_6_0.objects.Device device = 21; // Caption: Device;
	string disposition = 22; // Caption: Disposition; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.VULNERABILITY_FINDING_DISPOSITION_ID disposition_id = 23; // Caption: Disposition ID; Profile: security_control;
	int64 duration = 24; // Caption: Duration Milliseconds;
	int64 end_time = 25; // Caption: End Time;
	repeated ocsf.v1_6_0.objects.Enrichment enrichments = 26; // Caption: Enrichments;
	ocsf.v1_6_0.objects.FindingInfo finding_info = 27; // Caption: Finding Information;
	ocsf.v1_6_0.objects.FirewallRule firewall_rule = 28; // Caption: Firewall Rule; Profile: security_control;
	string impact = 29; // Caption: Impact; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.VULNERABILITY_FINDING_IMPACT_ID impact_id = 30; // Caption: Impact ID; Profile: incident;
	int32 impact_score = 31; // Caption: Impact Score; Profile: incident;
	bool is_alert = 32; // Caption: Alert; Profile: security_control;
	bool is_suspected_breach = 33; // Caption: Suspected Breach; Profile: incident;
	repeated ocsf.v1_6_0.objects.Malware malware = 34; // Caption: Malware; Profile: security_control;
	ocsf.v1_6_0.objects.MalwareScanInfo malware_scan_info = 35; // Caption: Malware Scan Info; Profile: security_control;
	string message = 36; // Caption: Message;
	ocsf.v1_6_0.objects.Metadata metadata = 37; // Caption: Metadata;
	repeated ocsf.v1_6_0.objects.Observable observables = 38; // Caption: Observables;
	repeated ocsf.v1_6_0.objects.Osint osint = 39; // Caption: OSINT; Profile: osint;
	ocsf.v1_6_0.objects.Policy policy = 40; // Caption: Policy; Profile: security_control;
	string priority = 41; // Caption: Priority; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.VULNERABILITY_FINDING_PRIORITY_ID priority_id = 42; // Caption: Priority ID; Profile: incident;
	string raw_data = 43; // Caption: Raw Data;
	ocsf.v1_6_0.objects.Fingerprint raw_data_hash = 44; // Caption: Raw Data Hash;
	int64 raw_data_size = 45; // Caption: Raw Data Size;
	ocsf.v1_6_0.objects.ResourceDetails resource = 46; // Caption: Resource;
	repeated ocsf.v1_6_0.objects.ResourceDetails resources = 47; // Caption: Resources Array;
	string risk_details = 48; // Caption: Risk Details; Profile: security_control;
	string risk_level = 49; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_6_0.events.findings.enums.VULNERABILITY_FINDING_RISK_LEVEL_ID risk_level_id = 50; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 51; // Caption: Risk Score; Profile: security_control;
	string severity = 52; // Caption: Severity;
	ocsf.v1_6_0.events.findings.enums.VULNERABILITY_FINDING_SEVERITY_ID severity_id = 53; // Caption: Severity ID;
	string src_url = 54; // Profile: incident; Caption: Source URL;
	int64 start_time = 55; // Caption: Start Time;
	string status = 56; // Caption: Status;
	string status_code = 57; // Caption: Status Code;
	string status_detail = 58; // Caption: Status Detail;
	ocsf.v1_6_0.events.findings.enums.VULNERABILITY_FINDING_STATUS_ID status_id = 59; // Caption: Status ID;
	ocsf.v1_6_0.objects.Ticket ticket = 60; // Profile: incident; Caption: Ticket;
	repeated ocsf.v1_6_0.objects.Ticket tickets = 61; // Caption: Tickets; Profile: incident;
	int64 time = 62; // Caption: Event Time;
	int32 timezone_offset = 63; // Caption: Timezone Offset;
	string type_name = 64; // Caption: Type Name;
	ocsf.v1_6_0.events.findings.enums.VULNERABILITY_FINDING_TYPE_UID type_uid = 65; // Caption: Type ID;
	google.protobuf.Struct unmapped = 66; // Caption: Unmapped Data;
	ocsf.v1_6_0.objects.VendorAttributes vendor_attributes = 67; // Caption: Vendor Attributes;
	string verdict = 68; // Caption: Verdict; Profile: incident;
	ocsf.v1_6_0.events.findings.enums.VULNERABILITY_FINDING_VERDICT_ID verdict_id = 69; // Caption: Verdict ID; Profile: incident;
	repeated ocsf.v1_6_0.objects.Vulnerability vulnerabilities = 70; // Caption: Vulnerabilities;
}