// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: ocsf/v1_0_0/events/discovery/discovery.proto

//go:build !protoopaque

package discovery

import (
	enums "github.com/valllabh/ocsf-schema-golang/ocsf/v1_0_0/events/discovery/enums"
	objects "github.com/valllabh/ocsf-schema-golang/ocsf/v1_0_0/objects"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event: discovery
// Event UID: 2
// URL: https://schema.ocsf.io/1.0.0/classes/config_state
type ConfigState struct {
	state              protoimpl.MessageState          `protogen:"hybrid.v1"`
	ActivityId         enums.CONFIG_STATE_ACTIVITY_ID  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3,enum=ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_ACTIVITY_ID" json:"activity_id,omitempty"`     // Caption: Activity ID;
	ActivityName       string                          `protobuf:"bytes,2,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`                                                                 // Caption: Activity;
	Actor              *objects.Actor                  `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`                                                                                                   // Caption: Actor;
	Api                *objects.Api                    `protobuf:"bytes,4,opt,name=api,proto3" json:"api,omitempty"`                                                                                                       // Caption: API Details; Profile: cloud;
	CategoryName       string                          `protobuf:"bytes,5,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`                                                                 // Caption: Category;
	CategoryUid        enums.CONFIG_STATE_CATEGORY_UID `protobuf:"varint,6,opt,name=category_uid,json=categoryUid,proto3,enum=ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_CATEGORY_UID" json:"category_uid,omitempty"` // Caption: Category ID;
	CisBenchmarkResult *objects.CisBenchmarkResult     `protobuf:"bytes,7,opt,name=cis_benchmark_result,json=cisBenchmarkResult,proto3" json:"cis_benchmark_result,omitempty"`                                             // Caption: CIS Benchmark Result;
	ClassName          string                          `protobuf:"bytes,8,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`                                                                          // Caption: Class;
	ClassUid           enums.CONFIG_STATE_CLASS_UID    `protobuf:"varint,9,opt,name=class_uid,json=classUid,proto3,enum=ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_CLASS_UID" json:"class_uid,omitempty"`             // Caption: Class ID;
	Cloud              *objects.Cloud                  `protobuf:"bytes,10,opt,name=cloud,proto3" json:"cloud,omitempty"`                                                                                                  // Profile: cloud; Caption: Cloud;
	Count              int32                           `protobuf:"varint,11,opt,name=count,proto3" json:"count,omitempty"`                                                                                                 // Caption: Count;
	Device             *objects.Device                 `protobuf:"bytes,12,opt,name=device,proto3" json:"device,omitempty"`                                                                                                // Caption: Device;
	Duration           int32                           `protobuf:"varint,13,opt,name=duration,proto3" json:"duration,omitempty"`                                                                                           // Caption: Duration;
	EndTime            int64                           `protobuf:"varint,14,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                                                                              // Caption: End Time;
	Enrichments        []*objects.Enrichment           `protobuf:"bytes,15,rep,name=enrichments,proto3" json:"enrichments,omitempty"`                                                                                      // Caption: Enrichments;
	Message            string                          `protobuf:"bytes,16,opt,name=message,proto3" json:"message,omitempty"`                                                                                              // Caption: Message;
	Metadata           *objects.Metadata               `protobuf:"bytes,17,opt,name=metadata,proto3" json:"metadata,omitempty"`                                                                                            // Caption: Metadata;
	Observables        []*objects.Observable           `protobuf:"bytes,18,rep,name=observables,proto3" json:"observables,omitempty"`                                                                                      // Caption: Observables;
	RawData            string                          `protobuf:"bytes,19,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`                                                                               // Caption: Raw Data;
	Severity           string                          `protobuf:"bytes,20,opt,name=severity,proto3" json:"severity,omitempty"`                                                                                            // Caption: Severity;
	SeverityId         enums.CONFIG_STATE_SEVERITY_ID  `protobuf:"varint,21,opt,name=severity_id,json=severityId,proto3,enum=ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_SEVERITY_ID" json:"severity_id,omitempty"`    // Caption: Severity ID;
	StartTime          int64                           `protobuf:"varint,22,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                                                                        // Caption: Start Time;
	Status             string                          `protobuf:"bytes,23,opt,name=status,proto3" json:"status,omitempty"`                                                                                                // Caption: Status;
	StatusCode         string                          `protobuf:"bytes,24,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                                      // Caption: Status Code;
	StatusDetail       string                          `protobuf:"bytes,25,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"`                                                                // Caption: Status Details;
	StatusId           enums.CONFIG_STATE_STATUS_ID    `protobuf:"varint,26,opt,name=status_id,json=statusId,proto3,enum=ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_STATUS_ID" json:"status_id,omitempty"`            // Caption: Status ID;
	Time               int64                           `protobuf:"varint,27,opt,name=time,proto3" json:"time,omitempty"`                                                                                                   // Caption: Event Time;
	TimezoneOffset     int32                           `protobuf:"varint,28,opt,name=timezone_offset,json=timezoneOffset,proto3" json:"timezone_offset,omitempty"`                                                         // Caption: Timezone Offset;
	TypeName           string                          `protobuf:"bytes,29,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`                                                                            // Caption: Type Name;
	TypeUid            enums.CONFIG_STATE_TYPE_UID     `protobuf:"varint,30,opt,name=type_uid,json=typeUid,proto3,enum=ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_TYPE_UID" json:"type_uid,omitempty"`                // Caption: Type ID;
	Unmapped           *structpb.Struct                `protobuf:"bytes,31,opt,name=unmapped,proto3" json:"unmapped,omitempty"`                                                                                            // Caption: Unmapped Data;
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfigState) Reset() {
	*x = ConfigState{}
	mi := &file_ocsf_v1_0_0_events_discovery_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigState) ProtoMessage() {}

func (x *ConfigState) ProtoReflect() protoreflect.Message {
	mi := &file_ocsf_v1_0_0_events_discovery_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigState) GetActivityId() enums.CONFIG_STATE_ACTIVITY_ID {
	if x != nil {
		return x.ActivityId
	}
	return enums.CONFIG_STATE_ACTIVITY_ID(0)
}

func (x *ConfigState) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *ConfigState) GetActor() *objects.Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ConfigState) GetApi() *objects.Api {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *ConfigState) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ConfigState) GetCategoryUid() enums.CONFIG_STATE_CATEGORY_UID {
	if x != nil {
		return x.CategoryUid
	}
	return enums.CONFIG_STATE_CATEGORY_UID(0)
}

func (x *ConfigState) GetCisBenchmarkResult() *objects.CisBenchmarkResult {
	if x != nil {
		return x.CisBenchmarkResult
	}
	return nil
}

func (x *ConfigState) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *ConfigState) GetClassUid() enums.CONFIG_STATE_CLASS_UID {
	if x != nil {
		return x.ClassUid
	}
	return enums.CONFIG_STATE_CLASS_UID(0)
}

func (x *ConfigState) GetCloud() *objects.Cloud {
	if x != nil {
		return x.Cloud
	}
	return nil
}

func (x *ConfigState) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ConfigState) GetDevice() *objects.Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *ConfigState) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ConfigState) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ConfigState) GetEnrichments() []*objects.Enrichment {
	if x != nil {
		return x.Enrichments
	}
	return nil
}

func (x *ConfigState) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigState) GetMetadata() *objects.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ConfigState) GetObservables() []*objects.Observable {
	if x != nil {
		return x.Observables
	}
	return nil
}

func (x *ConfigState) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *ConfigState) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ConfigState) GetSeverityId() enums.CONFIG_STATE_SEVERITY_ID {
	if x != nil {
		return x.SeverityId
	}
	return enums.CONFIG_STATE_SEVERITY_ID(0)
}

func (x *ConfigState) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ConfigState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConfigState) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *ConfigState) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

func (x *ConfigState) GetStatusId() enums.CONFIG_STATE_STATUS_ID {
	if x != nil {
		return x.StatusId
	}
	return enums.CONFIG_STATE_STATUS_ID(0)
}

func (x *ConfigState) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ConfigState) GetTimezoneOffset() int32 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

func (x *ConfigState) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *ConfigState) GetTypeUid() enums.CONFIG_STATE_TYPE_UID {
	if x != nil {
		return x.TypeUid
	}
	return enums.CONFIG_STATE_TYPE_UID(0)
}

func (x *ConfigState) GetUnmapped() *structpb.Struct {
	if x != nil {
		return x.Unmapped
	}
	return nil
}

func (x *ConfigState) SetActivityId(v enums.CONFIG_STATE_ACTIVITY_ID) {
	x.ActivityId = v
}

func (x *ConfigState) SetActivityName(v string) {
	x.ActivityName = v
}

func (x *ConfigState) SetActor(v *objects.Actor) {
	x.Actor = v
}

func (x *ConfigState) SetApi(v *objects.Api) {
	x.Api = v
}

func (x *ConfigState) SetCategoryName(v string) {
	x.CategoryName = v
}

func (x *ConfigState) SetCategoryUid(v enums.CONFIG_STATE_CATEGORY_UID) {
	x.CategoryUid = v
}

func (x *ConfigState) SetCisBenchmarkResult(v *objects.CisBenchmarkResult) {
	x.CisBenchmarkResult = v
}

func (x *ConfigState) SetClassName(v string) {
	x.ClassName = v
}

func (x *ConfigState) SetClassUid(v enums.CONFIG_STATE_CLASS_UID) {
	x.ClassUid = v
}

func (x *ConfigState) SetCloud(v *objects.Cloud) {
	x.Cloud = v
}

func (x *ConfigState) SetCount(v int32) {
	x.Count = v
}

func (x *ConfigState) SetDevice(v *objects.Device) {
	x.Device = v
}

func (x *ConfigState) SetDuration(v int32) {
	x.Duration = v
}

func (x *ConfigState) SetEndTime(v int64) {
	x.EndTime = v
}

func (x *ConfigState) SetEnrichments(v []*objects.Enrichment) {
	x.Enrichments = v
}

func (x *ConfigState) SetMessage(v string) {
	x.Message = v
}

func (x *ConfigState) SetMetadata(v *objects.Metadata) {
	x.Metadata = v
}

func (x *ConfigState) SetObservables(v []*objects.Observable) {
	x.Observables = v
}

func (x *ConfigState) SetRawData(v string) {
	x.RawData = v
}

func (x *ConfigState) SetSeverity(v string) {
	x.Severity = v
}

func (x *ConfigState) SetSeverityId(v enums.CONFIG_STATE_SEVERITY_ID) {
	x.SeverityId = v
}

func (x *ConfigState) SetStartTime(v int64) {
	x.StartTime = v
}

func (x *ConfigState) SetStatus(v string) {
	x.Status = v
}

func (x *ConfigState) SetStatusCode(v string) {
	x.StatusCode = v
}

func (x *ConfigState) SetStatusDetail(v string) {
	x.StatusDetail = v
}

func (x *ConfigState) SetStatusId(v enums.CONFIG_STATE_STATUS_ID) {
	x.StatusId = v
}

func (x *ConfigState) SetTime(v int64) {
	x.Time = v
}

func (x *ConfigState) SetTimezoneOffset(v int32) {
	x.TimezoneOffset = v
}

func (x *ConfigState) SetTypeName(v string) {
	x.TypeName = v
}

func (x *ConfigState) SetTypeUid(v enums.CONFIG_STATE_TYPE_UID) {
	x.TypeUid = v
}

func (x *ConfigState) SetUnmapped(v *structpb.Struct) {
	x.Unmapped = v
}

func (x *ConfigState) HasActor() bool {
	if x == nil {
		return false
	}
	return x.Actor != nil
}

func (x *ConfigState) HasApi() bool {
	if x == nil {
		return false
	}
	return x.Api != nil
}

func (x *ConfigState) HasCisBenchmarkResult() bool {
	if x == nil {
		return false
	}
	return x.CisBenchmarkResult != nil
}

func (x *ConfigState) HasCloud() bool {
	if x == nil {
		return false
	}
	return x.Cloud != nil
}

func (x *ConfigState) HasDevice() bool {
	if x == nil {
		return false
	}
	return x.Device != nil
}

func (x *ConfigState) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *ConfigState) HasUnmapped() bool {
	if x == nil {
		return false
	}
	return x.Unmapped != nil
}

func (x *ConfigState) ClearActor() {
	x.Actor = nil
}

func (x *ConfigState) ClearApi() {
	x.Api = nil
}

func (x *ConfigState) ClearCisBenchmarkResult() {
	x.CisBenchmarkResult = nil
}

func (x *ConfigState) ClearCloud() {
	x.Cloud = nil
}

func (x *ConfigState) ClearDevice() {
	x.Device = nil
}

func (x *ConfigState) ClearMetadata() {
	x.Metadata = nil
}

func (x *ConfigState) ClearUnmapped() {
	x.Unmapped = nil
}

type ConfigState_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ActivityId         enums.CONFIG_STATE_ACTIVITY_ID
	ActivityName       string
	Actor              *objects.Actor
	Api                *objects.Api
	CategoryName       string
	CategoryUid        enums.CONFIG_STATE_CATEGORY_UID
	CisBenchmarkResult *objects.CisBenchmarkResult
	ClassName          string
	ClassUid           enums.CONFIG_STATE_CLASS_UID
	Cloud              *objects.Cloud
	Count              int32
	Device             *objects.Device
	Duration           int32
	EndTime            int64
	Enrichments        []*objects.Enrichment
	Message            string
	Metadata           *objects.Metadata
	Observables        []*objects.Observable
	RawData            string
	Severity           string
	SeverityId         enums.CONFIG_STATE_SEVERITY_ID
	StartTime          int64
	Status             string
	StatusCode         string
	StatusDetail       string
	StatusId           enums.CONFIG_STATE_STATUS_ID
	Time               int64
	TimezoneOffset     int32
	TypeName           string
	TypeUid            enums.CONFIG_STATE_TYPE_UID
	Unmapped           *structpb.Struct
}

func (b0 ConfigState_builder) Build() *ConfigState {
	m0 := &ConfigState{}
	b, x := &b0, m0
	_, _ = b, x
	x.ActivityId = b.ActivityId
	x.ActivityName = b.ActivityName
	x.Actor = b.Actor
	x.Api = b.Api
	x.CategoryName = b.CategoryName
	x.CategoryUid = b.CategoryUid
	x.CisBenchmarkResult = b.CisBenchmarkResult
	x.ClassName = b.ClassName
	x.ClassUid = b.ClassUid
	x.Cloud = b.Cloud
	x.Count = b.Count
	x.Device = b.Device
	x.Duration = b.Duration
	x.EndTime = b.EndTime
	x.Enrichments = b.Enrichments
	x.Message = b.Message
	x.Metadata = b.Metadata
	x.Observables = b.Observables
	x.RawData = b.RawData
	x.Severity = b.Severity
	x.SeverityId = b.SeverityId
	x.StartTime = b.StartTime
	x.Status = b.Status
	x.StatusCode = b.StatusCode
	x.StatusDetail = b.StatusDetail
	x.StatusId = b.StatusId
	x.Time = b.Time
	x.TimezoneOffset = b.TimezoneOffset
	x.TypeName = b.TypeName
	x.TypeUid = b.TypeUid
	x.Unmapped = b.Unmapped
	return m0
}

// Event: discovery
// Event UID: 0
// URL: https://schema.ocsf.io/1.0.0/classes/discovery
type Discovery struct {
	state          protoimpl.MessageState       `protogen:"hybrid.v1"`
	ActivityId     enums.DISCOVERY_ACTIVITY_ID  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3,enum=ocsf.v1_0_0.events.discovery.enums.DISCOVERY_ACTIVITY_ID" json:"activity_id,omitempty"`     // Caption: Activity ID;
	ActivityName   string                       `protobuf:"bytes,2,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`                                                              // Caption: Activity;
	Api            *objects.Api                 `protobuf:"bytes,3,opt,name=api,proto3" json:"api,omitempty"`                                                                                                    // Caption: API Details; Profile: cloud;
	CategoryName   string                       `protobuf:"bytes,4,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`                                                              // Caption: Category;
	CategoryUid    enums.DISCOVERY_CATEGORY_UID `protobuf:"varint,5,opt,name=category_uid,json=categoryUid,proto3,enum=ocsf.v1_0_0.events.discovery.enums.DISCOVERY_CATEGORY_UID" json:"category_uid,omitempty"` // Caption: Category ID;
	ClassName      string                       `protobuf:"bytes,6,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`                                                                       // Caption: Class;
	ClassUid       enums.DISCOVERY_CLASS_UID    `protobuf:"varint,7,opt,name=class_uid,json=classUid,proto3,enum=ocsf.v1_0_0.events.discovery.enums.DISCOVERY_CLASS_UID" json:"class_uid,omitempty"`             // Caption: Class ID;
	Cloud          *objects.Cloud               `protobuf:"bytes,8,opt,name=cloud,proto3" json:"cloud,omitempty"`                                                                                                // Caption: Cloud; Profile: cloud;
	Count          int32                        `protobuf:"varint,9,opt,name=count,proto3" json:"count,omitempty"`                                                                                               // Caption: Count;
	Duration       int32                        `protobuf:"varint,10,opt,name=duration,proto3" json:"duration,omitempty"`                                                                                        // Caption: Duration;
	EndTime        int64                        `protobuf:"varint,11,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                                                                           // Caption: End Time;
	Enrichments    []*objects.Enrichment        `protobuf:"bytes,12,rep,name=enrichments,proto3" json:"enrichments,omitempty"`                                                                                   // Caption: Enrichments;
	Message        string                       `protobuf:"bytes,13,opt,name=message,proto3" json:"message,omitempty"`                                                                                           // Caption: Message;
	Metadata       *objects.Metadata            `protobuf:"bytes,14,opt,name=metadata,proto3" json:"metadata,omitempty"`                                                                                         // Caption: Metadata;
	Observables    []*objects.Observable        `protobuf:"bytes,15,rep,name=observables,proto3" json:"observables,omitempty"`                                                                                   // Caption: Observables;
	RawData        string                       `protobuf:"bytes,16,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`                                                                            // Caption: Raw Data;
	Severity       string                       `protobuf:"bytes,17,opt,name=severity,proto3" json:"severity,omitempty"`                                                                                         // Caption: Severity;
	SeverityId     enums.DISCOVERY_SEVERITY_ID  `protobuf:"varint,18,opt,name=severity_id,json=severityId,proto3,enum=ocsf.v1_0_0.events.discovery.enums.DISCOVERY_SEVERITY_ID" json:"severity_id,omitempty"`    // Caption: Severity ID;
	StartTime      int64                        `protobuf:"varint,19,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                                                                     // Caption: Start Time;
	Status         string                       `protobuf:"bytes,20,opt,name=status,proto3" json:"status,omitempty"`                                                                                             // Caption: Status;
	StatusCode     string                       `protobuf:"bytes,21,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                                   // Caption: Status Code;
	StatusDetail   string                       `protobuf:"bytes,22,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"`                                                             // Caption: Status Details;
	StatusId       enums.DISCOVERY_STATUS_ID    `protobuf:"varint,23,opt,name=status_id,json=statusId,proto3,enum=ocsf.v1_0_0.events.discovery.enums.DISCOVERY_STATUS_ID" json:"status_id,omitempty"`            // Caption: Status ID;
	Time           int64                        `protobuf:"varint,24,opt,name=time,proto3" json:"time,omitempty"`                                                                                                // Caption: Event Time;
	TimezoneOffset int32                        `protobuf:"varint,25,opt,name=timezone_offset,json=timezoneOffset,proto3" json:"timezone_offset,omitempty"`                                                      // Caption: Timezone Offset;
	TypeName       string                       `protobuf:"bytes,26,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`                                                                         // Caption: Type Name;
	TypeUid        enums.DISCOVERY_TYPE_UID     `protobuf:"varint,27,opt,name=type_uid,json=typeUid,proto3,enum=ocsf.v1_0_0.events.discovery.enums.DISCOVERY_TYPE_UID" json:"type_uid,omitempty"`                // Caption: Type ID;
	Unmapped       *structpb.Struct             `protobuf:"bytes,28,opt,name=unmapped,proto3" json:"unmapped,omitempty"`                                                                                         // Caption: Unmapped Data;
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Discovery) Reset() {
	*x = Discovery{}
	mi := &file_ocsf_v1_0_0_events_discovery_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discovery) ProtoMessage() {}

func (x *Discovery) ProtoReflect() protoreflect.Message {
	mi := &file_ocsf_v1_0_0_events_discovery_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Discovery) GetActivityId() enums.DISCOVERY_ACTIVITY_ID {
	if x != nil {
		return x.ActivityId
	}
	return enums.DISCOVERY_ACTIVITY_ID(0)
}

func (x *Discovery) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *Discovery) GetApi() *objects.Api {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *Discovery) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Discovery) GetCategoryUid() enums.DISCOVERY_CATEGORY_UID {
	if x != nil {
		return x.CategoryUid
	}
	return enums.DISCOVERY_CATEGORY_UID(0)
}

func (x *Discovery) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Discovery) GetClassUid() enums.DISCOVERY_CLASS_UID {
	if x != nil {
		return x.ClassUid
	}
	return enums.DISCOVERY_CLASS_UID(0)
}

func (x *Discovery) GetCloud() *objects.Cloud {
	if x != nil {
		return x.Cloud
	}
	return nil
}

func (x *Discovery) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Discovery) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Discovery) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Discovery) GetEnrichments() []*objects.Enrichment {
	if x != nil {
		return x.Enrichments
	}
	return nil
}

func (x *Discovery) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Discovery) GetMetadata() *objects.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Discovery) GetObservables() []*objects.Observable {
	if x != nil {
		return x.Observables
	}
	return nil
}

func (x *Discovery) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *Discovery) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Discovery) GetSeverityId() enums.DISCOVERY_SEVERITY_ID {
	if x != nil {
		return x.SeverityId
	}
	return enums.DISCOVERY_SEVERITY_ID(0)
}

func (x *Discovery) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Discovery) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Discovery) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *Discovery) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

func (x *Discovery) GetStatusId() enums.DISCOVERY_STATUS_ID {
	if x != nil {
		return x.StatusId
	}
	return enums.DISCOVERY_STATUS_ID(0)
}

func (x *Discovery) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Discovery) GetTimezoneOffset() int32 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

func (x *Discovery) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *Discovery) GetTypeUid() enums.DISCOVERY_TYPE_UID {
	if x != nil {
		return x.TypeUid
	}
	return enums.DISCOVERY_TYPE_UID(0)
}

func (x *Discovery) GetUnmapped() *structpb.Struct {
	if x != nil {
		return x.Unmapped
	}
	return nil
}

func (x *Discovery) SetActivityId(v enums.DISCOVERY_ACTIVITY_ID) {
	x.ActivityId = v
}

func (x *Discovery) SetActivityName(v string) {
	x.ActivityName = v
}

func (x *Discovery) SetApi(v *objects.Api) {
	x.Api = v
}

func (x *Discovery) SetCategoryName(v string) {
	x.CategoryName = v
}

func (x *Discovery) SetCategoryUid(v enums.DISCOVERY_CATEGORY_UID) {
	x.CategoryUid = v
}

func (x *Discovery) SetClassName(v string) {
	x.ClassName = v
}

func (x *Discovery) SetClassUid(v enums.DISCOVERY_CLASS_UID) {
	x.ClassUid = v
}

func (x *Discovery) SetCloud(v *objects.Cloud) {
	x.Cloud = v
}

func (x *Discovery) SetCount(v int32) {
	x.Count = v
}

func (x *Discovery) SetDuration(v int32) {
	x.Duration = v
}

func (x *Discovery) SetEndTime(v int64) {
	x.EndTime = v
}

func (x *Discovery) SetEnrichments(v []*objects.Enrichment) {
	x.Enrichments = v
}

func (x *Discovery) SetMessage(v string) {
	x.Message = v
}

func (x *Discovery) SetMetadata(v *objects.Metadata) {
	x.Metadata = v
}

func (x *Discovery) SetObservables(v []*objects.Observable) {
	x.Observables = v
}

func (x *Discovery) SetRawData(v string) {
	x.RawData = v
}

func (x *Discovery) SetSeverity(v string) {
	x.Severity = v
}

func (x *Discovery) SetSeverityId(v enums.DISCOVERY_SEVERITY_ID) {
	x.SeverityId = v
}

func (x *Discovery) SetStartTime(v int64) {
	x.StartTime = v
}

func (x *Discovery) SetStatus(v string) {
	x.Status = v
}

func (x *Discovery) SetStatusCode(v string) {
	x.StatusCode = v
}

func (x *Discovery) SetStatusDetail(v string) {
	x.StatusDetail = v
}

func (x *Discovery) SetStatusId(v enums.DISCOVERY_STATUS_ID) {
	x.StatusId = v
}

func (x *Discovery) SetTime(v int64) {
	x.Time = v
}

func (x *Discovery) SetTimezoneOffset(v int32) {
	x.TimezoneOffset = v
}

func (x *Discovery) SetTypeName(v string) {
	x.TypeName = v
}

func (x *Discovery) SetTypeUid(v enums.DISCOVERY_TYPE_UID) {
	x.TypeUid = v
}

func (x *Discovery) SetUnmapped(v *structpb.Struct) {
	x.Unmapped = v
}

func (x *Discovery) HasApi() bool {
	if x == nil {
		return false
	}
	return x.Api != nil
}

func (x *Discovery) HasCloud() bool {
	if x == nil {
		return false
	}
	return x.Cloud != nil
}

func (x *Discovery) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *Discovery) HasUnmapped() bool {
	if x == nil {
		return false
	}
	return x.Unmapped != nil
}

func (x *Discovery) ClearApi() {
	x.Api = nil
}

func (x *Discovery) ClearCloud() {
	x.Cloud = nil
}

func (x *Discovery) ClearMetadata() {
	x.Metadata = nil
}

func (x *Discovery) ClearUnmapped() {
	x.Unmapped = nil
}

type Discovery_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ActivityId     enums.DISCOVERY_ACTIVITY_ID
	ActivityName   string
	Api            *objects.Api
	CategoryName   string
	CategoryUid    enums.DISCOVERY_CATEGORY_UID
	ClassName      string
	ClassUid       enums.DISCOVERY_CLASS_UID
	Cloud          *objects.Cloud
	Count          int32
	Duration       int32
	EndTime        int64
	Enrichments    []*objects.Enrichment
	Message        string
	Metadata       *objects.Metadata
	Observables    []*objects.Observable
	RawData        string
	Severity       string
	SeverityId     enums.DISCOVERY_SEVERITY_ID
	StartTime      int64
	Status         string
	StatusCode     string
	StatusDetail   string
	StatusId       enums.DISCOVERY_STATUS_ID
	Time           int64
	TimezoneOffset int32
	TypeName       string
	TypeUid        enums.DISCOVERY_TYPE_UID
	Unmapped       *structpb.Struct
}

func (b0 Discovery_builder) Build() *Discovery {
	m0 := &Discovery{}
	b, x := &b0, m0
	_, _ = b, x
	x.ActivityId = b.ActivityId
	x.ActivityName = b.ActivityName
	x.Api = b.Api
	x.CategoryName = b.CategoryName
	x.CategoryUid = b.CategoryUid
	x.ClassName = b.ClassName
	x.ClassUid = b.ClassUid
	x.Cloud = b.Cloud
	x.Count = b.Count
	x.Duration = b.Duration
	x.EndTime = b.EndTime
	x.Enrichments = b.Enrichments
	x.Message = b.Message
	x.Metadata = b.Metadata
	x.Observables = b.Observables
	x.RawData = b.RawData
	x.Severity = b.Severity
	x.SeverityId = b.SeverityId
	x.StartTime = b.StartTime
	x.Status = b.Status
	x.StatusCode = b.StatusCode
	x.StatusDetail = b.StatusDetail
	x.StatusId = b.StatusId
	x.Time = b.Time
	x.TimezoneOffset = b.TimezoneOffset
	x.TypeName = b.TypeName
	x.TypeUid = b.TypeUid
	x.Unmapped = b.Unmapped
	return m0
}

// Event: discovery
// Event UID: 1
// URL: https://schema.ocsf.io/1.0.0/classes/inventory_info
type InventoryInfo struct {
	state          protoimpl.MessageState            `protogen:"hybrid.v1"`
	ActivityId     enums.INVENTORY_INFO_ACTIVITY_ID  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3,enum=ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_ACTIVITY_ID" json:"activity_id,omitempty"`     // Caption: Activity ID;
	ActivityName   string                            `protobuf:"bytes,2,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`                                                                   // Caption: Activity;
	Actor          *objects.Actor                    `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`                                                                                                     // Caption: Actor;
	Api            *objects.Api                      `protobuf:"bytes,4,opt,name=api,proto3" json:"api,omitempty"`                                                                                                         // Caption: API Details; Profile: cloud;
	CategoryName   string                            `protobuf:"bytes,5,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`                                                                   // Caption: Category;
	CategoryUid    enums.INVENTORY_INFO_CATEGORY_UID `protobuf:"varint,6,opt,name=category_uid,json=categoryUid,proto3,enum=ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_CATEGORY_UID" json:"category_uid,omitempty"` // Caption: Category ID;
	ClassName      string                            `protobuf:"bytes,7,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`                                                                            // Caption: Class;
	ClassUid       enums.INVENTORY_INFO_CLASS_UID    `protobuf:"varint,8,opt,name=class_uid,json=classUid,proto3,enum=ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_CLASS_UID" json:"class_uid,omitempty"`             // Caption: Class ID;
	Cloud          *objects.Cloud                    `protobuf:"bytes,9,opt,name=cloud,proto3" json:"cloud,omitempty"`                                                                                                     // Caption: Cloud; Profile: cloud;
	Count          int32                             `protobuf:"varint,10,opt,name=count,proto3" json:"count,omitempty"`                                                                                                   // Caption: Count;
	Device         *objects.Device                   `protobuf:"bytes,11,opt,name=device,proto3" json:"device,omitempty"`                                                                                                  // Caption: Device;
	Duration       int32                             `protobuf:"varint,12,opt,name=duration,proto3" json:"duration,omitempty"`                                                                                             // Caption: Duration;
	EndTime        int64                             `protobuf:"varint,13,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                                                                                // Caption: End Time;
	Enrichments    []*objects.Enrichment             `protobuf:"bytes,14,rep,name=enrichments,proto3" json:"enrichments,omitempty"`                                                                                        // Caption: Enrichments;
	Message        string                            `protobuf:"bytes,15,opt,name=message,proto3" json:"message,omitempty"`                                                                                                // Caption: Message;
	Metadata       *objects.Metadata                 `protobuf:"bytes,16,opt,name=metadata,proto3" json:"metadata,omitempty"`                                                                                              // Caption: Metadata;
	Observables    []*objects.Observable             `protobuf:"bytes,17,rep,name=observables,proto3" json:"observables,omitempty"`                                                                                        // Caption: Observables;
	RawData        string                            `protobuf:"bytes,18,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`                                                                                 // Caption: Raw Data;
	Severity       string                            `protobuf:"bytes,19,opt,name=severity,proto3" json:"severity,omitempty"`                                                                                              // Caption: Severity;
	SeverityId     enums.INVENTORY_INFO_SEVERITY_ID  `protobuf:"varint,20,opt,name=severity_id,json=severityId,proto3,enum=ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_SEVERITY_ID" json:"severity_id,omitempty"`    // Caption: Severity ID;
	StartTime      int64                             `protobuf:"varint,21,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                                                                          // Caption: Start Time;
	Status         string                            `protobuf:"bytes,22,opt,name=status,proto3" json:"status,omitempty"`                                                                                                  // Caption: Status;
	StatusCode     string                            `protobuf:"bytes,23,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                                        // Caption: Status Code;
	StatusDetail   string                            `protobuf:"bytes,24,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"`                                                                  // Caption: Status Details;
	StatusId       enums.INVENTORY_INFO_STATUS_ID    `protobuf:"varint,25,opt,name=status_id,json=statusId,proto3,enum=ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_STATUS_ID" json:"status_id,omitempty"`            // Caption: Status ID;
	Time           int64                             `protobuf:"varint,26,opt,name=time,proto3" json:"time,omitempty"`                                                                                                     // Caption: Event Time;
	TimezoneOffset int32                             `protobuf:"varint,27,opt,name=timezone_offset,json=timezoneOffset,proto3" json:"timezone_offset,omitempty"`                                                           // Caption: Timezone Offset;
	TypeName       string                            `protobuf:"bytes,28,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`                                                                              // Caption: Type Name;
	TypeUid        enums.INVENTORY_INFO_TYPE_UID     `protobuf:"varint,29,opt,name=type_uid,json=typeUid,proto3,enum=ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_TYPE_UID" json:"type_uid,omitempty"`                // Caption: Type ID;
	Unmapped       *structpb.Struct                  `protobuf:"bytes,30,opt,name=unmapped,proto3" json:"unmapped,omitempty"`                                                                                              // Caption: Unmapped Data;
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InventoryInfo) Reset() {
	*x = InventoryInfo{}
	mi := &file_ocsf_v1_0_0_events_discovery_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryInfo) ProtoMessage() {}

func (x *InventoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ocsf_v1_0_0_events_discovery_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InventoryInfo) GetActivityId() enums.INVENTORY_INFO_ACTIVITY_ID {
	if x != nil {
		return x.ActivityId
	}
	return enums.INVENTORY_INFO_ACTIVITY_ID(0)
}

func (x *InventoryInfo) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *InventoryInfo) GetActor() *objects.Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *InventoryInfo) GetApi() *objects.Api {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *InventoryInfo) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *InventoryInfo) GetCategoryUid() enums.INVENTORY_INFO_CATEGORY_UID {
	if x != nil {
		return x.CategoryUid
	}
	return enums.INVENTORY_INFO_CATEGORY_UID(0)
}

func (x *InventoryInfo) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *InventoryInfo) GetClassUid() enums.INVENTORY_INFO_CLASS_UID {
	if x != nil {
		return x.ClassUid
	}
	return enums.INVENTORY_INFO_CLASS_UID(0)
}

func (x *InventoryInfo) GetCloud() *objects.Cloud {
	if x != nil {
		return x.Cloud
	}
	return nil
}

func (x *InventoryInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *InventoryInfo) GetDevice() *objects.Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *InventoryInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *InventoryInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *InventoryInfo) GetEnrichments() []*objects.Enrichment {
	if x != nil {
		return x.Enrichments
	}
	return nil
}

func (x *InventoryInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InventoryInfo) GetMetadata() *objects.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InventoryInfo) GetObservables() []*objects.Observable {
	if x != nil {
		return x.Observables
	}
	return nil
}

func (x *InventoryInfo) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *InventoryInfo) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *InventoryInfo) GetSeverityId() enums.INVENTORY_INFO_SEVERITY_ID {
	if x != nil {
		return x.SeverityId
	}
	return enums.INVENTORY_INFO_SEVERITY_ID(0)
}

func (x *InventoryInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *InventoryInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InventoryInfo) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *InventoryInfo) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

func (x *InventoryInfo) GetStatusId() enums.INVENTORY_INFO_STATUS_ID {
	if x != nil {
		return x.StatusId
	}
	return enums.INVENTORY_INFO_STATUS_ID(0)
}

func (x *InventoryInfo) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *InventoryInfo) GetTimezoneOffset() int32 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

func (x *InventoryInfo) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *InventoryInfo) GetTypeUid() enums.INVENTORY_INFO_TYPE_UID {
	if x != nil {
		return x.TypeUid
	}
	return enums.INVENTORY_INFO_TYPE_UID(0)
}

func (x *InventoryInfo) GetUnmapped() *structpb.Struct {
	if x != nil {
		return x.Unmapped
	}
	return nil
}

func (x *InventoryInfo) SetActivityId(v enums.INVENTORY_INFO_ACTIVITY_ID) {
	x.ActivityId = v
}

func (x *InventoryInfo) SetActivityName(v string) {
	x.ActivityName = v
}

func (x *InventoryInfo) SetActor(v *objects.Actor) {
	x.Actor = v
}

func (x *InventoryInfo) SetApi(v *objects.Api) {
	x.Api = v
}

func (x *InventoryInfo) SetCategoryName(v string) {
	x.CategoryName = v
}

func (x *InventoryInfo) SetCategoryUid(v enums.INVENTORY_INFO_CATEGORY_UID) {
	x.CategoryUid = v
}

func (x *InventoryInfo) SetClassName(v string) {
	x.ClassName = v
}

func (x *InventoryInfo) SetClassUid(v enums.INVENTORY_INFO_CLASS_UID) {
	x.ClassUid = v
}

func (x *InventoryInfo) SetCloud(v *objects.Cloud) {
	x.Cloud = v
}

func (x *InventoryInfo) SetCount(v int32) {
	x.Count = v
}

func (x *InventoryInfo) SetDevice(v *objects.Device) {
	x.Device = v
}

func (x *InventoryInfo) SetDuration(v int32) {
	x.Duration = v
}

func (x *InventoryInfo) SetEndTime(v int64) {
	x.EndTime = v
}

func (x *InventoryInfo) SetEnrichments(v []*objects.Enrichment) {
	x.Enrichments = v
}

func (x *InventoryInfo) SetMessage(v string) {
	x.Message = v
}

func (x *InventoryInfo) SetMetadata(v *objects.Metadata) {
	x.Metadata = v
}

func (x *InventoryInfo) SetObservables(v []*objects.Observable) {
	x.Observables = v
}

func (x *InventoryInfo) SetRawData(v string) {
	x.RawData = v
}

func (x *InventoryInfo) SetSeverity(v string) {
	x.Severity = v
}

func (x *InventoryInfo) SetSeverityId(v enums.INVENTORY_INFO_SEVERITY_ID) {
	x.SeverityId = v
}

func (x *InventoryInfo) SetStartTime(v int64) {
	x.StartTime = v
}

func (x *InventoryInfo) SetStatus(v string) {
	x.Status = v
}

func (x *InventoryInfo) SetStatusCode(v string) {
	x.StatusCode = v
}

func (x *InventoryInfo) SetStatusDetail(v string) {
	x.StatusDetail = v
}

func (x *InventoryInfo) SetStatusId(v enums.INVENTORY_INFO_STATUS_ID) {
	x.StatusId = v
}

func (x *InventoryInfo) SetTime(v int64) {
	x.Time = v
}

func (x *InventoryInfo) SetTimezoneOffset(v int32) {
	x.TimezoneOffset = v
}

func (x *InventoryInfo) SetTypeName(v string) {
	x.TypeName = v
}

func (x *InventoryInfo) SetTypeUid(v enums.INVENTORY_INFO_TYPE_UID) {
	x.TypeUid = v
}

func (x *InventoryInfo) SetUnmapped(v *structpb.Struct) {
	x.Unmapped = v
}

func (x *InventoryInfo) HasActor() bool {
	if x == nil {
		return false
	}
	return x.Actor != nil
}

func (x *InventoryInfo) HasApi() bool {
	if x == nil {
		return false
	}
	return x.Api != nil
}

func (x *InventoryInfo) HasCloud() bool {
	if x == nil {
		return false
	}
	return x.Cloud != nil
}

func (x *InventoryInfo) HasDevice() bool {
	if x == nil {
		return false
	}
	return x.Device != nil
}

func (x *InventoryInfo) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *InventoryInfo) HasUnmapped() bool {
	if x == nil {
		return false
	}
	return x.Unmapped != nil
}

func (x *InventoryInfo) ClearActor() {
	x.Actor = nil
}

func (x *InventoryInfo) ClearApi() {
	x.Api = nil
}

func (x *InventoryInfo) ClearCloud() {
	x.Cloud = nil
}

func (x *InventoryInfo) ClearDevice() {
	x.Device = nil
}

func (x *InventoryInfo) ClearMetadata() {
	x.Metadata = nil
}

func (x *InventoryInfo) ClearUnmapped() {
	x.Unmapped = nil
}

type InventoryInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ActivityId     enums.INVENTORY_INFO_ACTIVITY_ID
	ActivityName   string
	Actor          *objects.Actor
	Api            *objects.Api
	CategoryName   string
	CategoryUid    enums.INVENTORY_INFO_CATEGORY_UID
	ClassName      string
	ClassUid       enums.INVENTORY_INFO_CLASS_UID
	Cloud          *objects.Cloud
	Count          int32
	Device         *objects.Device
	Duration       int32
	EndTime        int64
	Enrichments    []*objects.Enrichment
	Message        string
	Metadata       *objects.Metadata
	Observables    []*objects.Observable
	RawData        string
	Severity       string
	SeverityId     enums.INVENTORY_INFO_SEVERITY_ID
	StartTime      int64
	Status         string
	StatusCode     string
	StatusDetail   string
	StatusId       enums.INVENTORY_INFO_STATUS_ID
	Time           int64
	TimezoneOffset int32
	TypeName       string
	TypeUid        enums.INVENTORY_INFO_TYPE_UID
	Unmapped       *structpb.Struct
}

func (b0 InventoryInfo_builder) Build() *InventoryInfo {
	m0 := &InventoryInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.ActivityId = b.ActivityId
	x.ActivityName = b.ActivityName
	x.Actor = b.Actor
	x.Api = b.Api
	x.CategoryName = b.CategoryName
	x.CategoryUid = b.CategoryUid
	x.ClassName = b.ClassName
	x.ClassUid = b.ClassUid
	x.Cloud = b.Cloud
	x.Count = b.Count
	x.Device = b.Device
	x.Duration = b.Duration
	x.EndTime = b.EndTime
	x.Enrichments = b.Enrichments
	x.Message = b.Message
	x.Metadata = b.Metadata
	x.Observables = b.Observables
	x.RawData = b.RawData
	x.Severity = b.Severity
	x.SeverityId = b.SeverityId
	x.StartTime = b.StartTime
	x.Status = b.Status
	x.StatusCode = b.StatusCode
	x.StatusDetail = b.StatusDetail
	x.StatusId = b.StatusId
	x.Time = b.Time
	x.TimezoneOffset = b.TimezoneOffset
	x.TypeName = b.TypeName
	x.TypeUid = b.TypeUid
	x.Unmapped = b.Unmapped
	return m0
}

var File_ocsf_v1_0_0_events_discovery_discovery_proto protoreflect.FileDescriptor

const file_ocsf_v1_0_0_events_discovery_discovery_proto_rawDesc = "" +
	"\n" +
	",ocsf/v1_0_0/events/discovery/discovery.proto\x12\x1cocsf.v1_0_0.events.discovery\x1a.ocsf/v1_0_0/events/discovery/enums/enums.proto\x1a!ocsf/v1_0_0/objects/objects.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa9\f\n" +
	"\vConfigState\x12]\n" +
	"\vactivity_id\x18\x01 \x01(\x0e2<.ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_ACTIVITY_IDR\n" +
	"activityId\x12#\n" +
	"\ractivity_name\x18\x02 \x01(\tR\factivityName\x120\n" +
	"\x05actor\x18\x03 \x01(\v2\x1a.ocsf.v1_0_0.objects.ActorR\x05actor\x12*\n" +
	"\x03api\x18\x04 \x01(\v2\x18.ocsf.v1_0_0.objects.ApiR\x03api\x12#\n" +
	"\rcategory_name\x18\x05 \x01(\tR\fcategoryName\x12`\n" +
	"\fcategory_uid\x18\x06 \x01(\x0e2=.ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_CATEGORY_UIDR\vcategoryUid\x12Y\n" +
	"\x14cis_benchmark_result\x18\a \x01(\v2'.ocsf.v1_0_0.objects.CisBenchmarkResultR\x12cisBenchmarkResult\x12\x1d\n" +
	"\n" +
	"class_name\x18\b \x01(\tR\tclassName\x12W\n" +
	"\tclass_uid\x18\t \x01(\x0e2:.ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_CLASS_UIDR\bclassUid\x120\n" +
	"\x05cloud\x18\n" +
	" \x01(\v2\x1a.ocsf.v1_0_0.objects.CloudR\x05cloud\x12\x14\n" +
	"\x05count\x18\v \x01(\x05R\x05count\x123\n" +
	"\x06device\x18\f \x01(\v2\x1b.ocsf.v1_0_0.objects.DeviceR\x06device\x12\x1a\n" +
	"\bduration\x18\r \x01(\x05R\bduration\x12\x19\n" +
	"\bend_time\x18\x0e \x01(\x03R\aendTime\x12A\n" +
	"\venrichments\x18\x0f \x03(\v2\x1f.ocsf.v1_0_0.objects.EnrichmentR\venrichments\x12\x18\n" +
	"\amessage\x18\x10 \x01(\tR\amessage\x129\n" +
	"\bmetadata\x18\x11 \x01(\v2\x1d.ocsf.v1_0_0.objects.MetadataR\bmetadata\x12A\n" +
	"\vobservables\x18\x12 \x03(\v2\x1f.ocsf.v1_0_0.objects.ObservableR\vobservables\x12\x19\n" +
	"\braw_data\x18\x13 \x01(\tR\arawData\x12\x1a\n" +
	"\bseverity\x18\x14 \x01(\tR\bseverity\x12]\n" +
	"\vseverity_id\x18\x15 \x01(\x0e2<.ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_SEVERITY_IDR\n" +
	"severityId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x16 \x01(\x03R\tstartTime\x12\x16\n" +
	"\x06status\x18\x17 \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18\x18 \x01(\tR\n" +
	"statusCode\x12#\n" +
	"\rstatus_detail\x18\x19 \x01(\tR\fstatusDetail\x12W\n" +
	"\tstatus_id\x18\x1a \x01(\x0e2:.ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_STATUS_IDR\bstatusId\x12\x12\n" +
	"\x04time\x18\x1b \x01(\x03R\x04time\x12'\n" +
	"\x0ftimezone_offset\x18\x1c \x01(\x05R\x0etimezoneOffset\x12\x1b\n" +
	"\ttype_name\x18\x1d \x01(\tR\btypeName\x12T\n" +
	"\btype_uid\x18\x1e \x01(\x0e29.ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_TYPE_UIDR\atypeUid\x123\n" +
	"\bunmapped\x18\x1f \x01(\v2\x17.google.protobuf.StructR\bunmapped\"\xd3\n" +
	"\n" +
	"\tDiscovery\x12Z\n" +
	"\vactivity_id\x18\x01 \x01(\x0e29.ocsf.v1_0_0.events.discovery.enums.DISCOVERY_ACTIVITY_IDR\n" +
	"activityId\x12#\n" +
	"\ractivity_name\x18\x02 \x01(\tR\factivityName\x12*\n" +
	"\x03api\x18\x03 \x01(\v2\x18.ocsf.v1_0_0.objects.ApiR\x03api\x12#\n" +
	"\rcategory_name\x18\x04 \x01(\tR\fcategoryName\x12]\n" +
	"\fcategory_uid\x18\x05 \x01(\x0e2:.ocsf.v1_0_0.events.discovery.enums.DISCOVERY_CATEGORY_UIDR\vcategoryUid\x12\x1d\n" +
	"\n" +
	"class_name\x18\x06 \x01(\tR\tclassName\x12T\n" +
	"\tclass_uid\x18\a \x01(\x0e27.ocsf.v1_0_0.events.discovery.enums.DISCOVERY_CLASS_UIDR\bclassUid\x120\n" +
	"\x05cloud\x18\b \x01(\v2\x1a.ocsf.v1_0_0.objects.CloudR\x05cloud\x12\x14\n" +
	"\x05count\x18\t \x01(\x05R\x05count\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\x05R\bduration\x12\x19\n" +
	"\bend_time\x18\v \x01(\x03R\aendTime\x12A\n" +
	"\venrichments\x18\f \x03(\v2\x1f.ocsf.v1_0_0.objects.EnrichmentR\venrichments\x12\x18\n" +
	"\amessage\x18\r \x01(\tR\amessage\x129\n" +
	"\bmetadata\x18\x0e \x01(\v2\x1d.ocsf.v1_0_0.objects.MetadataR\bmetadata\x12A\n" +
	"\vobservables\x18\x0f \x03(\v2\x1f.ocsf.v1_0_0.objects.ObservableR\vobservables\x12\x19\n" +
	"\braw_data\x18\x10 \x01(\tR\arawData\x12\x1a\n" +
	"\bseverity\x18\x11 \x01(\tR\bseverity\x12Z\n" +
	"\vseverity_id\x18\x12 \x01(\x0e29.ocsf.v1_0_0.events.discovery.enums.DISCOVERY_SEVERITY_IDR\n" +
	"severityId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x13 \x01(\x03R\tstartTime\x12\x16\n" +
	"\x06status\x18\x14 \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18\x15 \x01(\tR\n" +
	"statusCode\x12#\n" +
	"\rstatus_detail\x18\x16 \x01(\tR\fstatusDetail\x12T\n" +
	"\tstatus_id\x18\x17 \x01(\x0e27.ocsf.v1_0_0.events.discovery.enums.DISCOVERY_STATUS_IDR\bstatusId\x12\x12\n" +
	"\x04time\x18\x18 \x01(\x03R\x04time\x12'\n" +
	"\x0ftimezone_offset\x18\x19 \x01(\x05R\x0etimezoneOffset\x12\x1b\n" +
	"\ttype_name\x18\x1a \x01(\tR\btypeName\x12Q\n" +
	"\btype_uid\x18\x1b \x01(\x0e26.ocsf.v1_0_0.events.discovery.enums.DISCOVERY_TYPE_UIDR\atypeUid\x123\n" +
	"\bunmapped\x18\x1c \x01(\v2\x17.google.protobuf.StructR\bunmapped\"\xdc\v\n" +
	"\rInventoryInfo\x12_\n" +
	"\vactivity_id\x18\x01 \x01(\x0e2>.ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_ACTIVITY_IDR\n" +
	"activityId\x12#\n" +
	"\ractivity_name\x18\x02 \x01(\tR\factivityName\x120\n" +
	"\x05actor\x18\x03 \x01(\v2\x1a.ocsf.v1_0_0.objects.ActorR\x05actor\x12*\n" +
	"\x03api\x18\x04 \x01(\v2\x18.ocsf.v1_0_0.objects.ApiR\x03api\x12#\n" +
	"\rcategory_name\x18\x05 \x01(\tR\fcategoryName\x12b\n" +
	"\fcategory_uid\x18\x06 \x01(\x0e2?.ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_CATEGORY_UIDR\vcategoryUid\x12\x1d\n" +
	"\n" +
	"class_name\x18\a \x01(\tR\tclassName\x12Y\n" +
	"\tclass_uid\x18\b \x01(\x0e2<.ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_CLASS_UIDR\bclassUid\x120\n" +
	"\x05cloud\x18\t \x01(\v2\x1a.ocsf.v1_0_0.objects.CloudR\x05cloud\x12\x14\n" +
	"\x05count\x18\n" +
	" \x01(\x05R\x05count\x123\n" +
	"\x06device\x18\v \x01(\v2\x1b.ocsf.v1_0_0.objects.DeviceR\x06device\x12\x1a\n" +
	"\bduration\x18\f \x01(\x05R\bduration\x12\x19\n" +
	"\bend_time\x18\r \x01(\x03R\aendTime\x12A\n" +
	"\venrichments\x18\x0e \x03(\v2\x1f.ocsf.v1_0_0.objects.EnrichmentR\venrichments\x12\x18\n" +
	"\amessage\x18\x0f \x01(\tR\amessage\x129\n" +
	"\bmetadata\x18\x10 \x01(\v2\x1d.ocsf.v1_0_0.objects.MetadataR\bmetadata\x12A\n" +
	"\vobservables\x18\x11 \x03(\v2\x1f.ocsf.v1_0_0.objects.ObservableR\vobservables\x12\x19\n" +
	"\braw_data\x18\x12 \x01(\tR\arawData\x12\x1a\n" +
	"\bseverity\x18\x13 \x01(\tR\bseverity\x12_\n" +
	"\vseverity_id\x18\x14 \x01(\x0e2>.ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_SEVERITY_IDR\n" +
	"severityId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x15 \x01(\x03R\tstartTime\x12\x16\n" +
	"\x06status\x18\x16 \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18\x17 \x01(\tR\n" +
	"statusCode\x12#\n" +
	"\rstatus_detail\x18\x18 \x01(\tR\fstatusDetail\x12Y\n" +
	"\tstatus_id\x18\x19 \x01(\x0e2<.ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_STATUS_IDR\bstatusId\x12\x12\n" +
	"\x04time\x18\x1a \x01(\x03R\x04time\x12'\n" +
	"\x0ftimezone_offset\x18\x1b \x01(\x05R\x0etimezoneOffset\x12\x1b\n" +
	"\ttype_name\x18\x1c \x01(\tR\btypeName\x12V\n" +
	"\btype_uid\x18\x1d \x01(\x0e2;.ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_TYPE_UIDR\atypeUid\x123\n" +
	"\bunmapped\x18\x1e \x01(\v2\x17.google.protobuf.StructR\bunmappedB\x83\x02\n" +
	" com.ocsf.v1_0_0.events.discoveryB\x0eDiscoveryProtoP\x01ZCgithub.com/valllabh/ocsf-schema-golang/ocsf/v1_0_0/events/discovery\xa2\x02\x04OVED\xaa\x02\x1aOcsf.V100.Events.Discovery\xca\x02\x1aOcsf\\V100\\Events\\Discovery\xe2\x02&Ocsf\\V100\\Events\\Discovery\\GPBMetadata\xea\x02\x1dOcsf::V100::Events::Discoveryb\x06proto3"

var file_ocsf_v1_0_0_events_discovery_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ocsf_v1_0_0_events_discovery_discovery_proto_goTypes = []any{
	(*ConfigState)(nil),                    // 0: ocsf.v1_0_0.events.discovery.ConfigState
	(*Discovery)(nil),                      // 1: ocsf.v1_0_0.events.discovery.Discovery
	(*InventoryInfo)(nil),                  // 2: ocsf.v1_0_0.events.discovery.InventoryInfo
	(enums.CONFIG_STATE_ACTIVITY_ID)(0),    // 3: ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_ACTIVITY_ID
	(*objects.Actor)(nil),                  // 4: ocsf.v1_0_0.objects.Actor
	(*objects.Api)(nil),                    // 5: ocsf.v1_0_0.objects.Api
	(enums.CONFIG_STATE_CATEGORY_UID)(0),   // 6: ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_CATEGORY_UID
	(*objects.CisBenchmarkResult)(nil),     // 7: ocsf.v1_0_0.objects.CisBenchmarkResult
	(enums.CONFIG_STATE_CLASS_UID)(0),      // 8: ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_CLASS_UID
	(*objects.Cloud)(nil),                  // 9: ocsf.v1_0_0.objects.Cloud
	(*objects.Device)(nil),                 // 10: ocsf.v1_0_0.objects.Device
	(*objects.Enrichment)(nil),             // 11: ocsf.v1_0_0.objects.Enrichment
	(*objects.Metadata)(nil),               // 12: ocsf.v1_0_0.objects.Metadata
	(*objects.Observable)(nil),             // 13: ocsf.v1_0_0.objects.Observable
	(enums.CONFIG_STATE_SEVERITY_ID)(0),    // 14: ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_SEVERITY_ID
	(enums.CONFIG_STATE_STATUS_ID)(0),      // 15: ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_STATUS_ID
	(enums.CONFIG_STATE_TYPE_UID)(0),       // 16: ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_TYPE_UID
	(*structpb.Struct)(nil),                // 17: google.protobuf.Struct
	(enums.DISCOVERY_ACTIVITY_ID)(0),       // 18: ocsf.v1_0_0.events.discovery.enums.DISCOVERY_ACTIVITY_ID
	(enums.DISCOVERY_CATEGORY_UID)(0),      // 19: ocsf.v1_0_0.events.discovery.enums.DISCOVERY_CATEGORY_UID
	(enums.DISCOVERY_CLASS_UID)(0),         // 20: ocsf.v1_0_0.events.discovery.enums.DISCOVERY_CLASS_UID
	(enums.DISCOVERY_SEVERITY_ID)(0),       // 21: ocsf.v1_0_0.events.discovery.enums.DISCOVERY_SEVERITY_ID
	(enums.DISCOVERY_STATUS_ID)(0),         // 22: ocsf.v1_0_0.events.discovery.enums.DISCOVERY_STATUS_ID
	(enums.DISCOVERY_TYPE_UID)(0),          // 23: ocsf.v1_0_0.events.discovery.enums.DISCOVERY_TYPE_UID
	(enums.INVENTORY_INFO_ACTIVITY_ID)(0),  // 24: ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_ACTIVITY_ID
	(enums.INVENTORY_INFO_CATEGORY_UID)(0), // 25: ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_CATEGORY_UID
	(enums.INVENTORY_INFO_CLASS_UID)(0),    // 26: ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_CLASS_UID
	(enums.INVENTORY_INFO_SEVERITY_ID)(0),  // 27: ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_SEVERITY_ID
	(enums.INVENTORY_INFO_STATUS_ID)(0),    // 28: ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_STATUS_ID
	(enums.INVENTORY_INFO_TYPE_UID)(0),     // 29: ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_TYPE_UID
}
var file_ocsf_v1_0_0_events_discovery_discovery_proto_depIdxs = []int32{
	3,  // 0: ocsf.v1_0_0.events.discovery.ConfigState.activity_id:type_name -> ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_ACTIVITY_ID
	4,  // 1: ocsf.v1_0_0.events.discovery.ConfigState.actor:type_name -> ocsf.v1_0_0.objects.Actor
	5,  // 2: ocsf.v1_0_0.events.discovery.ConfigState.api:type_name -> ocsf.v1_0_0.objects.Api
	6,  // 3: ocsf.v1_0_0.events.discovery.ConfigState.category_uid:type_name -> ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_CATEGORY_UID
	7,  // 4: ocsf.v1_0_0.events.discovery.ConfigState.cis_benchmark_result:type_name -> ocsf.v1_0_0.objects.CisBenchmarkResult
	8,  // 5: ocsf.v1_0_0.events.discovery.ConfigState.class_uid:type_name -> ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_CLASS_UID
	9,  // 6: ocsf.v1_0_0.events.discovery.ConfigState.cloud:type_name -> ocsf.v1_0_0.objects.Cloud
	10, // 7: ocsf.v1_0_0.events.discovery.ConfigState.device:type_name -> ocsf.v1_0_0.objects.Device
	11, // 8: ocsf.v1_0_0.events.discovery.ConfigState.enrichments:type_name -> ocsf.v1_0_0.objects.Enrichment
	12, // 9: ocsf.v1_0_0.events.discovery.ConfigState.metadata:type_name -> ocsf.v1_0_0.objects.Metadata
	13, // 10: ocsf.v1_0_0.events.discovery.ConfigState.observables:type_name -> ocsf.v1_0_0.objects.Observable
	14, // 11: ocsf.v1_0_0.events.discovery.ConfigState.severity_id:type_name -> ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_SEVERITY_ID
	15, // 12: ocsf.v1_0_0.events.discovery.ConfigState.status_id:type_name -> ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_STATUS_ID
	16, // 13: ocsf.v1_0_0.events.discovery.ConfigState.type_uid:type_name -> ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_TYPE_UID
	17, // 14: ocsf.v1_0_0.events.discovery.ConfigState.unmapped:type_name -> google.protobuf.Struct
	18, // 15: ocsf.v1_0_0.events.discovery.Discovery.activity_id:type_name -> ocsf.v1_0_0.events.discovery.enums.DISCOVERY_ACTIVITY_ID
	5,  // 16: ocsf.v1_0_0.events.discovery.Discovery.api:type_name -> ocsf.v1_0_0.objects.Api
	19, // 17: ocsf.v1_0_0.events.discovery.Discovery.category_uid:type_name -> ocsf.v1_0_0.events.discovery.enums.DISCOVERY_CATEGORY_UID
	20, // 18: ocsf.v1_0_0.events.discovery.Discovery.class_uid:type_name -> ocsf.v1_0_0.events.discovery.enums.DISCOVERY_CLASS_UID
	9,  // 19: ocsf.v1_0_0.events.discovery.Discovery.cloud:type_name -> ocsf.v1_0_0.objects.Cloud
	11, // 20: ocsf.v1_0_0.events.discovery.Discovery.enrichments:type_name -> ocsf.v1_0_0.objects.Enrichment
	12, // 21: ocsf.v1_0_0.events.discovery.Discovery.metadata:type_name -> ocsf.v1_0_0.objects.Metadata
	13, // 22: ocsf.v1_0_0.events.discovery.Discovery.observables:type_name -> ocsf.v1_0_0.objects.Observable
	21, // 23: ocsf.v1_0_0.events.discovery.Discovery.severity_id:type_name -> ocsf.v1_0_0.events.discovery.enums.DISCOVERY_SEVERITY_ID
	22, // 24: ocsf.v1_0_0.events.discovery.Discovery.status_id:type_name -> ocsf.v1_0_0.events.discovery.enums.DISCOVERY_STATUS_ID
	23, // 25: ocsf.v1_0_0.events.discovery.Discovery.type_uid:type_name -> ocsf.v1_0_0.events.discovery.enums.DISCOVERY_TYPE_UID
	17, // 26: ocsf.v1_0_0.events.discovery.Discovery.unmapped:type_name -> google.protobuf.Struct
	24, // 27: ocsf.v1_0_0.events.discovery.InventoryInfo.activity_id:type_name -> ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_ACTIVITY_ID
	4,  // 28: ocsf.v1_0_0.events.discovery.InventoryInfo.actor:type_name -> ocsf.v1_0_0.objects.Actor
	5,  // 29: ocsf.v1_0_0.events.discovery.InventoryInfo.api:type_name -> ocsf.v1_0_0.objects.Api
	25, // 30: ocsf.v1_0_0.events.discovery.InventoryInfo.category_uid:type_name -> ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_CATEGORY_UID
	26, // 31: ocsf.v1_0_0.events.discovery.InventoryInfo.class_uid:type_name -> ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_CLASS_UID
	9,  // 32: ocsf.v1_0_0.events.discovery.InventoryInfo.cloud:type_name -> ocsf.v1_0_0.objects.Cloud
	10, // 33: ocsf.v1_0_0.events.discovery.InventoryInfo.device:type_name -> ocsf.v1_0_0.objects.Device
	11, // 34: ocsf.v1_0_0.events.discovery.InventoryInfo.enrichments:type_name -> ocsf.v1_0_0.objects.Enrichment
	12, // 35: ocsf.v1_0_0.events.discovery.InventoryInfo.metadata:type_name -> ocsf.v1_0_0.objects.Metadata
	13, // 36: ocsf.v1_0_0.events.discovery.InventoryInfo.observables:type_name -> ocsf.v1_0_0.objects.Observable
	27, // 37: ocsf.v1_0_0.events.discovery.InventoryInfo.severity_id:type_name -> ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_SEVERITY_ID
	28, // 38: ocsf.v1_0_0.events.discovery.InventoryInfo.status_id:type_name -> ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_STATUS_ID
	29, // 39: ocsf.v1_0_0.events.discovery.InventoryInfo.type_uid:type_name -> ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_TYPE_UID
	17, // 40: ocsf.v1_0_0.events.discovery.InventoryInfo.unmapped:type_name -> google.protobuf.Struct
	41, // [41:41] is the sub-list for method output_type
	41, // [41:41] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_ocsf_v1_0_0_events_discovery_discovery_proto_init() }
func file_ocsf_v1_0_0_events_discovery_discovery_proto_init() {
	if File_ocsf_v1_0_0_events_discovery_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocsf_v1_0_0_events_discovery_discovery_proto_rawDesc), len(file_ocsf_v1_0_0_events_discovery_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocsf_v1_0_0_events_discovery_discovery_proto_goTypes,
		DependencyIndexes: file_ocsf_v1_0_0_events_discovery_discovery_proto_depIdxs,
		MessageInfos:      file_ocsf_v1_0_0_events_discovery_discovery_proto_msgTypes,
	}.Build()
	File_ocsf_v1_0_0_events_discovery_discovery_proto = out.File
	file_ocsf_v1_0_0_events_discovery_discovery_proto_goTypes = nil
	file_ocsf_v1_0_0_events_discovery_discovery_proto_depIdxs = nil
}
