// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: ocsf/v1_0_0/events/discovery/enums/enums.proto

//go:build protoopaque

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CONFIG_STATE_ACTIVITY_ID int32

const (
	CONFIG_STATE_ACTIVITY_ID_CONFIG_STATE_ACTIVITY_ID_UNKNOWN CONFIG_STATE_ACTIVITY_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	CONFIG_STATE_ACTIVITY_ID_CONFIG_STATE_ACTIVITY_ID_LOG     CONFIG_STATE_ACTIVITY_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	CONFIG_STATE_ACTIVITY_ID_CONFIG_STATE_ACTIVITY_ID_COLLECT CONFIG_STATE_ACTIVITY_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	CONFIG_STATE_ACTIVITY_ID_CONFIG_STATE_ACTIVITY_ID_OTHER   CONFIG_STATE_ACTIVITY_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for CONFIG_STATE_ACTIVITY_ID.
var (
	CONFIG_STATE_ACTIVITY_ID_name = map[int32]string{
		0:  "CONFIG_STATE_ACTIVITY_ID_UNKNOWN",
		1:  "CONFIG_STATE_ACTIVITY_ID_LOG",
		2:  "CONFIG_STATE_ACTIVITY_ID_COLLECT",
		99: "CONFIG_STATE_ACTIVITY_ID_OTHER",
	}
	CONFIG_STATE_ACTIVITY_ID_value = map[string]int32{
		"CONFIG_STATE_ACTIVITY_ID_UNKNOWN": 0,
		"CONFIG_STATE_ACTIVITY_ID_LOG":     1,
		"CONFIG_STATE_ACTIVITY_ID_COLLECT": 2,
		"CONFIG_STATE_ACTIVITY_ID_OTHER":   99,
	}
)

func (x CONFIG_STATE_ACTIVITY_ID) Enum() *CONFIG_STATE_ACTIVITY_ID {
	p := new(CONFIG_STATE_ACTIVITY_ID)
	*p = x
	return p
}

func (x CONFIG_STATE_ACTIVITY_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CONFIG_STATE_ACTIVITY_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[0].Descriptor()
}

func (CONFIG_STATE_ACTIVITY_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[0]
}

func (x CONFIG_STATE_ACTIVITY_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type CONFIG_STATE_CATEGORY_UID int32

const (
	CONFIG_STATE_CATEGORY_UID_CONFIG_STATE_CATEGORY_UID_UNSPECIFIED CONFIG_STATE_CATEGORY_UID = 0 // Type: NON_OCSF_VALUE;
	CONFIG_STATE_CATEGORY_UID_CONFIG_STATE_CATEGORY_UID_DISCOVERY   CONFIG_STATE_CATEGORY_UID = 5 // Type: OCSF_VALUE; EnumValue: 5;
)

// Enum value maps for CONFIG_STATE_CATEGORY_UID.
var (
	CONFIG_STATE_CATEGORY_UID_name = map[int32]string{
		0: "CONFIG_STATE_CATEGORY_UID_UNSPECIFIED",
		5: "CONFIG_STATE_CATEGORY_UID_DISCOVERY",
	}
	CONFIG_STATE_CATEGORY_UID_value = map[string]int32{
		"CONFIG_STATE_CATEGORY_UID_UNSPECIFIED": 0,
		"CONFIG_STATE_CATEGORY_UID_DISCOVERY":   5,
	}
)

func (x CONFIG_STATE_CATEGORY_UID) Enum() *CONFIG_STATE_CATEGORY_UID {
	p := new(CONFIG_STATE_CATEGORY_UID)
	*p = x
	return p
}

func (x CONFIG_STATE_CATEGORY_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CONFIG_STATE_CATEGORY_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[1].Descriptor()
}

func (CONFIG_STATE_CATEGORY_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[1]
}

func (x CONFIG_STATE_CATEGORY_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type CONFIG_STATE_CLASS_UID int32

const (
	CONFIG_STATE_CLASS_UID_CONFIG_STATE_CLASS_UID_UNSPECIFIED         CONFIG_STATE_CLASS_UID = 0    // Type: NON_OCSF_VALUE;
	CONFIG_STATE_CLASS_UID_CONFIG_STATE_CLASS_UID_DEVICE_CONFIG_STATE CONFIG_STATE_CLASS_UID = 5002 // Type: OCSF_VALUE; EnumValue: 5002;
)

// Enum value maps for CONFIG_STATE_CLASS_UID.
var (
	CONFIG_STATE_CLASS_UID_name = map[int32]string{
		0:    "CONFIG_STATE_CLASS_UID_UNSPECIFIED",
		5002: "CONFIG_STATE_CLASS_UID_DEVICE_CONFIG_STATE",
	}
	CONFIG_STATE_CLASS_UID_value = map[string]int32{
		"CONFIG_STATE_CLASS_UID_UNSPECIFIED":         0,
		"CONFIG_STATE_CLASS_UID_DEVICE_CONFIG_STATE": 5002,
	}
)

func (x CONFIG_STATE_CLASS_UID) Enum() *CONFIG_STATE_CLASS_UID {
	p := new(CONFIG_STATE_CLASS_UID)
	*p = x
	return p
}

func (x CONFIG_STATE_CLASS_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CONFIG_STATE_CLASS_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[2].Descriptor()
}

func (CONFIG_STATE_CLASS_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[2]
}

func (x CONFIG_STATE_CLASS_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type CONFIG_STATE_SEVERITY_ID int32

const (
	CONFIG_STATE_SEVERITY_ID_CONFIG_STATE_SEVERITY_ID_UNKNOWN       CONFIG_STATE_SEVERITY_ID = 0  // EnumValue: 0; Type: OCSF_VALUE;
	CONFIG_STATE_SEVERITY_ID_CONFIG_STATE_SEVERITY_ID_INFORMATIONAL CONFIG_STATE_SEVERITY_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	CONFIG_STATE_SEVERITY_ID_CONFIG_STATE_SEVERITY_ID_LOW           CONFIG_STATE_SEVERITY_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	CONFIG_STATE_SEVERITY_ID_CONFIG_STATE_SEVERITY_ID_MEDIUM        CONFIG_STATE_SEVERITY_ID = 3  // Type: OCSF_VALUE; EnumValue: 3;
	CONFIG_STATE_SEVERITY_ID_CONFIG_STATE_SEVERITY_ID_HIGH          CONFIG_STATE_SEVERITY_ID = 4  // Type: OCSF_VALUE; EnumValue: 4;
	CONFIG_STATE_SEVERITY_ID_CONFIG_STATE_SEVERITY_ID_CRITICAL      CONFIG_STATE_SEVERITY_ID = 5  // Type: OCSF_VALUE; EnumValue: 5;
	CONFIG_STATE_SEVERITY_ID_CONFIG_STATE_SEVERITY_ID_FATAL         CONFIG_STATE_SEVERITY_ID = 6  // Type: OCSF_VALUE; EnumValue: 6;
	CONFIG_STATE_SEVERITY_ID_CONFIG_STATE_SEVERITY_ID_OTHER         CONFIG_STATE_SEVERITY_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for CONFIG_STATE_SEVERITY_ID.
var (
	CONFIG_STATE_SEVERITY_ID_name = map[int32]string{
		0:  "CONFIG_STATE_SEVERITY_ID_UNKNOWN",
		1:  "CONFIG_STATE_SEVERITY_ID_INFORMATIONAL",
		2:  "CONFIG_STATE_SEVERITY_ID_LOW",
		3:  "CONFIG_STATE_SEVERITY_ID_MEDIUM",
		4:  "CONFIG_STATE_SEVERITY_ID_HIGH",
		5:  "CONFIG_STATE_SEVERITY_ID_CRITICAL",
		6:  "CONFIG_STATE_SEVERITY_ID_FATAL",
		99: "CONFIG_STATE_SEVERITY_ID_OTHER",
	}
	CONFIG_STATE_SEVERITY_ID_value = map[string]int32{
		"CONFIG_STATE_SEVERITY_ID_UNKNOWN":       0,
		"CONFIG_STATE_SEVERITY_ID_INFORMATIONAL": 1,
		"CONFIG_STATE_SEVERITY_ID_LOW":           2,
		"CONFIG_STATE_SEVERITY_ID_MEDIUM":        3,
		"CONFIG_STATE_SEVERITY_ID_HIGH":          4,
		"CONFIG_STATE_SEVERITY_ID_CRITICAL":      5,
		"CONFIG_STATE_SEVERITY_ID_FATAL":         6,
		"CONFIG_STATE_SEVERITY_ID_OTHER":         99,
	}
)

func (x CONFIG_STATE_SEVERITY_ID) Enum() *CONFIG_STATE_SEVERITY_ID {
	p := new(CONFIG_STATE_SEVERITY_ID)
	*p = x
	return p
}

func (x CONFIG_STATE_SEVERITY_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CONFIG_STATE_SEVERITY_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[3].Descriptor()
}

func (CONFIG_STATE_SEVERITY_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[3]
}

func (x CONFIG_STATE_SEVERITY_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type CONFIG_STATE_STATUS_ID int32

const (
	CONFIG_STATE_STATUS_ID_CONFIG_STATE_STATUS_ID_UNKNOWN CONFIG_STATE_STATUS_ID = 0  // EnumValue: 0; Type: OCSF_VALUE;
	CONFIG_STATE_STATUS_ID_CONFIG_STATE_STATUS_ID_SUCCESS CONFIG_STATE_STATUS_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	CONFIG_STATE_STATUS_ID_CONFIG_STATE_STATUS_ID_FAILURE CONFIG_STATE_STATUS_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	CONFIG_STATE_STATUS_ID_CONFIG_STATE_STATUS_ID_OTHER   CONFIG_STATE_STATUS_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for CONFIG_STATE_STATUS_ID.
var (
	CONFIG_STATE_STATUS_ID_name = map[int32]string{
		0:  "CONFIG_STATE_STATUS_ID_UNKNOWN",
		1:  "CONFIG_STATE_STATUS_ID_SUCCESS",
		2:  "CONFIG_STATE_STATUS_ID_FAILURE",
		99: "CONFIG_STATE_STATUS_ID_OTHER",
	}
	CONFIG_STATE_STATUS_ID_value = map[string]int32{
		"CONFIG_STATE_STATUS_ID_UNKNOWN": 0,
		"CONFIG_STATE_STATUS_ID_SUCCESS": 1,
		"CONFIG_STATE_STATUS_ID_FAILURE": 2,
		"CONFIG_STATE_STATUS_ID_OTHER":   99,
	}
)

func (x CONFIG_STATE_STATUS_ID) Enum() *CONFIG_STATE_STATUS_ID {
	p := new(CONFIG_STATE_STATUS_ID)
	*p = x
	return p
}

func (x CONFIG_STATE_STATUS_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CONFIG_STATE_STATUS_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[4].Descriptor()
}

func (CONFIG_STATE_STATUS_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[4]
}

func (x CONFIG_STATE_STATUS_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type CONFIG_STATE_TYPE_UID int32

const (
	CONFIG_STATE_TYPE_UID_CONFIG_STATE_TYPE_UID_UNSPECIFIED                 CONFIG_STATE_TYPE_UID = 0      // Type: NON_OCSF_VALUE;
	CONFIG_STATE_TYPE_UID_CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_UNKNOWN CONFIG_STATE_TYPE_UID = 500200 // EnumValue: 500200; Type: OCSF_VALUE;
	CONFIG_STATE_TYPE_UID_CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_LOG     CONFIG_STATE_TYPE_UID = 500201 // Type: OCSF_VALUE; EnumValue: 500201;
	CONFIG_STATE_TYPE_UID_CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_COLLECT CONFIG_STATE_TYPE_UID = 500202 // Type: OCSF_VALUE; EnumValue: 500202;
	CONFIG_STATE_TYPE_UID_CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_OTHER   CONFIG_STATE_TYPE_UID = 500299 // Type: OCSF_VALUE; EnumValue: 500299;
)

// Enum value maps for CONFIG_STATE_TYPE_UID.
var (
	CONFIG_STATE_TYPE_UID_name = map[int32]string{
		0:      "CONFIG_STATE_TYPE_UID_UNSPECIFIED",
		500200: "CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_UNKNOWN",
		500201: "CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_LOG",
		500202: "CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_COLLECT",
		500299: "CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_OTHER",
	}
	CONFIG_STATE_TYPE_UID_value = map[string]int32{
		"CONFIG_STATE_TYPE_UID_UNSPECIFIED":                 0,
		"CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_UNKNOWN": 500200,
		"CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_LOG":     500201,
		"CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_COLLECT": 500202,
		"CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_OTHER":   500299,
	}
)

func (x CONFIG_STATE_TYPE_UID) Enum() *CONFIG_STATE_TYPE_UID {
	p := new(CONFIG_STATE_TYPE_UID)
	*p = x
	return p
}

func (x CONFIG_STATE_TYPE_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CONFIG_STATE_TYPE_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[5].Descriptor()
}

func (CONFIG_STATE_TYPE_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[5]
}

func (x CONFIG_STATE_TYPE_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type DISCOVERY_ACTIVITY_ID int32

const (
	DISCOVERY_ACTIVITY_ID_DISCOVERY_ACTIVITY_ID_UNKNOWN DISCOVERY_ACTIVITY_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	DISCOVERY_ACTIVITY_ID_DISCOVERY_ACTIVITY_ID_LOG     DISCOVERY_ACTIVITY_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	DISCOVERY_ACTIVITY_ID_DISCOVERY_ACTIVITY_ID_COLLECT DISCOVERY_ACTIVITY_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	DISCOVERY_ACTIVITY_ID_DISCOVERY_ACTIVITY_ID_OTHER   DISCOVERY_ACTIVITY_ID = 99 // EnumValue: 99; Type: OCSF_VALUE;
)

// Enum value maps for DISCOVERY_ACTIVITY_ID.
var (
	DISCOVERY_ACTIVITY_ID_name = map[int32]string{
		0:  "DISCOVERY_ACTIVITY_ID_UNKNOWN",
		1:  "DISCOVERY_ACTIVITY_ID_LOG",
		2:  "DISCOVERY_ACTIVITY_ID_COLLECT",
		99: "DISCOVERY_ACTIVITY_ID_OTHER",
	}
	DISCOVERY_ACTIVITY_ID_value = map[string]int32{
		"DISCOVERY_ACTIVITY_ID_UNKNOWN": 0,
		"DISCOVERY_ACTIVITY_ID_LOG":     1,
		"DISCOVERY_ACTIVITY_ID_COLLECT": 2,
		"DISCOVERY_ACTIVITY_ID_OTHER":   99,
	}
)

func (x DISCOVERY_ACTIVITY_ID) Enum() *DISCOVERY_ACTIVITY_ID {
	p := new(DISCOVERY_ACTIVITY_ID)
	*p = x
	return p
}

func (x DISCOVERY_ACTIVITY_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DISCOVERY_ACTIVITY_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[6].Descriptor()
}

func (DISCOVERY_ACTIVITY_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[6]
}

func (x DISCOVERY_ACTIVITY_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type DISCOVERY_CATEGORY_UID int32

const (
	DISCOVERY_CATEGORY_UID_DISCOVERY_CATEGORY_UID_UNSPECIFIED DISCOVERY_CATEGORY_UID = 0 // Type: NON_OCSF_VALUE;
	DISCOVERY_CATEGORY_UID_DISCOVERY_CATEGORY_UID_DISCOVERY   DISCOVERY_CATEGORY_UID = 5 // Type: OCSF_VALUE; EnumValue: 5;
)

// Enum value maps for DISCOVERY_CATEGORY_UID.
var (
	DISCOVERY_CATEGORY_UID_name = map[int32]string{
		0: "DISCOVERY_CATEGORY_UID_UNSPECIFIED",
		5: "DISCOVERY_CATEGORY_UID_DISCOVERY",
	}
	DISCOVERY_CATEGORY_UID_value = map[string]int32{
		"DISCOVERY_CATEGORY_UID_UNSPECIFIED": 0,
		"DISCOVERY_CATEGORY_UID_DISCOVERY":   5,
	}
)

func (x DISCOVERY_CATEGORY_UID) Enum() *DISCOVERY_CATEGORY_UID {
	p := new(DISCOVERY_CATEGORY_UID)
	*p = x
	return p
}

func (x DISCOVERY_CATEGORY_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DISCOVERY_CATEGORY_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[7].Descriptor()
}

func (DISCOVERY_CATEGORY_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[7]
}

func (x DISCOVERY_CATEGORY_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type DISCOVERY_CLASS_UID int32

const (
	DISCOVERY_CLASS_UID_DISCOVERY_CLASS_UID_UNSPECIFIED DISCOVERY_CLASS_UID = 0    // Type: NON_OCSF_VALUE;
	DISCOVERY_CLASS_UID_DISCOVERY_CLASS_UID_DISCOVERY   DISCOVERY_CLASS_UID = 5000 // Type: OCSF_VALUE; EnumValue: 5000;
)

// Enum value maps for DISCOVERY_CLASS_UID.
var (
	DISCOVERY_CLASS_UID_name = map[int32]string{
		0:    "DISCOVERY_CLASS_UID_UNSPECIFIED",
		5000: "DISCOVERY_CLASS_UID_DISCOVERY",
	}
	DISCOVERY_CLASS_UID_value = map[string]int32{
		"DISCOVERY_CLASS_UID_UNSPECIFIED": 0,
		"DISCOVERY_CLASS_UID_DISCOVERY":   5000,
	}
)

func (x DISCOVERY_CLASS_UID) Enum() *DISCOVERY_CLASS_UID {
	p := new(DISCOVERY_CLASS_UID)
	*p = x
	return p
}

func (x DISCOVERY_CLASS_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DISCOVERY_CLASS_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[8].Descriptor()
}

func (DISCOVERY_CLASS_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[8]
}

func (x DISCOVERY_CLASS_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type DISCOVERY_SEVERITY_ID int32

const (
	DISCOVERY_SEVERITY_ID_DISCOVERY_SEVERITY_ID_UNKNOWN       DISCOVERY_SEVERITY_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	DISCOVERY_SEVERITY_ID_DISCOVERY_SEVERITY_ID_INFORMATIONAL DISCOVERY_SEVERITY_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	DISCOVERY_SEVERITY_ID_DISCOVERY_SEVERITY_ID_LOW           DISCOVERY_SEVERITY_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	DISCOVERY_SEVERITY_ID_DISCOVERY_SEVERITY_ID_MEDIUM        DISCOVERY_SEVERITY_ID = 3  // Type: OCSF_VALUE; EnumValue: 3;
	DISCOVERY_SEVERITY_ID_DISCOVERY_SEVERITY_ID_HIGH          DISCOVERY_SEVERITY_ID = 4  // EnumValue: 4; Type: OCSF_VALUE;
	DISCOVERY_SEVERITY_ID_DISCOVERY_SEVERITY_ID_CRITICAL      DISCOVERY_SEVERITY_ID = 5  // EnumValue: 5; Type: OCSF_VALUE;
	DISCOVERY_SEVERITY_ID_DISCOVERY_SEVERITY_ID_FATAL         DISCOVERY_SEVERITY_ID = 6  // Type: OCSF_VALUE; EnumValue: 6;
	DISCOVERY_SEVERITY_ID_DISCOVERY_SEVERITY_ID_OTHER         DISCOVERY_SEVERITY_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for DISCOVERY_SEVERITY_ID.
var (
	DISCOVERY_SEVERITY_ID_name = map[int32]string{
		0:  "DISCOVERY_SEVERITY_ID_UNKNOWN",
		1:  "DISCOVERY_SEVERITY_ID_INFORMATIONAL",
		2:  "DISCOVERY_SEVERITY_ID_LOW",
		3:  "DISCOVERY_SEVERITY_ID_MEDIUM",
		4:  "DISCOVERY_SEVERITY_ID_HIGH",
		5:  "DISCOVERY_SEVERITY_ID_CRITICAL",
		6:  "DISCOVERY_SEVERITY_ID_FATAL",
		99: "DISCOVERY_SEVERITY_ID_OTHER",
	}
	DISCOVERY_SEVERITY_ID_value = map[string]int32{
		"DISCOVERY_SEVERITY_ID_UNKNOWN":       0,
		"DISCOVERY_SEVERITY_ID_INFORMATIONAL": 1,
		"DISCOVERY_SEVERITY_ID_LOW":           2,
		"DISCOVERY_SEVERITY_ID_MEDIUM":        3,
		"DISCOVERY_SEVERITY_ID_HIGH":          4,
		"DISCOVERY_SEVERITY_ID_CRITICAL":      5,
		"DISCOVERY_SEVERITY_ID_FATAL":         6,
		"DISCOVERY_SEVERITY_ID_OTHER":         99,
	}
)

func (x DISCOVERY_SEVERITY_ID) Enum() *DISCOVERY_SEVERITY_ID {
	p := new(DISCOVERY_SEVERITY_ID)
	*p = x
	return p
}

func (x DISCOVERY_SEVERITY_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DISCOVERY_SEVERITY_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[9].Descriptor()
}

func (DISCOVERY_SEVERITY_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[9]
}

func (x DISCOVERY_SEVERITY_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type DISCOVERY_STATUS_ID int32

const (
	DISCOVERY_STATUS_ID_DISCOVERY_STATUS_ID_UNKNOWN DISCOVERY_STATUS_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	DISCOVERY_STATUS_ID_DISCOVERY_STATUS_ID_SUCCESS DISCOVERY_STATUS_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	DISCOVERY_STATUS_ID_DISCOVERY_STATUS_ID_FAILURE DISCOVERY_STATUS_ID = 2  // EnumValue: 2; Type: OCSF_VALUE;
	DISCOVERY_STATUS_ID_DISCOVERY_STATUS_ID_OTHER   DISCOVERY_STATUS_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for DISCOVERY_STATUS_ID.
var (
	DISCOVERY_STATUS_ID_name = map[int32]string{
		0:  "DISCOVERY_STATUS_ID_UNKNOWN",
		1:  "DISCOVERY_STATUS_ID_SUCCESS",
		2:  "DISCOVERY_STATUS_ID_FAILURE",
		99: "DISCOVERY_STATUS_ID_OTHER",
	}
	DISCOVERY_STATUS_ID_value = map[string]int32{
		"DISCOVERY_STATUS_ID_UNKNOWN": 0,
		"DISCOVERY_STATUS_ID_SUCCESS": 1,
		"DISCOVERY_STATUS_ID_FAILURE": 2,
		"DISCOVERY_STATUS_ID_OTHER":   99,
	}
)

func (x DISCOVERY_STATUS_ID) Enum() *DISCOVERY_STATUS_ID {
	p := new(DISCOVERY_STATUS_ID)
	*p = x
	return p
}

func (x DISCOVERY_STATUS_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DISCOVERY_STATUS_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[10].Descriptor()
}

func (DISCOVERY_STATUS_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[10]
}

func (x DISCOVERY_STATUS_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type DISCOVERY_TYPE_UID int32

const (
	DISCOVERY_TYPE_UID_DISCOVERY_TYPE_UID_UNSPECIFIED       DISCOVERY_TYPE_UID = 0      // Type: NON_OCSF_VALUE;
	DISCOVERY_TYPE_UID_DISCOVERY_TYPE_UID_DISCOVERY_UNKNOWN DISCOVERY_TYPE_UID = 500000 // Type: OCSF_VALUE; EnumValue: 500000;
	DISCOVERY_TYPE_UID_DISCOVERY_TYPE_UID_DISCOVERY_LOG     DISCOVERY_TYPE_UID = 500001 // Type: OCSF_VALUE; EnumValue: 500001;
	DISCOVERY_TYPE_UID_DISCOVERY_TYPE_UID_DISCOVERY_COLLECT DISCOVERY_TYPE_UID = 500002 // Type: OCSF_VALUE; EnumValue: 500002;
	DISCOVERY_TYPE_UID_DISCOVERY_TYPE_UID_DISCOVERY_OTHER   DISCOVERY_TYPE_UID = 500099 // Type: OCSF_VALUE; EnumValue: 500099;
)

// Enum value maps for DISCOVERY_TYPE_UID.
var (
	DISCOVERY_TYPE_UID_name = map[int32]string{
		0:      "DISCOVERY_TYPE_UID_UNSPECIFIED",
		500000: "DISCOVERY_TYPE_UID_DISCOVERY_UNKNOWN",
		500001: "DISCOVERY_TYPE_UID_DISCOVERY_LOG",
		500002: "DISCOVERY_TYPE_UID_DISCOVERY_COLLECT",
		500099: "DISCOVERY_TYPE_UID_DISCOVERY_OTHER",
	}
	DISCOVERY_TYPE_UID_value = map[string]int32{
		"DISCOVERY_TYPE_UID_UNSPECIFIED":       0,
		"DISCOVERY_TYPE_UID_DISCOVERY_UNKNOWN": 500000,
		"DISCOVERY_TYPE_UID_DISCOVERY_LOG":     500001,
		"DISCOVERY_TYPE_UID_DISCOVERY_COLLECT": 500002,
		"DISCOVERY_TYPE_UID_DISCOVERY_OTHER":   500099,
	}
)

func (x DISCOVERY_TYPE_UID) Enum() *DISCOVERY_TYPE_UID {
	p := new(DISCOVERY_TYPE_UID)
	*p = x
	return p
}

func (x DISCOVERY_TYPE_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DISCOVERY_TYPE_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[11].Descriptor()
}

func (DISCOVERY_TYPE_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[11]
}

func (x DISCOVERY_TYPE_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type INVENTORY_INFO_ACTIVITY_ID int32

const (
	INVENTORY_INFO_ACTIVITY_ID_INVENTORY_INFO_ACTIVITY_ID_UNKNOWN INVENTORY_INFO_ACTIVITY_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	INVENTORY_INFO_ACTIVITY_ID_INVENTORY_INFO_ACTIVITY_ID_LOG     INVENTORY_INFO_ACTIVITY_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	INVENTORY_INFO_ACTIVITY_ID_INVENTORY_INFO_ACTIVITY_ID_COLLECT INVENTORY_INFO_ACTIVITY_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	INVENTORY_INFO_ACTIVITY_ID_INVENTORY_INFO_ACTIVITY_ID_OTHER   INVENTORY_INFO_ACTIVITY_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for INVENTORY_INFO_ACTIVITY_ID.
var (
	INVENTORY_INFO_ACTIVITY_ID_name = map[int32]string{
		0:  "INVENTORY_INFO_ACTIVITY_ID_UNKNOWN",
		1:  "INVENTORY_INFO_ACTIVITY_ID_LOG",
		2:  "INVENTORY_INFO_ACTIVITY_ID_COLLECT",
		99: "INVENTORY_INFO_ACTIVITY_ID_OTHER",
	}
	INVENTORY_INFO_ACTIVITY_ID_value = map[string]int32{
		"INVENTORY_INFO_ACTIVITY_ID_UNKNOWN": 0,
		"INVENTORY_INFO_ACTIVITY_ID_LOG":     1,
		"INVENTORY_INFO_ACTIVITY_ID_COLLECT": 2,
		"INVENTORY_INFO_ACTIVITY_ID_OTHER":   99,
	}
)

func (x INVENTORY_INFO_ACTIVITY_ID) Enum() *INVENTORY_INFO_ACTIVITY_ID {
	p := new(INVENTORY_INFO_ACTIVITY_ID)
	*p = x
	return p
}

func (x INVENTORY_INFO_ACTIVITY_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (INVENTORY_INFO_ACTIVITY_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[12].Descriptor()
}

func (INVENTORY_INFO_ACTIVITY_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[12]
}

func (x INVENTORY_INFO_ACTIVITY_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type INVENTORY_INFO_CATEGORY_UID int32

const (
	INVENTORY_INFO_CATEGORY_UID_INVENTORY_INFO_CATEGORY_UID_UNSPECIFIED INVENTORY_INFO_CATEGORY_UID = 0 // Type: NON_OCSF_VALUE;
	INVENTORY_INFO_CATEGORY_UID_INVENTORY_INFO_CATEGORY_UID_DISCOVERY   INVENTORY_INFO_CATEGORY_UID = 5 // Type: OCSF_VALUE; EnumValue: 5;
)

// Enum value maps for INVENTORY_INFO_CATEGORY_UID.
var (
	INVENTORY_INFO_CATEGORY_UID_name = map[int32]string{
		0: "INVENTORY_INFO_CATEGORY_UID_UNSPECIFIED",
		5: "INVENTORY_INFO_CATEGORY_UID_DISCOVERY",
	}
	INVENTORY_INFO_CATEGORY_UID_value = map[string]int32{
		"INVENTORY_INFO_CATEGORY_UID_UNSPECIFIED": 0,
		"INVENTORY_INFO_CATEGORY_UID_DISCOVERY":   5,
	}
)

func (x INVENTORY_INFO_CATEGORY_UID) Enum() *INVENTORY_INFO_CATEGORY_UID {
	p := new(INVENTORY_INFO_CATEGORY_UID)
	*p = x
	return p
}

func (x INVENTORY_INFO_CATEGORY_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (INVENTORY_INFO_CATEGORY_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[13].Descriptor()
}

func (INVENTORY_INFO_CATEGORY_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[13]
}

func (x INVENTORY_INFO_CATEGORY_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type INVENTORY_INFO_CLASS_UID int32

const (
	INVENTORY_INFO_CLASS_UID_INVENTORY_INFO_CLASS_UID_UNSPECIFIED           INVENTORY_INFO_CLASS_UID = 0    // Type: NON_OCSF_VALUE;
	INVENTORY_INFO_CLASS_UID_INVENTORY_INFO_CLASS_UID_DEVICE_INVENTORY_INFO INVENTORY_INFO_CLASS_UID = 5001 // Type: OCSF_VALUE; EnumValue: 5001;
)

// Enum value maps for INVENTORY_INFO_CLASS_UID.
var (
	INVENTORY_INFO_CLASS_UID_name = map[int32]string{
		0:    "INVENTORY_INFO_CLASS_UID_UNSPECIFIED",
		5001: "INVENTORY_INFO_CLASS_UID_DEVICE_INVENTORY_INFO",
	}
	INVENTORY_INFO_CLASS_UID_value = map[string]int32{
		"INVENTORY_INFO_CLASS_UID_UNSPECIFIED":           0,
		"INVENTORY_INFO_CLASS_UID_DEVICE_INVENTORY_INFO": 5001,
	}
)

func (x INVENTORY_INFO_CLASS_UID) Enum() *INVENTORY_INFO_CLASS_UID {
	p := new(INVENTORY_INFO_CLASS_UID)
	*p = x
	return p
}

func (x INVENTORY_INFO_CLASS_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (INVENTORY_INFO_CLASS_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[14].Descriptor()
}

func (INVENTORY_INFO_CLASS_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[14]
}

func (x INVENTORY_INFO_CLASS_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type INVENTORY_INFO_SEVERITY_ID int32

const (
	INVENTORY_INFO_SEVERITY_ID_INVENTORY_INFO_SEVERITY_ID_UNKNOWN       INVENTORY_INFO_SEVERITY_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	INVENTORY_INFO_SEVERITY_ID_INVENTORY_INFO_SEVERITY_ID_INFORMATIONAL INVENTORY_INFO_SEVERITY_ID = 1  // EnumValue: 1; Type: OCSF_VALUE;
	INVENTORY_INFO_SEVERITY_ID_INVENTORY_INFO_SEVERITY_ID_LOW           INVENTORY_INFO_SEVERITY_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	INVENTORY_INFO_SEVERITY_ID_INVENTORY_INFO_SEVERITY_ID_MEDIUM        INVENTORY_INFO_SEVERITY_ID = 3  // Type: OCSF_VALUE; EnumValue: 3;
	INVENTORY_INFO_SEVERITY_ID_INVENTORY_INFO_SEVERITY_ID_HIGH          INVENTORY_INFO_SEVERITY_ID = 4  // Type: OCSF_VALUE; EnumValue: 4;
	INVENTORY_INFO_SEVERITY_ID_INVENTORY_INFO_SEVERITY_ID_CRITICAL      INVENTORY_INFO_SEVERITY_ID = 5  // Type: OCSF_VALUE; EnumValue: 5;
	INVENTORY_INFO_SEVERITY_ID_INVENTORY_INFO_SEVERITY_ID_FATAL         INVENTORY_INFO_SEVERITY_ID = 6  // EnumValue: 6; Type: OCSF_VALUE;
	INVENTORY_INFO_SEVERITY_ID_INVENTORY_INFO_SEVERITY_ID_OTHER         INVENTORY_INFO_SEVERITY_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for INVENTORY_INFO_SEVERITY_ID.
var (
	INVENTORY_INFO_SEVERITY_ID_name = map[int32]string{
		0:  "INVENTORY_INFO_SEVERITY_ID_UNKNOWN",
		1:  "INVENTORY_INFO_SEVERITY_ID_INFORMATIONAL",
		2:  "INVENTORY_INFO_SEVERITY_ID_LOW",
		3:  "INVENTORY_INFO_SEVERITY_ID_MEDIUM",
		4:  "INVENTORY_INFO_SEVERITY_ID_HIGH",
		5:  "INVENTORY_INFO_SEVERITY_ID_CRITICAL",
		6:  "INVENTORY_INFO_SEVERITY_ID_FATAL",
		99: "INVENTORY_INFO_SEVERITY_ID_OTHER",
	}
	INVENTORY_INFO_SEVERITY_ID_value = map[string]int32{
		"INVENTORY_INFO_SEVERITY_ID_UNKNOWN":       0,
		"INVENTORY_INFO_SEVERITY_ID_INFORMATIONAL": 1,
		"INVENTORY_INFO_SEVERITY_ID_LOW":           2,
		"INVENTORY_INFO_SEVERITY_ID_MEDIUM":        3,
		"INVENTORY_INFO_SEVERITY_ID_HIGH":          4,
		"INVENTORY_INFO_SEVERITY_ID_CRITICAL":      5,
		"INVENTORY_INFO_SEVERITY_ID_FATAL":         6,
		"INVENTORY_INFO_SEVERITY_ID_OTHER":         99,
	}
)

func (x INVENTORY_INFO_SEVERITY_ID) Enum() *INVENTORY_INFO_SEVERITY_ID {
	p := new(INVENTORY_INFO_SEVERITY_ID)
	*p = x
	return p
}

func (x INVENTORY_INFO_SEVERITY_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (INVENTORY_INFO_SEVERITY_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[15].Descriptor()
}

func (INVENTORY_INFO_SEVERITY_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[15]
}

func (x INVENTORY_INFO_SEVERITY_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type INVENTORY_INFO_STATUS_ID int32

const (
	INVENTORY_INFO_STATUS_ID_INVENTORY_INFO_STATUS_ID_UNKNOWN INVENTORY_INFO_STATUS_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	INVENTORY_INFO_STATUS_ID_INVENTORY_INFO_STATUS_ID_SUCCESS INVENTORY_INFO_STATUS_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	INVENTORY_INFO_STATUS_ID_INVENTORY_INFO_STATUS_ID_FAILURE INVENTORY_INFO_STATUS_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	INVENTORY_INFO_STATUS_ID_INVENTORY_INFO_STATUS_ID_OTHER   INVENTORY_INFO_STATUS_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for INVENTORY_INFO_STATUS_ID.
var (
	INVENTORY_INFO_STATUS_ID_name = map[int32]string{
		0:  "INVENTORY_INFO_STATUS_ID_UNKNOWN",
		1:  "INVENTORY_INFO_STATUS_ID_SUCCESS",
		2:  "INVENTORY_INFO_STATUS_ID_FAILURE",
		99: "INVENTORY_INFO_STATUS_ID_OTHER",
	}
	INVENTORY_INFO_STATUS_ID_value = map[string]int32{
		"INVENTORY_INFO_STATUS_ID_UNKNOWN": 0,
		"INVENTORY_INFO_STATUS_ID_SUCCESS": 1,
		"INVENTORY_INFO_STATUS_ID_FAILURE": 2,
		"INVENTORY_INFO_STATUS_ID_OTHER":   99,
	}
)

func (x INVENTORY_INFO_STATUS_ID) Enum() *INVENTORY_INFO_STATUS_ID {
	p := new(INVENTORY_INFO_STATUS_ID)
	*p = x
	return p
}

func (x INVENTORY_INFO_STATUS_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (INVENTORY_INFO_STATUS_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[16].Descriptor()
}

func (INVENTORY_INFO_STATUS_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[16]
}

func (x INVENTORY_INFO_STATUS_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type INVENTORY_INFO_TYPE_UID int32

const (
	INVENTORY_INFO_TYPE_UID_INVENTORY_INFO_TYPE_UID_UNSPECIFIED                   INVENTORY_INFO_TYPE_UID = 0      // Type: NON_OCSF_VALUE;
	INVENTORY_INFO_TYPE_UID_INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_UNKNOWN INVENTORY_INFO_TYPE_UID = 500100 // Type: OCSF_VALUE; EnumValue: 500100;
	INVENTORY_INFO_TYPE_UID_INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_LOG     INVENTORY_INFO_TYPE_UID = 500101 // Type: OCSF_VALUE; EnumValue: 500101;
	INVENTORY_INFO_TYPE_UID_INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_COLLECT INVENTORY_INFO_TYPE_UID = 500102 // Type: OCSF_VALUE; EnumValue: 500102;
	INVENTORY_INFO_TYPE_UID_INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_OTHER   INVENTORY_INFO_TYPE_UID = 500199 // Type: OCSF_VALUE; EnumValue: 500199;
)

// Enum value maps for INVENTORY_INFO_TYPE_UID.
var (
	INVENTORY_INFO_TYPE_UID_name = map[int32]string{
		0:      "INVENTORY_INFO_TYPE_UID_UNSPECIFIED",
		500100: "INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_UNKNOWN",
		500101: "INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_LOG",
		500102: "INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_COLLECT",
		500199: "INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_OTHER",
	}
	INVENTORY_INFO_TYPE_UID_value = map[string]int32{
		"INVENTORY_INFO_TYPE_UID_UNSPECIFIED":                   0,
		"INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_UNKNOWN": 500100,
		"INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_LOG":     500101,
		"INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_COLLECT": 500102,
		"INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_OTHER":   500199,
	}
)

func (x INVENTORY_INFO_TYPE_UID) Enum() *INVENTORY_INFO_TYPE_UID {
	p := new(INVENTORY_INFO_TYPE_UID)
	*p = x
	return p
}

func (x INVENTORY_INFO_TYPE_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (INVENTORY_INFO_TYPE_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[17].Descriptor()
}

func (INVENTORY_INFO_TYPE_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes[17]
}

func (x INVENTORY_INFO_TYPE_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_ocsf_v1_0_0_events_discovery_enums_enums_proto protoreflect.FileDescriptor

const file_ocsf_v1_0_0_events_discovery_enums_enums_proto_rawDesc = "" +
	"\n" +
	".ocsf/v1_0_0/events/discovery/enums/enums.proto\x12\"ocsf.v1_0_0.events.discovery.enums*\xac\x01\n" +
	"\x18CONFIG_STATE_ACTIVITY_ID\x12$\n" +
	" CONFIG_STATE_ACTIVITY_ID_UNKNOWN\x10\x00\x12 \n" +
	"\x1cCONFIG_STATE_ACTIVITY_ID_LOG\x10\x01\x12$\n" +
	" CONFIG_STATE_ACTIVITY_ID_COLLECT\x10\x02\x12\"\n" +
	"\x1eCONFIG_STATE_ACTIVITY_ID_OTHER\x10c*o\n" +
	"\x19CONFIG_STATE_CATEGORY_UID\x12)\n" +
	"%CONFIG_STATE_CATEGORY_UID_UNSPECIFIED\x10\x00\x12'\n" +
	"#CONFIG_STATE_CATEGORY_UID_DISCOVERY\x10\x05*q\n" +
	"\x16CONFIG_STATE_CLASS_UID\x12&\n" +
	"\"CONFIG_STATE_CLASS_UID_UNSPECIFIED\x10\x00\x12/\n" +
	"*CONFIG_STATE_CLASS_UID_DEVICE_CONFIG_STATE\x10\x8a'*\xc5\x02\n" +
	"\x18CONFIG_STATE_SEVERITY_ID\x12$\n" +
	" CONFIG_STATE_SEVERITY_ID_UNKNOWN\x10\x00\x12*\n" +
	"&CONFIG_STATE_SEVERITY_ID_INFORMATIONAL\x10\x01\x12 \n" +
	"\x1cCONFIG_STATE_SEVERITY_ID_LOW\x10\x02\x12#\n" +
	"\x1fCONFIG_STATE_SEVERITY_ID_MEDIUM\x10\x03\x12!\n" +
	"\x1dCONFIG_STATE_SEVERITY_ID_HIGH\x10\x04\x12%\n" +
	"!CONFIG_STATE_SEVERITY_ID_CRITICAL\x10\x05\x12\"\n" +
	"\x1eCONFIG_STATE_SEVERITY_ID_FATAL\x10\x06\x12\"\n" +
	"\x1eCONFIG_STATE_SEVERITY_ID_OTHER\x10c*\xa6\x01\n" +
	"\x16CONFIG_STATE_STATUS_ID\x12\"\n" +
	"\x1eCONFIG_STATE_STATUS_ID_UNKNOWN\x10\x00\x12\"\n" +
	"\x1eCONFIG_STATE_STATUS_ID_SUCCESS\x10\x01\x12\"\n" +
	"\x1eCONFIG_STATE_STATUS_ID_FAILURE\x10\x02\x12 \n" +
	"\x1cCONFIG_STATE_STATUS_ID_OTHER\x10c*\x9c\x02\n" +
	"\x15CONFIG_STATE_TYPE_UID\x12%\n" +
	"!CONFIG_STATE_TYPE_UID_UNSPECIFIED\x10\x00\x127\n" +
	"1CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_UNKNOWN\x10\xe8\xc3\x1e\x123\n" +
	"-CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_LOG\x10\xe9\xc3\x1e\x127\n" +
	"1CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_COLLECT\x10\xea\xc3\x1e\x125\n" +
	"/CONFIG_STATE_TYPE_UID_DEVICE_CONFIG_STATE_OTHER\x10\xcb\xc4\x1e*\x9d\x01\n" +
	"\x15DISCOVERY_ACTIVITY_ID\x12!\n" +
	"\x1dDISCOVERY_ACTIVITY_ID_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19DISCOVERY_ACTIVITY_ID_LOG\x10\x01\x12!\n" +
	"\x1dDISCOVERY_ACTIVITY_ID_COLLECT\x10\x02\x12\x1f\n" +
	"\x1bDISCOVERY_ACTIVITY_ID_OTHER\x10c*f\n" +
	"\x16DISCOVERY_CATEGORY_UID\x12&\n" +
	"\"DISCOVERY_CATEGORY_UID_UNSPECIFIED\x10\x00\x12$\n" +
	" DISCOVERY_CATEGORY_UID_DISCOVERY\x10\x05*^\n" +
	"\x13DISCOVERY_CLASS_UID\x12#\n" +
	"\x1fDISCOVERY_CLASS_UID_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1dDISCOVERY_CLASS_UID_DISCOVERY\x10\x88'*\xaa\x02\n" +
	"\x15DISCOVERY_SEVERITY_ID\x12!\n" +
	"\x1dDISCOVERY_SEVERITY_ID_UNKNOWN\x10\x00\x12'\n" +
	"#DISCOVERY_SEVERITY_ID_INFORMATIONAL\x10\x01\x12\x1d\n" +
	"\x19DISCOVERY_SEVERITY_ID_LOW\x10\x02\x12 \n" +
	"\x1cDISCOVERY_SEVERITY_ID_MEDIUM\x10\x03\x12\x1e\n" +
	"\x1aDISCOVERY_SEVERITY_ID_HIGH\x10\x04\x12\"\n" +
	"\x1eDISCOVERY_SEVERITY_ID_CRITICAL\x10\x05\x12\x1f\n" +
	"\x1bDISCOVERY_SEVERITY_ID_FATAL\x10\x06\x12\x1f\n" +
	"\x1bDISCOVERY_SEVERITY_ID_OTHER\x10c*\x97\x01\n" +
	"\x13DISCOVERY_STATUS_ID\x12\x1f\n" +
	"\x1bDISCOVERY_STATUS_ID_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bDISCOVERY_STATUS_ID_SUCCESS\x10\x01\x12\x1f\n" +
	"\x1bDISCOVERY_STATUS_ID_FAILURE\x10\x02\x12\x1d\n" +
	"\x19DISCOVERY_STATUS_ID_OTHER\x10c*\xe2\x01\n" +
	"\x12DISCOVERY_TYPE_UID\x12\"\n" +
	"\x1eDISCOVERY_TYPE_UID_UNSPECIFIED\x10\x00\x12*\n" +
	"$DISCOVERY_TYPE_UID_DISCOVERY_UNKNOWN\x10\xa0\xc2\x1e\x12&\n" +
	" DISCOVERY_TYPE_UID_DISCOVERY_LOG\x10\xa1\xc2\x1e\x12*\n" +
	"$DISCOVERY_TYPE_UID_DISCOVERY_COLLECT\x10\xa2\xc2\x1e\x12(\n" +
	"\"DISCOVERY_TYPE_UID_DISCOVERY_OTHER\x10\x83\xc3\x1e*\xb6\x01\n" +
	"\x1aINVENTORY_INFO_ACTIVITY_ID\x12&\n" +
	"\"INVENTORY_INFO_ACTIVITY_ID_UNKNOWN\x10\x00\x12\"\n" +
	"\x1eINVENTORY_INFO_ACTIVITY_ID_LOG\x10\x01\x12&\n" +
	"\"INVENTORY_INFO_ACTIVITY_ID_COLLECT\x10\x02\x12$\n" +
	" INVENTORY_INFO_ACTIVITY_ID_OTHER\x10c*u\n" +
	"\x1bINVENTORY_INFO_CATEGORY_UID\x12+\n" +
	"'INVENTORY_INFO_CATEGORY_UID_UNSPECIFIED\x10\x00\x12)\n" +
	"%INVENTORY_INFO_CATEGORY_UID_DISCOVERY\x10\x05*y\n" +
	"\x18INVENTORY_INFO_CLASS_UID\x12(\n" +
	"$INVENTORY_INFO_CLASS_UID_UNSPECIFIED\x10\x00\x123\n" +
	".INVENTORY_INFO_CLASS_UID_DEVICE_INVENTORY_INFO\x10\x89'*\xd7\x02\n" +
	"\x1aINVENTORY_INFO_SEVERITY_ID\x12&\n" +
	"\"INVENTORY_INFO_SEVERITY_ID_UNKNOWN\x10\x00\x12,\n" +
	"(INVENTORY_INFO_SEVERITY_ID_INFORMATIONAL\x10\x01\x12\"\n" +
	"\x1eINVENTORY_INFO_SEVERITY_ID_LOW\x10\x02\x12%\n" +
	"!INVENTORY_INFO_SEVERITY_ID_MEDIUM\x10\x03\x12#\n" +
	"\x1fINVENTORY_INFO_SEVERITY_ID_HIGH\x10\x04\x12'\n" +
	"#INVENTORY_INFO_SEVERITY_ID_CRITICAL\x10\x05\x12$\n" +
	" INVENTORY_INFO_SEVERITY_ID_FATAL\x10\x06\x12$\n" +
	" INVENTORY_INFO_SEVERITY_ID_OTHER\x10c*\xb0\x01\n" +
	"\x18INVENTORY_INFO_STATUS_ID\x12$\n" +
	" INVENTORY_INFO_STATUS_ID_UNKNOWN\x10\x00\x12$\n" +
	" INVENTORY_INFO_STATUS_ID_SUCCESS\x10\x01\x12$\n" +
	" INVENTORY_INFO_STATUS_ID_FAILURE\x10\x02\x12\"\n" +
	"\x1eINVENTORY_INFO_STATUS_ID_OTHER\x10c*\xb0\x02\n" +
	"\x17INVENTORY_INFO_TYPE_UID\x12'\n" +
	"#INVENTORY_INFO_TYPE_UID_UNSPECIFIED\x10\x00\x12;\n" +
	"5INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_UNKNOWN\x10\x84\xc3\x1e\x127\n" +
	"1INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_LOG\x10\x85\xc3\x1e\x12;\n" +
	"5INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_COLLECT\x10\x86\xc3\x1e\x129\n" +
	"3INVENTORY_INFO_TYPE_UID_DEVICE_INVENTORY_INFO_OTHER\x10\xe7\xc3\x1eB\xa5\x02\n" +
	"&com.ocsf.v1_0_0.events.discovery.enumsB\n" +
	"EnumsProtoP\x01ZIgithub.com/valllabh/ocsf-schema-golang/ocsf/v1_0_0/events/discovery/enums\xa2\x02\x05OVEDE\xaa\x02 Ocsf.V100.Events.Discovery.Enums\xca\x02 Ocsf\\V100\\Events\\Discovery\\Enums\xe2\x02,Ocsf\\V100\\Events\\Discovery\\Enums\\GPBMetadata\xea\x02$Ocsf::V100::Events::Discovery::Enumsb\x06proto3"

var file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 18)
var file_ocsf_v1_0_0_events_discovery_enums_enums_proto_goTypes = []any{
	(CONFIG_STATE_ACTIVITY_ID)(0),    // 0: ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_ACTIVITY_ID
	(CONFIG_STATE_CATEGORY_UID)(0),   // 1: ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_CATEGORY_UID
	(CONFIG_STATE_CLASS_UID)(0),      // 2: ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_CLASS_UID
	(CONFIG_STATE_SEVERITY_ID)(0),    // 3: ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_SEVERITY_ID
	(CONFIG_STATE_STATUS_ID)(0),      // 4: ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_STATUS_ID
	(CONFIG_STATE_TYPE_UID)(0),       // 5: ocsf.v1_0_0.events.discovery.enums.CONFIG_STATE_TYPE_UID
	(DISCOVERY_ACTIVITY_ID)(0),       // 6: ocsf.v1_0_0.events.discovery.enums.DISCOVERY_ACTIVITY_ID
	(DISCOVERY_CATEGORY_UID)(0),      // 7: ocsf.v1_0_0.events.discovery.enums.DISCOVERY_CATEGORY_UID
	(DISCOVERY_CLASS_UID)(0),         // 8: ocsf.v1_0_0.events.discovery.enums.DISCOVERY_CLASS_UID
	(DISCOVERY_SEVERITY_ID)(0),       // 9: ocsf.v1_0_0.events.discovery.enums.DISCOVERY_SEVERITY_ID
	(DISCOVERY_STATUS_ID)(0),         // 10: ocsf.v1_0_0.events.discovery.enums.DISCOVERY_STATUS_ID
	(DISCOVERY_TYPE_UID)(0),          // 11: ocsf.v1_0_0.events.discovery.enums.DISCOVERY_TYPE_UID
	(INVENTORY_INFO_ACTIVITY_ID)(0),  // 12: ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_ACTIVITY_ID
	(INVENTORY_INFO_CATEGORY_UID)(0), // 13: ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_CATEGORY_UID
	(INVENTORY_INFO_CLASS_UID)(0),    // 14: ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_CLASS_UID
	(INVENTORY_INFO_SEVERITY_ID)(0),  // 15: ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_SEVERITY_ID
	(INVENTORY_INFO_STATUS_ID)(0),    // 16: ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_STATUS_ID
	(INVENTORY_INFO_TYPE_UID)(0),     // 17: ocsf.v1_0_0.events.discovery.enums.INVENTORY_INFO_TYPE_UID
}
var file_ocsf_v1_0_0_events_discovery_enums_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ocsf_v1_0_0_events_discovery_enums_enums_proto_init() }
func file_ocsf_v1_0_0_events_discovery_enums_enums_proto_init() {
	if File_ocsf_v1_0_0_events_discovery_enums_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocsf_v1_0_0_events_discovery_enums_enums_proto_rawDesc), len(file_ocsf_v1_0_0_events_discovery_enums_enums_proto_rawDesc)),
			NumEnums:      18,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocsf_v1_0_0_events_discovery_enums_enums_proto_goTypes,
		DependencyIndexes: file_ocsf_v1_0_0_events_discovery_enums_enums_proto_depIdxs,
		EnumInfos:         file_ocsf_v1_0_0_events_discovery_enums_enums_proto_enumTypes,
	}.Build()
	File_ocsf_v1_0_0_events_discovery_enums_enums_proto = out.File
	file_ocsf_v1_0_0_events_discovery_enums_enums_proto_goTypes = nil
	file_ocsf_v1_0_0_events_discovery_enums_enums_proto_depIdxs = nil
}
