syntax = "proto3";

package ocsf.v1_4_0.events.unmanned_systems.enums;

option go_package = "/ocsf/v1_4_0/events/unmanned_systems/enums";

option java_package = "com.your.project.generated.ocsf.v1_4_0.events.unmanned_systems.enums";

option java_multiple_files = true;

enum AIRBORNE_BROADCAST_ACTIVITY_ACTION_ID {
	AIRBORNE_BROADCAST_ACTIVITY_ACTION_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	AIRBORNE_BROADCAST_ACTIVITY_ACTION_ID_ALLOWED = 1; // Type: OCSF_VALUE; EnumValue: 1;
	AIRBORNE_BROADCAST_ACTIVITY_ACTION_ID_DENIED = 2; // Type: OCSF_VALUE; EnumValue: 2;
	AIRBORNE_BROADCAST_ACTIVITY_ACTION_ID_OBSERVED = 3; // Type: OCSF_VALUE; EnumValue: 3;
	AIRBORNE_BROADCAST_ACTIVITY_ACTION_ID_MODIFIED = 4; // Type: OCSF_VALUE; EnumValue: 4;
	AIRBORNE_BROADCAST_ACTIVITY_ACTION_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum AIRBORNE_BROADCAST_ACTIVITY_ACTIVITY_ID {
	AIRBORNE_BROADCAST_ACTIVITY_ACTIVITY_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	AIRBORNE_BROADCAST_ACTIVITY_ACTIVITY_ID_CAPTURE = 1; // EnumValue: 1; Type: OCSF_VALUE;
	AIRBORNE_BROADCAST_ACTIVITY_ACTIVITY_ID_RECORD = 2; // EnumValue: 2; Type: OCSF_VALUE;
	AIRBORNE_BROADCAST_ACTIVITY_ACTIVITY_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum AIRBORNE_BROADCAST_ACTIVITY_CATEGORY_UID {
	AIRBORNE_BROADCAST_ACTIVITY_CATEGORY_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	AIRBORNE_BROADCAST_ACTIVITY_CATEGORY_UID_UNMANNED_SYSTEMS = 8; // Type: OCSF_VALUE; EnumValue: 8;
}

enum AIRBORNE_BROADCAST_ACTIVITY_CLASS_UID {
	AIRBORNE_BROADCAST_ACTIVITY_CLASS_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	AIRBORNE_BROADCAST_ACTIVITY_CLASS_UID_AIRBORNE_BROADCAST_ACTIVITY = 8002; // Type: OCSF_VALUE; EnumValue: 8002;
}

enum AIRBORNE_BROADCAST_ACTIVITY_CONFIDENCE_ID {
	AIRBORNE_BROADCAST_ACTIVITY_CONFIDENCE_ID_UNKNOWN = 0; // EnumValue: 0; Type: OCSF_VALUE;
	AIRBORNE_BROADCAST_ACTIVITY_CONFIDENCE_ID_LOW = 1; // Type: OCSF_VALUE; EnumValue: 1;
	AIRBORNE_BROADCAST_ACTIVITY_CONFIDENCE_ID_MEDIUM = 2; // Type: OCSF_VALUE; EnumValue: 2;
	AIRBORNE_BROADCAST_ACTIVITY_CONFIDENCE_ID_HIGH = 3; // Type: OCSF_VALUE; EnumValue: 3;
	AIRBORNE_BROADCAST_ACTIVITY_CONFIDENCE_ID_OTHER = 99; // EnumValue: 99; Type: OCSF_VALUE;
}

enum AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID {
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_ALLOWED = 1; // Type: OCSF_VALUE; EnumValue: 1;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_BLOCKED = 2; // Type: OCSF_VALUE; EnumValue: 2;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_QUARANTINED = 3; // Type: OCSF_VALUE; EnumValue: 3;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_ISOLATED = 4; // Type: OCSF_VALUE; EnumValue: 4;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_DELETED = 5; // Type: OCSF_VALUE; EnumValue: 5;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_DROPPED = 6; // EnumValue: 6; Type: OCSF_VALUE;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_CUSTOM_ACTION = 7; // EnumValue: 7; Type: OCSF_VALUE;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_APPROVED = 8; // Type: OCSF_VALUE; EnumValue: 8;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_RESTORED = 9; // Type: OCSF_VALUE; EnumValue: 9;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_EXONERATED = 10; // Type: OCSF_VALUE; EnumValue: 10;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_CORRECTED = 11; // Type: OCSF_VALUE; EnumValue: 11;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_PARTIALLY_CORRECTED = 12; // EnumValue: 12; Type: OCSF_VALUE;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_UNCORRECTED = 13; // Type: OCSF_VALUE; EnumValue: 13;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_DELAYED = 14; // Type: OCSF_VALUE; EnumValue: 14;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_DETECTED = 15; // Type: OCSF_VALUE; EnumValue: 15;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_NO_ACTION = 16; // Type: OCSF_VALUE; EnumValue: 16;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_LOGGED = 17; // Type: OCSF_VALUE; EnumValue: 17;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_TAGGED = 18; // Type: OCSF_VALUE; EnumValue: 18;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_ALERT = 19; // Type: OCSF_VALUE; EnumValue: 19;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_COUNT = 20; // Type: OCSF_VALUE; EnumValue: 20;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_RESET = 21; // Type: OCSF_VALUE; EnumValue: 21;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_CAPTCHA = 22; // EnumValue: 22; Type: OCSF_VALUE;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_CHALLENGE = 23; // Type: OCSF_VALUE; EnumValue: 23;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_ACCESS_REVOKED = 24; // Type: OCSF_VALUE; EnumValue: 24;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_REJECTED = 25; // EnumValue: 25; Type: OCSF_VALUE;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_UNAUTHORIZED = 26; // Type: OCSF_VALUE; EnumValue: 26;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_ERROR = 27; // Type: OCSF_VALUE; EnumValue: 27;
	AIRBORNE_BROADCAST_ACTIVITY_DISPOSITION_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum AIRBORNE_BROADCAST_ACTIVITY_RISK_LEVEL_ID {
	AIRBORNE_BROADCAST_ACTIVITY_RISK_LEVEL_ID_INFO = 0; // Type: OCSF_VALUE; EnumValue: 0;
	AIRBORNE_BROADCAST_ACTIVITY_RISK_LEVEL_ID_LOW = 1; // Type: OCSF_VALUE; EnumValue: 1;
	AIRBORNE_BROADCAST_ACTIVITY_RISK_LEVEL_ID_MEDIUM = 2; // Type: OCSF_VALUE; EnumValue: 2;
	AIRBORNE_BROADCAST_ACTIVITY_RISK_LEVEL_ID_HIGH = 3; // Type: OCSF_VALUE; EnumValue: 3;
	AIRBORNE_BROADCAST_ACTIVITY_RISK_LEVEL_ID_CRITICAL = 4; // EnumValue: 4; Type: OCSF_VALUE;
	AIRBORNE_BROADCAST_ACTIVITY_RISK_LEVEL_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum AIRBORNE_BROADCAST_ACTIVITY_SEVERITY_ID {
	AIRBORNE_BROADCAST_ACTIVITY_SEVERITY_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	AIRBORNE_BROADCAST_ACTIVITY_SEVERITY_ID_INFORMATIONAL = 1; // Type: OCSF_VALUE; EnumValue: 1;
	AIRBORNE_BROADCAST_ACTIVITY_SEVERITY_ID_LOW = 2; // Type: OCSF_VALUE; EnumValue: 2;
	AIRBORNE_BROADCAST_ACTIVITY_SEVERITY_ID_MEDIUM = 3; // Type: OCSF_VALUE; EnumValue: 3;
	AIRBORNE_BROADCAST_ACTIVITY_SEVERITY_ID_HIGH = 4; // Type: OCSF_VALUE; EnumValue: 4;
	AIRBORNE_BROADCAST_ACTIVITY_SEVERITY_ID_CRITICAL = 5; // Type: OCSF_VALUE; EnumValue: 5;
	AIRBORNE_BROADCAST_ACTIVITY_SEVERITY_ID_FATAL = 6; // Type: OCSF_VALUE; EnumValue: 6;
	AIRBORNE_BROADCAST_ACTIVITY_SEVERITY_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum AIRBORNE_BROADCAST_ACTIVITY_STATUS_ID {
	AIRBORNE_BROADCAST_ACTIVITY_STATUS_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	AIRBORNE_BROADCAST_ACTIVITY_STATUS_ID_SUCCESS = 1; // EnumValue: 1; Type: OCSF_VALUE;
	AIRBORNE_BROADCAST_ACTIVITY_STATUS_ID_FAILURE = 2; // Type: OCSF_VALUE; EnumValue: 2;
	AIRBORNE_BROADCAST_ACTIVITY_STATUS_ID_OTHER = 99; // EnumValue: 99; Type: OCSF_VALUE;
}

enum AIRBORNE_BROADCAST_ACTIVITY_TYPE_UID {
	AIRBORNE_BROADCAST_ACTIVITY_TYPE_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	AIRBORNE_BROADCAST_ACTIVITY_TYPE_UID_AIRBORNE_BROADCAST_ACTIVITY_UNKNOWN = 800200; // Type: OCSF_VALUE; EnumValue: 800200;
	AIRBORNE_BROADCAST_ACTIVITY_TYPE_UID_AIRBORNE_BROADCAST_ACTIVITY_CAPTURE = 800201; // Type: OCSF_VALUE; EnumValue: 800201;
	AIRBORNE_BROADCAST_ACTIVITY_TYPE_UID_AIRBORNE_BROADCAST_ACTIVITY_RECORD = 800202; // Type: OCSF_VALUE; EnumValue: 800202;
	AIRBORNE_BROADCAST_ACTIVITY_TYPE_UID_AIRBORNE_BROADCAST_ACTIVITY_OTHER = 800299; // Type: OCSF_VALUE; EnumValue: 800299;
}

enum DRONE_FLIGHTS_ACTIVITY_ACTION_ID {
	DRONE_FLIGHTS_ACTIVITY_ACTION_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	DRONE_FLIGHTS_ACTIVITY_ACTION_ID_ALLOWED = 1; // Type: OCSF_VALUE; EnumValue: 1;
	DRONE_FLIGHTS_ACTIVITY_ACTION_ID_DENIED = 2; // Type: OCSF_VALUE; EnumValue: 2;
	DRONE_FLIGHTS_ACTIVITY_ACTION_ID_OBSERVED = 3; // Type: OCSF_VALUE; EnumValue: 3;
	DRONE_FLIGHTS_ACTIVITY_ACTION_ID_MODIFIED = 4; // EnumValue: 4; Type: OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_ACTION_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum DRONE_FLIGHTS_ACTIVITY_ACTIVITY_ID {
	DRONE_FLIGHTS_ACTIVITY_ACTIVITY_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	DRONE_FLIGHTS_ACTIVITY_ACTIVITY_ID_CAPTURE = 1; // EnumValue: 1; Type: OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_ACTIVITY_ID_RECORD = 2; // Type: OCSF_VALUE; EnumValue: 2;
	DRONE_FLIGHTS_ACTIVITY_ACTIVITY_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum DRONE_FLIGHTS_ACTIVITY_AUTH_PROTOCOL_ID {
	DRONE_FLIGHTS_ACTIVITY_AUTH_PROTOCOL_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	DRONE_FLIGHTS_ACTIVITY_AUTH_PROTOCOL_ID_NTLM = 1; // Type: OCSF_VALUE; EnumValue: 1;
	DRONE_FLIGHTS_ACTIVITY_AUTH_PROTOCOL_ID_KERBEROS = 2; // Type: OCSF_VALUE; EnumValue: 2;
	DRONE_FLIGHTS_ACTIVITY_AUTH_PROTOCOL_ID_DIGEST = 3; // Type: OCSF_VALUE; EnumValue: 3;
	DRONE_FLIGHTS_ACTIVITY_AUTH_PROTOCOL_ID_OPEN_ID = 4; // Type: OCSF_VALUE; EnumValue: 4;
	DRONE_FLIGHTS_ACTIVITY_AUTH_PROTOCOL_ID_SAML = 5; // Type: OCSF_VALUE; EnumValue: 5;
	DRONE_FLIGHTS_ACTIVITY_AUTH_PROTOCOL_ID_OAUTH_2_0 = 6; // Type: OCSF_VALUE; EnumValue: 6;
	DRONE_FLIGHTS_ACTIVITY_AUTH_PROTOCOL_ID_PAP = 7; // Type: OCSF_VALUE; EnumValue: 7;
	DRONE_FLIGHTS_ACTIVITY_AUTH_PROTOCOL_ID_CHAP = 8; // Type: OCSF_VALUE; EnumValue: 8;
	DRONE_FLIGHTS_ACTIVITY_AUTH_PROTOCOL_ID_EAP = 9; // Type: OCSF_VALUE; EnumValue: 9;
	DRONE_FLIGHTS_ACTIVITY_AUTH_PROTOCOL_ID_RADIUS = 10; // EnumValue: 10; Type: OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_AUTH_PROTOCOL_ID_BASIC_AUTHENTICATION = 11; // EnumValue: 11; Type: OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_AUTH_PROTOCOL_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum DRONE_FLIGHTS_ACTIVITY_CATEGORY_UID {
	DRONE_FLIGHTS_ACTIVITY_CATEGORY_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_CATEGORY_UID_UNMANNED_SYSTEMS = 8; // Type: OCSF_VALUE; EnumValue: 8;
}

enum DRONE_FLIGHTS_ACTIVITY_CLASS_UID {
	DRONE_FLIGHTS_ACTIVITY_CLASS_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_CLASS_UID_DRONE_FLIGHTS_ACTIVITY = 8001; // Type: OCSF_VALUE; EnumValue: 8001;
}

enum DRONE_FLIGHTS_ACTIVITY_CONFIDENCE_ID {
	DRONE_FLIGHTS_ACTIVITY_CONFIDENCE_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	DRONE_FLIGHTS_ACTIVITY_CONFIDENCE_ID_LOW = 1; // EnumValue: 1; Type: OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_CONFIDENCE_ID_MEDIUM = 2; // Type: OCSF_VALUE; EnumValue: 2;
	DRONE_FLIGHTS_ACTIVITY_CONFIDENCE_ID_HIGH = 3; // Type: OCSF_VALUE; EnumValue: 3;
	DRONE_FLIGHTS_ACTIVITY_CONFIDENCE_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID {
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_ALLOWED = 1; // Type: OCSF_VALUE; EnumValue: 1;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_BLOCKED = 2; // Type: OCSF_VALUE; EnumValue: 2;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_QUARANTINED = 3; // EnumValue: 3; Type: OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_ISOLATED = 4; // EnumValue: 4; Type: OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_DELETED = 5; // Type: OCSF_VALUE; EnumValue: 5;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_DROPPED = 6; // EnumValue: 6; Type: OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_CUSTOM_ACTION = 7; // Type: OCSF_VALUE; EnumValue: 7;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_APPROVED = 8; // Type: OCSF_VALUE; EnumValue: 8;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_RESTORED = 9; // Type: OCSF_VALUE; EnumValue: 9;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_EXONERATED = 10; // Type: OCSF_VALUE; EnumValue: 10;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_CORRECTED = 11; // Type: OCSF_VALUE; EnumValue: 11;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_PARTIALLY_CORRECTED = 12; // Type: OCSF_VALUE; EnumValue: 12;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_UNCORRECTED = 13; // Type: OCSF_VALUE; EnumValue: 13;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_DELAYED = 14; // Type: OCSF_VALUE; EnumValue: 14;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_DETECTED = 15; // EnumValue: 15; Type: OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_NO_ACTION = 16; // EnumValue: 16; Type: OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_LOGGED = 17; // Type: OCSF_VALUE; EnumValue: 17;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_TAGGED = 18; // Type: OCSF_VALUE; EnumValue: 18;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_ALERT = 19; // Type: OCSF_VALUE; EnumValue: 19;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_COUNT = 20; // Type: OCSF_VALUE; EnumValue: 20;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_RESET = 21; // Type: OCSF_VALUE; EnumValue: 21;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_CAPTCHA = 22; // Type: OCSF_VALUE; EnumValue: 22;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_CHALLENGE = 23; // Type: OCSF_VALUE; EnumValue: 23;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_ACCESS_REVOKED = 24; // Type: OCSF_VALUE; EnumValue: 24;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_REJECTED = 25; // Type: OCSF_VALUE; EnumValue: 25;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_UNAUTHORIZED = 26; // Type: OCSF_VALUE; EnumValue: 26;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_ERROR = 27; // Type: OCSF_VALUE; EnumValue: 27;
	DRONE_FLIGHTS_ACTIVITY_DISPOSITION_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum DRONE_FLIGHTS_ACTIVITY_RISK_LEVEL_ID {
	DRONE_FLIGHTS_ACTIVITY_RISK_LEVEL_ID_INFO = 0; // Type: OCSF_VALUE; EnumValue: 0;
	DRONE_FLIGHTS_ACTIVITY_RISK_LEVEL_ID_LOW = 1; // Type: OCSF_VALUE; EnumValue: 1;
	DRONE_FLIGHTS_ACTIVITY_RISK_LEVEL_ID_MEDIUM = 2; // EnumValue: 2; Type: OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_RISK_LEVEL_ID_HIGH = 3; // Type: OCSF_VALUE; EnumValue: 3;
	DRONE_FLIGHTS_ACTIVITY_RISK_LEVEL_ID_CRITICAL = 4; // Type: OCSF_VALUE; EnumValue: 4;
	DRONE_FLIGHTS_ACTIVITY_RISK_LEVEL_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum DRONE_FLIGHTS_ACTIVITY_SEVERITY_ID {
	DRONE_FLIGHTS_ACTIVITY_SEVERITY_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	DRONE_FLIGHTS_ACTIVITY_SEVERITY_ID_INFORMATIONAL = 1; // Type: OCSF_VALUE; EnumValue: 1;
	DRONE_FLIGHTS_ACTIVITY_SEVERITY_ID_LOW = 2; // Type: OCSF_VALUE; EnumValue: 2;
	DRONE_FLIGHTS_ACTIVITY_SEVERITY_ID_MEDIUM = 3; // Type: OCSF_VALUE; EnumValue: 3;
	DRONE_FLIGHTS_ACTIVITY_SEVERITY_ID_HIGH = 4; // EnumValue: 4; Type: OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_SEVERITY_ID_CRITICAL = 5; // Type: OCSF_VALUE; EnumValue: 5;
	DRONE_FLIGHTS_ACTIVITY_SEVERITY_ID_FATAL = 6; // Type: OCSF_VALUE; EnumValue: 6;
	DRONE_FLIGHTS_ACTIVITY_SEVERITY_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum DRONE_FLIGHTS_ACTIVITY_STATUS_ID {
	DRONE_FLIGHTS_ACTIVITY_STATUS_ID_UNKNOWN = 0; // EnumValue: 0; Type: OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_STATUS_ID_SUCCESS = 1; // Type: OCSF_VALUE; EnumValue: 1;
	DRONE_FLIGHTS_ACTIVITY_STATUS_ID_FAILURE = 2; // Type: OCSF_VALUE; EnumValue: 2;
	DRONE_FLIGHTS_ACTIVITY_STATUS_ID_AIRBORNE = 3; // Type: OCSF_VALUE; EnumValue: 3;
	DRONE_FLIGHTS_ACTIVITY_STATUS_ID_EMERGENCY = 4; // Type: OCSF_VALUE; EnumValue: 4;
	DRONE_FLIGHTS_ACTIVITY_STATUS_ID_REMOTE_ID_SYSTEM_FAILURE = 5; // Type: OCSF_VALUE; EnumValue: 5;
	DRONE_FLIGHTS_ACTIVITY_STATUS_ID_RESERVED = 6; // Type: OCSF_VALUE; EnumValue: 6;
	DRONE_FLIGHTS_ACTIVITY_STATUS_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum DRONE_FLIGHTS_ACTIVITY_TYPE_UID {
	DRONE_FLIGHTS_ACTIVITY_TYPE_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_TYPE_UID_DRONE_FLIGHTS_ACTIVITY_UNKNOWN = 800100; // Type: OCSF_VALUE; EnumValue: 800100;
	DRONE_FLIGHTS_ACTIVITY_TYPE_UID_DRONE_FLIGHTS_ACTIVITY_CAPTURE = 800101; // Type: OCSF_VALUE; EnumValue: 800101;
	DRONE_FLIGHTS_ACTIVITY_TYPE_UID_DRONE_FLIGHTS_ACTIVITY_RECORD = 800102; // EnumValue: 800102; Type: OCSF_VALUE;
	DRONE_FLIGHTS_ACTIVITY_TYPE_UID_DRONE_FLIGHTS_ACTIVITY_OTHER = 800199; // Type: OCSF_VALUE; EnumValue: 800199;
}

enum UNMANNED_SYSTEMS_ACTION_ID {
	UNMANNED_SYSTEMS_ACTION_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	UNMANNED_SYSTEMS_ACTION_ID_ALLOWED = 1; // Type: OCSF_VALUE; EnumValue: 1;
	UNMANNED_SYSTEMS_ACTION_ID_DENIED = 2; // Type: OCSF_VALUE; EnumValue: 2;
	UNMANNED_SYSTEMS_ACTION_ID_OBSERVED = 3; // Type: OCSF_VALUE; EnumValue: 3;
	UNMANNED_SYSTEMS_ACTION_ID_MODIFIED = 4; // Type: OCSF_VALUE; EnumValue: 4;
	UNMANNED_SYSTEMS_ACTION_ID_OTHER = 99; // EnumValue: 99; Type: OCSF_VALUE;
}

enum UNMANNED_SYSTEMS_ACTIVITY_ID {
	UNMANNED_SYSTEMS_ACTIVITY_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	UNMANNED_SYSTEMS_ACTIVITY_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum UNMANNED_SYSTEMS_CATEGORY_UID {
	UNMANNED_SYSTEMS_CATEGORY_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	UNMANNED_SYSTEMS_CATEGORY_UID_UNMANNED_SYSTEMS = 8; // Type: OCSF_VALUE; EnumValue: 8;
}

enum UNMANNED_SYSTEMS_CLASS_UID {
	UNMANNED_SYSTEMS_CLASS_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	UNMANNED_SYSTEMS_CLASS_UID_UNMANNED_SYSTEMS = 8000; // Type: OCSF_VALUE; EnumValue: 8000;
}

enum UNMANNED_SYSTEMS_CONFIDENCE_ID {
	UNMANNED_SYSTEMS_CONFIDENCE_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	UNMANNED_SYSTEMS_CONFIDENCE_ID_LOW = 1; // Type: OCSF_VALUE; EnumValue: 1;
	UNMANNED_SYSTEMS_CONFIDENCE_ID_MEDIUM = 2; // EnumValue: 2; Type: OCSF_VALUE;
	UNMANNED_SYSTEMS_CONFIDENCE_ID_HIGH = 3; // Type: OCSF_VALUE; EnumValue: 3;
	UNMANNED_SYSTEMS_CONFIDENCE_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum UNMANNED_SYSTEMS_DISPOSITION_ID {
	UNMANNED_SYSTEMS_DISPOSITION_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	UNMANNED_SYSTEMS_DISPOSITION_ID_ALLOWED = 1; // Type: OCSF_VALUE; EnumValue: 1;
	UNMANNED_SYSTEMS_DISPOSITION_ID_BLOCKED = 2; // Type: OCSF_VALUE; EnumValue: 2;
	UNMANNED_SYSTEMS_DISPOSITION_ID_QUARANTINED = 3; // Type: OCSF_VALUE; EnumValue: 3;
	UNMANNED_SYSTEMS_DISPOSITION_ID_ISOLATED = 4; // Type: OCSF_VALUE; EnumValue: 4;
	UNMANNED_SYSTEMS_DISPOSITION_ID_DELETED = 5; // Type: OCSF_VALUE; EnumValue: 5;
	UNMANNED_SYSTEMS_DISPOSITION_ID_DROPPED = 6; // Type: OCSF_VALUE; EnumValue: 6;
	UNMANNED_SYSTEMS_DISPOSITION_ID_CUSTOM_ACTION = 7; // Type: OCSF_VALUE; EnumValue: 7;
	UNMANNED_SYSTEMS_DISPOSITION_ID_APPROVED = 8; // Type: OCSF_VALUE; EnumValue: 8;
	UNMANNED_SYSTEMS_DISPOSITION_ID_RESTORED = 9; // EnumValue: 9; Type: OCSF_VALUE;
	UNMANNED_SYSTEMS_DISPOSITION_ID_EXONERATED = 10; // Type: OCSF_VALUE; EnumValue: 10;
	UNMANNED_SYSTEMS_DISPOSITION_ID_CORRECTED = 11; // Type: OCSF_VALUE; EnumValue: 11;
	UNMANNED_SYSTEMS_DISPOSITION_ID_PARTIALLY_CORRECTED = 12; // Type: OCSF_VALUE; EnumValue: 12;
	UNMANNED_SYSTEMS_DISPOSITION_ID_UNCORRECTED = 13; // EnumValue: 13; Type: OCSF_VALUE;
	UNMANNED_SYSTEMS_DISPOSITION_ID_DELAYED = 14; // Type: OCSF_VALUE; EnumValue: 14;
	UNMANNED_SYSTEMS_DISPOSITION_ID_DETECTED = 15; // EnumValue: 15; Type: OCSF_VALUE;
	UNMANNED_SYSTEMS_DISPOSITION_ID_NO_ACTION = 16; // Type: OCSF_VALUE; EnumValue: 16;
	UNMANNED_SYSTEMS_DISPOSITION_ID_LOGGED = 17; // Type: OCSF_VALUE; EnumValue: 17;
	UNMANNED_SYSTEMS_DISPOSITION_ID_TAGGED = 18; // Type: OCSF_VALUE; EnumValue: 18;
	UNMANNED_SYSTEMS_DISPOSITION_ID_ALERT = 19; // Type: OCSF_VALUE; EnumValue: 19;
	UNMANNED_SYSTEMS_DISPOSITION_ID_COUNT = 20; // Type: OCSF_VALUE; EnumValue: 20;
	UNMANNED_SYSTEMS_DISPOSITION_ID_RESET = 21; // Type: OCSF_VALUE; EnumValue: 21;
	UNMANNED_SYSTEMS_DISPOSITION_ID_CAPTCHA = 22; // Type: OCSF_VALUE; EnumValue: 22;
	UNMANNED_SYSTEMS_DISPOSITION_ID_CHALLENGE = 23; // Type: OCSF_VALUE; EnumValue: 23;
	UNMANNED_SYSTEMS_DISPOSITION_ID_ACCESS_REVOKED = 24; // Type: OCSF_VALUE; EnumValue: 24;
	UNMANNED_SYSTEMS_DISPOSITION_ID_REJECTED = 25; // Type: OCSF_VALUE; EnumValue: 25;
	UNMANNED_SYSTEMS_DISPOSITION_ID_UNAUTHORIZED = 26; // Type: OCSF_VALUE; EnumValue: 26;
	UNMANNED_SYSTEMS_DISPOSITION_ID_ERROR = 27; // Type: OCSF_VALUE; EnumValue: 27;
	UNMANNED_SYSTEMS_DISPOSITION_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum UNMANNED_SYSTEMS_RISK_LEVEL_ID {
	UNMANNED_SYSTEMS_RISK_LEVEL_ID_INFO = 0; // Type: OCSF_VALUE; EnumValue: 0;
	UNMANNED_SYSTEMS_RISK_LEVEL_ID_LOW = 1; // Type: OCSF_VALUE; EnumValue: 1;
	UNMANNED_SYSTEMS_RISK_LEVEL_ID_MEDIUM = 2; // Type: OCSF_VALUE; EnumValue: 2;
	UNMANNED_SYSTEMS_RISK_LEVEL_ID_HIGH = 3; // Type: OCSF_VALUE; EnumValue: 3;
	UNMANNED_SYSTEMS_RISK_LEVEL_ID_CRITICAL = 4; // Type: OCSF_VALUE; EnumValue: 4;
	UNMANNED_SYSTEMS_RISK_LEVEL_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum UNMANNED_SYSTEMS_SEVERITY_ID {
	UNMANNED_SYSTEMS_SEVERITY_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	UNMANNED_SYSTEMS_SEVERITY_ID_INFORMATIONAL = 1; // Type: OCSF_VALUE; EnumValue: 1;
	UNMANNED_SYSTEMS_SEVERITY_ID_LOW = 2; // Type: OCSF_VALUE; EnumValue: 2;
	UNMANNED_SYSTEMS_SEVERITY_ID_MEDIUM = 3; // EnumValue: 3; Type: OCSF_VALUE;
	UNMANNED_SYSTEMS_SEVERITY_ID_HIGH = 4; // Type: OCSF_VALUE; EnumValue: 4;
	UNMANNED_SYSTEMS_SEVERITY_ID_CRITICAL = 5; // Type: OCSF_VALUE; EnumValue: 5;
	UNMANNED_SYSTEMS_SEVERITY_ID_FATAL = 6; // EnumValue: 6; Type: OCSF_VALUE;
	UNMANNED_SYSTEMS_SEVERITY_ID_OTHER = 99; // EnumValue: 99; Type: OCSF_VALUE;
}

enum UNMANNED_SYSTEMS_STATUS_ID {
	UNMANNED_SYSTEMS_STATUS_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	UNMANNED_SYSTEMS_STATUS_ID_SUCCESS = 1; // Type: OCSF_VALUE; EnumValue: 1;
	UNMANNED_SYSTEMS_STATUS_ID_FAILURE = 2; // Type: OCSF_VALUE; EnumValue: 2;
	UNMANNED_SYSTEMS_STATUS_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum UNMANNED_SYSTEMS_TYPE_UID {
	UNMANNED_SYSTEMS_TYPE_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	UNMANNED_SYSTEMS_TYPE_UID_UNMANNED_SYSTEMS_UNKNOWN = 800000; // Type: OCSF_VALUE; EnumValue: 800000;
	UNMANNED_SYSTEMS_TYPE_UID_UNMANNED_SYSTEMS_OTHER = 800099; // Type: OCSF_VALUE; EnumValue: 800099;
}