syntax = "proto3";

package ocsf.v1_4_0.events.remediation.enums;

option go_package = "/ocsf/v1_4_0/events/remediation/enums";

option java_package = "com.your.project.generated.ocsf.v1_4_0.events.remediation.enums";

option java_multiple_files = true;

enum FILE_REMEDIATION_ACTIVITY_ACTION_ID {
	FILE_REMEDIATION_ACTIVITY_ACTION_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	FILE_REMEDIATION_ACTIVITY_ACTION_ID_ALLOWED = 1; // Type: OCSF_VALUE; EnumValue: 1;
	FILE_REMEDIATION_ACTIVITY_ACTION_ID_DENIED = 2; // Type: OCSF_VALUE; EnumValue: 2;
	FILE_REMEDIATION_ACTIVITY_ACTION_ID_OBSERVED = 3; // Type: OCSF_VALUE; EnumValue: 3;
	FILE_REMEDIATION_ACTIVITY_ACTION_ID_MODIFIED = 4; // Type: OCSF_VALUE; EnumValue: 4;
	FILE_REMEDIATION_ACTIVITY_ACTION_ID_OTHER = 99; // EnumValue: 99; Type: OCSF_VALUE;
}

enum FILE_REMEDIATION_ACTIVITY_ACTIVITY_ID {
	FILE_REMEDIATION_ACTIVITY_ACTIVITY_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	FILE_REMEDIATION_ACTIVITY_ACTIVITY_ID_ISOLATE = 1; // EnumValue: 1; Type: OCSF_VALUE;
	FILE_REMEDIATION_ACTIVITY_ACTIVITY_ID_EVICT = 2; // Type: OCSF_VALUE; EnumValue: 2;
	FILE_REMEDIATION_ACTIVITY_ACTIVITY_ID_RESTORE = 3; // EnumValue: 3; Type: OCSF_VALUE;
	FILE_REMEDIATION_ACTIVITY_ACTIVITY_ID_HARDEN = 4; // Type: OCSF_VALUE; EnumValue: 4;
	FILE_REMEDIATION_ACTIVITY_ACTIVITY_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum FILE_REMEDIATION_ACTIVITY_CATEGORY_UID {
	FILE_REMEDIATION_ACTIVITY_CATEGORY_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	FILE_REMEDIATION_ACTIVITY_CATEGORY_UID_REMEDIATION = 7; // EnumValue: 7; Type: OCSF_VALUE;
}

enum FILE_REMEDIATION_ACTIVITY_CLASS_UID {
	FILE_REMEDIATION_ACTIVITY_CLASS_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	FILE_REMEDIATION_ACTIVITY_CLASS_UID_FILE_REMEDIATION_ACTIVITY = 7002; // EnumValue: 7002; Type: OCSF_VALUE;
}

enum FILE_REMEDIATION_ACTIVITY_CONFIDENCE_ID {
	FILE_REMEDIATION_ACTIVITY_CONFIDENCE_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	FILE_REMEDIATION_ACTIVITY_CONFIDENCE_ID_LOW = 1; // Type: OCSF_VALUE; EnumValue: 1;
	FILE_REMEDIATION_ACTIVITY_CONFIDENCE_ID_MEDIUM = 2; // Type: OCSF_VALUE; EnumValue: 2;
	FILE_REMEDIATION_ACTIVITY_CONFIDENCE_ID_HIGH = 3; // EnumValue: 3; Type: OCSF_VALUE;
	FILE_REMEDIATION_ACTIVITY_CONFIDENCE_ID_OTHER = 99; // EnumValue: 99; Type: OCSF_VALUE;
}

enum FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID {
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_ALLOWED = 1; // Type: OCSF_VALUE; EnumValue: 1;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_BLOCKED = 2; // Type: OCSF_VALUE; EnumValue: 2;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_QUARANTINED = 3; // Type: OCSF_VALUE; EnumValue: 3;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_ISOLATED = 4; // Type: OCSF_VALUE; EnumValue: 4;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_DELETED = 5; // Type: OCSF_VALUE; EnumValue: 5;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_DROPPED = 6; // Type: OCSF_VALUE; EnumValue: 6;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_CUSTOM_ACTION = 7; // Type: OCSF_VALUE; EnumValue: 7;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_APPROVED = 8; // Type: OCSF_VALUE; EnumValue: 8;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_RESTORED = 9; // Type: OCSF_VALUE; EnumValue: 9;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_EXONERATED = 10; // Type: OCSF_VALUE; EnumValue: 10;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_CORRECTED = 11; // Type: OCSF_VALUE; EnumValue: 11;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_PARTIALLY_CORRECTED = 12; // Type: OCSF_VALUE; EnumValue: 12;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_UNCORRECTED = 13; // Type: OCSF_VALUE; EnumValue: 13;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_DELAYED = 14; // Type: OCSF_VALUE; EnumValue: 14;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_DETECTED = 15; // Type: OCSF_VALUE; EnumValue: 15;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_NO_ACTION = 16; // Type: OCSF_VALUE; EnumValue: 16;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_LOGGED = 17; // Type: OCSF_VALUE; EnumValue: 17;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_TAGGED = 18; // Type: OCSF_VALUE; EnumValue: 18;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_ALERT = 19; // Type: OCSF_VALUE; EnumValue: 19;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_COUNT = 20; // EnumValue: 20; Type: OCSF_VALUE;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_RESET = 21; // Type: OCSF_VALUE; EnumValue: 21;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_CAPTCHA = 22; // Type: OCSF_VALUE; EnumValue: 22;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_CHALLENGE = 23; // Type: OCSF_VALUE; EnumValue: 23;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_ACCESS_REVOKED = 24; // Type: OCSF_VALUE; EnumValue: 24;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_REJECTED = 25; // Type: OCSF_VALUE; EnumValue: 25;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_UNAUTHORIZED = 26; // Type: OCSF_VALUE; EnumValue: 26;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_ERROR = 27; // Type: OCSF_VALUE; EnumValue: 27;
	FILE_REMEDIATION_ACTIVITY_DISPOSITION_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum FILE_REMEDIATION_ACTIVITY_RISK_LEVEL_ID {
	FILE_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_INFO = 0; // EnumValue: 0; Type: OCSF_VALUE;
	FILE_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_LOW = 1; // Type: OCSF_VALUE; EnumValue: 1;
	FILE_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_MEDIUM = 2; // Type: OCSF_VALUE; EnumValue: 2;
	FILE_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_HIGH = 3; // Type: OCSF_VALUE; EnumValue: 3;
	FILE_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_CRITICAL = 4; // Type: OCSF_VALUE; EnumValue: 4;
	FILE_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum FILE_REMEDIATION_ACTIVITY_SEVERITY_ID {
	FILE_REMEDIATION_ACTIVITY_SEVERITY_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	FILE_REMEDIATION_ACTIVITY_SEVERITY_ID_INFORMATIONAL = 1; // Type: OCSF_VALUE; EnumValue: 1;
	FILE_REMEDIATION_ACTIVITY_SEVERITY_ID_LOW = 2; // Type: OCSF_VALUE; EnumValue: 2;
	FILE_REMEDIATION_ACTIVITY_SEVERITY_ID_MEDIUM = 3; // Type: OCSF_VALUE; EnumValue: 3;
	FILE_REMEDIATION_ACTIVITY_SEVERITY_ID_HIGH = 4; // Type: OCSF_VALUE; EnumValue: 4;
	FILE_REMEDIATION_ACTIVITY_SEVERITY_ID_CRITICAL = 5; // Type: OCSF_VALUE; EnumValue: 5;
	FILE_REMEDIATION_ACTIVITY_SEVERITY_ID_FATAL = 6; // Type: OCSF_VALUE; EnumValue: 6;
	FILE_REMEDIATION_ACTIVITY_SEVERITY_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum FILE_REMEDIATION_ACTIVITY_STATUS_ID {
	FILE_REMEDIATION_ACTIVITY_STATUS_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	FILE_REMEDIATION_ACTIVITY_STATUS_ID_SUCCESS = 1; // Type: OCSF_VALUE; EnumValue: 1;
	FILE_REMEDIATION_ACTIVITY_STATUS_ID_FAILURE = 2; // Type: OCSF_VALUE; EnumValue: 2;
	FILE_REMEDIATION_ACTIVITY_STATUS_ID_DOES_NOT_EXIST = 3; // Type: OCSF_VALUE; EnumValue: 3;
	FILE_REMEDIATION_ACTIVITY_STATUS_ID_PARTIAL = 4; // Type: OCSF_VALUE; EnumValue: 4;
	FILE_REMEDIATION_ACTIVITY_STATUS_ID_UNSUPPORTED = 5; // Type: OCSF_VALUE; EnumValue: 5;
	FILE_REMEDIATION_ACTIVITY_STATUS_ID_ERROR = 6; // Type: OCSF_VALUE; EnumValue: 6;
	FILE_REMEDIATION_ACTIVITY_STATUS_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum FILE_REMEDIATION_ACTIVITY_TYPE_UID {
	FILE_REMEDIATION_ACTIVITY_TYPE_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	FILE_REMEDIATION_ACTIVITY_TYPE_UID_FILE_REMEDIATION_ACTIVITY_UNKNOWN = 700200; // Type: OCSF_VALUE; EnumValue: 700200;
	FILE_REMEDIATION_ACTIVITY_TYPE_UID_FILE_REMEDIATION_ACTIVITY_ISOLATE = 700201; // Type: OCSF_VALUE; EnumValue: 700201;
	FILE_REMEDIATION_ACTIVITY_TYPE_UID_FILE_REMEDIATION_ACTIVITY_EVICT = 700202; // EnumValue: 700202; Type: OCSF_VALUE;
	FILE_REMEDIATION_ACTIVITY_TYPE_UID_FILE_REMEDIATION_ACTIVITY_RESTORE = 700203; // Type: OCSF_VALUE; EnumValue: 700203;
	FILE_REMEDIATION_ACTIVITY_TYPE_UID_FILE_REMEDIATION_ACTIVITY_HARDEN = 700204; // Type: OCSF_VALUE; EnumValue: 700204;
	FILE_REMEDIATION_ACTIVITY_TYPE_UID_FILE_REMEDIATION_ACTIVITY_OTHER = 700299; // Type: OCSF_VALUE; EnumValue: 700299;
}

enum NETWORK_REMEDIATION_ACTIVITY_ACTION_ID {
	NETWORK_REMEDIATION_ACTIVITY_ACTION_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	NETWORK_REMEDIATION_ACTIVITY_ACTION_ID_ALLOWED = 1; // EnumValue: 1; Type: OCSF_VALUE;
	NETWORK_REMEDIATION_ACTIVITY_ACTION_ID_DENIED = 2; // Type: OCSF_VALUE; EnumValue: 2;
	NETWORK_REMEDIATION_ACTIVITY_ACTION_ID_OBSERVED = 3; // Type: OCSF_VALUE; EnumValue: 3;
	NETWORK_REMEDIATION_ACTIVITY_ACTION_ID_MODIFIED = 4; // Type: OCSF_VALUE; EnumValue: 4;
	NETWORK_REMEDIATION_ACTIVITY_ACTION_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum NETWORK_REMEDIATION_ACTIVITY_ACTIVITY_ID {
	NETWORK_REMEDIATION_ACTIVITY_ACTIVITY_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	NETWORK_REMEDIATION_ACTIVITY_ACTIVITY_ID_ISOLATE = 1; // Type: OCSF_VALUE; EnumValue: 1;
	NETWORK_REMEDIATION_ACTIVITY_ACTIVITY_ID_EVICT = 2; // Type: OCSF_VALUE; EnumValue: 2;
	NETWORK_REMEDIATION_ACTIVITY_ACTIVITY_ID_RESTORE = 3; // Type: OCSF_VALUE; EnumValue: 3;
	NETWORK_REMEDIATION_ACTIVITY_ACTIVITY_ID_HARDEN = 4; // Type: OCSF_VALUE; EnumValue: 4;
	NETWORK_REMEDIATION_ACTIVITY_ACTIVITY_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum NETWORK_REMEDIATION_ACTIVITY_CATEGORY_UID {
	NETWORK_REMEDIATION_ACTIVITY_CATEGORY_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	NETWORK_REMEDIATION_ACTIVITY_CATEGORY_UID_REMEDIATION = 7; // Type: OCSF_VALUE; EnumValue: 7;
}

enum NETWORK_REMEDIATION_ACTIVITY_CLASS_UID {
	NETWORK_REMEDIATION_ACTIVITY_CLASS_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	NETWORK_REMEDIATION_ACTIVITY_CLASS_UID_NETWORK_REMEDIATION_ACTIVITY = 7004; // Type: OCSF_VALUE; EnumValue: 7004;
}

enum NETWORK_REMEDIATION_ACTIVITY_CONFIDENCE_ID {
	NETWORK_REMEDIATION_ACTIVITY_CONFIDENCE_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	NETWORK_REMEDIATION_ACTIVITY_CONFIDENCE_ID_LOW = 1; // Type: OCSF_VALUE; EnumValue: 1;
	NETWORK_REMEDIATION_ACTIVITY_CONFIDENCE_ID_MEDIUM = 2; // Type: OCSF_VALUE; EnumValue: 2;
	NETWORK_REMEDIATION_ACTIVITY_CONFIDENCE_ID_HIGH = 3; // Type: OCSF_VALUE; EnumValue: 3;
	NETWORK_REMEDIATION_ACTIVITY_CONFIDENCE_ID_OTHER = 99; // EnumValue: 99; Type: OCSF_VALUE;
}

enum NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID {
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_ALLOWED = 1; // Type: OCSF_VALUE; EnumValue: 1;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_BLOCKED = 2; // Type: OCSF_VALUE; EnumValue: 2;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_QUARANTINED = 3; // Type: OCSF_VALUE; EnumValue: 3;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_ISOLATED = 4; // Type: OCSF_VALUE; EnumValue: 4;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_DELETED = 5; // Type: OCSF_VALUE; EnumValue: 5;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_DROPPED = 6; // Type: OCSF_VALUE; EnumValue: 6;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_CUSTOM_ACTION = 7; // Type: OCSF_VALUE; EnumValue: 7;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_APPROVED = 8; // Type: OCSF_VALUE; EnumValue: 8;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_RESTORED = 9; // Type: OCSF_VALUE; EnumValue: 9;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_EXONERATED = 10; // Type: OCSF_VALUE; EnumValue: 10;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_CORRECTED = 11; // Type: OCSF_VALUE; EnumValue: 11;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_PARTIALLY_CORRECTED = 12; // Type: OCSF_VALUE; EnumValue: 12;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_UNCORRECTED = 13; // Type: OCSF_VALUE; EnumValue: 13;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_DELAYED = 14; // Type: OCSF_VALUE; EnumValue: 14;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_DETECTED = 15; // EnumValue: 15; Type: OCSF_VALUE;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_NO_ACTION = 16; // Type: OCSF_VALUE; EnumValue: 16;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_LOGGED = 17; // Type: OCSF_VALUE; EnumValue: 17;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_TAGGED = 18; // Type: OCSF_VALUE; EnumValue: 18;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_ALERT = 19; // Type: OCSF_VALUE; EnumValue: 19;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_COUNT = 20; // Type: OCSF_VALUE; EnumValue: 20;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_RESET = 21; // Type: OCSF_VALUE; EnumValue: 21;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_CAPTCHA = 22; // Type: OCSF_VALUE; EnumValue: 22;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_CHALLENGE = 23; // Type: OCSF_VALUE; EnumValue: 23;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_ACCESS_REVOKED = 24; // EnumValue: 24; Type: OCSF_VALUE;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_REJECTED = 25; // Type: OCSF_VALUE; EnumValue: 25;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_UNAUTHORIZED = 26; // Type: OCSF_VALUE; EnumValue: 26;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_ERROR = 27; // Type: OCSF_VALUE; EnumValue: 27;
	NETWORK_REMEDIATION_ACTIVITY_DISPOSITION_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum NETWORK_REMEDIATION_ACTIVITY_RISK_LEVEL_ID {
	NETWORK_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_INFO = 0; // Type: OCSF_VALUE; EnumValue: 0;
	NETWORK_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_LOW = 1; // Type: OCSF_VALUE; EnumValue: 1;
	NETWORK_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_MEDIUM = 2; // EnumValue: 2; Type: OCSF_VALUE;
	NETWORK_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_HIGH = 3; // Type: OCSF_VALUE; EnumValue: 3;
	NETWORK_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_CRITICAL = 4; // Type: OCSF_VALUE; EnumValue: 4;
	NETWORK_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum NETWORK_REMEDIATION_ACTIVITY_SEVERITY_ID {
	NETWORK_REMEDIATION_ACTIVITY_SEVERITY_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	NETWORK_REMEDIATION_ACTIVITY_SEVERITY_ID_INFORMATIONAL = 1; // Type: OCSF_VALUE; EnumValue: 1;
	NETWORK_REMEDIATION_ACTIVITY_SEVERITY_ID_LOW = 2; // Type: OCSF_VALUE; EnumValue: 2;
	NETWORK_REMEDIATION_ACTIVITY_SEVERITY_ID_MEDIUM = 3; // Type: OCSF_VALUE; EnumValue: 3;
	NETWORK_REMEDIATION_ACTIVITY_SEVERITY_ID_HIGH = 4; // Type: OCSF_VALUE; EnumValue: 4;
	NETWORK_REMEDIATION_ACTIVITY_SEVERITY_ID_CRITICAL = 5; // Type: OCSF_VALUE; EnumValue: 5;
	NETWORK_REMEDIATION_ACTIVITY_SEVERITY_ID_FATAL = 6; // Type: OCSF_VALUE; EnumValue: 6;
	NETWORK_REMEDIATION_ACTIVITY_SEVERITY_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum NETWORK_REMEDIATION_ACTIVITY_STATUS_ID {
	NETWORK_REMEDIATION_ACTIVITY_STATUS_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	NETWORK_REMEDIATION_ACTIVITY_STATUS_ID_SUCCESS = 1; // Type: OCSF_VALUE; EnumValue: 1;
	NETWORK_REMEDIATION_ACTIVITY_STATUS_ID_FAILURE = 2; // Type: OCSF_VALUE; EnumValue: 2;
	NETWORK_REMEDIATION_ACTIVITY_STATUS_ID_DOES_NOT_EXIST = 3; // Type: OCSF_VALUE; EnumValue: 3;
	NETWORK_REMEDIATION_ACTIVITY_STATUS_ID_PARTIAL = 4; // Type: OCSF_VALUE; EnumValue: 4;
	NETWORK_REMEDIATION_ACTIVITY_STATUS_ID_UNSUPPORTED = 5; // Type: OCSF_VALUE; EnumValue: 5;
	NETWORK_REMEDIATION_ACTIVITY_STATUS_ID_ERROR = 6; // Type: OCSF_VALUE; EnumValue: 6;
	NETWORK_REMEDIATION_ACTIVITY_STATUS_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum NETWORK_REMEDIATION_ACTIVITY_TYPE_UID {
	NETWORK_REMEDIATION_ACTIVITY_TYPE_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	NETWORK_REMEDIATION_ACTIVITY_TYPE_UID_NETWORK_REMEDIATION_ACTIVITY_UNKNOWN = 700400; // EnumValue: 700400; Type: OCSF_VALUE;
	NETWORK_REMEDIATION_ACTIVITY_TYPE_UID_NETWORK_REMEDIATION_ACTIVITY_ISOLATE = 700401; // EnumValue: 700401; Type: OCSF_VALUE;
	NETWORK_REMEDIATION_ACTIVITY_TYPE_UID_NETWORK_REMEDIATION_ACTIVITY_EVICT = 700402; // Type: OCSF_VALUE; EnumValue: 700402;
	NETWORK_REMEDIATION_ACTIVITY_TYPE_UID_NETWORK_REMEDIATION_ACTIVITY_RESTORE = 700403; // Type: OCSF_VALUE; EnumValue: 700403;
	NETWORK_REMEDIATION_ACTIVITY_TYPE_UID_NETWORK_REMEDIATION_ACTIVITY_HARDEN = 700404; // Type: OCSF_VALUE; EnumValue: 700404;
	NETWORK_REMEDIATION_ACTIVITY_TYPE_UID_NETWORK_REMEDIATION_ACTIVITY_OTHER = 700499; // Type: OCSF_VALUE; EnumValue: 700499;
}

enum PROCESS_REMEDIATION_ACTIVITY_ACTION_ID {
	PROCESS_REMEDIATION_ACTIVITY_ACTION_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	PROCESS_REMEDIATION_ACTIVITY_ACTION_ID_ALLOWED = 1; // Type: OCSF_VALUE; EnumValue: 1;
	PROCESS_REMEDIATION_ACTIVITY_ACTION_ID_DENIED = 2; // Type: OCSF_VALUE; EnumValue: 2;
	PROCESS_REMEDIATION_ACTIVITY_ACTION_ID_OBSERVED = 3; // Type: OCSF_VALUE; EnumValue: 3;
	PROCESS_REMEDIATION_ACTIVITY_ACTION_ID_MODIFIED = 4; // Type: OCSF_VALUE; EnumValue: 4;
	PROCESS_REMEDIATION_ACTIVITY_ACTION_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum PROCESS_REMEDIATION_ACTIVITY_ACTIVITY_ID {
	PROCESS_REMEDIATION_ACTIVITY_ACTIVITY_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	PROCESS_REMEDIATION_ACTIVITY_ACTIVITY_ID_ISOLATE = 1; // Type: OCSF_VALUE; EnumValue: 1;
	PROCESS_REMEDIATION_ACTIVITY_ACTIVITY_ID_EVICT = 2; // Type: OCSF_VALUE; EnumValue: 2;
	PROCESS_REMEDIATION_ACTIVITY_ACTIVITY_ID_RESTORE = 3; // Type: OCSF_VALUE; EnumValue: 3;
	PROCESS_REMEDIATION_ACTIVITY_ACTIVITY_ID_HARDEN = 4; // Type: OCSF_VALUE; EnumValue: 4;
	PROCESS_REMEDIATION_ACTIVITY_ACTIVITY_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum PROCESS_REMEDIATION_ACTIVITY_CATEGORY_UID {
	PROCESS_REMEDIATION_ACTIVITY_CATEGORY_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	PROCESS_REMEDIATION_ACTIVITY_CATEGORY_UID_REMEDIATION = 7; // Type: OCSF_VALUE; EnumValue: 7;
}

enum PROCESS_REMEDIATION_ACTIVITY_CLASS_UID {
	PROCESS_REMEDIATION_ACTIVITY_CLASS_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	PROCESS_REMEDIATION_ACTIVITY_CLASS_UID_PROCESS_REMEDIATION_ACTIVITY = 7003; // Type: OCSF_VALUE; EnumValue: 7003;
}

enum PROCESS_REMEDIATION_ACTIVITY_CONFIDENCE_ID {
	PROCESS_REMEDIATION_ACTIVITY_CONFIDENCE_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	PROCESS_REMEDIATION_ACTIVITY_CONFIDENCE_ID_LOW = 1; // Type: OCSF_VALUE; EnumValue: 1;
	PROCESS_REMEDIATION_ACTIVITY_CONFIDENCE_ID_MEDIUM = 2; // Type: OCSF_VALUE; EnumValue: 2;
	PROCESS_REMEDIATION_ACTIVITY_CONFIDENCE_ID_HIGH = 3; // Type: OCSF_VALUE; EnumValue: 3;
	PROCESS_REMEDIATION_ACTIVITY_CONFIDENCE_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID {
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_ALLOWED = 1; // Type: OCSF_VALUE; EnumValue: 1;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_BLOCKED = 2; // Type: OCSF_VALUE; EnumValue: 2;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_QUARANTINED = 3; // Type: OCSF_VALUE; EnumValue: 3;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_ISOLATED = 4; // Type: OCSF_VALUE; EnumValue: 4;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_DELETED = 5; // Type: OCSF_VALUE; EnumValue: 5;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_DROPPED = 6; // Type: OCSF_VALUE; EnumValue: 6;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_CUSTOM_ACTION = 7; // Type: OCSF_VALUE; EnumValue: 7;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_APPROVED = 8; // Type: OCSF_VALUE; EnumValue: 8;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_RESTORED = 9; // Type: OCSF_VALUE; EnumValue: 9;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_EXONERATED = 10; // Type: OCSF_VALUE; EnumValue: 10;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_CORRECTED = 11; // Type: OCSF_VALUE; EnumValue: 11;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_PARTIALLY_CORRECTED = 12; // Type: OCSF_VALUE; EnumValue: 12;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_UNCORRECTED = 13; // Type: OCSF_VALUE; EnumValue: 13;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_DELAYED = 14; // Type: OCSF_VALUE; EnumValue: 14;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_DETECTED = 15; // Type: OCSF_VALUE; EnumValue: 15;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_NO_ACTION = 16; // Type: OCSF_VALUE; EnumValue: 16;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_LOGGED = 17; // Type: OCSF_VALUE; EnumValue: 17;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_TAGGED = 18; // Type: OCSF_VALUE; EnumValue: 18;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_ALERT = 19; // Type: OCSF_VALUE; EnumValue: 19;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_COUNT = 20; // Type: OCSF_VALUE; EnumValue: 20;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_RESET = 21; // EnumValue: 21; Type: OCSF_VALUE;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_CAPTCHA = 22; // EnumValue: 22; Type: OCSF_VALUE;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_CHALLENGE = 23; // EnumValue: 23; Type: OCSF_VALUE;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_ACCESS_REVOKED = 24; // Type: OCSF_VALUE; EnumValue: 24;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_REJECTED = 25; // Type: OCSF_VALUE; EnumValue: 25;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_UNAUTHORIZED = 26; // Type: OCSF_VALUE; EnumValue: 26;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_ERROR = 27; // Type: OCSF_VALUE; EnumValue: 27;
	PROCESS_REMEDIATION_ACTIVITY_DISPOSITION_ID_OTHER = 99; // EnumValue: 99; Type: OCSF_VALUE;
}

enum PROCESS_REMEDIATION_ACTIVITY_RISK_LEVEL_ID {
	PROCESS_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_INFO = 0; // Type: OCSF_VALUE; EnumValue: 0;
	PROCESS_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_LOW = 1; // Type: OCSF_VALUE; EnumValue: 1;
	PROCESS_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_MEDIUM = 2; // Type: OCSF_VALUE; EnumValue: 2;
	PROCESS_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_HIGH = 3; // EnumValue: 3; Type: OCSF_VALUE;
	PROCESS_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_CRITICAL = 4; // EnumValue: 4; Type: OCSF_VALUE;
	PROCESS_REMEDIATION_ACTIVITY_RISK_LEVEL_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum PROCESS_REMEDIATION_ACTIVITY_SEVERITY_ID {
	PROCESS_REMEDIATION_ACTIVITY_SEVERITY_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	PROCESS_REMEDIATION_ACTIVITY_SEVERITY_ID_INFORMATIONAL = 1; // Type: OCSF_VALUE; EnumValue: 1;
	PROCESS_REMEDIATION_ACTIVITY_SEVERITY_ID_LOW = 2; // Type: OCSF_VALUE; EnumValue: 2;
	PROCESS_REMEDIATION_ACTIVITY_SEVERITY_ID_MEDIUM = 3; // EnumValue: 3; Type: OCSF_VALUE;
	PROCESS_REMEDIATION_ACTIVITY_SEVERITY_ID_HIGH = 4; // Type: OCSF_VALUE; EnumValue: 4;
	PROCESS_REMEDIATION_ACTIVITY_SEVERITY_ID_CRITICAL = 5; // Type: OCSF_VALUE; EnumValue: 5;
	PROCESS_REMEDIATION_ACTIVITY_SEVERITY_ID_FATAL = 6; // Type: OCSF_VALUE; EnumValue: 6;
	PROCESS_REMEDIATION_ACTIVITY_SEVERITY_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum PROCESS_REMEDIATION_ACTIVITY_STATUS_ID {
	PROCESS_REMEDIATION_ACTIVITY_STATUS_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	PROCESS_REMEDIATION_ACTIVITY_STATUS_ID_SUCCESS = 1; // Type: OCSF_VALUE; EnumValue: 1;
	PROCESS_REMEDIATION_ACTIVITY_STATUS_ID_FAILURE = 2; // Type: OCSF_VALUE; EnumValue: 2;
	PROCESS_REMEDIATION_ACTIVITY_STATUS_ID_DOES_NOT_EXIST = 3; // Type: OCSF_VALUE; EnumValue: 3;
	PROCESS_REMEDIATION_ACTIVITY_STATUS_ID_PARTIAL = 4; // Type: OCSF_VALUE; EnumValue: 4;
	PROCESS_REMEDIATION_ACTIVITY_STATUS_ID_UNSUPPORTED = 5; // EnumValue: 5; Type: OCSF_VALUE;
	PROCESS_REMEDIATION_ACTIVITY_STATUS_ID_ERROR = 6; // Type: OCSF_VALUE; EnumValue: 6;
	PROCESS_REMEDIATION_ACTIVITY_STATUS_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum PROCESS_REMEDIATION_ACTIVITY_TYPE_UID {
	PROCESS_REMEDIATION_ACTIVITY_TYPE_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	PROCESS_REMEDIATION_ACTIVITY_TYPE_UID_PROCESS_REMEDIATION_ACTIVITY_UNKNOWN = 700300; // Type: OCSF_VALUE; EnumValue: 700300;
	PROCESS_REMEDIATION_ACTIVITY_TYPE_UID_PROCESS_REMEDIATION_ACTIVITY_ISOLATE = 700301; // Type: OCSF_VALUE; EnumValue: 700301;
	PROCESS_REMEDIATION_ACTIVITY_TYPE_UID_PROCESS_REMEDIATION_ACTIVITY_EVICT = 700302; // Type: OCSF_VALUE; EnumValue: 700302;
	PROCESS_REMEDIATION_ACTIVITY_TYPE_UID_PROCESS_REMEDIATION_ACTIVITY_RESTORE = 700303; // Type: OCSF_VALUE; EnumValue: 700303;
	PROCESS_REMEDIATION_ACTIVITY_TYPE_UID_PROCESS_REMEDIATION_ACTIVITY_HARDEN = 700304; // Type: OCSF_VALUE; EnumValue: 700304;
	PROCESS_REMEDIATION_ACTIVITY_TYPE_UID_PROCESS_REMEDIATION_ACTIVITY_OTHER = 700399; // Type: OCSF_VALUE; EnumValue: 700399;
}

enum REMEDIATION_ACTIVITY_ACTION_ID {
	REMEDIATION_ACTIVITY_ACTION_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	REMEDIATION_ACTIVITY_ACTION_ID_ALLOWED = 1; // Type: OCSF_VALUE; EnumValue: 1;
	REMEDIATION_ACTIVITY_ACTION_ID_DENIED = 2; // Type: OCSF_VALUE; EnumValue: 2;
	REMEDIATION_ACTIVITY_ACTION_ID_OBSERVED = 3; // Type: OCSF_VALUE; EnumValue: 3;
	REMEDIATION_ACTIVITY_ACTION_ID_MODIFIED = 4; // Type: OCSF_VALUE; EnumValue: 4;
	REMEDIATION_ACTIVITY_ACTION_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum REMEDIATION_ACTIVITY_ACTIVITY_ID {
	REMEDIATION_ACTIVITY_ACTIVITY_ID_UNKNOWN = 0; // EnumValue: 0; Type: OCSF_VALUE;
	REMEDIATION_ACTIVITY_ACTIVITY_ID_ISOLATE = 1; // Type: OCSF_VALUE; EnumValue: 1;
	REMEDIATION_ACTIVITY_ACTIVITY_ID_EVICT = 2; // Type: OCSF_VALUE; EnumValue: 2;
	REMEDIATION_ACTIVITY_ACTIVITY_ID_RESTORE = 3; // EnumValue: 3; Type: OCSF_VALUE;
	REMEDIATION_ACTIVITY_ACTIVITY_ID_HARDEN = 4; // Type: OCSF_VALUE; EnumValue: 4;
	REMEDIATION_ACTIVITY_ACTIVITY_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum REMEDIATION_ACTIVITY_CATEGORY_UID {
	REMEDIATION_ACTIVITY_CATEGORY_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	REMEDIATION_ACTIVITY_CATEGORY_UID_REMEDIATION = 7; // Type: OCSF_VALUE; EnumValue: 7;
}

enum REMEDIATION_ACTIVITY_CLASS_UID {
	REMEDIATION_ACTIVITY_CLASS_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	REMEDIATION_ACTIVITY_CLASS_UID_REMEDIATION_ACTIVITY = 7001; // Type: OCSF_VALUE; EnumValue: 7001;
}

enum REMEDIATION_ACTIVITY_CONFIDENCE_ID {
	REMEDIATION_ACTIVITY_CONFIDENCE_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	REMEDIATION_ACTIVITY_CONFIDENCE_ID_LOW = 1; // Type: OCSF_VALUE; EnumValue: 1;
	REMEDIATION_ACTIVITY_CONFIDENCE_ID_MEDIUM = 2; // Type: OCSF_VALUE; EnumValue: 2;
	REMEDIATION_ACTIVITY_CONFIDENCE_ID_HIGH = 3; // Type: OCSF_VALUE; EnumValue: 3;
	REMEDIATION_ACTIVITY_CONFIDENCE_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum REMEDIATION_ACTIVITY_DISPOSITION_ID {
	REMEDIATION_ACTIVITY_DISPOSITION_ID_UNKNOWN = 0; // EnumValue: 0; Type: OCSF_VALUE;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_ALLOWED = 1; // Type: OCSF_VALUE; EnumValue: 1;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_BLOCKED = 2; // EnumValue: 2; Type: OCSF_VALUE;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_QUARANTINED = 3; // Type: OCSF_VALUE; EnumValue: 3;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_ISOLATED = 4; // EnumValue: 4; Type: OCSF_VALUE;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_DELETED = 5; // Type: OCSF_VALUE; EnumValue: 5;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_DROPPED = 6; // Type: OCSF_VALUE; EnumValue: 6;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_CUSTOM_ACTION = 7; // Type: OCSF_VALUE; EnumValue: 7;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_APPROVED = 8; // Type: OCSF_VALUE; EnumValue: 8;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_RESTORED = 9; // Type: OCSF_VALUE; EnumValue: 9;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_EXONERATED = 10; // Type: OCSF_VALUE; EnumValue: 10;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_CORRECTED = 11; // Type: OCSF_VALUE; EnumValue: 11;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_PARTIALLY_CORRECTED = 12; // Type: OCSF_VALUE; EnumValue: 12;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_UNCORRECTED = 13; // Type: OCSF_VALUE; EnumValue: 13;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_DELAYED = 14; // Type: OCSF_VALUE; EnumValue: 14;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_DETECTED = 15; // Type: OCSF_VALUE; EnumValue: 15;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_NO_ACTION = 16; // Type: OCSF_VALUE; EnumValue: 16;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_LOGGED = 17; // Type: OCSF_VALUE; EnumValue: 17;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_TAGGED = 18; // Type: OCSF_VALUE; EnumValue: 18;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_ALERT = 19; // Type: OCSF_VALUE; EnumValue: 19;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_COUNT = 20; // Type: OCSF_VALUE; EnumValue: 20;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_RESET = 21; // Type: OCSF_VALUE; EnumValue: 21;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_CAPTCHA = 22; // EnumValue: 22; Type: OCSF_VALUE;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_CHALLENGE = 23; // Type: OCSF_VALUE; EnumValue: 23;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_ACCESS_REVOKED = 24; // Type: OCSF_VALUE; EnumValue: 24;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_REJECTED = 25; // Type: OCSF_VALUE; EnumValue: 25;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_UNAUTHORIZED = 26; // Type: OCSF_VALUE; EnumValue: 26;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_ERROR = 27; // Type: OCSF_VALUE; EnumValue: 27;
	REMEDIATION_ACTIVITY_DISPOSITION_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum REMEDIATION_ACTIVITY_RISK_LEVEL_ID {
	REMEDIATION_ACTIVITY_RISK_LEVEL_ID_INFO = 0; // Type: OCSF_VALUE; EnumValue: 0;
	REMEDIATION_ACTIVITY_RISK_LEVEL_ID_LOW = 1; // Type: OCSF_VALUE; EnumValue: 1;
	REMEDIATION_ACTIVITY_RISK_LEVEL_ID_MEDIUM = 2; // Type: OCSF_VALUE; EnumValue: 2;
	REMEDIATION_ACTIVITY_RISK_LEVEL_ID_HIGH = 3; // Type: OCSF_VALUE; EnumValue: 3;
	REMEDIATION_ACTIVITY_RISK_LEVEL_ID_CRITICAL = 4; // Type: OCSF_VALUE; EnumValue: 4;
	REMEDIATION_ACTIVITY_RISK_LEVEL_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum REMEDIATION_ACTIVITY_SEVERITY_ID {
	REMEDIATION_ACTIVITY_SEVERITY_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	REMEDIATION_ACTIVITY_SEVERITY_ID_INFORMATIONAL = 1; // Type: OCSF_VALUE; EnumValue: 1;
	REMEDIATION_ACTIVITY_SEVERITY_ID_LOW = 2; // Type: OCSF_VALUE; EnumValue: 2;
	REMEDIATION_ACTIVITY_SEVERITY_ID_MEDIUM = 3; // EnumValue: 3; Type: OCSF_VALUE;
	REMEDIATION_ACTIVITY_SEVERITY_ID_HIGH = 4; // Type: OCSF_VALUE; EnumValue: 4;
	REMEDIATION_ACTIVITY_SEVERITY_ID_CRITICAL = 5; // Type: OCSF_VALUE; EnumValue: 5;
	REMEDIATION_ACTIVITY_SEVERITY_ID_FATAL = 6; // Type: OCSF_VALUE; EnumValue: 6;
	REMEDIATION_ACTIVITY_SEVERITY_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum REMEDIATION_ACTIVITY_STATUS_ID {
	REMEDIATION_ACTIVITY_STATUS_ID_UNKNOWN = 0; // Type: OCSF_VALUE; EnumValue: 0;
	REMEDIATION_ACTIVITY_STATUS_ID_SUCCESS = 1; // Type: OCSF_VALUE; EnumValue: 1;
	REMEDIATION_ACTIVITY_STATUS_ID_FAILURE = 2; // Type: OCSF_VALUE; EnumValue: 2;
	REMEDIATION_ACTIVITY_STATUS_ID_DOES_NOT_EXIST = 3; // Type: OCSF_VALUE; EnumValue: 3;
	REMEDIATION_ACTIVITY_STATUS_ID_PARTIAL = 4; // Type: OCSF_VALUE; EnumValue: 4;
	REMEDIATION_ACTIVITY_STATUS_ID_UNSUPPORTED = 5; // Type: OCSF_VALUE; EnumValue: 5;
	REMEDIATION_ACTIVITY_STATUS_ID_ERROR = 6; // EnumValue: 6; Type: OCSF_VALUE;
	REMEDIATION_ACTIVITY_STATUS_ID_OTHER = 99; // Type: OCSF_VALUE; EnumValue: 99;
}

enum REMEDIATION_ACTIVITY_TYPE_UID {
	REMEDIATION_ACTIVITY_TYPE_UID_UNSPECIFIED = 0; // Type: NON_OCSF_VALUE;
	REMEDIATION_ACTIVITY_TYPE_UID_REMEDIATION_ACTIVITY_UNKNOWN = 700100; // Type: OCSF_VALUE; EnumValue: 700100;
	REMEDIATION_ACTIVITY_TYPE_UID_REMEDIATION_ACTIVITY_ISOLATE = 700101; // Type: OCSF_VALUE; EnumValue: 700101;
	REMEDIATION_ACTIVITY_TYPE_UID_REMEDIATION_ACTIVITY_EVICT = 700102; // Type: OCSF_VALUE; EnumValue: 700102;
	REMEDIATION_ACTIVITY_TYPE_UID_REMEDIATION_ACTIVITY_RESTORE = 700103; // Type: OCSF_VALUE; EnumValue: 700103;
	REMEDIATION_ACTIVITY_TYPE_UID_REMEDIATION_ACTIVITY_HARDEN = 700104; // Type: OCSF_VALUE; EnumValue: 700104;
	REMEDIATION_ACTIVITY_TYPE_UID_REMEDIATION_ACTIVITY_OTHER = 700199; // EnumValue: 700199; Type: OCSF_VALUE;
}