syntax = "proto3";

package ocsf.v1_5_0.events.network;

option go_package = "/ocsf/v1_5_0/events/network";

option java_package = "com.your.project.generated.ocsf.v1_5_0.events.network";

option java_multiple_files = true;

import "ocsf/v1_5_0/events/network/enums/enums.proto";

import "ocsf/v1_5_0/objects/objects.proto";

import "google/protobuf/struct.proto";

// Event: network
// Event UID: 4
// URL: https://schema.ocsf.io/1.5.0/classes/dhcp_activity
message DhcpActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.DHCP_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.DHCP_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_5_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_5_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_5_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_5_0.events.network.enums.DHCP_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_5_0.events.network.enums.DHCP_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_5_0.objects.Cloud cloud = 14; // Caption: Cloud; Profile: cloud;
	string confidence = 15; // Caption: Confidence; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.DHCP_ACTIVITY_CONFIDENCE_ID confidence_id = 16; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 17; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkConnectionInfo connection_info = 18; // Caption: Connection Info;
	int32 count = 19; // Caption: Count;
	ocsf.v1_5_0.objects.Device device = 20; // Caption: Device; Profile: host;
	string disposition = 21; // Caption: Disposition; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.DHCP_ACTIVITY_DISPOSITION_ID disposition_id = 22; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkEndpoint dst_endpoint = 23; // Caption: Destination Endpoint;
	int64 duration = 24; // Caption: Duration Milliseconds;
	int64 end_time = 25; // Caption: End Time;
	repeated ocsf.v1_5_0.objects.Enrichment enrichments = 26; // Caption: Enrichments;
	ocsf.v1_5_0.objects.FirewallRule firewall_rule = 27; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 28; // Caption: Alert; Profile: security_control;
	bool is_renewal = 29; // Caption: Renewal;
	repeated ocsf.v1_5_0.objects.Ja4Fingerprint ja4_fingerprint_list = 30; // Caption: JA4+ Fingerprints;
	int32 lease_dur = 31; // Caption: Lease Duration;
	ocsf.v1_5_0.objects.LoadBalancer load_balancer = 32; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_5_0.objects.Malware malware = 33; // Caption: Malware; Profile: security_control;
	ocsf.v1_5_0.objects.MalwareScanInfo malware_scan_info = 34; // Caption: Malware Scan Info; Profile: security_control;
	string message = 35; // Caption: Message;
	ocsf.v1_5_0.objects.Metadata metadata = 36; // Caption: Metadata;
	repeated ocsf.v1_5_0.objects.Observable observables = 37; // Caption: Observables;
	repeated ocsf.v1_5_0.objects.Osint osint = 38; // Caption: OSINT; Profile: osint;
	ocsf.v1_5_0.objects.Policy policy = 39; // Caption: Policy; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkProxy proxy = 40; // Caption: Proxy;
	ocsf.v1_5_0.objects.NetworkConnectionInfo proxy_connection_info = 41; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkProxy proxy_endpoint = 42; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpRequest proxy_http_request = 43; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpResponse proxy_http_response = 44; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_5_0.objects.Tls proxy_tls = 45; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkTraffic proxy_traffic = 46; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 47; // Caption: Raw Data;
	int64 raw_data_size = 48; // Caption: Raw Data Size;
	ocsf.v1_5_0.objects.NetworkInterface relay = 49; // Caption: Relay;
	string risk_details = 50; // Caption: Risk Details; Profile: security_control;
	string risk_level = 51; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.DHCP_ACTIVITY_RISK_LEVEL_ID risk_level_id = 52; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 53; // Caption: Risk Score; Profile: security_control;
	string severity = 54; // Caption: Severity;
	ocsf.v1_5_0.events.network.enums.DHCP_ACTIVITY_SEVERITY_ID severity_id = 55; // Caption: Severity ID;
	ocsf.v1_5_0.objects.NetworkEndpoint src_endpoint = 56; // Caption: Source Endpoint;
	int64 start_time = 57; // Caption: Start Time;
	string status = 58; // Caption: Status;
	string status_code = 59; // Caption: Status Code;
	string status_detail = 60; // Caption: Status Detail;
	ocsf.v1_5_0.events.network.enums.DHCP_ACTIVITY_STATUS_ID status_id = 61; // Caption: Status ID;
	int64 time = 62; // Caption: Event Time;
	int32 timezone_offset = 63; // Caption: Timezone Offset;
	ocsf.v1_5_0.objects.Tls tls = 64; // Caption: TLS;
	ocsf.v1_5_0.objects.NetworkTraffic traffic = 65; // Caption: Traffic;
	string transaction_uid = 66; // Caption: Transaction UID;
	string type_name = 67; // Caption: Type Name;
	ocsf.v1_5_0.events.network.enums.DHCP_ACTIVITY_TYPE_UID type_uid = 68; // Caption: Type ID;
	google.protobuf.Struct unmapped = 69; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 3
// URL: https://schema.ocsf.io/1.5.0/classes/dns_activity
message DnsActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.DNS_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.DNS_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_5_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	repeated ocsf.v1_5_0.objects.DnsAnswer answers = 6; // Caption: DNS Answer;
	ocsf.v1_5_0.objects.Api api = 7; // Caption: API Details; Profile: cloud;
	string app_name = 8; // Caption: Application Name;
	repeated ocsf.v1_5_0.objects.Attack attacks = 9; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Authorization authorizations = 10; // Caption: Authorization Information; Profile: security_control;
	string category_name = 11; // Caption: Category;
	ocsf.v1_5_0.events.network.enums.DNS_ACTIVITY_CATEGORY_UID category_uid = 12; // Caption: Category ID;
	string class_name = 13; // Caption: Class;
	ocsf.v1_5_0.events.network.enums.DNS_ACTIVITY_CLASS_UID class_uid = 14; // Caption: Class ID;
	ocsf.v1_5_0.objects.Cloud cloud = 15; // Caption: Cloud; Profile: cloud;
	string confidence = 16; // Caption: Confidence; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.DNS_ACTIVITY_CONFIDENCE_ID confidence_id = 17; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 18; // Profile: security_control; Caption: Confidence Score;
	ocsf.v1_5_0.objects.NetworkConnectionInfo connection_info = 19; // Caption: Connection Info;
	int32 count = 20; // Caption: Count;
	ocsf.v1_5_0.objects.Device device = 21; // Caption: Device; Profile: host;
	string disposition = 22; // Caption: Disposition; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.DNS_ACTIVITY_DISPOSITION_ID disposition_id = 23; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkEndpoint dst_endpoint = 24; // Caption: Destination Endpoint;
	int64 duration = 25; // Caption: Duration Milliseconds;
	int64 end_time = 26; // Caption: End Time;
	repeated ocsf.v1_5_0.objects.Enrichment enrichments = 27; // Caption: Enrichments;
	ocsf.v1_5_0.objects.FirewallRule firewall_rule = 28; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 29; // Profile: security_control; Caption: Alert;
	repeated ocsf.v1_5_0.objects.Ja4Fingerprint ja4_fingerprint_list = 30; // Caption: JA4+ Fingerprints;
	ocsf.v1_5_0.objects.LoadBalancer load_balancer = 31; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_5_0.objects.Malware malware = 32; // Caption: Malware; Profile: security_control;
	ocsf.v1_5_0.objects.MalwareScanInfo malware_scan_info = 33; // Caption: Malware Scan Info; Profile: security_control;
	string message = 34; // Caption: Message;
	ocsf.v1_5_0.objects.Metadata metadata = 35; // Caption: Metadata;
	repeated ocsf.v1_5_0.objects.Observable observables = 36; // Caption: Observables;
	repeated ocsf.v1_5_0.objects.Osint osint = 37; // Caption: OSINT; Profile: osint;
	ocsf.v1_5_0.objects.Policy policy = 38; // Caption: Policy; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkProxy proxy = 39; // Caption: Proxy;
	ocsf.v1_5_0.objects.NetworkConnectionInfo proxy_connection_info = 40; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkProxy proxy_endpoint = 41; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpRequest proxy_http_request = 42; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpResponse proxy_http_response = 43; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_5_0.objects.Tls proxy_tls = 44; // Profile: network_proxy; Caption: Proxy TLS;
	ocsf.v1_5_0.objects.NetworkTraffic proxy_traffic = 45; // Caption: Proxy Traffic; Profile: network_proxy;
	ocsf.v1_5_0.objects.DnsQuery query = 46; // Caption: DNS Query;
	int64 query_time = 47; // Caption: Query Time;
	string raw_data = 48; // Caption: Raw Data;
	int64 raw_data_size = 49; // Caption: Raw Data Size;
	string rcode = 50; // Caption: Response Code;
	ocsf.v1_5_0.events.network.enums.DNS_ACTIVITY_RCODE_ID rcode_id = 51; // Caption: Response Code ID;
	int64 response_time = 52; // Caption: Response Time;
	string risk_details = 53; // Caption: Risk Details; Profile: security_control;
	string risk_level = 54; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.DNS_ACTIVITY_RISK_LEVEL_ID risk_level_id = 55; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 56; // Caption: Risk Score; Profile: security_control;
	string severity = 57; // Caption: Severity;
	ocsf.v1_5_0.events.network.enums.DNS_ACTIVITY_SEVERITY_ID severity_id = 58; // Caption: Severity ID;
	ocsf.v1_5_0.objects.NetworkEndpoint src_endpoint = 59; // Caption: Source Endpoint;
	int64 start_time = 60; // Caption: Start Time;
	string status = 61; // Caption: Status;
	string status_code = 62; // Caption: Status Code;
	string status_detail = 63; // Caption: Status Detail;
	ocsf.v1_5_0.events.network.enums.DNS_ACTIVITY_STATUS_ID status_id = 64; // Caption: Status ID;
	int64 time = 65; // Caption: Event Time;
	int32 timezone_offset = 66; // Caption: Timezone Offset;
	ocsf.v1_5_0.objects.Tls tls = 67; // Caption: TLS;
	ocsf.v1_5_0.objects.NetworkTraffic traffic = 68; // Caption: Traffic;
	string type_name = 69; // Caption: Type Name;
	ocsf.v1_5_0.events.network.enums.DNS_ACTIVITY_TYPE_UID type_uid = 70; // Caption: Type ID;
	google.protobuf.Struct unmapped = 71; // Caption: Unmapped Data;
}

// Event UID: 9
// URL: https://schema.ocsf.io/1.5.0/classes/email_activity
// Event: network
message EmailActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.EMAIL_ACTIVITY_ACTION_ID action_id = 2; // Profile: security_control; Caption: Action ID;
	ocsf.v1_5_0.events.network.enums.EMAIL_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_5_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_5_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	repeated ocsf.v1_5_0.objects.Attack attacks = 7; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	int32 attempt = 8; // Caption: Attempt;
	repeated ocsf.v1_5_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string banner = 10; // Caption: Protocol Banner;
	string category_name = 11; // Caption: Category;
	ocsf.v1_5_0.events.network.enums.EMAIL_ACTIVITY_CATEGORY_UID category_uid = 12; // Caption: Category ID;
	string class_name = 13; // Caption: Class;
	ocsf.v1_5_0.events.network.enums.EMAIL_ACTIVITY_CLASS_UID class_uid = 14; // Caption: Class ID;
	ocsf.v1_5_0.objects.Cloud cloud = 15; // Caption: Cloud; Profile: cloud;
	string command = 16; // Caption: Command;
	string confidence = 17; // Caption: Confidence; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.EMAIL_ACTIVITY_CONFIDENCE_ID confidence_id = 18; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 19; // Caption: Confidence Score; Profile: security_control;
	int32 count = 20; // Caption: Count;
	ocsf.v1_5_0.objects.Device device = 21; // Caption: Device; Profile: host;
	string direction = 22; // Caption: Direction;
	ocsf.v1_5_0.events.network.enums.EMAIL_ACTIVITY_DIRECTION_ID direction_id = 23; // Caption: Direction ID;
	string disposition = 24; // Caption: Disposition; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.EMAIL_ACTIVITY_DISPOSITION_ID disposition_id = 25; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkEndpoint dst_endpoint = 26; // Caption: Destination Endpoint;
	int64 duration = 27; // Caption: Duration Milliseconds;
	ocsf.v1_5_0.objects.Email email = 28; // Caption: Email;
	ocsf.v1_5_0.objects.EmailAuth email_auth = 29; // Caption: Email Authentication;
	int64 end_time = 30; // Caption: End Time;
	repeated ocsf.v1_5_0.objects.Enrichment enrichments = 31; // Caption: Enrichments;
	ocsf.v1_5_0.objects.FirewallRule firewall_rule = 32; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 33; // Profile: security_control; Caption: Alert;
	repeated ocsf.v1_5_0.objects.Malware malware = 34; // Profile: security_control; Caption: Malware;
	ocsf.v1_5_0.objects.MalwareScanInfo malware_scan_info = 35; // Caption: Malware Scan Info; Profile: security_control;
	string message = 36; // Caption: Message;
	string message_trace_uid = 37; // Caption: Message Trace UID;
	ocsf.v1_5_0.objects.Metadata metadata = 38; // Caption: Metadata;
	repeated ocsf.v1_5_0.objects.Observable observables = 39; // Caption: Observables;
	repeated ocsf.v1_5_0.objects.Osint osint = 40; // Caption: OSINT; Profile: osint;
	ocsf.v1_5_0.objects.Policy policy = 41; // Caption: Policy; Profile: security_control;
	string protocol_name = 42; // Caption: Protocol Name;
	string raw_data = 43; // Caption: Raw Data;
	int64 raw_data_size = 44; // Caption: Raw Data Size;
	string risk_details = 45; // Caption: Risk Details; Profile: security_control;
	string risk_level = 46; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.EMAIL_ACTIVITY_RISK_LEVEL_ID risk_level_id = 47; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 48; // Caption: Risk Score; Profile: security_control;
	string severity = 49; // Caption: Severity;
	ocsf.v1_5_0.events.network.enums.EMAIL_ACTIVITY_SEVERITY_ID severity_id = 50; // Caption: Severity ID;
	string smtp_hello = 51; // Caption: SMTP Hello;
	ocsf.v1_5_0.objects.NetworkEndpoint src_endpoint = 52; // Caption: Source Endpoint;
	int64 start_time = 53; // Caption: Start Time;
	string status = 54; // Caption: Status;
	string status_code = 55; // Caption: Status Code;
	string status_detail = 56; // Caption: Status Detail;
	ocsf.v1_5_0.events.network.enums.EMAIL_ACTIVITY_STATUS_ID status_id = 57; // Caption: Status ID;
	int64 time = 58; // Caption: Event Time;
	int32 timezone_offset = 59; // Caption: Timezone Offset;
	string type_name = 60; // Caption: Type Name;
	ocsf.v1_5_0.events.network.enums.EMAIL_ACTIVITY_TYPE_UID type_uid = 61; // Caption: Type ID;
	google.protobuf.Struct unmapped = 62; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 11
// URL: https://schema.ocsf.io/1.5.0/classes/email_file_activity
message EmailFileActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.EMAIL_FILE_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.EMAIL_FILE_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_5_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_5_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	repeated ocsf.v1_5_0.objects.Attack attacks = 7; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Authorization authorizations = 8; // Caption: Authorization Information; Profile: security_control;
	string category_name = 9; // Caption: Category;
	ocsf.v1_5_0.events.network.enums.EMAIL_FILE_ACTIVITY_CATEGORY_UID category_uid = 10; // Caption: Category ID;
	string class_name = 11; // Caption: Class;
	ocsf.v1_5_0.events.network.enums.EMAIL_FILE_ACTIVITY_CLASS_UID class_uid = 12; // Caption: Class ID;
	ocsf.v1_5_0.objects.Cloud cloud = 13; // Caption: Cloud; Profile: cloud;
	string confidence = 14; // Caption: Confidence; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.EMAIL_FILE_ACTIVITY_CONFIDENCE_ID confidence_id = 15; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 16; // Caption: Confidence Score; Profile: security_control;
	int32 count = 17; // Caption: Count;
	ocsf.v1_5_0.objects.Device device = 18; // Profile: host; Caption: Device;
	string disposition = 19; // Caption: Disposition; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.EMAIL_FILE_ACTIVITY_DISPOSITION_ID disposition_id = 20; // Profile: security_control; Caption: Disposition ID;
	int64 duration = 21; // Caption: Duration Milliseconds;
	string email_uid = 22; // Caption: Email UID;
	int64 end_time = 23; // Caption: End Time;
	repeated ocsf.v1_5_0.objects.Enrichment enrichments = 24; // Caption: Enrichments;
	ocsf.v1_5_0.objects.File file = 25; // Caption: File;
	ocsf.v1_5_0.objects.FirewallRule firewall_rule = 26; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 27; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Malware malware = 28; // Caption: Malware; Profile: security_control;
	ocsf.v1_5_0.objects.MalwareScanInfo malware_scan_info = 29; // Caption: Malware Scan Info; Profile: security_control;
	string message = 30; // Caption: Message;
	ocsf.v1_5_0.objects.Metadata metadata = 31; // Caption: Metadata;
	repeated ocsf.v1_5_0.objects.Observable observables = 32; // Caption: Observables;
	repeated ocsf.v1_5_0.objects.Osint osint = 33; // Caption: OSINT; Profile: osint;
	ocsf.v1_5_0.objects.Policy policy = 34; // Caption: Policy; Profile: security_control;
	string raw_data = 35; // Caption: Raw Data;
	int64 raw_data_size = 36; // Caption: Raw Data Size;
	string risk_details = 37; // Caption: Risk Details; Profile: security_control;
	string risk_level = 38; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.EMAIL_FILE_ACTIVITY_RISK_LEVEL_ID risk_level_id = 39; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 40; // Profile: security_control; Caption: Risk Score;
	string severity = 41; // Caption: Severity;
	ocsf.v1_5_0.events.network.enums.EMAIL_FILE_ACTIVITY_SEVERITY_ID severity_id = 42; // Caption: Severity ID;
	int64 start_time = 43; // Caption: Start Time;
	string status = 44; // Caption: Status;
	string status_code = 45; // Caption: Status Code;
	string status_detail = 46; // Caption: Status Detail;
	ocsf.v1_5_0.events.network.enums.EMAIL_FILE_ACTIVITY_STATUS_ID status_id = 47; // Caption: Status ID;
	int64 time = 48; // Caption: Event Time;
	int32 timezone_offset = 49; // Caption: Timezone Offset;
	string type_name = 50; // Caption: Type Name;
	ocsf.v1_5_0.events.network.enums.EMAIL_FILE_ACTIVITY_TYPE_UID type_uid = 51; // Caption: Type ID;
	google.protobuf.Struct unmapped = 52; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 12
// URL: https://schema.ocsf.io/1.5.0/classes/email_url_activity
message EmailUrlActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.EMAIL_URL_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.EMAIL_URL_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_5_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_5_0.objects.Api api = 6; // Profile: cloud; Caption: API Details;
	repeated ocsf.v1_5_0.objects.Attack attacks = 7; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Authorization authorizations = 8; // Caption: Authorization Information; Profile: security_control;
	string category_name = 9; // Caption: Category;
	ocsf.v1_5_0.events.network.enums.EMAIL_URL_ACTIVITY_CATEGORY_UID category_uid = 10; // Caption: Category ID;
	string class_name = 11; // Caption: Class;
	ocsf.v1_5_0.events.network.enums.EMAIL_URL_ACTIVITY_CLASS_UID class_uid = 12; // Caption: Class ID;
	ocsf.v1_5_0.objects.Cloud cloud = 13; // Caption: Cloud; Profile: cloud;
	string confidence = 14; // Caption: Confidence; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.EMAIL_URL_ACTIVITY_CONFIDENCE_ID confidence_id = 15; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 16; // Caption: Confidence Score; Profile: security_control;
	int32 count = 17; // Caption: Count;
	ocsf.v1_5_0.objects.Device device = 18; // Caption: Device; Profile: host;
	string disposition = 19; // Caption: Disposition; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.EMAIL_URL_ACTIVITY_DISPOSITION_ID disposition_id = 20; // Caption: Disposition ID; Profile: security_control;
	int64 duration = 21; // Caption: Duration Milliseconds;
	string email_uid = 22; // Caption: Email UID;
	int64 end_time = 23; // Caption: End Time;
	repeated ocsf.v1_5_0.objects.Enrichment enrichments = 24; // Caption: Enrichments;
	ocsf.v1_5_0.objects.FirewallRule firewall_rule = 25; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 26; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Malware malware = 27; // Caption: Malware; Profile: security_control;
	ocsf.v1_5_0.objects.MalwareScanInfo malware_scan_info = 28; // Caption: Malware Scan Info; Profile: security_control;
	string message = 29; // Caption: Message;
	ocsf.v1_5_0.objects.Metadata metadata = 30; // Caption: Metadata;
	repeated ocsf.v1_5_0.objects.Observable observables = 31; // Caption: Observables;
	repeated ocsf.v1_5_0.objects.Osint osint = 32; // Caption: OSINT; Profile: osint;
	ocsf.v1_5_0.objects.Policy policy = 33; // Caption: Policy; Profile: security_control;
	string raw_data = 34; // Caption: Raw Data;
	int64 raw_data_size = 35; // Caption: Raw Data Size;
	string risk_details = 36; // Caption: Risk Details; Profile: security_control;
	string risk_level = 37; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.EMAIL_URL_ACTIVITY_RISK_LEVEL_ID risk_level_id = 38; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 39; // Caption: Risk Score; Profile: security_control;
	string severity = 40; // Caption: Severity;
	ocsf.v1_5_0.events.network.enums.EMAIL_URL_ACTIVITY_SEVERITY_ID severity_id = 41; // Caption: Severity ID;
	int64 start_time = 42; // Caption: Start Time;
	string status = 43; // Caption: Status;
	string status_code = 44; // Caption: Status Code;
	string status_detail = 45; // Caption: Status Detail;
	ocsf.v1_5_0.events.network.enums.EMAIL_URL_ACTIVITY_STATUS_ID status_id = 46; // Caption: Status ID;
	int64 time = 47; // Caption: Event Time;
	int32 timezone_offset = 48; // Caption: Timezone Offset;
	string type_name = 49; // Caption: Type Name;
	ocsf.v1_5_0.events.network.enums.EMAIL_URL_ACTIVITY_TYPE_UID type_uid = 50; // Caption: Type ID;
	google.protobuf.Struct unmapped = 51; // Caption: Unmapped Data;
	ocsf.v1_5_0.objects.Url url = 52; // Caption: URL;
}

// Event: network
// Event UID: 8
// URL: https://schema.ocsf.io/1.5.0/classes/ftp_activity
message FtpActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.FTP_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.FTP_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_5_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_5_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_5_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_5_0.events.network.enums.FTP_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_5_0.events.network.enums.FTP_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_5_0.objects.Cloud cloud = 14; // Caption: Cloud; Profile: cloud;
	repeated int32 codes = 15; // Caption: Response Codes;
	string command = 16; // Caption: Command;
	repeated string command_responses = 17; // Caption: Command Responses;
	string confidence = 18; // Caption: Confidence; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.FTP_ACTIVITY_CONFIDENCE_ID confidence_id = 19; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 20; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkConnectionInfo connection_info = 21; // Caption: Connection Info;
	int32 count = 22; // Caption: Count;
	ocsf.v1_5_0.objects.Device device = 23; // Caption: Device; Profile: host;
	string disposition = 24; // Caption: Disposition; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.FTP_ACTIVITY_DISPOSITION_ID disposition_id = 25; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkEndpoint dst_endpoint = 26; // Caption: Destination Endpoint;
	int64 duration = 27; // Caption: Duration Milliseconds;
	int64 end_time = 28; // Caption: End Time;
	repeated ocsf.v1_5_0.objects.Enrichment enrichments = 29; // Caption: Enrichments;
	ocsf.v1_5_0.objects.File file = 30; // Caption: File;
	ocsf.v1_5_0.objects.FirewallRule firewall_rule = 31; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 32; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Ja4Fingerprint ja4_fingerprint_list = 33; // Caption: JA4+ Fingerprints;
	ocsf.v1_5_0.objects.LoadBalancer load_balancer = 34; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_5_0.objects.Malware malware = 35; // Caption: Malware; Profile: security_control;
	ocsf.v1_5_0.objects.MalwareScanInfo malware_scan_info = 36; // Caption: Malware Scan Info; Profile: security_control;
	string message = 37; // Caption: Message;
	ocsf.v1_5_0.objects.Metadata metadata = 38; // Caption: Metadata;
	string name = 39; // Caption: Name;
	repeated ocsf.v1_5_0.objects.Observable observables = 40; // Caption: Observables;
	repeated ocsf.v1_5_0.objects.Osint osint = 41; // Caption: OSINT; Profile: osint;
	ocsf.v1_5_0.objects.Policy policy = 42; // Caption: Policy; Profile: security_control;
	int32 port = 43; // Caption: Port;
	ocsf.v1_5_0.objects.NetworkProxy proxy = 44; // Caption: Proxy;
	ocsf.v1_5_0.objects.NetworkConnectionInfo proxy_connection_info = 45; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkProxy proxy_endpoint = 46; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpRequest proxy_http_request = 47; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpResponse proxy_http_response = 48; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_5_0.objects.Tls proxy_tls = 49; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkTraffic proxy_traffic = 50; // Profile: network_proxy; Caption: Proxy Traffic;
	string raw_data = 51; // Caption: Raw Data;
	int64 raw_data_size = 52; // Caption: Raw Data Size;
	string risk_details = 53; // Caption: Risk Details; Profile: security_control;
	string risk_level = 54; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.FTP_ACTIVITY_RISK_LEVEL_ID risk_level_id = 55; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 56; // Profile: security_control; Caption: Risk Score;
	string severity = 57; // Caption: Severity;
	ocsf.v1_5_0.events.network.enums.FTP_ACTIVITY_SEVERITY_ID severity_id = 58; // Caption: Severity ID;
	ocsf.v1_5_0.objects.NetworkEndpoint src_endpoint = 59; // Caption: Source Endpoint;
	int64 start_time = 60; // Caption: Start Time;
	string status = 61; // Caption: Status;
	string status_code = 62; // Caption: Status Code;
	string status_detail = 63; // Caption: Status Detail;
	ocsf.v1_5_0.events.network.enums.FTP_ACTIVITY_STATUS_ID status_id = 64; // Caption: Status ID;
	int64 time = 65; // Caption: Event Time;
	int32 timezone_offset = 66; // Caption: Timezone Offset;
	ocsf.v1_5_0.objects.Tls tls = 67; // Caption: TLS;
	ocsf.v1_5_0.objects.NetworkTraffic traffic = 68; // Caption: Traffic;
	string type = 69; // Caption: Type;
	string type_name = 70; // Caption: Type Name;
	ocsf.v1_5_0.events.network.enums.FTP_ACTIVITY_TYPE_UID type_uid = 71; // Caption: Type ID;
	google.protobuf.Struct unmapped = 72; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 2
// URL: https://schema.ocsf.io/1.5.0/classes/http_activity
message HttpActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.HTTP_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.HTTP_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_5_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_5_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_5_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_5_0.events.network.enums.HTTP_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_5_0.events.network.enums.HTTP_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_5_0.objects.Cloud cloud = 14; // Caption: Cloud; Profile: cloud;
	string confidence = 15; // Caption: Confidence; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.HTTP_ACTIVITY_CONFIDENCE_ID confidence_id = 16; // Profile: security_control; Caption: Confidence ID;
	int32 confidence_score = 17; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkConnectionInfo connection_info = 18; // Caption: Connection Info;
	int32 count = 19; // Caption: Count;
	ocsf.v1_5_0.objects.Device device = 20; // Caption: Device; Profile: host;
	string disposition = 21; // Caption: Disposition; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.HTTP_ACTIVITY_DISPOSITION_ID disposition_id = 22; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkEndpoint dst_endpoint = 23; // Caption: Destination Endpoint;
	int64 duration = 24; // Caption: Duration Milliseconds;
	int64 end_time = 25; // Caption: End Time;
	repeated ocsf.v1_5_0.objects.Enrichment enrichments = 26; // Caption: Enrichments;
	ocsf.v1_5_0.objects.File file = 27; // Caption: File;
	ocsf.v1_5_0.objects.FirewallRule firewall_rule = 28; // Profile: security_control; Caption: Firewall Rule;
	repeated ocsf.v1_5_0.objects.HttpCookie http_cookies = 29; // Caption: HTTP Cookies;
	ocsf.v1_5_0.objects.HttpRequest http_request = 30; // Caption: HTTP Request;
	ocsf.v1_5_0.objects.HttpResponse http_response = 31; // Caption: HTTP Response;
	int32 http_status = 32; // Caption: HTTP Status;
	bool is_alert = 33; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Ja4Fingerprint ja4_fingerprint_list = 34; // Caption: JA4+ Fingerprints;
	ocsf.v1_5_0.objects.LoadBalancer load_balancer = 35; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_5_0.objects.Malware malware = 36; // Profile: security_control; Caption: Malware;
	ocsf.v1_5_0.objects.MalwareScanInfo malware_scan_info = 37; // Caption: Malware Scan Info; Profile: security_control;
	string message = 38; // Caption: Message;
	ocsf.v1_5_0.objects.Metadata metadata = 39; // Caption: Metadata;
	repeated ocsf.v1_5_0.objects.Observable observables = 40; // Caption: Observables;
	repeated ocsf.v1_5_0.objects.Osint osint = 41; // Caption: OSINT; Profile: osint;
	ocsf.v1_5_0.objects.Policy policy = 42; // Caption: Policy; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkProxy proxy = 43; // Caption: Proxy;
	ocsf.v1_5_0.objects.NetworkConnectionInfo proxy_connection_info = 44; // Profile: network_proxy; Caption: Proxy Connection Info;
	ocsf.v1_5_0.objects.NetworkProxy proxy_endpoint = 45; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpRequest proxy_http_request = 46; // Profile: network_proxy; Caption: Proxy HTTP Request;
	ocsf.v1_5_0.objects.HttpResponse proxy_http_response = 47; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_5_0.objects.Tls proxy_tls = 48; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkTraffic proxy_traffic = 49; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 50; // Caption: Raw Data;
	int64 raw_data_size = 51; // Caption: Raw Data Size;
	string risk_details = 52; // Caption: Risk Details; Profile: security_control;
	string risk_level = 53; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.HTTP_ACTIVITY_RISK_LEVEL_ID risk_level_id = 54; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 55; // Caption: Risk Score; Profile: security_control;
	string severity = 56; // Caption: Severity;
	ocsf.v1_5_0.events.network.enums.HTTP_ACTIVITY_SEVERITY_ID severity_id = 57; // Caption: Severity ID;
	ocsf.v1_5_0.objects.NetworkEndpoint src_endpoint = 58; // Caption: Source Endpoint;
	int64 start_time = 59; // Caption: Start Time;
	string status = 60; // Caption: Status;
	string status_code = 61; // Caption: Status Code;
	string status_detail = 62; // Caption: Status Detail;
	ocsf.v1_5_0.events.network.enums.HTTP_ACTIVITY_STATUS_ID status_id = 63; // Caption: Status ID;
	int64 time = 64; // Caption: Event Time;
	int32 timezone_offset = 65; // Caption: Timezone Offset;
	ocsf.v1_5_0.objects.Tls tls = 66; // Caption: TLS;
	ocsf.v1_5_0.objects.Trace trace = 67; // Caption: Trace; Profile: trace;
	ocsf.v1_5_0.objects.NetworkTraffic traffic = 68; // Caption: Traffic;
	string type_name = 69; // Caption: Type Name;
	ocsf.v1_5_0.events.network.enums.HTTP_ACTIVITY_TYPE_UID type_uid = 70; // Caption: Type ID;
	google.protobuf.Struct unmapped = 71; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 0
// URL: https://schema.ocsf.io/1.5.0/classes/network
message Network {
	string action = 1; // Profile: security_control; Caption: Action;
	ocsf.v1_5_0.events.network.enums.NETWORK_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NETWORK_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_5_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_5_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_5_0.objects.Attack attacks = 8; // Profile: security_control; Caption: MITRE ATT&CK® and ATLAS™ Details;
	repeated ocsf.v1_5_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_5_0.events.network.enums.NETWORK_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_5_0.events.network.enums.NETWORK_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_5_0.objects.Cloud cloud = 14; // Caption: Cloud; Profile: cloud;
	string confidence = 15; // Caption: Confidence; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NETWORK_CONFIDENCE_ID confidence_id = 16; // Profile: security_control; Caption: Confidence ID;
	int32 confidence_score = 17; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkConnectionInfo connection_info = 18; // Caption: Connection Info;
	int32 count = 19; // Caption: Count;
	ocsf.v1_5_0.objects.Device device = 20; // Caption: Device; Profile: host;
	string disposition = 21; // Caption: Disposition; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NETWORK_DISPOSITION_ID disposition_id = 22; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkEndpoint dst_endpoint = 23; // Caption: Destination Endpoint;
	int64 duration = 24; // Caption: Duration Milliseconds;
	int64 end_time = 25; // Caption: End Time;
	repeated ocsf.v1_5_0.objects.Enrichment enrichments = 26; // Caption: Enrichments;
	ocsf.v1_5_0.objects.FirewallRule firewall_rule = 27; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 28; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Ja4Fingerprint ja4_fingerprint_list = 29; // Caption: JA4+ Fingerprints;
	ocsf.v1_5_0.objects.LoadBalancer load_balancer = 30; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_5_0.objects.Malware malware = 31; // Caption: Malware; Profile: security_control;
	ocsf.v1_5_0.objects.MalwareScanInfo malware_scan_info = 32; // Profile: security_control; Caption: Malware Scan Info;
	string message = 33; // Caption: Message;
	ocsf.v1_5_0.objects.Metadata metadata = 34; // Caption: Metadata;
	repeated ocsf.v1_5_0.objects.Observable observables = 35; // Caption: Observables;
	repeated ocsf.v1_5_0.objects.Osint osint = 36; // Caption: OSINT; Profile: osint;
	ocsf.v1_5_0.objects.Policy policy = 37; // Caption: Policy; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkProxy proxy = 38; // Caption: Proxy;
	ocsf.v1_5_0.objects.NetworkConnectionInfo proxy_connection_info = 39; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkProxy proxy_endpoint = 40; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpRequest proxy_http_request = 41; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpResponse proxy_http_response = 42; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_5_0.objects.Tls proxy_tls = 43; // Profile: network_proxy; Caption: Proxy TLS;
	ocsf.v1_5_0.objects.NetworkTraffic proxy_traffic = 44; // Profile: network_proxy; Caption: Proxy Traffic;
	string raw_data = 45; // Caption: Raw Data;
	int64 raw_data_size = 46; // Caption: Raw Data Size;
	string risk_details = 47; // Caption: Risk Details; Profile: security_control;
	string risk_level = 48; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NETWORK_RISK_LEVEL_ID risk_level_id = 49; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 50; // Caption: Risk Score; Profile: security_control;
	string severity = 51; // Caption: Severity;
	ocsf.v1_5_0.events.network.enums.NETWORK_SEVERITY_ID severity_id = 52; // Caption: Severity ID;
	ocsf.v1_5_0.objects.NetworkEndpoint src_endpoint = 53; // Caption: Source Endpoint;
	int64 start_time = 54; // Caption: Start Time;
	string status = 55; // Caption: Status;
	string status_code = 56; // Caption: Status Code;
	string status_detail = 57; // Caption: Status Detail;
	ocsf.v1_5_0.events.network.enums.NETWORK_STATUS_ID status_id = 58; // Caption: Status ID;
	int64 time = 59; // Caption: Event Time;
	int32 timezone_offset = 60; // Caption: Timezone Offset;
	ocsf.v1_5_0.objects.Tls tls = 61; // Caption: TLS;
	ocsf.v1_5_0.objects.NetworkTraffic traffic = 62; // Caption: Traffic;
	string type_name = 63; // Caption: Type Name;
	ocsf.v1_5_0.events.network.enums.NETWORK_TYPE_UID type_uid = 64; // Caption: Type ID;
	google.protobuf.Struct unmapped = 65; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 1
// URL: https://schema.ocsf.io/1.5.0/classes/network_activity
message NetworkActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NETWORK_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NETWORK_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_5_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_5_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_5_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_5_0.events.network.enums.NETWORK_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_5_0.events.network.enums.NETWORK_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_5_0.objects.Cloud cloud = 14; // Caption: Cloud; Profile: cloud;
	string confidence = 15; // Caption: Confidence; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NETWORK_ACTIVITY_CONFIDENCE_ID confidence_id = 16; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 17; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkConnectionInfo connection_info = 18; // Caption: Connection Info;
	int32 count = 19; // Caption: Count;
	ocsf.v1_5_0.objects.Device device = 20; // Caption: Device; Profile: host;
	string disposition = 21; // Caption: Disposition; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NETWORK_ACTIVITY_DISPOSITION_ID disposition_id = 22; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkEndpoint dst_endpoint = 23; // Caption: Destination Endpoint;
	int64 duration = 24; // Caption: Duration Milliseconds;
	int64 end_time = 25; // Caption: End Time;
	repeated ocsf.v1_5_0.objects.Enrichment enrichments = 26; // Caption: Enrichments;
	ocsf.v1_5_0.objects.FirewallRule firewall_rule = 27; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 28; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Ja4Fingerprint ja4_fingerprint_list = 29; // Caption: JA4+ Fingerprints;
	ocsf.v1_5_0.objects.LoadBalancer load_balancer = 30; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_5_0.objects.Malware malware = 31; // Caption: Malware; Profile: security_control;
	ocsf.v1_5_0.objects.MalwareScanInfo malware_scan_info = 32; // Caption: Malware Scan Info; Profile: security_control;
	string message = 33; // Caption: Message;
	ocsf.v1_5_0.objects.Metadata metadata = 34; // Caption: Metadata;
	repeated ocsf.v1_5_0.objects.Observable observables = 35; // Caption: Observables;
	repeated ocsf.v1_5_0.objects.Osint osint = 36; // Caption: OSINT; Profile: osint;
	ocsf.v1_5_0.objects.Policy policy = 37; // Caption: Policy; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkProxy proxy = 38; // Caption: Proxy;
	ocsf.v1_5_0.objects.NetworkConnectionInfo proxy_connection_info = 39; // Profile: network_proxy; Caption: Proxy Connection Info;
	ocsf.v1_5_0.objects.NetworkProxy proxy_endpoint = 40; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpRequest proxy_http_request = 41; // Profile: network_proxy; Caption: Proxy HTTP Request;
	ocsf.v1_5_0.objects.HttpResponse proxy_http_response = 42; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_5_0.objects.Tls proxy_tls = 43; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkTraffic proxy_traffic = 44; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 45; // Caption: Raw Data;
	int64 raw_data_size = 46; // Caption: Raw Data Size;
	string risk_details = 47; // Caption: Risk Details; Profile: security_control;
	string risk_level = 48; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NETWORK_ACTIVITY_RISK_LEVEL_ID risk_level_id = 49; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 50; // Profile: security_control; Caption: Risk Score;
	string severity = 51; // Caption: Severity;
	ocsf.v1_5_0.events.network.enums.NETWORK_ACTIVITY_SEVERITY_ID severity_id = 52; // Caption: Severity ID;
	ocsf.v1_5_0.objects.NetworkEndpoint src_endpoint = 53; // Caption: Source Endpoint;
	int64 start_time = 54; // Caption: Start Time;
	string status = 55; // Caption: Status;
	string status_code = 56; // Caption: Status Code;
	string status_detail = 57; // Caption: Status Detail;
	ocsf.v1_5_0.events.network.enums.NETWORK_ACTIVITY_STATUS_ID status_id = 58; // Caption: Status ID;
	int64 time = 59; // Caption: Event Time;
	int32 timezone_offset = 60; // Caption: Timezone Offset;
	ocsf.v1_5_0.objects.Tls tls = 61; // Caption: TLS;
	ocsf.v1_5_0.objects.NetworkTraffic traffic = 62; // Caption: Traffic;
	string type_name = 63; // Caption: Type Name;
	ocsf.v1_5_0.events.network.enums.NETWORK_ACTIVITY_TYPE_UID type_uid = 64; // Caption: Type ID;
	google.protobuf.Struct unmapped = 65; // Caption: Unmapped Data;
	ocsf.v1_5_0.objects.Url url = 66; // Caption: URL;
}

// Event: network
// Event UID: 10
// URL: https://schema.ocsf.io/1.5.0/classes/network_file_activity
message NetworkFileActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NETWORK_FILE_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NETWORK_FILE_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_5_0.objects.Actor actor = 5; // Caption: Actor;
	ocsf.v1_5_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_5_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_5_0.events.network.enums.NETWORK_FILE_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_5_0.events.network.enums.NETWORK_FILE_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_5_0.objects.Cloud cloud = 14; // Caption: Cloud; Profile: cloud;
	string confidence = 15; // Caption: Confidence; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NETWORK_FILE_ACTIVITY_CONFIDENCE_ID confidence_id = 16; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 17; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkConnectionInfo connection_info = 18; // Caption: Connection Info;
	int32 count = 19; // Caption: Count;
	ocsf.v1_5_0.objects.Device device = 20; // Caption: Device; Profile: host;
	string disposition = 21; // Caption: Disposition; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NETWORK_FILE_ACTIVITY_DISPOSITION_ID disposition_id = 22; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkEndpoint dst_endpoint = 23; // Caption: Destination Endpoint;
	int64 duration = 24; // Caption: Duration Milliseconds;
	int64 end_time = 25; // Caption: End Time;
	repeated ocsf.v1_5_0.objects.Enrichment enrichments = 26; // Caption: Enrichments;
	int64 expiration_time = 27; // Caption: Expiration Time;
	ocsf.v1_5_0.objects.File file = 28; // Caption: File;
	ocsf.v1_5_0.objects.FirewallRule firewall_rule = 29; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 30; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Ja4Fingerprint ja4_fingerprint_list = 31; // Caption: JA4+ Fingerprints;
	ocsf.v1_5_0.objects.LoadBalancer load_balancer = 32; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_5_0.objects.Malware malware = 33; // Caption: Malware; Profile: security_control;
	ocsf.v1_5_0.objects.MalwareScanInfo malware_scan_info = 34; // Caption: Malware Scan Info; Profile: security_control;
	string message = 35; // Caption: Message;
	ocsf.v1_5_0.objects.Metadata metadata = 36; // Caption: Metadata;
	repeated ocsf.v1_5_0.objects.Observable observables = 37; // Caption: Observables;
	repeated ocsf.v1_5_0.objects.Osint osint = 38; // Caption: OSINT; Profile: osint;
	ocsf.v1_5_0.objects.Policy policy = 39; // Caption: Policy; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkProxy proxy = 40; // Caption: Proxy;
	ocsf.v1_5_0.objects.NetworkConnectionInfo proxy_connection_info = 41; // Profile: network_proxy; Caption: Proxy Connection Info;
	ocsf.v1_5_0.objects.NetworkProxy proxy_endpoint = 42; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpRequest proxy_http_request = 43; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpResponse proxy_http_response = 44; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_5_0.objects.Tls proxy_tls = 45; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkTraffic proxy_traffic = 46; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 47; // Caption: Raw Data;
	int64 raw_data_size = 48; // Caption: Raw Data Size;
	string risk_details = 49; // Caption: Risk Details; Profile: security_control;
	string risk_level = 50; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NETWORK_FILE_ACTIVITY_RISK_LEVEL_ID risk_level_id = 51; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 52; // Caption: Risk Score; Profile: security_control;
	string severity = 53; // Caption: Severity;
	ocsf.v1_5_0.events.network.enums.NETWORK_FILE_ACTIVITY_SEVERITY_ID severity_id = 54; // Caption: Severity ID;
	ocsf.v1_5_0.objects.NetworkEndpoint src_endpoint = 55; // Caption: Source Endpoint;
	int64 start_time = 56; // Caption: Start Time;
	string status = 57; // Caption: Status;
	string status_code = 58; // Caption: Status Code;
	string status_detail = 59; // Caption: Status Detail;
	ocsf.v1_5_0.events.network.enums.NETWORK_FILE_ACTIVITY_STATUS_ID status_id = 60; // Caption: Status ID;
	int64 time = 61; // Caption: Event Time;
	int32 timezone_offset = 62; // Caption: Timezone Offset;
	ocsf.v1_5_0.objects.Tls tls = 63; // Caption: TLS;
	ocsf.v1_5_0.objects.NetworkTraffic traffic = 64; // Caption: Traffic;
	string type_name = 65; // Caption: Type Name;
	ocsf.v1_5_0.events.network.enums.NETWORK_FILE_ACTIVITY_TYPE_UID type_uid = 66; // Caption: Type ID;
	google.protobuf.Struct unmapped = 67; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 13
// URL: https://schema.ocsf.io/1.5.0/classes/ntp_activity
message NtpActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NTP_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NTP_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_5_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_5_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_5_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_5_0.events.network.enums.NTP_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_5_0.events.network.enums.NTP_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_5_0.objects.Cloud cloud = 14; // Caption: Cloud; Profile: cloud;
	string confidence = 15; // Caption: Confidence; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NTP_ACTIVITY_CONFIDENCE_ID confidence_id = 16; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 17; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkConnectionInfo connection_info = 18; // Caption: Connection Info;
	int32 count = 19; // Caption: Count;
	int32 delay = 20; // Caption: Root Delay;
	ocsf.v1_5_0.objects.Device device = 21; // Caption: Device; Profile: host;
	int32 dispersion = 22; // Caption: Root Dispersion;
	string disposition = 23; // Caption: Disposition; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.NTP_ACTIVITY_DISPOSITION_ID disposition_id = 24; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkEndpoint dst_endpoint = 25; // Caption: Destination Endpoint;
	int64 duration = 26; // Caption: Duration Milliseconds;
	int64 end_time = 27; // Caption: End Time;
	repeated ocsf.v1_5_0.objects.Enrichment enrichments = 28; // Caption: Enrichments;
	ocsf.v1_5_0.objects.FirewallRule firewall_rule = 29; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 30; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Ja4Fingerprint ja4_fingerprint_list = 31; // Caption: JA4+ Fingerprints;
	ocsf.v1_5_0.objects.LoadBalancer load_balancer = 32; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_5_0.objects.Malware malware = 33; // Caption: Malware; Profile: security_control;
	ocsf.v1_5_0.objects.MalwareScanInfo malware_scan_info = 34; // Caption: Malware Scan Info; Profile: security_control;
	string message = 35; // Caption: Message;
	ocsf.v1_5_0.objects.Metadata metadata = 36; // Caption: Metadata;
	repeated ocsf.v1_5_0.objects.Observable observables = 37; // Caption: Observables;
	repeated ocsf.v1_5_0.objects.Osint osint = 38; // Caption: OSINT; Profile: osint;
	ocsf.v1_5_0.objects.Policy policy = 39; // Caption: Policy; Profile: security_control;
	int32 precision = 40; // Caption: Precision;
	ocsf.v1_5_0.objects.NetworkProxy proxy = 41; // Caption: Proxy;
	ocsf.v1_5_0.objects.NetworkConnectionInfo proxy_connection_info = 42; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkProxy proxy_endpoint = 43; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpRequest proxy_http_request = 44; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpResponse proxy_http_response = 45; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_5_0.objects.Tls proxy_tls = 46; // Profile: network_proxy; Caption: Proxy TLS;
	ocsf.v1_5_0.objects.NetworkTraffic proxy_traffic = 47; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 48; // Caption: Raw Data;
	int64 raw_data_size = 49; // Caption: Raw Data Size;
	string risk_details = 50; // Caption: Risk Details; Profile: security_control;
	string risk_level = 51; // Profile: security_control; Caption: Risk Level;
	ocsf.v1_5_0.events.network.enums.NTP_ACTIVITY_RISK_LEVEL_ID risk_level_id = 52; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 53; // Caption: Risk Score; Profile: security_control;
	string severity = 54; // Caption: Severity;
	ocsf.v1_5_0.events.network.enums.NTP_ACTIVITY_SEVERITY_ID severity_id = 55; // Caption: Severity ID;
	ocsf.v1_5_0.objects.NetworkEndpoint src_endpoint = 56; // Caption: Source Endpoint;
	int64 start_time = 57; // Caption: Start Time;
	string status = 58; // Caption: Status;
	string status_code = 59; // Caption: Status Code;
	string status_detail = 60; // Caption: Status Detail;
	ocsf.v1_5_0.events.network.enums.NTP_ACTIVITY_STATUS_ID status_id = 61; // Caption: Status ID;
	string stratum = 62; // Caption: Stratum;
	ocsf.v1_5_0.events.network.enums.NTP_ACTIVITY_STRATUM_ID stratum_id = 63; // Caption: Stratum ID;
	int64 time = 64; // Caption: Event Time;
	int32 timezone_offset = 65; // Caption: Timezone Offset;
	ocsf.v1_5_0.objects.Tls tls = 66; // Caption: TLS;
	ocsf.v1_5_0.objects.NetworkTraffic traffic = 67; // Caption: Traffic;
	string type_name = 68; // Caption: Type Name;
	ocsf.v1_5_0.events.network.enums.NTP_ACTIVITY_TYPE_UID type_uid = 69; // Caption: Type ID;
	google.protobuf.Struct unmapped = 70; // Caption: Unmapped Data;
	string version = 71; // Caption: Version;
}

// Event: network
// Event UID: 5
// URL: https://schema.ocsf.io/1.5.0/classes/rdp_activity
message RdpActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.RDP_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.RDP_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_5_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_5_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_5_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	repeated string capabilities = 10; // Caption: Capabilities;
	string category_name = 11; // Caption: Category;
	ocsf.v1_5_0.events.network.enums.RDP_ACTIVITY_CATEGORY_UID category_uid = 12; // Caption: Category ID;
	repeated string certificate_chain = 13; // Caption: Certificate Chain;
	string class_name = 14; // Caption: Class;
	ocsf.v1_5_0.events.network.enums.RDP_ACTIVITY_CLASS_UID class_uid = 15; // Caption: Class ID;
	ocsf.v1_5_0.objects.Cloud cloud = 16; // Caption: Cloud; Profile: cloud;
	string confidence = 17; // Caption: Confidence; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.RDP_ACTIVITY_CONFIDENCE_ID confidence_id = 18; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 19; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkConnectionInfo connection_info = 20; // Caption: Connection Info;
	int32 count = 21; // Caption: Count;
	ocsf.v1_5_0.objects.Device device = 22; // Caption: Device;
	string disposition = 23; // Caption: Disposition; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.RDP_ACTIVITY_DISPOSITION_ID disposition_id = 24; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkEndpoint dst_endpoint = 25; // Caption: Destination Endpoint;
	int64 duration = 26; // Caption: Duration Milliseconds;
	int64 end_time = 27; // Caption: End Time;
	repeated ocsf.v1_5_0.objects.Enrichment enrichments = 28; // Caption: Enrichments;
	ocsf.v1_5_0.objects.File file = 29; // Caption: File;
	ocsf.v1_5_0.objects.FirewallRule firewall_rule = 30; // Caption: Firewall Rule; Profile: security_control;
	string identifier_cookie = 31; // Caption: Identifier Cookie;
	bool is_alert = 32; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Ja4Fingerprint ja4_fingerprint_list = 33; // Caption: JA4+ Fingerprints;
	ocsf.v1_5_0.objects.KeyboardInfo keyboard_info = 34; // Caption: Keyboard Information;
	ocsf.v1_5_0.objects.LoadBalancer load_balancer = 35; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_5_0.objects.Malware malware = 36; // Caption: Malware; Profile: security_control;
	ocsf.v1_5_0.objects.MalwareScanInfo malware_scan_info = 37; // Caption: Malware Scan Info; Profile: security_control;
	string message = 38; // Caption: Message;
	ocsf.v1_5_0.objects.Metadata metadata = 39; // Caption: Metadata;
	repeated ocsf.v1_5_0.objects.Observable observables = 40; // Caption: Observables;
	repeated ocsf.v1_5_0.objects.Osint osint = 41; // Caption: OSINT; Profile: osint;
	ocsf.v1_5_0.objects.Policy policy = 42; // Caption: Policy; Profile: security_control;
	string protocol_ver = 43; // Caption: Protocol Version;
	ocsf.v1_5_0.objects.NetworkProxy proxy = 44; // Caption: Proxy;
	ocsf.v1_5_0.objects.NetworkConnectionInfo proxy_connection_info = 45; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkProxy proxy_endpoint = 46; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpRequest proxy_http_request = 47; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpResponse proxy_http_response = 48; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_5_0.objects.Tls proxy_tls = 49; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkTraffic proxy_traffic = 50; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 51; // Caption: Raw Data;
	int64 raw_data_size = 52; // Caption: Raw Data Size;
	ocsf.v1_5_0.objects.Display remote_display = 53; // Caption: Remote Display;
	ocsf.v1_5_0.objects.Request request = 54; // Caption: API Request Details;
	ocsf.v1_5_0.objects.Response response = 55; // Caption: API Response Details;
	string risk_details = 56; // Caption: Risk Details; Profile: security_control;
	string risk_level = 57; // Profile: security_control; Caption: Risk Level;
	ocsf.v1_5_0.events.network.enums.RDP_ACTIVITY_RISK_LEVEL_ID risk_level_id = 58; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 59; // Caption: Risk Score; Profile: security_control;
	string severity = 60; // Caption: Severity;
	ocsf.v1_5_0.events.network.enums.RDP_ACTIVITY_SEVERITY_ID severity_id = 61; // Caption: Severity ID;
	ocsf.v1_5_0.objects.NetworkEndpoint src_endpoint = 62; // Caption: Source Endpoint;
	int64 start_time = 63; // Caption: Start Time;
	string status = 64; // Caption: Status;
	string status_code = 65; // Caption: Status Code;
	string status_detail = 66; // Caption: Status Detail;
	ocsf.v1_5_0.events.network.enums.RDP_ACTIVITY_STATUS_ID status_id = 67; // Caption: Status ID;
	int64 time = 68; // Caption: Event Time;
	int32 timezone_offset = 69; // Caption: Timezone Offset;
	ocsf.v1_5_0.objects.Tls tls = 70; // Caption: TLS;
	ocsf.v1_5_0.objects.NetworkTraffic traffic = 71; // Caption: Traffic;
	string type_name = 72; // Caption: Type Name;
	ocsf.v1_5_0.events.network.enums.RDP_ACTIVITY_TYPE_UID type_uid = 73; // Caption: Type ID;
	google.protobuf.Struct unmapped = 74; // Caption: Unmapped Data;
}

// Event UID: 6
// URL: https://schema.ocsf.io/1.5.0/classes/smb_activity
// Event: network
message SmbActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.SMB_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.SMB_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_5_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_5_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_5_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_5_0.events.network.enums.SMB_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_5_0.events.network.enums.SMB_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	repeated string client_dialects = 14; // Caption: Client Dialects;
	ocsf.v1_5_0.objects.Cloud cloud = 15; // Caption: Cloud; Profile: cloud;
	string command = 16; // Caption: Command;
	string confidence = 17; // Caption: Confidence; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.SMB_ACTIVITY_CONFIDENCE_ID confidence_id = 18; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 19; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkConnectionInfo connection_info = 20; // Caption: Connection Info;
	int32 count = 21; // Caption: Count;
	ocsf.v1_5_0.objects.DceRpc dce_rpc = 22; // Caption: Distributed Computing Environment/Remote Procedure Call (DCE/RPC);
	ocsf.v1_5_0.objects.Device device = 23; // Caption: Device; Profile: host;
	string dialect = 24; // Caption: Dialect;
	string disposition = 25; // Caption: Disposition; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.SMB_ACTIVITY_DISPOSITION_ID disposition_id = 26; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkEndpoint dst_endpoint = 27; // Caption: Destination Endpoint;
	int64 duration = 28; // Caption: Duration Milliseconds;
	int64 end_time = 29; // Caption: End Time;
	repeated ocsf.v1_5_0.objects.Enrichment enrichments = 30; // Caption: Enrichments;
	ocsf.v1_5_0.objects.File file = 31; // Caption: File;
	ocsf.v1_5_0.objects.FirewallRule firewall_rule = 32; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 33; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Ja4Fingerprint ja4_fingerprint_list = 34; // Caption: JA4+ Fingerprints;
	ocsf.v1_5_0.objects.LoadBalancer load_balancer = 35; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_5_0.objects.Malware malware = 36; // Caption: Malware; Profile: security_control;
	ocsf.v1_5_0.objects.MalwareScanInfo malware_scan_info = 37; // Caption: Malware Scan Info; Profile: security_control;
	string message = 38; // Caption: Message;
	ocsf.v1_5_0.objects.Metadata metadata = 39; // Caption: Metadata;
	repeated ocsf.v1_5_0.objects.Observable observables = 40; // Caption: Observables;
	string open_type = 41; // Caption: Open Type;
	repeated ocsf.v1_5_0.objects.Osint osint = 42; // Caption: OSINT; Profile: osint;
	ocsf.v1_5_0.objects.Policy policy = 43; // Caption: Policy; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkProxy proxy = 44; // Caption: Proxy;
	ocsf.v1_5_0.objects.NetworkConnectionInfo proxy_connection_info = 45; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkProxy proxy_endpoint = 46; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpRequest proxy_http_request = 47; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpResponse proxy_http_response = 48; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_5_0.objects.Tls proxy_tls = 49; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkTraffic proxy_traffic = 50; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 51; // Caption: Raw Data;
	int64 raw_data_size = 52; // Caption: Raw Data Size;
	ocsf.v1_5_0.objects.Response response = 53; // Caption: API Response Details;
	string risk_details = 54; // Profile: security_control; Caption: Risk Details;
	string risk_level = 55; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.SMB_ACTIVITY_RISK_LEVEL_ID risk_level_id = 56; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 57; // Caption: Risk Score; Profile: security_control;
	string severity = 58; // Caption: Severity;
	ocsf.v1_5_0.events.network.enums.SMB_ACTIVITY_SEVERITY_ID severity_id = 59; // Caption: Severity ID;
	string share = 60; // Caption: Share;
	string share_type = 61; // Caption: Share Type;
	ocsf.v1_5_0.events.network.enums.SMB_ACTIVITY_SHARE_TYPE_ID share_type_id = 62; // Caption: Share Type ID;
	ocsf.v1_5_0.objects.NetworkEndpoint src_endpoint = 63; // Caption: Source Endpoint;
	int64 start_time = 64; // Caption: Start Time;
	string status = 65; // Caption: Status;
	string status_code = 66; // Caption: Status Code;
	string status_detail = 67; // Caption: Status Detail;
	ocsf.v1_5_0.events.network.enums.SMB_ACTIVITY_STATUS_ID status_id = 68; // Caption: Status ID;
	int64 time = 69; // Caption: Event Time;
	int32 timezone_offset = 70; // Caption: Timezone Offset;
	ocsf.v1_5_0.objects.Tls tls = 71; // Caption: TLS;
	ocsf.v1_5_0.objects.NetworkTraffic traffic = 72; // Caption: Traffic;
	string tree_uid = 73; // Caption: Tree UID;
	string type_name = 74; // Caption: Type Name;
	ocsf.v1_5_0.events.network.enums.SMB_ACTIVITY_TYPE_UID type_uid = 75; // Caption: Type ID;
	google.protobuf.Struct unmapped = 76; // Caption: Unmapped Data;
}

// Event UID: 7
// URL: https://schema.ocsf.io/1.5.0/classes/ssh_activity
// Event: network
message SshActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.SSH_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.SSH_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_5_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_5_0.objects.Api api = 6; // Profile: cloud; Caption: API Details;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_5_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	string auth_type = 9; // Caption: Authentication Type;
	ocsf.v1_5_0.events.network.enums.SSH_ACTIVITY_AUTH_TYPE_ID auth_type_id = 10; // Caption: Authentication Type ID;
	repeated ocsf.v1_5_0.objects.Authorization authorizations = 11; // Caption: Authorization Information; Profile: security_control;
	string category_name = 12; // Caption: Category;
	ocsf.v1_5_0.events.network.enums.SSH_ACTIVITY_CATEGORY_UID category_uid = 13; // Caption: Category ID;
	string class_name = 14; // Caption: Class;
	ocsf.v1_5_0.events.network.enums.SSH_ACTIVITY_CLASS_UID class_uid = 15; // Caption: Class ID;
	ocsf.v1_5_0.objects.Hassh client_hassh = 16; // Caption: Client HASSH;
	ocsf.v1_5_0.objects.Cloud cloud = 17; // Caption: Cloud; Profile: cloud;
	string confidence = 18; // Caption: Confidence; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.SSH_ACTIVITY_CONFIDENCE_ID confidence_id = 19; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 20; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkConnectionInfo connection_info = 21; // Caption: Connection Info;
	int32 count = 22; // Caption: Count;
	ocsf.v1_5_0.objects.Device device = 23; // Caption: Device; Profile: host;
	string disposition = 24; // Caption: Disposition; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.SSH_ACTIVITY_DISPOSITION_ID disposition_id = 25; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkEndpoint dst_endpoint = 26; // Caption: Destination Endpoint;
	int64 duration = 27; // Caption: Duration Milliseconds;
	int64 end_time = 28; // Caption: End Time;
	repeated ocsf.v1_5_0.objects.Enrichment enrichments = 29; // Caption: Enrichments;
	ocsf.v1_5_0.objects.File file = 30; // Caption: File;
	ocsf.v1_5_0.objects.FirewallRule firewall_rule = 31; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 32; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Ja4Fingerprint ja4_fingerprint_list = 33; // Caption: JA4+ Fingerprints;
	ocsf.v1_5_0.objects.LoadBalancer load_balancer = 34; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_5_0.objects.Malware malware = 35; // Caption: Malware; Profile: security_control;
	ocsf.v1_5_0.objects.MalwareScanInfo malware_scan_info = 36; // Caption: Malware Scan Info; Profile: security_control;
	string message = 37; // Caption: Message;
	ocsf.v1_5_0.objects.Metadata metadata = 38; // Caption: Metadata;
	repeated ocsf.v1_5_0.objects.Observable observables = 39; // Caption: Observables;
	repeated ocsf.v1_5_0.objects.Osint osint = 40; // Caption: OSINT; Profile: osint;
	ocsf.v1_5_0.objects.Policy policy = 41; // Caption: Policy; Profile: security_control;
	string protocol_ver = 42; // Caption: Protocol Version;
	ocsf.v1_5_0.objects.NetworkProxy proxy = 43; // Caption: Proxy;
	ocsf.v1_5_0.objects.NetworkConnectionInfo proxy_connection_info = 44; // Profile: network_proxy; Caption: Proxy Connection Info;
	ocsf.v1_5_0.objects.NetworkProxy proxy_endpoint = 45; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpRequest proxy_http_request = 46; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpResponse proxy_http_response = 47; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_5_0.objects.Tls proxy_tls = 48; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkTraffic proxy_traffic = 49; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 50; // Caption: Raw Data;
	int64 raw_data_size = 51; // Caption: Raw Data Size;
	string risk_details = 52; // Caption: Risk Details; Profile: security_control;
	string risk_level = 53; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.SSH_ACTIVITY_RISK_LEVEL_ID risk_level_id = 54; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 55; // Profile: security_control; Caption: Risk Score;
	ocsf.v1_5_0.objects.Hassh server_hassh = 56; // Caption: Server HASSH;
	string severity = 57; // Caption: Severity;
	ocsf.v1_5_0.events.network.enums.SSH_ACTIVITY_SEVERITY_ID severity_id = 58; // Caption: Severity ID;
	ocsf.v1_5_0.objects.NetworkEndpoint src_endpoint = 59; // Caption: Source Endpoint;
	int64 start_time = 60; // Caption: Start Time;
	string status = 61; // Caption: Status;
	string status_code = 62; // Caption: Status Code;
	string status_detail = 63; // Caption: Status Detail;
	ocsf.v1_5_0.events.network.enums.SSH_ACTIVITY_STATUS_ID status_id = 64; // Caption: Status ID;
	int64 time = 65; // Caption: Event Time;
	int32 timezone_offset = 66; // Caption: Timezone Offset;
	ocsf.v1_5_0.objects.Tls tls = 67; // Caption: TLS;
	ocsf.v1_5_0.objects.NetworkTraffic traffic = 68; // Caption: Traffic;
	string type_name = 69; // Caption: Type Name;
	ocsf.v1_5_0.events.network.enums.SSH_ACTIVITY_TYPE_UID type_uid = 70; // Caption: Type ID;
	google.protobuf.Struct unmapped = 71; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 14
// URL: https://schema.ocsf.io/1.5.0/classes/tunnel_activity
message TunnelActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.TUNNEL_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.TUNNEL_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_5_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_5_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_5_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_5_0.events.network.enums.TUNNEL_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_5_0.events.network.enums.TUNNEL_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_5_0.objects.Cloud cloud = 14; // Caption: Cloud; Profile: cloud;
	string confidence = 15; // Caption: Confidence; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.TUNNEL_ACTIVITY_CONFIDENCE_ID confidence_id = 16; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 17; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkConnectionInfo connection_info = 18; // Caption: Connection Info;
	int32 count = 19; // Caption: Count;
	ocsf.v1_5_0.objects.Device device = 20; // Caption: Device;
	string disposition = 21; // Profile: security_control; Caption: Disposition;
	ocsf.v1_5_0.events.network.enums.TUNNEL_ACTIVITY_DISPOSITION_ID disposition_id = 22; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_5_0.objects.NetworkEndpoint dst_endpoint = 23; // Caption: Destination Endpoint;
	int64 duration = 24; // Caption: Duration Milliseconds;
	int64 end_time = 25; // Caption: End Time;
	repeated ocsf.v1_5_0.objects.Enrichment enrichments = 26; // Caption: Enrichments;
	ocsf.v1_5_0.objects.FirewallRule firewall_rule = 27; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 28; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_5_0.objects.Ja4Fingerprint ja4_fingerprint_list = 29; // Caption: JA4+ Fingerprints;
	ocsf.v1_5_0.objects.LoadBalancer load_balancer = 30; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_5_0.objects.Malware malware = 31; // Caption: Malware; Profile: security_control;
	ocsf.v1_5_0.objects.MalwareScanInfo malware_scan_info = 32; // Caption: Malware Scan Info; Profile: security_control;
	string message = 33; // Caption: Message;
	ocsf.v1_5_0.objects.Metadata metadata = 34; // Caption: Metadata;
	repeated ocsf.v1_5_0.objects.Observable observables = 35; // Caption: Observables;
	repeated ocsf.v1_5_0.objects.Osint osint = 36; // Profile: osint; Caption: OSINT;
	ocsf.v1_5_0.objects.Policy policy = 37; // Caption: Policy; Profile: security_control;
	string protocol_name = 38; // Caption: Protocol Name;
	ocsf.v1_5_0.objects.NetworkProxy proxy = 39; // Caption: Proxy;
	ocsf.v1_5_0.objects.NetworkConnectionInfo proxy_connection_info = 40; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkProxy proxy_endpoint = 41; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpRequest proxy_http_request = 42; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_5_0.objects.HttpResponse proxy_http_response = 43; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_5_0.objects.Tls proxy_tls = 44; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_5_0.objects.NetworkTraffic proxy_traffic = 45; // Profile: network_proxy; Caption: Proxy Traffic;
	string raw_data = 46; // Caption: Raw Data;
	int64 raw_data_size = 47; // Caption: Raw Data Size;
	string risk_details = 48; // Caption: Risk Details; Profile: security_control;
	string risk_level = 49; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_5_0.events.network.enums.TUNNEL_ACTIVITY_RISK_LEVEL_ID risk_level_id = 50; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 51; // Caption: Risk Score; Profile: security_control;
	ocsf.v1_5_0.objects.Session session = 52; // Caption: Session;
	string severity = 53; // Caption: Severity;
	ocsf.v1_5_0.events.network.enums.TUNNEL_ACTIVITY_SEVERITY_ID severity_id = 54; // Caption: Severity ID;
	ocsf.v1_5_0.objects.NetworkEndpoint src_endpoint = 55; // Caption: Source Endpoint;
	int64 start_time = 56; // Caption: Start Time;
	string status = 57; // Caption: Status;
	string status_code = 58; // Caption: Status Code;
	string status_detail = 59; // Caption: Status Detail;
	ocsf.v1_5_0.events.network.enums.TUNNEL_ACTIVITY_STATUS_ID status_id = 60; // Caption: Status ID;
	int64 time = 61; // Caption: Event Time;
	int32 timezone_offset = 62; // Caption: Timezone Offset;
	ocsf.v1_5_0.objects.Tls tls = 63; // Caption: TLS;
	ocsf.v1_5_0.objects.NetworkTraffic traffic = 64; // Caption: Traffic;
	ocsf.v1_5_0.objects.NetworkInterface tunnel_interface = 65; // Caption: Interface;
	string tunnel_type = 66; // Caption: Type;
	ocsf.v1_5_0.events.network.enums.TUNNEL_ACTIVITY_TUNNEL_TYPE_ID tunnel_type_id = 67; // Caption: Type;
	string type_name = 68; // Caption: Type Name;
	ocsf.v1_5_0.events.network.enums.TUNNEL_ACTIVITY_TYPE_UID type_uid = 69; // Caption: Type ID;
	google.protobuf.Struct unmapped = 70; // Caption: Unmapped Data;
	ocsf.v1_5_0.objects.User user = 71; // Caption: User;
}