// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: ocsf/v1_0_0/events/findings/findings.proto

//go:build !protoopaque

package findings

import (
	enums "github.com/valllabh/ocsf-schema-golang/ocsf/v1_0_0/events/findings/enums"
	objects "github.com/valllabh/ocsf-schema-golang/ocsf/v1_0_0/objects"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event: findings
// Event UID: 0
// URL: https://schema.ocsf.io/1.0.0/classes/findings
type Findings struct {
	state          protoimpl.MessageState      `protogen:"hybrid.v1"`
	ActivityId     enums.FINDINGS_ACTIVITY_ID  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3,enum=ocsf.v1_0_0.events.findings.enums.FINDINGS_ACTIVITY_ID" json:"activity_id,omitempty"`     // Caption: Activity ID;
	ActivityName   string                      `protobuf:"bytes,2,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`                                                            // Caption: Activity;
	Api            *objects.Api                `protobuf:"bytes,3,opt,name=api,proto3" json:"api,omitempty"`                                                                                                  // Caption: API Details; Profile: cloud;
	CategoryName   string                      `protobuf:"bytes,4,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`                                                            // Caption: Category;
	CategoryUid    enums.FINDINGS_CATEGORY_UID `protobuf:"varint,5,opt,name=category_uid,json=categoryUid,proto3,enum=ocsf.v1_0_0.events.findings.enums.FINDINGS_CATEGORY_UID" json:"category_uid,omitempty"` // Caption: Category ID;
	ClassName      string                      `protobuf:"bytes,6,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`                                                                     // Caption: Class;
	ClassUid       enums.FINDINGS_CLASS_UID    `protobuf:"varint,7,opt,name=class_uid,json=classUid,proto3,enum=ocsf.v1_0_0.events.findings.enums.FINDINGS_CLASS_UID" json:"class_uid,omitempty"`             // Caption: Class ID;
	Cloud          *objects.Cloud              `protobuf:"bytes,8,opt,name=cloud,proto3" json:"cloud,omitempty"`                                                                                              // Caption: Cloud; Profile: cloud;
	Count          int32                       `protobuf:"varint,9,opt,name=count,proto3" json:"count,omitempty"`                                                                                             // Caption: Count;
	Duration       int32                       `protobuf:"varint,10,opt,name=duration,proto3" json:"duration,omitempty"`                                                                                      // Caption: Duration;
	EndTime        int64                       `protobuf:"varint,11,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                                                                         // Caption: End Time;
	Enrichments    []*objects.Enrichment       `protobuf:"bytes,12,rep,name=enrichments,proto3" json:"enrichments,omitempty"`                                                                                 // Caption: Enrichments;
	Message        string                      `protobuf:"bytes,13,opt,name=message,proto3" json:"message,omitempty"`                                                                                         // Caption: Message;
	Metadata       *objects.Metadata           `protobuf:"bytes,14,opt,name=metadata,proto3" json:"metadata,omitempty"`                                                                                       // Caption: Metadata;
	Observables    []*objects.Observable       `protobuf:"bytes,15,rep,name=observables,proto3" json:"observables,omitempty"`                                                                                 // Caption: Observables;
	RawData        string                      `protobuf:"bytes,16,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`                                                                          // Caption: Raw Data;
	Severity       string                      `protobuf:"bytes,17,opt,name=severity,proto3" json:"severity,omitempty"`                                                                                       // Caption: Severity;
	SeverityId     enums.FINDINGS_SEVERITY_ID  `protobuf:"varint,18,opt,name=severity_id,json=severityId,proto3,enum=ocsf.v1_0_0.events.findings.enums.FINDINGS_SEVERITY_ID" json:"severity_id,omitempty"`    // Caption: Severity ID;
	StartTime      int64                       `protobuf:"varint,19,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                                                                   // Caption: Start Time;
	Status         string                      `protobuf:"bytes,20,opt,name=status,proto3" json:"status,omitempty"`                                                                                           // Caption: Status;
	StatusCode     string                      `protobuf:"bytes,21,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                                 // Caption: Status Code;
	StatusDetail   string                      `protobuf:"bytes,22,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"`                                                           // Caption: Status Details;
	StatusId       enums.FINDINGS_STATUS_ID    `protobuf:"varint,23,opt,name=status_id,json=statusId,proto3,enum=ocsf.v1_0_0.events.findings.enums.FINDINGS_STATUS_ID" json:"status_id,omitempty"`            // Caption: Status ID;
	Time           int64                       `protobuf:"varint,24,opt,name=time,proto3" json:"time,omitempty"`                                                                                              // Caption: Event Time;
	TimezoneOffset int32                       `protobuf:"varint,25,opt,name=timezone_offset,json=timezoneOffset,proto3" json:"timezone_offset,omitempty"`                                                    // Caption: Timezone Offset;
	TypeName       string                      `protobuf:"bytes,26,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`                                                                       // Caption: Type Name;
	TypeUid        enums.FINDINGS_TYPE_UID     `protobuf:"varint,27,opt,name=type_uid,json=typeUid,proto3,enum=ocsf.v1_0_0.events.findings.enums.FINDINGS_TYPE_UID" json:"type_uid,omitempty"`                // Caption: Type ID;
	Unmapped       *structpb.Struct            `protobuf:"bytes,28,opt,name=unmapped,proto3" json:"unmapped,omitempty"`                                                                                       // Caption: Unmapped Data;
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Findings) Reset() {
	*x = Findings{}
	mi := &file_ocsf_v1_0_0_events_findings_findings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Findings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Findings) ProtoMessage() {}

func (x *Findings) ProtoReflect() protoreflect.Message {
	mi := &file_ocsf_v1_0_0_events_findings_findings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Findings) GetActivityId() enums.FINDINGS_ACTIVITY_ID {
	if x != nil {
		return x.ActivityId
	}
	return enums.FINDINGS_ACTIVITY_ID(0)
}

func (x *Findings) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *Findings) GetApi() *objects.Api {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *Findings) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Findings) GetCategoryUid() enums.FINDINGS_CATEGORY_UID {
	if x != nil {
		return x.CategoryUid
	}
	return enums.FINDINGS_CATEGORY_UID(0)
}

func (x *Findings) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Findings) GetClassUid() enums.FINDINGS_CLASS_UID {
	if x != nil {
		return x.ClassUid
	}
	return enums.FINDINGS_CLASS_UID(0)
}

func (x *Findings) GetCloud() *objects.Cloud {
	if x != nil {
		return x.Cloud
	}
	return nil
}

func (x *Findings) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Findings) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Findings) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Findings) GetEnrichments() []*objects.Enrichment {
	if x != nil {
		return x.Enrichments
	}
	return nil
}

func (x *Findings) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Findings) GetMetadata() *objects.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Findings) GetObservables() []*objects.Observable {
	if x != nil {
		return x.Observables
	}
	return nil
}

func (x *Findings) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *Findings) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Findings) GetSeverityId() enums.FINDINGS_SEVERITY_ID {
	if x != nil {
		return x.SeverityId
	}
	return enums.FINDINGS_SEVERITY_ID(0)
}

func (x *Findings) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Findings) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Findings) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *Findings) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

func (x *Findings) GetStatusId() enums.FINDINGS_STATUS_ID {
	if x != nil {
		return x.StatusId
	}
	return enums.FINDINGS_STATUS_ID(0)
}

func (x *Findings) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Findings) GetTimezoneOffset() int32 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

func (x *Findings) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *Findings) GetTypeUid() enums.FINDINGS_TYPE_UID {
	if x != nil {
		return x.TypeUid
	}
	return enums.FINDINGS_TYPE_UID(0)
}

func (x *Findings) GetUnmapped() *structpb.Struct {
	if x != nil {
		return x.Unmapped
	}
	return nil
}

func (x *Findings) SetActivityId(v enums.FINDINGS_ACTIVITY_ID) {
	x.ActivityId = v
}

func (x *Findings) SetActivityName(v string) {
	x.ActivityName = v
}

func (x *Findings) SetApi(v *objects.Api) {
	x.Api = v
}

func (x *Findings) SetCategoryName(v string) {
	x.CategoryName = v
}

func (x *Findings) SetCategoryUid(v enums.FINDINGS_CATEGORY_UID) {
	x.CategoryUid = v
}

func (x *Findings) SetClassName(v string) {
	x.ClassName = v
}

func (x *Findings) SetClassUid(v enums.FINDINGS_CLASS_UID) {
	x.ClassUid = v
}

func (x *Findings) SetCloud(v *objects.Cloud) {
	x.Cloud = v
}

func (x *Findings) SetCount(v int32) {
	x.Count = v
}

func (x *Findings) SetDuration(v int32) {
	x.Duration = v
}

func (x *Findings) SetEndTime(v int64) {
	x.EndTime = v
}

func (x *Findings) SetEnrichments(v []*objects.Enrichment) {
	x.Enrichments = v
}

func (x *Findings) SetMessage(v string) {
	x.Message = v
}

func (x *Findings) SetMetadata(v *objects.Metadata) {
	x.Metadata = v
}

func (x *Findings) SetObservables(v []*objects.Observable) {
	x.Observables = v
}

func (x *Findings) SetRawData(v string) {
	x.RawData = v
}

func (x *Findings) SetSeverity(v string) {
	x.Severity = v
}

func (x *Findings) SetSeverityId(v enums.FINDINGS_SEVERITY_ID) {
	x.SeverityId = v
}

func (x *Findings) SetStartTime(v int64) {
	x.StartTime = v
}

func (x *Findings) SetStatus(v string) {
	x.Status = v
}

func (x *Findings) SetStatusCode(v string) {
	x.StatusCode = v
}

func (x *Findings) SetStatusDetail(v string) {
	x.StatusDetail = v
}

func (x *Findings) SetStatusId(v enums.FINDINGS_STATUS_ID) {
	x.StatusId = v
}

func (x *Findings) SetTime(v int64) {
	x.Time = v
}

func (x *Findings) SetTimezoneOffset(v int32) {
	x.TimezoneOffset = v
}

func (x *Findings) SetTypeName(v string) {
	x.TypeName = v
}

func (x *Findings) SetTypeUid(v enums.FINDINGS_TYPE_UID) {
	x.TypeUid = v
}

func (x *Findings) SetUnmapped(v *structpb.Struct) {
	x.Unmapped = v
}

func (x *Findings) HasApi() bool {
	if x == nil {
		return false
	}
	return x.Api != nil
}

func (x *Findings) HasCloud() bool {
	if x == nil {
		return false
	}
	return x.Cloud != nil
}

func (x *Findings) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *Findings) HasUnmapped() bool {
	if x == nil {
		return false
	}
	return x.Unmapped != nil
}

func (x *Findings) ClearApi() {
	x.Api = nil
}

func (x *Findings) ClearCloud() {
	x.Cloud = nil
}

func (x *Findings) ClearMetadata() {
	x.Metadata = nil
}

func (x *Findings) ClearUnmapped() {
	x.Unmapped = nil
}

type Findings_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ActivityId     enums.FINDINGS_ACTIVITY_ID
	ActivityName   string
	Api            *objects.Api
	CategoryName   string
	CategoryUid    enums.FINDINGS_CATEGORY_UID
	ClassName      string
	ClassUid       enums.FINDINGS_CLASS_UID
	Cloud          *objects.Cloud
	Count          int32
	Duration       int32
	EndTime        int64
	Enrichments    []*objects.Enrichment
	Message        string
	Metadata       *objects.Metadata
	Observables    []*objects.Observable
	RawData        string
	Severity       string
	SeverityId     enums.FINDINGS_SEVERITY_ID
	StartTime      int64
	Status         string
	StatusCode     string
	StatusDetail   string
	StatusId       enums.FINDINGS_STATUS_ID
	Time           int64
	TimezoneOffset int32
	TypeName       string
	TypeUid        enums.FINDINGS_TYPE_UID
	Unmapped       *structpb.Struct
}

func (b0 Findings_builder) Build() *Findings {
	m0 := &Findings{}
	b, x := &b0, m0
	_, _ = b, x
	x.ActivityId = b.ActivityId
	x.ActivityName = b.ActivityName
	x.Api = b.Api
	x.CategoryName = b.CategoryName
	x.CategoryUid = b.CategoryUid
	x.ClassName = b.ClassName
	x.ClassUid = b.ClassUid
	x.Cloud = b.Cloud
	x.Count = b.Count
	x.Duration = b.Duration
	x.EndTime = b.EndTime
	x.Enrichments = b.Enrichments
	x.Message = b.Message
	x.Metadata = b.Metadata
	x.Observables = b.Observables
	x.RawData = b.RawData
	x.Severity = b.Severity
	x.SeverityId = b.SeverityId
	x.StartTime = b.StartTime
	x.Status = b.Status
	x.StatusCode = b.StatusCode
	x.StatusDetail = b.StatusDetail
	x.StatusId = b.StatusId
	x.Time = b.Time
	x.TimezoneOffset = b.TimezoneOffset
	x.TypeName = b.TypeName
	x.TypeUid = b.TypeUid
	x.Unmapped = b.Unmapped
	return m0
}

// Event: findings
// Event UID: 1
// URL: https://schema.ocsf.io/1.0.0/classes/security_finding
type SecurityFinding struct {
	state           protoimpl.MessageState               `protogen:"hybrid.v1"`
	ActivityId      enums.SECURITY_FINDING_ACTIVITY_ID   `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3,enum=ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_ACTIVITY_ID" json:"activity_id,omitempty"`          // Caption: Activity ID;
	ActivityName    string                               `protobuf:"bytes,2,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`                                                                         // Caption: Activity;
	Analytic        *objects.Analytic                    `protobuf:"bytes,3,opt,name=analytic,proto3" json:"analytic,omitempty"`                                                                                                     // Caption: Analytic;
	Api             *objects.Api                         `protobuf:"bytes,4,opt,name=api,proto3" json:"api,omitempty"`                                                                                                               // Profile: cloud; Caption: API Details;
	Attacks         []*objects.Attack                    `protobuf:"bytes,5,rep,name=attacks,proto3" json:"attacks,omitempty"`                                                                                                       // Caption: Attacks;
	CategoryName    string                               `protobuf:"bytes,6,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`                                                                         // Caption: Category;
	CategoryUid     enums.SECURITY_FINDING_CATEGORY_UID  `protobuf:"varint,7,opt,name=category_uid,json=categoryUid,proto3,enum=ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_CATEGORY_UID" json:"category_uid,omitempty"`      // Caption: Category ID;
	CisCsc          []*objects.CisControl                `protobuf:"bytes,8,rep,name=cis_csc,json=cisCsc,proto3" json:"cis_csc,omitempty"`                                                                                           // Caption: CIS CSC;
	ClassName       string                               `protobuf:"bytes,9,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`                                                                                  // Caption: Class;
	ClassUid        enums.SECURITY_FINDING_CLASS_UID     `protobuf:"varint,10,opt,name=class_uid,json=classUid,proto3,enum=ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_CLASS_UID" json:"class_uid,omitempty"`                 // Caption: Class ID;
	Cloud           *objects.Cloud                       `protobuf:"bytes,11,opt,name=cloud,proto3" json:"cloud,omitempty"`                                                                                                          // Caption: Cloud; Profile: cloud;
	Compliance      *objects.Compliance                  `protobuf:"bytes,12,opt,name=compliance,proto3" json:"compliance,omitempty"`                                                                                                // Caption: Compliance;
	Confidence      string                               `protobuf:"bytes,13,opt,name=confidence,proto3" json:"confidence,omitempty"`                                                                                                // Caption: Confidence;
	ConfidenceId    enums.SECURITY_FINDING_CONFIDENCE_ID `protobuf:"varint,14,opt,name=confidence_id,json=confidenceId,proto3,enum=ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_CONFIDENCE_ID" json:"confidence_id,omitempty"` // Caption: Confidence Id;
	ConfidenceScore int32                                `protobuf:"varint,15,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`                                                              // Caption: Confidence Score;
	Count           int32                                `protobuf:"varint,16,opt,name=count,proto3" json:"count,omitempty"`                                                                                                         // Caption: Count;
	DataSources     []string                             `protobuf:"bytes,17,rep,name=data_sources,json=dataSources,proto3" json:"data_sources,omitempty"`                                                                           // Caption: Data Sources;
	Duration        int32                                `protobuf:"varint,18,opt,name=duration,proto3" json:"duration,omitempty"`                                                                                                   // Caption: Duration;
	EndTime         int64                                `protobuf:"varint,19,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                                                                                      // Caption: End Time;
	Enrichments     []*objects.Enrichment                `protobuf:"bytes,20,rep,name=enrichments,proto3" json:"enrichments,omitempty"`                                                                                              // Caption: Enrichments;
	Evidence        *structpb.Struct                     `protobuf:"bytes,21,opt,name=evidence,proto3" json:"evidence,omitempty"`                                                                                                    // Caption: Evidence;
	Finding         *objects.Finding                     `protobuf:"bytes,22,opt,name=finding,proto3" json:"finding,omitempty"`                                                                                                      // Caption: Finding;
	Impact          string                               `protobuf:"bytes,23,opt,name=impact,proto3" json:"impact,omitempty"`                                                                                                        // Caption: Impact;
	ImpactId        enums.SECURITY_FINDING_IMPACT_ID     `protobuf:"varint,24,opt,name=impact_id,json=impactId,proto3,enum=ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_IMPACT_ID" json:"impact_id,omitempty"`                 // Caption: Impact ID;
	ImpactScore     int32                                `protobuf:"varint,25,opt,name=impact_score,json=impactScore,proto3" json:"impact_score,omitempty"`                                                                          // Caption: Impact;
	KillChain       []*objects.KillChain                 `protobuf:"bytes,26,rep,name=kill_chain,json=killChain,proto3" json:"kill_chain,omitempty"`                                                                                 // Caption: Kill Chain;
	Malware         []*objects.Malware                   `protobuf:"bytes,27,rep,name=malware,proto3" json:"malware,omitempty"`                                                                                                      // Caption: Malware;
	Message         string                               `protobuf:"bytes,28,opt,name=message,proto3" json:"message,omitempty"`                                                                                                      // Caption: Message;
	Metadata        *objects.Metadata                    `protobuf:"bytes,29,opt,name=metadata,proto3" json:"metadata,omitempty"`                                                                                                    // Caption: Metadata;
	Nist            []string                             `protobuf:"bytes,30,rep,name=nist,proto3" json:"nist,omitempty"`                                                                                                            // Caption: NIST List;
	Observables     []*objects.Observable                `protobuf:"bytes,31,rep,name=observables,proto3" json:"observables,omitempty"`                                                                                              // Caption: Observables;
	Process         *objects.Process                     `protobuf:"bytes,32,opt,name=process,proto3" json:"process,omitempty"`                                                                                                      // Caption: Process;
	RawData         string                               `protobuf:"bytes,33,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`                                                                                       // Caption: Raw Data;
	Resources       []*objects.ResourceDetails           `protobuf:"bytes,34,rep,name=resources,proto3" json:"resources,omitempty"`                                                                                                  // Caption: Resources Array;
	RiskLevel       string                               `protobuf:"bytes,35,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`                                                                                 // Caption: Risk Level;
	RiskLevelId     enums.SECURITY_FINDING_RISK_LEVEL_ID `protobuf:"varint,36,opt,name=risk_level_id,json=riskLevelId,proto3,enum=ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_RISK_LEVEL_ID" json:"risk_level_id,omitempty"`  // Caption: Risk Level ID;
	RiskScore       int32                                `protobuf:"varint,37,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`                                                                                // Caption: Risk Score;
	Severity        string                               `protobuf:"bytes,38,opt,name=severity,proto3" json:"severity,omitempty"`                                                                                                    // Caption: Severity;
	SeverityId      enums.SECURITY_FINDING_SEVERITY_ID   `protobuf:"varint,39,opt,name=severity_id,json=severityId,proto3,enum=ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_SEVERITY_ID" json:"severity_id,omitempty"`         // Caption: Severity ID;
	StartTime       int64                                `protobuf:"varint,40,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                                                                                // Caption: Start Time;
	State           string                               `protobuf:"bytes,41,opt,name=state,proto3" json:"state,omitempty"`                                                                                                          // Caption: State;
	StateId         enums.SECURITY_FINDING_STATE_ID      `protobuf:"varint,42,opt,name=state_id,json=stateId,proto3,enum=ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_STATE_ID" json:"state_id,omitempty"`                     // Caption: State ID;
	Status          string                               `protobuf:"bytes,43,opt,name=status,proto3" json:"status,omitempty"`                                                                                                        // Caption: Status;
	StatusCode      string                               `protobuf:"bytes,44,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                                              // Caption: Status Code;
	StatusDetail    string                               `protobuf:"bytes,45,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"`                                                                        // Caption: Status Details;
	StatusId        enums.SECURITY_FINDING_STATUS_ID     `protobuf:"varint,46,opt,name=status_id,json=statusId,proto3,enum=ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_STATUS_ID" json:"status_id,omitempty"`                 // Caption: Status ID;
	Time            int64                                `protobuf:"varint,47,opt,name=time,proto3" json:"time,omitempty"`                                                                                                           // Caption: Event Time;
	TimezoneOffset  int32                                `protobuf:"varint,48,opt,name=timezone_offset,json=timezoneOffset,proto3" json:"timezone_offset,omitempty"`                                                                 // Caption: Timezone Offset;
	TypeName        string                               `protobuf:"bytes,49,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`                                                                                    // Caption: Type Name;
	TypeUid         enums.SECURITY_FINDING_TYPE_UID      `protobuf:"varint,50,opt,name=type_uid,json=typeUid,proto3,enum=ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_TYPE_UID" json:"type_uid,omitempty"`                     // Caption: Type ID;
	Unmapped        *structpb.Struct                     `protobuf:"bytes,51,opt,name=unmapped,proto3" json:"unmapped,omitempty"`                                                                                                    // Caption: Unmapped Data;
	Vulnerabilities []*objects.Vulnerability             `protobuf:"bytes,52,rep,name=vulnerabilities,proto3" json:"vulnerabilities,omitempty"`                                                                                      // Caption: Vulnerabilities;
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SecurityFinding) Reset() {
	*x = SecurityFinding{}
	mi := &file_ocsf_v1_0_0_events_findings_findings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityFinding) ProtoMessage() {}

func (x *SecurityFinding) ProtoReflect() protoreflect.Message {
	mi := &file_ocsf_v1_0_0_events_findings_findings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecurityFinding) GetActivityId() enums.SECURITY_FINDING_ACTIVITY_ID {
	if x != nil {
		return x.ActivityId
	}
	return enums.SECURITY_FINDING_ACTIVITY_ID(0)
}

func (x *SecurityFinding) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *SecurityFinding) GetAnalytic() *objects.Analytic {
	if x != nil {
		return x.Analytic
	}
	return nil
}

func (x *SecurityFinding) GetApi() *objects.Api {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *SecurityFinding) GetAttacks() []*objects.Attack {
	if x != nil {
		return x.Attacks
	}
	return nil
}

func (x *SecurityFinding) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *SecurityFinding) GetCategoryUid() enums.SECURITY_FINDING_CATEGORY_UID {
	if x != nil {
		return x.CategoryUid
	}
	return enums.SECURITY_FINDING_CATEGORY_UID(0)
}

func (x *SecurityFinding) GetCisCsc() []*objects.CisControl {
	if x != nil {
		return x.CisCsc
	}
	return nil
}

func (x *SecurityFinding) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *SecurityFinding) GetClassUid() enums.SECURITY_FINDING_CLASS_UID {
	if x != nil {
		return x.ClassUid
	}
	return enums.SECURITY_FINDING_CLASS_UID(0)
}

func (x *SecurityFinding) GetCloud() *objects.Cloud {
	if x != nil {
		return x.Cloud
	}
	return nil
}

func (x *SecurityFinding) GetCompliance() *objects.Compliance {
	if x != nil {
		return x.Compliance
	}
	return nil
}

func (x *SecurityFinding) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *SecurityFinding) GetConfidenceId() enums.SECURITY_FINDING_CONFIDENCE_ID {
	if x != nil {
		return x.ConfidenceId
	}
	return enums.SECURITY_FINDING_CONFIDENCE_ID(0)
}

func (x *SecurityFinding) GetConfidenceScore() int32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *SecurityFinding) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SecurityFinding) GetDataSources() []string {
	if x != nil {
		return x.DataSources
	}
	return nil
}

func (x *SecurityFinding) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SecurityFinding) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SecurityFinding) GetEnrichments() []*objects.Enrichment {
	if x != nil {
		return x.Enrichments
	}
	return nil
}

func (x *SecurityFinding) GetEvidence() *structpb.Struct {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *SecurityFinding) GetFinding() *objects.Finding {
	if x != nil {
		return x.Finding
	}
	return nil
}

func (x *SecurityFinding) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

func (x *SecurityFinding) GetImpactId() enums.SECURITY_FINDING_IMPACT_ID {
	if x != nil {
		return x.ImpactId
	}
	return enums.SECURITY_FINDING_IMPACT_ID(0)
}

func (x *SecurityFinding) GetImpactScore() int32 {
	if x != nil {
		return x.ImpactScore
	}
	return 0
}

func (x *SecurityFinding) GetKillChain() []*objects.KillChain {
	if x != nil {
		return x.KillChain
	}
	return nil
}

func (x *SecurityFinding) GetMalware() []*objects.Malware {
	if x != nil {
		return x.Malware
	}
	return nil
}

func (x *SecurityFinding) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SecurityFinding) GetMetadata() *objects.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SecurityFinding) GetNist() []string {
	if x != nil {
		return x.Nist
	}
	return nil
}

func (x *SecurityFinding) GetObservables() []*objects.Observable {
	if x != nil {
		return x.Observables
	}
	return nil
}

func (x *SecurityFinding) GetProcess() *objects.Process {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *SecurityFinding) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *SecurityFinding) GetResources() []*objects.ResourceDetails {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *SecurityFinding) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *SecurityFinding) GetRiskLevelId() enums.SECURITY_FINDING_RISK_LEVEL_ID {
	if x != nil {
		return x.RiskLevelId
	}
	return enums.SECURITY_FINDING_RISK_LEVEL_ID(0)
}

func (x *SecurityFinding) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *SecurityFinding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *SecurityFinding) GetSeverityId() enums.SECURITY_FINDING_SEVERITY_ID {
	if x != nil {
		return x.SeverityId
	}
	return enums.SECURITY_FINDING_SEVERITY_ID(0)
}

func (x *SecurityFinding) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SecurityFinding) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SecurityFinding) GetStateId() enums.SECURITY_FINDING_STATE_ID {
	if x != nil {
		return x.StateId
	}
	return enums.SECURITY_FINDING_STATE_ID(0)
}

func (x *SecurityFinding) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SecurityFinding) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *SecurityFinding) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

func (x *SecurityFinding) GetStatusId() enums.SECURITY_FINDING_STATUS_ID {
	if x != nil {
		return x.StatusId
	}
	return enums.SECURITY_FINDING_STATUS_ID(0)
}

func (x *SecurityFinding) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SecurityFinding) GetTimezoneOffset() int32 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

func (x *SecurityFinding) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *SecurityFinding) GetTypeUid() enums.SECURITY_FINDING_TYPE_UID {
	if x != nil {
		return x.TypeUid
	}
	return enums.SECURITY_FINDING_TYPE_UID(0)
}

func (x *SecurityFinding) GetUnmapped() *structpb.Struct {
	if x != nil {
		return x.Unmapped
	}
	return nil
}

func (x *SecurityFinding) GetVulnerabilities() []*objects.Vulnerability {
	if x != nil {
		return x.Vulnerabilities
	}
	return nil
}

func (x *SecurityFinding) SetActivityId(v enums.SECURITY_FINDING_ACTIVITY_ID) {
	x.ActivityId = v
}

func (x *SecurityFinding) SetActivityName(v string) {
	x.ActivityName = v
}

func (x *SecurityFinding) SetAnalytic(v *objects.Analytic) {
	x.Analytic = v
}

func (x *SecurityFinding) SetApi(v *objects.Api) {
	x.Api = v
}

func (x *SecurityFinding) SetAttacks(v []*objects.Attack) {
	x.Attacks = v
}

func (x *SecurityFinding) SetCategoryName(v string) {
	x.CategoryName = v
}

func (x *SecurityFinding) SetCategoryUid(v enums.SECURITY_FINDING_CATEGORY_UID) {
	x.CategoryUid = v
}

func (x *SecurityFinding) SetCisCsc(v []*objects.CisControl) {
	x.CisCsc = v
}

func (x *SecurityFinding) SetClassName(v string) {
	x.ClassName = v
}

func (x *SecurityFinding) SetClassUid(v enums.SECURITY_FINDING_CLASS_UID) {
	x.ClassUid = v
}

func (x *SecurityFinding) SetCloud(v *objects.Cloud) {
	x.Cloud = v
}

func (x *SecurityFinding) SetCompliance(v *objects.Compliance) {
	x.Compliance = v
}

func (x *SecurityFinding) SetConfidence(v string) {
	x.Confidence = v
}

func (x *SecurityFinding) SetConfidenceId(v enums.SECURITY_FINDING_CONFIDENCE_ID) {
	x.ConfidenceId = v
}

func (x *SecurityFinding) SetConfidenceScore(v int32) {
	x.ConfidenceScore = v
}

func (x *SecurityFinding) SetCount(v int32) {
	x.Count = v
}

func (x *SecurityFinding) SetDataSources(v []string) {
	x.DataSources = v
}

func (x *SecurityFinding) SetDuration(v int32) {
	x.Duration = v
}

func (x *SecurityFinding) SetEndTime(v int64) {
	x.EndTime = v
}

func (x *SecurityFinding) SetEnrichments(v []*objects.Enrichment) {
	x.Enrichments = v
}

func (x *SecurityFinding) SetEvidence(v *structpb.Struct) {
	x.Evidence = v
}

func (x *SecurityFinding) SetFinding(v *objects.Finding) {
	x.Finding = v
}

func (x *SecurityFinding) SetImpact(v string) {
	x.Impact = v
}

func (x *SecurityFinding) SetImpactId(v enums.SECURITY_FINDING_IMPACT_ID) {
	x.ImpactId = v
}

func (x *SecurityFinding) SetImpactScore(v int32) {
	x.ImpactScore = v
}

func (x *SecurityFinding) SetKillChain(v []*objects.KillChain) {
	x.KillChain = v
}

func (x *SecurityFinding) SetMalware(v []*objects.Malware) {
	x.Malware = v
}

func (x *SecurityFinding) SetMessage(v string) {
	x.Message = v
}

func (x *SecurityFinding) SetMetadata(v *objects.Metadata) {
	x.Metadata = v
}

func (x *SecurityFinding) SetNist(v []string) {
	x.Nist = v
}

func (x *SecurityFinding) SetObservables(v []*objects.Observable) {
	x.Observables = v
}

func (x *SecurityFinding) SetProcess(v *objects.Process) {
	x.Process = v
}

func (x *SecurityFinding) SetRawData(v string) {
	x.RawData = v
}

func (x *SecurityFinding) SetResources(v []*objects.ResourceDetails) {
	x.Resources = v
}

func (x *SecurityFinding) SetRiskLevel(v string) {
	x.RiskLevel = v
}

func (x *SecurityFinding) SetRiskLevelId(v enums.SECURITY_FINDING_RISK_LEVEL_ID) {
	x.RiskLevelId = v
}

func (x *SecurityFinding) SetRiskScore(v int32) {
	x.RiskScore = v
}

func (x *SecurityFinding) SetSeverity(v string) {
	x.Severity = v
}

func (x *SecurityFinding) SetSeverityId(v enums.SECURITY_FINDING_SEVERITY_ID) {
	x.SeverityId = v
}

func (x *SecurityFinding) SetStartTime(v int64) {
	x.StartTime = v
}

func (x *SecurityFinding) SetState(v string) {
	x.State = v
}

func (x *SecurityFinding) SetStateId(v enums.SECURITY_FINDING_STATE_ID) {
	x.StateId = v
}

func (x *SecurityFinding) SetStatus(v string) {
	x.Status = v
}

func (x *SecurityFinding) SetStatusCode(v string) {
	x.StatusCode = v
}

func (x *SecurityFinding) SetStatusDetail(v string) {
	x.StatusDetail = v
}

func (x *SecurityFinding) SetStatusId(v enums.SECURITY_FINDING_STATUS_ID) {
	x.StatusId = v
}

func (x *SecurityFinding) SetTime(v int64) {
	x.Time = v
}

func (x *SecurityFinding) SetTimezoneOffset(v int32) {
	x.TimezoneOffset = v
}

func (x *SecurityFinding) SetTypeName(v string) {
	x.TypeName = v
}

func (x *SecurityFinding) SetTypeUid(v enums.SECURITY_FINDING_TYPE_UID) {
	x.TypeUid = v
}

func (x *SecurityFinding) SetUnmapped(v *structpb.Struct) {
	x.Unmapped = v
}

func (x *SecurityFinding) SetVulnerabilities(v []*objects.Vulnerability) {
	x.Vulnerabilities = v
}

func (x *SecurityFinding) HasAnalytic() bool {
	if x == nil {
		return false
	}
	return x.Analytic != nil
}

func (x *SecurityFinding) HasApi() bool {
	if x == nil {
		return false
	}
	return x.Api != nil
}

func (x *SecurityFinding) HasCloud() bool {
	if x == nil {
		return false
	}
	return x.Cloud != nil
}

func (x *SecurityFinding) HasCompliance() bool {
	if x == nil {
		return false
	}
	return x.Compliance != nil
}

func (x *SecurityFinding) HasEvidence() bool {
	if x == nil {
		return false
	}
	return x.Evidence != nil
}

func (x *SecurityFinding) HasFinding() bool {
	if x == nil {
		return false
	}
	return x.Finding != nil
}

func (x *SecurityFinding) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *SecurityFinding) HasProcess() bool {
	if x == nil {
		return false
	}
	return x.Process != nil
}

func (x *SecurityFinding) HasUnmapped() bool {
	if x == nil {
		return false
	}
	return x.Unmapped != nil
}

func (x *SecurityFinding) ClearAnalytic() {
	x.Analytic = nil
}

func (x *SecurityFinding) ClearApi() {
	x.Api = nil
}

func (x *SecurityFinding) ClearCloud() {
	x.Cloud = nil
}

func (x *SecurityFinding) ClearCompliance() {
	x.Compliance = nil
}

func (x *SecurityFinding) ClearEvidence() {
	x.Evidence = nil
}

func (x *SecurityFinding) ClearFinding() {
	x.Finding = nil
}

func (x *SecurityFinding) ClearMetadata() {
	x.Metadata = nil
}

func (x *SecurityFinding) ClearProcess() {
	x.Process = nil
}

func (x *SecurityFinding) ClearUnmapped() {
	x.Unmapped = nil
}

type SecurityFinding_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ActivityId      enums.SECURITY_FINDING_ACTIVITY_ID
	ActivityName    string
	Analytic        *objects.Analytic
	Api             *objects.Api
	Attacks         []*objects.Attack
	CategoryName    string
	CategoryUid     enums.SECURITY_FINDING_CATEGORY_UID
	CisCsc          []*objects.CisControl
	ClassName       string
	ClassUid        enums.SECURITY_FINDING_CLASS_UID
	Cloud           *objects.Cloud
	Compliance      *objects.Compliance
	Confidence      string
	ConfidenceId    enums.SECURITY_FINDING_CONFIDENCE_ID
	ConfidenceScore int32
	Count           int32
	DataSources     []string
	Duration        int32
	EndTime         int64
	Enrichments     []*objects.Enrichment
	Evidence        *structpb.Struct
	Finding         *objects.Finding
	Impact          string
	ImpactId        enums.SECURITY_FINDING_IMPACT_ID
	ImpactScore     int32
	KillChain       []*objects.KillChain
	Malware         []*objects.Malware
	Message         string
	Metadata        *objects.Metadata
	Nist            []string
	Observables     []*objects.Observable
	Process         *objects.Process
	RawData         string
	Resources       []*objects.ResourceDetails
	RiskLevel       string
	RiskLevelId     enums.SECURITY_FINDING_RISK_LEVEL_ID
	RiskScore       int32
	Severity        string
	SeverityId      enums.SECURITY_FINDING_SEVERITY_ID
	StartTime       int64
	State           string
	StateId         enums.SECURITY_FINDING_STATE_ID
	Status          string
	StatusCode      string
	StatusDetail    string
	StatusId        enums.SECURITY_FINDING_STATUS_ID
	Time            int64
	TimezoneOffset  int32
	TypeName        string
	TypeUid         enums.SECURITY_FINDING_TYPE_UID
	Unmapped        *structpb.Struct
	Vulnerabilities []*objects.Vulnerability
}

func (b0 SecurityFinding_builder) Build() *SecurityFinding {
	m0 := &SecurityFinding{}
	b, x := &b0, m0
	_, _ = b, x
	x.ActivityId = b.ActivityId
	x.ActivityName = b.ActivityName
	x.Analytic = b.Analytic
	x.Api = b.Api
	x.Attacks = b.Attacks
	x.CategoryName = b.CategoryName
	x.CategoryUid = b.CategoryUid
	x.CisCsc = b.CisCsc
	x.ClassName = b.ClassName
	x.ClassUid = b.ClassUid
	x.Cloud = b.Cloud
	x.Compliance = b.Compliance
	x.Confidence = b.Confidence
	x.ConfidenceId = b.ConfidenceId
	x.ConfidenceScore = b.ConfidenceScore
	x.Count = b.Count
	x.DataSources = b.DataSources
	x.Duration = b.Duration
	x.EndTime = b.EndTime
	x.Enrichments = b.Enrichments
	x.Evidence = b.Evidence
	x.Finding = b.Finding
	x.Impact = b.Impact
	x.ImpactId = b.ImpactId
	x.ImpactScore = b.ImpactScore
	x.KillChain = b.KillChain
	x.Malware = b.Malware
	x.Message = b.Message
	x.Metadata = b.Metadata
	x.Nist = b.Nist
	x.Observables = b.Observables
	x.Process = b.Process
	x.RawData = b.RawData
	x.Resources = b.Resources
	x.RiskLevel = b.RiskLevel
	x.RiskLevelId = b.RiskLevelId
	x.RiskScore = b.RiskScore
	x.Severity = b.Severity
	x.SeverityId = b.SeverityId
	x.StartTime = b.StartTime
	x.State = b.State
	x.StateId = b.StateId
	x.Status = b.Status
	x.StatusCode = b.StatusCode
	x.StatusDetail = b.StatusDetail
	x.StatusId = b.StatusId
	x.Time = b.Time
	x.TimezoneOffset = b.TimezoneOffset
	x.TypeName = b.TypeName
	x.TypeUid = b.TypeUid
	x.Unmapped = b.Unmapped
	x.Vulnerabilities = b.Vulnerabilities
	return m0
}

var File_ocsf_v1_0_0_events_findings_findings_proto protoreflect.FileDescriptor

const file_ocsf_v1_0_0_events_findings_findings_proto_rawDesc = "" +
	"\n" +
	"*ocsf/v1_0_0/events/findings/findings.proto\x12\x1bocsf.v1_0_0.events.findings\x1a-ocsf/v1_0_0/events/findings/enums/enums.proto\x1a!ocsf/v1_0_0/objects/objects.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc6\n" +
	"\n" +
	"\bFindings\x12X\n" +
	"\vactivity_id\x18\x01 \x01(\x0e27.ocsf.v1_0_0.events.findings.enums.FINDINGS_ACTIVITY_IDR\n" +
	"activityId\x12#\n" +
	"\ractivity_name\x18\x02 \x01(\tR\factivityName\x12*\n" +
	"\x03api\x18\x03 \x01(\v2\x18.ocsf.v1_0_0.objects.ApiR\x03api\x12#\n" +
	"\rcategory_name\x18\x04 \x01(\tR\fcategoryName\x12[\n" +
	"\fcategory_uid\x18\x05 \x01(\x0e28.ocsf.v1_0_0.events.findings.enums.FINDINGS_CATEGORY_UIDR\vcategoryUid\x12\x1d\n" +
	"\n" +
	"class_name\x18\x06 \x01(\tR\tclassName\x12R\n" +
	"\tclass_uid\x18\a \x01(\x0e25.ocsf.v1_0_0.events.findings.enums.FINDINGS_CLASS_UIDR\bclassUid\x120\n" +
	"\x05cloud\x18\b \x01(\v2\x1a.ocsf.v1_0_0.objects.CloudR\x05cloud\x12\x14\n" +
	"\x05count\x18\t \x01(\x05R\x05count\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\x05R\bduration\x12\x19\n" +
	"\bend_time\x18\v \x01(\x03R\aendTime\x12A\n" +
	"\venrichments\x18\f \x03(\v2\x1f.ocsf.v1_0_0.objects.EnrichmentR\venrichments\x12\x18\n" +
	"\amessage\x18\r \x01(\tR\amessage\x129\n" +
	"\bmetadata\x18\x0e \x01(\v2\x1d.ocsf.v1_0_0.objects.MetadataR\bmetadata\x12A\n" +
	"\vobservables\x18\x0f \x03(\v2\x1f.ocsf.v1_0_0.objects.ObservableR\vobservables\x12\x19\n" +
	"\braw_data\x18\x10 \x01(\tR\arawData\x12\x1a\n" +
	"\bseverity\x18\x11 \x01(\tR\bseverity\x12X\n" +
	"\vseverity_id\x18\x12 \x01(\x0e27.ocsf.v1_0_0.events.findings.enums.FINDINGS_SEVERITY_IDR\n" +
	"severityId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x13 \x01(\x03R\tstartTime\x12\x16\n" +
	"\x06status\x18\x14 \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18\x15 \x01(\tR\n" +
	"statusCode\x12#\n" +
	"\rstatus_detail\x18\x16 \x01(\tR\fstatusDetail\x12R\n" +
	"\tstatus_id\x18\x17 \x01(\x0e25.ocsf.v1_0_0.events.findings.enums.FINDINGS_STATUS_IDR\bstatusId\x12\x12\n" +
	"\x04time\x18\x18 \x01(\x03R\x04time\x12'\n" +
	"\x0ftimezone_offset\x18\x19 \x01(\x05R\x0etimezoneOffset\x12\x1b\n" +
	"\ttype_name\x18\x1a \x01(\tR\btypeName\x12O\n" +
	"\btype_uid\x18\x1b \x01(\x0e24.ocsf.v1_0_0.events.findings.enums.FINDINGS_TYPE_UIDR\atypeUid\x123\n" +
	"\bunmapped\x18\x1c \x01(\v2\x17.google.protobuf.StructR\bunmapped\"\xad\x15\n" +
	"\x0fSecurityFinding\x12`\n" +
	"\vactivity_id\x18\x01 \x01(\x0e2?.ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_ACTIVITY_IDR\n" +
	"activityId\x12#\n" +
	"\ractivity_name\x18\x02 \x01(\tR\factivityName\x129\n" +
	"\banalytic\x18\x03 \x01(\v2\x1d.ocsf.v1_0_0.objects.AnalyticR\banalytic\x12*\n" +
	"\x03api\x18\x04 \x01(\v2\x18.ocsf.v1_0_0.objects.ApiR\x03api\x125\n" +
	"\aattacks\x18\x05 \x03(\v2\x1b.ocsf.v1_0_0.objects.AttackR\aattacks\x12#\n" +
	"\rcategory_name\x18\x06 \x01(\tR\fcategoryName\x12c\n" +
	"\fcategory_uid\x18\a \x01(\x0e2@.ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_CATEGORY_UIDR\vcategoryUid\x128\n" +
	"\acis_csc\x18\b \x03(\v2\x1f.ocsf.v1_0_0.objects.CisControlR\x06cisCsc\x12\x1d\n" +
	"\n" +
	"class_name\x18\t \x01(\tR\tclassName\x12Z\n" +
	"\tclass_uid\x18\n" +
	" \x01(\x0e2=.ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_CLASS_UIDR\bclassUid\x120\n" +
	"\x05cloud\x18\v \x01(\v2\x1a.ocsf.v1_0_0.objects.CloudR\x05cloud\x12?\n" +
	"\n" +
	"compliance\x18\f \x01(\v2\x1f.ocsf.v1_0_0.objects.ComplianceR\n" +
	"compliance\x12\x1e\n" +
	"\n" +
	"confidence\x18\r \x01(\tR\n" +
	"confidence\x12f\n" +
	"\rconfidence_id\x18\x0e \x01(\x0e2A.ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_CONFIDENCE_IDR\fconfidenceId\x12)\n" +
	"\x10confidence_score\x18\x0f \x01(\x05R\x0fconfidenceScore\x12\x14\n" +
	"\x05count\x18\x10 \x01(\x05R\x05count\x12!\n" +
	"\fdata_sources\x18\x11 \x03(\tR\vdataSources\x12\x1a\n" +
	"\bduration\x18\x12 \x01(\x05R\bduration\x12\x19\n" +
	"\bend_time\x18\x13 \x01(\x03R\aendTime\x12A\n" +
	"\venrichments\x18\x14 \x03(\v2\x1f.ocsf.v1_0_0.objects.EnrichmentR\venrichments\x123\n" +
	"\bevidence\x18\x15 \x01(\v2\x17.google.protobuf.StructR\bevidence\x126\n" +
	"\afinding\x18\x16 \x01(\v2\x1c.ocsf.v1_0_0.objects.FindingR\afinding\x12\x16\n" +
	"\x06impact\x18\x17 \x01(\tR\x06impact\x12Z\n" +
	"\timpact_id\x18\x18 \x01(\x0e2=.ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_IMPACT_IDR\bimpactId\x12!\n" +
	"\fimpact_score\x18\x19 \x01(\x05R\vimpactScore\x12=\n" +
	"\n" +
	"kill_chain\x18\x1a \x03(\v2\x1e.ocsf.v1_0_0.objects.KillChainR\tkillChain\x126\n" +
	"\amalware\x18\x1b \x03(\v2\x1c.ocsf.v1_0_0.objects.MalwareR\amalware\x12\x18\n" +
	"\amessage\x18\x1c \x01(\tR\amessage\x129\n" +
	"\bmetadata\x18\x1d \x01(\v2\x1d.ocsf.v1_0_0.objects.MetadataR\bmetadata\x12\x12\n" +
	"\x04nist\x18\x1e \x03(\tR\x04nist\x12A\n" +
	"\vobservables\x18\x1f \x03(\v2\x1f.ocsf.v1_0_0.objects.ObservableR\vobservables\x126\n" +
	"\aprocess\x18  \x01(\v2\x1c.ocsf.v1_0_0.objects.ProcessR\aprocess\x12\x19\n" +
	"\braw_data\x18! \x01(\tR\arawData\x12B\n" +
	"\tresources\x18\" \x03(\v2$.ocsf.v1_0_0.objects.ResourceDetailsR\tresources\x12\x1d\n" +
	"\n" +
	"risk_level\x18# \x01(\tR\triskLevel\x12e\n" +
	"\rrisk_level_id\x18$ \x01(\x0e2A.ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_RISK_LEVEL_IDR\vriskLevelId\x12\x1d\n" +
	"\n" +
	"risk_score\x18% \x01(\x05R\triskScore\x12\x1a\n" +
	"\bseverity\x18& \x01(\tR\bseverity\x12`\n" +
	"\vseverity_id\x18' \x01(\x0e2?.ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_SEVERITY_IDR\n" +
	"severityId\x12\x1d\n" +
	"\n" +
	"start_time\x18( \x01(\x03R\tstartTime\x12\x14\n" +
	"\x05state\x18) \x01(\tR\x05state\x12W\n" +
	"\bstate_id\x18* \x01(\x0e2<.ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_STATE_IDR\astateId\x12\x16\n" +
	"\x06status\x18+ \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18, \x01(\tR\n" +
	"statusCode\x12#\n" +
	"\rstatus_detail\x18- \x01(\tR\fstatusDetail\x12Z\n" +
	"\tstatus_id\x18. \x01(\x0e2=.ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_STATUS_IDR\bstatusId\x12\x12\n" +
	"\x04time\x18/ \x01(\x03R\x04time\x12'\n" +
	"\x0ftimezone_offset\x180 \x01(\x05R\x0etimezoneOffset\x12\x1b\n" +
	"\ttype_name\x181 \x01(\tR\btypeName\x12W\n" +
	"\btype_uid\x182 \x01(\x0e2<.ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_TYPE_UIDR\atypeUid\x123\n" +
	"\bunmapped\x183 \x01(\v2\x17.google.protobuf.StructR\bunmapped\x12L\n" +
	"\x0fvulnerabilities\x184 \x03(\v2\".ocsf.v1_0_0.objects.VulnerabilityR\x0fvulnerabilitiesB\xfc\x01\n" +
	"\x1fcom.ocsf.v1_0_0.events.findingsB\rFindingsProtoP\x01ZBgithub.com/valllabh/ocsf-schema-golang/ocsf/v1_0_0/events/findings\xa2\x02\x04OVEF\xaa\x02\x19Ocsf.V100.Events.Findings\xca\x02\x19Ocsf\\V100\\Events\\Findings\xe2\x02%Ocsf\\V100\\Events\\Findings\\GPBMetadata\xea\x02\x1cOcsf::V100::Events::Findingsb\x06proto3"

var file_ocsf_v1_0_0_events_findings_findings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ocsf_v1_0_0_events_findings_findings_proto_goTypes = []any{
	(*Findings)(nil),                          // 0: ocsf.v1_0_0.events.findings.Findings
	(*SecurityFinding)(nil),                   // 1: ocsf.v1_0_0.events.findings.SecurityFinding
	(enums.FINDINGS_ACTIVITY_ID)(0),           // 2: ocsf.v1_0_0.events.findings.enums.FINDINGS_ACTIVITY_ID
	(*objects.Api)(nil),                       // 3: ocsf.v1_0_0.objects.Api
	(enums.FINDINGS_CATEGORY_UID)(0),          // 4: ocsf.v1_0_0.events.findings.enums.FINDINGS_CATEGORY_UID
	(enums.FINDINGS_CLASS_UID)(0),             // 5: ocsf.v1_0_0.events.findings.enums.FINDINGS_CLASS_UID
	(*objects.Cloud)(nil),                     // 6: ocsf.v1_0_0.objects.Cloud
	(*objects.Enrichment)(nil),                // 7: ocsf.v1_0_0.objects.Enrichment
	(*objects.Metadata)(nil),                  // 8: ocsf.v1_0_0.objects.Metadata
	(*objects.Observable)(nil),                // 9: ocsf.v1_0_0.objects.Observable
	(enums.FINDINGS_SEVERITY_ID)(0),           // 10: ocsf.v1_0_0.events.findings.enums.FINDINGS_SEVERITY_ID
	(enums.FINDINGS_STATUS_ID)(0),             // 11: ocsf.v1_0_0.events.findings.enums.FINDINGS_STATUS_ID
	(enums.FINDINGS_TYPE_UID)(0),              // 12: ocsf.v1_0_0.events.findings.enums.FINDINGS_TYPE_UID
	(*structpb.Struct)(nil),                   // 13: google.protobuf.Struct
	(enums.SECURITY_FINDING_ACTIVITY_ID)(0),   // 14: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_ACTIVITY_ID
	(*objects.Analytic)(nil),                  // 15: ocsf.v1_0_0.objects.Analytic
	(*objects.Attack)(nil),                    // 16: ocsf.v1_0_0.objects.Attack
	(enums.SECURITY_FINDING_CATEGORY_UID)(0),  // 17: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_CATEGORY_UID
	(*objects.CisControl)(nil),                // 18: ocsf.v1_0_0.objects.CisControl
	(enums.SECURITY_FINDING_CLASS_UID)(0),     // 19: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_CLASS_UID
	(*objects.Compliance)(nil),                // 20: ocsf.v1_0_0.objects.Compliance
	(enums.SECURITY_FINDING_CONFIDENCE_ID)(0), // 21: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_CONFIDENCE_ID
	(*objects.Finding)(nil),                   // 22: ocsf.v1_0_0.objects.Finding
	(enums.SECURITY_FINDING_IMPACT_ID)(0),     // 23: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_IMPACT_ID
	(*objects.KillChain)(nil),                 // 24: ocsf.v1_0_0.objects.KillChain
	(*objects.Malware)(nil),                   // 25: ocsf.v1_0_0.objects.Malware
	(*objects.Process)(nil),                   // 26: ocsf.v1_0_0.objects.Process
	(*objects.ResourceDetails)(nil),           // 27: ocsf.v1_0_0.objects.ResourceDetails
	(enums.SECURITY_FINDING_RISK_LEVEL_ID)(0), // 28: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_RISK_LEVEL_ID
	(enums.SECURITY_FINDING_SEVERITY_ID)(0),   // 29: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_SEVERITY_ID
	(enums.SECURITY_FINDING_STATE_ID)(0),      // 30: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_STATE_ID
	(enums.SECURITY_FINDING_STATUS_ID)(0),     // 31: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_STATUS_ID
	(enums.SECURITY_FINDING_TYPE_UID)(0),      // 32: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_TYPE_UID
	(*objects.Vulnerability)(nil),             // 33: ocsf.v1_0_0.objects.Vulnerability
}
var file_ocsf_v1_0_0_events_findings_findings_proto_depIdxs = []int32{
	2,  // 0: ocsf.v1_0_0.events.findings.Findings.activity_id:type_name -> ocsf.v1_0_0.events.findings.enums.FINDINGS_ACTIVITY_ID
	3,  // 1: ocsf.v1_0_0.events.findings.Findings.api:type_name -> ocsf.v1_0_0.objects.Api
	4,  // 2: ocsf.v1_0_0.events.findings.Findings.category_uid:type_name -> ocsf.v1_0_0.events.findings.enums.FINDINGS_CATEGORY_UID
	5,  // 3: ocsf.v1_0_0.events.findings.Findings.class_uid:type_name -> ocsf.v1_0_0.events.findings.enums.FINDINGS_CLASS_UID
	6,  // 4: ocsf.v1_0_0.events.findings.Findings.cloud:type_name -> ocsf.v1_0_0.objects.Cloud
	7,  // 5: ocsf.v1_0_0.events.findings.Findings.enrichments:type_name -> ocsf.v1_0_0.objects.Enrichment
	8,  // 6: ocsf.v1_0_0.events.findings.Findings.metadata:type_name -> ocsf.v1_0_0.objects.Metadata
	9,  // 7: ocsf.v1_0_0.events.findings.Findings.observables:type_name -> ocsf.v1_0_0.objects.Observable
	10, // 8: ocsf.v1_0_0.events.findings.Findings.severity_id:type_name -> ocsf.v1_0_0.events.findings.enums.FINDINGS_SEVERITY_ID
	11, // 9: ocsf.v1_0_0.events.findings.Findings.status_id:type_name -> ocsf.v1_0_0.events.findings.enums.FINDINGS_STATUS_ID
	12, // 10: ocsf.v1_0_0.events.findings.Findings.type_uid:type_name -> ocsf.v1_0_0.events.findings.enums.FINDINGS_TYPE_UID
	13, // 11: ocsf.v1_0_0.events.findings.Findings.unmapped:type_name -> google.protobuf.Struct
	14, // 12: ocsf.v1_0_0.events.findings.SecurityFinding.activity_id:type_name -> ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_ACTIVITY_ID
	15, // 13: ocsf.v1_0_0.events.findings.SecurityFinding.analytic:type_name -> ocsf.v1_0_0.objects.Analytic
	3,  // 14: ocsf.v1_0_0.events.findings.SecurityFinding.api:type_name -> ocsf.v1_0_0.objects.Api
	16, // 15: ocsf.v1_0_0.events.findings.SecurityFinding.attacks:type_name -> ocsf.v1_0_0.objects.Attack
	17, // 16: ocsf.v1_0_0.events.findings.SecurityFinding.category_uid:type_name -> ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_CATEGORY_UID
	18, // 17: ocsf.v1_0_0.events.findings.SecurityFinding.cis_csc:type_name -> ocsf.v1_0_0.objects.CisControl
	19, // 18: ocsf.v1_0_0.events.findings.SecurityFinding.class_uid:type_name -> ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_CLASS_UID
	6,  // 19: ocsf.v1_0_0.events.findings.SecurityFinding.cloud:type_name -> ocsf.v1_0_0.objects.Cloud
	20, // 20: ocsf.v1_0_0.events.findings.SecurityFinding.compliance:type_name -> ocsf.v1_0_0.objects.Compliance
	21, // 21: ocsf.v1_0_0.events.findings.SecurityFinding.confidence_id:type_name -> ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_CONFIDENCE_ID
	7,  // 22: ocsf.v1_0_0.events.findings.SecurityFinding.enrichments:type_name -> ocsf.v1_0_0.objects.Enrichment
	13, // 23: ocsf.v1_0_0.events.findings.SecurityFinding.evidence:type_name -> google.protobuf.Struct
	22, // 24: ocsf.v1_0_0.events.findings.SecurityFinding.finding:type_name -> ocsf.v1_0_0.objects.Finding
	23, // 25: ocsf.v1_0_0.events.findings.SecurityFinding.impact_id:type_name -> ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_IMPACT_ID
	24, // 26: ocsf.v1_0_0.events.findings.SecurityFinding.kill_chain:type_name -> ocsf.v1_0_0.objects.KillChain
	25, // 27: ocsf.v1_0_0.events.findings.SecurityFinding.malware:type_name -> ocsf.v1_0_0.objects.Malware
	8,  // 28: ocsf.v1_0_0.events.findings.SecurityFinding.metadata:type_name -> ocsf.v1_0_0.objects.Metadata
	9,  // 29: ocsf.v1_0_0.events.findings.SecurityFinding.observables:type_name -> ocsf.v1_0_0.objects.Observable
	26, // 30: ocsf.v1_0_0.events.findings.SecurityFinding.process:type_name -> ocsf.v1_0_0.objects.Process
	27, // 31: ocsf.v1_0_0.events.findings.SecurityFinding.resources:type_name -> ocsf.v1_0_0.objects.ResourceDetails
	28, // 32: ocsf.v1_0_0.events.findings.SecurityFinding.risk_level_id:type_name -> ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_RISK_LEVEL_ID
	29, // 33: ocsf.v1_0_0.events.findings.SecurityFinding.severity_id:type_name -> ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_SEVERITY_ID
	30, // 34: ocsf.v1_0_0.events.findings.SecurityFinding.state_id:type_name -> ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_STATE_ID
	31, // 35: ocsf.v1_0_0.events.findings.SecurityFinding.status_id:type_name -> ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_STATUS_ID
	32, // 36: ocsf.v1_0_0.events.findings.SecurityFinding.type_uid:type_name -> ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_TYPE_UID
	13, // 37: ocsf.v1_0_0.events.findings.SecurityFinding.unmapped:type_name -> google.protobuf.Struct
	33, // 38: ocsf.v1_0_0.events.findings.SecurityFinding.vulnerabilities:type_name -> ocsf.v1_0_0.objects.Vulnerability
	39, // [39:39] is the sub-list for method output_type
	39, // [39:39] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_ocsf_v1_0_0_events_findings_findings_proto_init() }
func file_ocsf_v1_0_0_events_findings_findings_proto_init() {
	if File_ocsf_v1_0_0_events_findings_findings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocsf_v1_0_0_events_findings_findings_proto_rawDesc), len(file_ocsf_v1_0_0_events_findings_findings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocsf_v1_0_0_events_findings_findings_proto_goTypes,
		DependencyIndexes: file_ocsf_v1_0_0_events_findings_findings_proto_depIdxs,
		MessageInfos:      file_ocsf_v1_0_0_events_findings_findings_proto_msgTypes,
	}.Build()
	File_ocsf_v1_0_0_events_findings_findings_proto = out.File
	file_ocsf_v1_0_0_events_findings_findings_proto_goTypes = nil
	file_ocsf_v1_0_0_events_findings_findings_proto_depIdxs = nil
}
