// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: ocsf/v1_5_0/events/other/other.proto

//go:build !protoopaque

package other

import (
	enums "github.com/valllabh/ocsf-schema-golang/ocsf/v1_5_0/events/other/enums"
	objects "github.com/valllabh/ocsf-schema-golang/ocsf/v1_5_0/objects"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event UID: 0
// URL: https://schema.ocsf.io/1.5.0/classes/base_event
// Event: other
type BaseEvent struct {
	state           protoimpl.MessageState          `protogen:"hybrid.v1"`
	Action          string                          `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                                                                                                    // Profile: security_control; Caption: Action;
	ActionId        enums.BASE_EVENT_ACTION_ID      `protobuf:"varint,2,opt,name=action_id,json=actionId,proto3,enum=ocsf.v1_5_0.events.other.enums.BASE_EVENT_ACTION_ID" json:"action_id,omitempty"`                      // Caption: Action ID; Profile: security_control;
	ActivityId      enums.BASE_EVENT_ACTIVITY_ID    `protobuf:"varint,3,opt,name=activity_id,json=activityId,proto3,enum=ocsf.v1_5_0.events.other.enums.BASE_EVENT_ACTIVITY_ID" json:"activity_id,omitempty"`              // Caption: Activity ID;
	ActivityName    string                          `protobuf:"bytes,4,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`                                                                    // Caption: Activity;
	Actor           *objects.Actor                  `protobuf:"bytes,5,opt,name=actor,proto3" json:"actor,omitempty"`                                                                                                      // Caption: Actor; Profile: host;
	Api             *objects.Api                    `protobuf:"bytes,6,opt,name=api,proto3" json:"api,omitempty"`                                                                                                          // Caption: API Details; Profile: cloud;
	Attacks         []*objects.Attack               `protobuf:"bytes,7,rep,name=attacks,proto3" json:"attacks,omitempty"`                                                                                                  // Caption: MITRE ATT&CK® and ATLAS™ Details; Profile: security_control;
	Authorizations  []*objects.Authorization        `protobuf:"bytes,8,rep,name=authorizations,proto3" json:"authorizations,omitempty"`                                                                                    // Caption: Authorization Information; Profile: security_control;
	CategoryName    string                          `protobuf:"bytes,9,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`                                                                    // Caption: Category;
	CategoryUid     enums.BASE_EVENT_CATEGORY_UID   `protobuf:"varint,10,opt,name=category_uid,json=categoryUid,proto3,enum=ocsf.v1_5_0.events.other.enums.BASE_EVENT_CATEGORY_UID" json:"category_uid,omitempty"`         // Caption: Category ID;
	ClassName       string                          `protobuf:"bytes,11,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`                                                                            // Caption: Class;
	ClassUid        enums.BASE_EVENT_CLASS_UID      `protobuf:"varint,12,opt,name=class_uid,json=classUid,proto3,enum=ocsf.v1_5_0.events.other.enums.BASE_EVENT_CLASS_UID" json:"class_uid,omitempty"`                     // Caption: Class ID;
	Cloud           *objects.Cloud                  `protobuf:"bytes,13,opt,name=cloud,proto3" json:"cloud,omitempty"`                                                                                                     // Caption: Cloud; Profile: cloud;
	Confidence      string                          `protobuf:"bytes,14,opt,name=confidence,proto3" json:"confidence,omitempty"`                                                                                           // Caption: Confidence; Profile: security_control;
	ConfidenceId    enums.BASE_EVENT_CONFIDENCE_ID  `protobuf:"varint,15,opt,name=confidence_id,json=confidenceId,proto3,enum=ocsf.v1_5_0.events.other.enums.BASE_EVENT_CONFIDENCE_ID" json:"confidence_id,omitempty"`     // Caption: Confidence ID; Profile: security_control;
	ConfidenceScore int32                           `protobuf:"varint,16,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`                                                         // Caption: Confidence Score; Profile: security_control;
	Count           int32                           `protobuf:"varint,17,opt,name=count,proto3" json:"count,omitempty"`                                                                                                    // Caption: Count;
	Device          *objects.Device                 `protobuf:"bytes,18,opt,name=device,proto3" json:"device,omitempty"`                                                                                                   // Caption: Device; Profile: host;
	Disposition     string                          `protobuf:"bytes,19,opt,name=disposition,proto3" json:"disposition,omitempty"`                                                                                         // Caption: Disposition; Profile: security_control;
	DispositionId   enums.BASE_EVENT_DISPOSITION_ID `protobuf:"varint,20,opt,name=disposition_id,json=dispositionId,proto3,enum=ocsf.v1_5_0.events.other.enums.BASE_EVENT_DISPOSITION_ID" json:"disposition_id,omitempty"` // Profile: security_control; Caption: Disposition ID;
	Duration        int64                           `protobuf:"varint,21,opt,name=duration,proto3" json:"duration,omitempty"`                                                                                              // Caption: Duration Milliseconds;
	EndTime         int64                           `protobuf:"varint,22,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                                                                                 // Caption: End Time;
	Enrichments     []*objects.Enrichment           `protobuf:"bytes,23,rep,name=enrichments,proto3" json:"enrichments,omitempty"`                                                                                         // Caption: Enrichments;
	FirewallRule    *objects.FirewallRule           `protobuf:"bytes,24,opt,name=firewall_rule,json=firewallRule,proto3" json:"firewall_rule,omitempty"`                                                                   // Caption: Firewall Rule; Profile: security_control;
	IsAlert         bool                            `protobuf:"varint,25,opt,name=is_alert,json=isAlert,proto3" json:"is_alert,omitempty"`                                                                                 // Caption: Alert; Profile: security_control;
	Malware         []*objects.Malware              `protobuf:"bytes,26,rep,name=malware,proto3" json:"malware,omitempty"`                                                                                                 // Caption: Malware; Profile: security_control;
	MalwareScanInfo *objects.MalwareScanInfo        `protobuf:"bytes,27,opt,name=malware_scan_info,json=malwareScanInfo,proto3" json:"malware_scan_info,omitempty"`                                                        // Caption: Malware Scan Info; Profile: security_control;
	Message         string                          `protobuf:"bytes,28,opt,name=message,proto3" json:"message,omitempty"`                                                                                                 // Caption: Message;
	Metadata        *objects.Metadata               `protobuf:"bytes,29,opt,name=metadata,proto3" json:"metadata,omitempty"`                                                                                               // Caption: Metadata;
	Observables     []*objects.Observable           `protobuf:"bytes,30,rep,name=observables,proto3" json:"observables,omitempty"`                                                                                         // Caption: Observables;
	Osint           []*objects.Osint                `protobuf:"bytes,31,rep,name=osint,proto3" json:"osint,omitempty"`                                                                                                     // Profile: osint; Caption: OSINT;
	Policy          *objects.Policy                 `protobuf:"bytes,32,opt,name=policy,proto3" json:"policy,omitempty"`                                                                                                   // Caption: Policy; Profile: security_control;
	RawData         string                          `protobuf:"bytes,33,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`                                                                                  // Caption: Raw Data;
	RawDataSize     int64                           `protobuf:"varint,34,opt,name=raw_data_size,json=rawDataSize,proto3" json:"raw_data_size,omitempty"`                                                                   // Caption: Raw Data Size;
	RiskDetails     string                          `protobuf:"bytes,35,opt,name=risk_details,json=riskDetails,proto3" json:"risk_details,omitempty"`                                                                      // Caption: Risk Details; Profile: security_control;
	RiskLevel       string                          `protobuf:"bytes,36,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`                                                                            // Caption: Risk Level; Profile: security_control;
	RiskLevelId     enums.BASE_EVENT_RISK_LEVEL_ID  `protobuf:"varint,37,opt,name=risk_level_id,json=riskLevelId,proto3,enum=ocsf.v1_5_0.events.other.enums.BASE_EVENT_RISK_LEVEL_ID" json:"risk_level_id,omitempty"`      // Caption: Risk Level ID; Profile: security_control;
	RiskScore       int32                           `protobuf:"varint,38,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`                                                                           // Caption: Risk Score; Profile: security_control;
	Severity        string                          `protobuf:"bytes,39,opt,name=severity,proto3" json:"severity,omitempty"`                                                                                               // Caption: Severity;
	SeverityId      enums.BASE_EVENT_SEVERITY_ID    `protobuf:"varint,40,opt,name=severity_id,json=severityId,proto3,enum=ocsf.v1_5_0.events.other.enums.BASE_EVENT_SEVERITY_ID" json:"severity_id,omitempty"`             // Caption: Severity ID;
	StartTime       int64                           `protobuf:"varint,41,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                                                                           // Caption: Start Time;
	Status          string                          `protobuf:"bytes,42,opt,name=status,proto3" json:"status,omitempty"`                                                                                                   // Caption: Status;
	StatusCode      string                          `protobuf:"bytes,43,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                                         // Caption: Status Code;
	StatusDetail    string                          `protobuf:"bytes,44,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"`                                                                   // Caption: Status Detail;
	StatusId        enums.BASE_EVENT_STATUS_ID      `protobuf:"varint,45,opt,name=status_id,json=statusId,proto3,enum=ocsf.v1_5_0.events.other.enums.BASE_EVENT_STATUS_ID" json:"status_id,omitempty"`                     // Caption: Status ID;
	Time            int64                           `protobuf:"varint,46,opt,name=time,proto3" json:"time,omitempty"`                                                                                                      // Caption: Event Time;
	TimezoneOffset  int32                           `protobuf:"varint,47,opt,name=timezone_offset,json=timezoneOffset,proto3" json:"timezone_offset,omitempty"`                                                            // Caption: Timezone Offset;
	TypeName        string                          `protobuf:"bytes,48,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`                                                                               // Caption: Type Name;
	TypeUid         int64                           `protobuf:"varint,49,opt,name=type_uid,json=typeUid,proto3" json:"type_uid,omitempty"`                                                                                 // Caption: Type ID;
	Unmapped        *structpb.Struct                `protobuf:"bytes,50,opt,name=unmapped,proto3" json:"unmapped,omitempty"`                                                                                               // Caption: Unmapped Data;
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BaseEvent) Reset() {
	*x = BaseEvent{}
	mi := &file_ocsf_v1_5_0_events_other_other_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseEvent) ProtoMessage() {}

func (x *BaseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ocsf_v1_5_0_events_other_other_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BaseEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *BaseEvent) GetActionId() enums.BASE_EVENT_ACTION_ID {
	if x != nil {
		return x.ActionId
	}
	return enums.BASE_EVENT_ACTION_ID(0)
}

func (x *BaseEvent) GetActivityId() enums.BASE_EVENT_ACTIVITY_ID {
	if x != nil {
		return x.ActivityId
	}
	return enums.BASE_EVENT_ACTIVITY_ID(0)
}

func (x *BaseEvent) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *BaseEvent) GetActor() *objects.Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *BaseEvent) GetApi() *objects.Api {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *BaseEvent) GetAttacks() []*objects.Attack {
	if x != nil {
		return x.Attacks
	}
	return nil
}

func (x *BaseEvent) GetAuthorizations() []*objects.Authorization {
	if x != nil {
		return x.Authorizations
	}
	return nil
}

func (x *BaseEvent) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *BaseEvent) GetCategoryUid() enums.BASE_EVENT_CATEGORY_UID {
	if x != nil {
		return x.CategoryUid
	}
	return enums.BASE_EVENT_CATEGORY_UID(0)
}

func (x *BaseEvent) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *BaseEvent) GetClassUid() enums.BASE_EVENT_CLASS_UID {
	if x != nil {
		return x.ClassUid
	}
	return enums.BASE_EVENT_CLASS_UID(0)
}

func (x *BaseEvent) GetCloud() *objects.Cloud {
	if x != nil {
		return x.Cloud
	}
	return nil
}

func (x *BaseEvent) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *BaseEvent) GetConfidenceId() enums.BASE_EVENT_CONFIDENCE_ID {
	if x != nil {
		return x.ConfidenceId
	}
	return enums.BASE_EVENT_CONFIDENCE_ID(0)
}

func (x *BaseEvent) GetConfidenceScore() int32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *BaseEvent) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BaseEvent) GetDevice() *objects.Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *BaseEvent) GetDisposition() string {
	if x != nil {
		return x.Disposition
	}
	return ""
}

func (x *BaseEvent) GetDispositionId() enums.BASE_EVENT_DISPOSITION_ID {
	if x != nil {
		return x.DispositionId
	}
	return enums.BASE_EVENT_DISPOSITION_ID(0)
}

func (x *BaseEvent) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *BaseEvent) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *BaseEvent) GetEnrichments() []*objects.Enrichment {
	if x != nil {
		return x.Enrichments
	}
	return nil
}

func (x *BaseEvent) GetFirewallRule() *objects.FirewallRule {
	if x != nil {
		return x.FirewallRule
	}
	return nil
}

func (x *BaseEvent) GetIsAlert() bool {
	if x != nil {
		return x.IsAlert
	}
	return false
}

func (x *BaseEvent) GetMalware() []*objects.Malware {
	if x != nil {
		return x.Malware
	}
	return nil
}

func (x *BaseEvent) GetMalwareScanInfo() *objects.MalwareScanInfo {
	if x != nil {
		return x.MalwareScanInfo
	}
	return nil
}

func (x *BaseEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BaseEvent) GetMetadata() *objects.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BaseEvent) GetObservables() []*objects.Observable {
	if x != nil {
		return x.Observables
	}
	return nil
}

func (x *BaseEvent) GetOsint() []*objects.Osint {
	if x != nil {
		return x.Osint
	}
	return nil
}

func (x *BaseEvent) GetPolicy() *objects.Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *BaseEvent) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *BaseEvent) GetRawDataSize() int64 {
	if x != nil {
		return x.RawDataSize
	}
	return 0
}

func (x *BaseEvent) GetRiskDetails() string {
	if x != nil {
		return x.RiskDetails
	}
	return ""
}

func (x *BaseEvent) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *BaseEvent) GetRiskLevelId() enums.BASE_EVENT_RISK_LEVEL_ID {
	if x != nil {
		return x.RiskLevelId
	}
	return enums.BASE_EVENT_RISK_LEVEL_ID(0)
}

func (x *BaseEvent) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *BaseEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *BaseEvent) GetSeverityId() enums.BASE_EVENT_SEVERITY_ID {
	if x != nil {
		return x.SeverityId
	}
	return enums.BASE_EVENT_SEVERITY_ID(0)
}

func (x *BaseEvent) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *BaseEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BaseEvent) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *BaseEvent) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

func (x *BaseEvent) GetStatusId() enums.BASE_EVENT_STATUS_ID {
	if x != nil {
		return x.StatusId
	}
	return enums.BASE_EVENT_STATUS_ID(0)
}

func (x *BaseEvent) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *BaseEvent) GetTimezoneOffset() int32 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

func (x *BaseEvent) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *BaseEvent) GetTypeUid() int64 {
	if x != nil {
		return x.TypeUid
	}
	return 0
}

func (x *BaseEvent) GetUnmapped() *structpb.Struct {
	if x != nil {
		return x.Unmapped
	}
	return nil
}

func (x *BaseEvent) SetAction(v string) {
	x.Action = v
}

func (x *BaseEvent) SetActionId(v enums.BASE_EVENT_ACTION_ID) {
	x.ActionId = v
}

func (x *BaseEvent) SetActivityId(v enums.BASE_EVENT_ACTIVITY_ID) {
	x.ActivityId = v
}

func (x *BaseEvent) SetActivityName(v string) {
	x.ActivityName = v
}

func (x *BaseEvent) SetActor(v *objects.Actor) {
	x.Actor = v
}

func (x *BaseEvent) SetApi(v *objects.Api) {
	x.Api = v
}

func (x *BaseEvent) SetAttacks(v []*objects.Attack) {
	x.Attacks = v
}

func (x *BaseEvent) SetAuthorizations(v []*objects.Authorization) {
	x.Authorizations = v
}

func (x *BaseEvent) SetCategoryName(v string) {
	x.CategoryName = v
}

func (x *BaseEvent) SetCategoryUid(v enums.BASE_EVENT_CATEGORY_UID) {
	x.CategoryUid = v
}

func (x *BaseEvent) SetClassName(v string) {
	x.ClassName = v
}

func (x *BaseEvent) SetClassUid(v enums.BASE_EVENT_CLASS_UID) {
	x.ClassUid = v
}

func (x *BaseEvent) SetCloud(v *objects.Cloud) {
	x.Cloud = v
}

func (x *BaseEvent) SetConfidence(v string) {
	x.Confidence = v
}

func (x *BaseEvent) SetConfidenceId(v enums.BASE_EVENT_CONFIDENCE_ID) {
	x.ConfidenceId = v
}

func (x *BaseEvent) SetConfidenceScore(v int32) {
	x.ConfidenceScore = v
}

func (x *BaseEvent) SetCount(v int32) {
	x.Count = v
}

func (x *BaseEvent) SetDevice(v *objects.Device) {
	x.Device = v
}

func (x *BaseEvent) SetDisposition(v string) {
	x.Disposition = v
}

func (x *BaseEvent) SetDispositionId(v enums.BASE_EVENT_DISPOSITION_ID) {
	x.DispositionId = v
}

func (x *BaseEvent) SetDuration(v int64) {
	x.Duration = v
}

func (x *BaseEvent) SetEndTime(v int64) {
	x.EndTime = v
}

func (x *BaseEvent) SetEnrichments(v []*objects.Enrichment) {
	x.Enrichments = v
}

func (x *BaseEvent) SetFirewallRule(v *objects.FirewallRule) {
	x.FirewallRule = v
}

func (x *BaseEvent) SetIsAlert(v bool) {
	x.IsAlert = v
}

func (x *BaseEvent) SetMalware(v []*objects.Malware) {
	x.Malware = v
}

func (x *BaseEvent) SetMalwareScanInfo(v *objects.MalwareScanInfo) {
	x.MalwareScanInfo = v
}

func (x *BaseEvent) SetMessage(v string) {
	x.Message = v
}

func (x *BaseEvent) SetMetadata(v *objects.Metadata) {
	x.Metadata = v
}

func (x *BaseEvent) SetObservables(v []*objects.Observable) {
	x.Observables = v
}

func (x *BaseEvent) SetOsint(v []*objects.Osint) {
	x.Osint = v
}

func (x *BaseEvent) SetPolicy(v *objects.Policy) {
	x.Policy = v
}

func (x *BaseEvent) SetRawData(v string) {
	x.RawData = v
}

func (x *BaseEvent) SetRawDataSize(v int64) {
	x.RawDataSize = v
}

func (x *BaseEvent) SetRiskDetails(v string) {
	x.RiskDetails = v
}

func (x *BaseEvent) SetRiskLevel(v string) {
	x.RiskLevel = v
}

func (x *BaseEvent) SetRiskLevelId(v enums.BASE_EVENT_RISK_LEVEL_ID) {
	x.RiskLevelId = v
}

func (x *BaseEvent) SetRiskScore(v int32) {
	x.RiskScore = v
}

func (x *BaseEvent) SetSeverity(v string) {
	x.Severity = v
}

func (x *BaseEvent) SetSeverityId(v enums.BASE_EVENT_SEVERITY_ID) {
	x.SeverityId = v
}

func (x *BaseEvent) SetStartTime(v int64) {
	x.StartTime = v
}

func (x *BaseEvent) SetStatus(v string) {
	x.Status = v
}

func (x *BaseEvent) SetStatusCode(v string) {
	x.StatusCode = v
}

func (x *BaseEvent) SetStatusDetail(v string) {
	x.StatusDetail = v
}

func (x *BaseEvent) SetStatusId(v enums.BASE_EVENT_STATUS_ID) {
	x.StatusId = v
}

func (x *BaseEvent) SetTime(v int64) {
	x.Time = v
}

func (x *BaseEvent) SetTimezoneOffset(v int32) {
	x.TimezoneOffset = v
}

func (x *BaseEvent) SetTypeName(v string) {
	x.TypeName = v
}

func (x *BaseEvent) SetTypeUid(v int64) {
	x.TypeUid = v
}

func (x *BaseEvent) SetUnmapped(v *structpb.Struct) {
	x.Unmapped = v
}

func (x *BaseEvent) HasActor() bool {
	if x == nil {
		return false
	}
	return x.Actor != nil
}

func (x *BaseEvent) HasApi() bool {
	if x == nil {
		return false
	}
	return x.Api != nil
}

func (x *BaseEvent) HasCloud() bool {
	if x == nil {
		return false
	}
	return x.Cloud != nil
}

func (x *BaseEvent) HasDevice() bool {
	if x == nil {
		return false
	}
	return x.Device != nil
}

func (x *BaseEvent) HasFirewallRule() bool {
	if x == nil {
		return false
	}
	return x.FirewallRule != nil
}

func (x *BaseEvent) HasMalwareScanInfo() bool {
	if x == nil {
		return false
	}
	return x.MalwareScanInfo != nil
}

func (x *BaseEvent) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *BaseEvent) HasPolicy() bool {
	if x == nil {
		return false
	}
	return x.Policy != nil
}

func (x *BaseEvent) HasUnmapped() bool {
	if x == nil {
		return false
	}
	return x.Unmapped != nil
}

func (x *BaseEvent) ClearActor() {
	x.Actor = nil
}

func (x *BaseEvent) ClearApi() {
	x.Api = nil
}

func (x *BaseEvent) ClearCloud() {
	x.Cloud = nil
}

func (x *BaseEvent) ClearDevice() {
	x.Device = nil
}

func (x *BaseEvent) ClearFirewallRule() {
	x.FirewallRule = nil
}

func (x *BaseEvent) ClearMalwareScanInfo() {
	x.MalwareScanInfo = nil
}

func (x *BaseEvent) ClearMetadata() {
	x.Metadata = nil
}

func (x *BaseEvent) ClearPolicy() {
	x.Policy = nil
}

func (x *BaseEvent) ClearUnmapped() {
	x.Unmapped = nil
}

type BaseEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Action          string
	ActionId        enums.BASE_EVENT_ACTION_ID
	ActivityId      enums.BASE_EVENT_ACTIVITY_ID
	ActivityName    string
	Actor           *objects.Actor
	Api             *objects.Api
	Attacks         []*objects.Attack
	Authorizations  []*objects.Authorization
	CategoryName    string
	CategoryUid     enums.BASE_EVENT_CATEGORY_UID
	ClassName       string
	ClassUid        enums.BASE_EVENT_CLASS_UID
	Cloud           *objects.Cloud
	Confidence      string
	ConfidenceId    enums.BASE_EVENT_CONFIDENCE_ID
	ConfidenceScore int32
	Count           int32
	Device          *objects.Device
	Disposition     string
	DispositionId   enums.BASE_EVENT_DISPOSITION_ID
	Duration        int64
	EndTime         int64
	Enrichments     []*objects.Enrichment
	FirewallRule    *objects.FirewallRule
	IsAlert         bool
	Malware         []*objects.Malware
	MalwareScanInfo *objects.MalwareScanInfo
	Message         string
	Metadata        *objects.Metadata
	Observables     []*objects.Observable
	Osint           []*objects.Osint
	Policy          *objects.Policy
	RawData         string
	RawDataSize     int64
	RiskDetails     string
	RiskLevel       string
	RiskLevelId     enums.BASE_EVENT_RISK_LEVEL_ID
	RiskScore       int32
	Severity        string
	SeverityId      enums.BASE_EVENT_SEVERITY_ID
	StartTime       int64
	Status          string
	StatusCode      string
	StatusDetail    string
	StatusId        enums.BASE_EVENT_STATUS_ID
	Time            int64
	TimezoneOffset  int32
	TypeName        string
	TypeUid         int64
	Unmapped        *structpb.Struct
}

func (b0 BaseEvent_builder) Build() *BaseEvent {
	m0 := &BaseEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.Action = b.Action
	x.ActionId = b.ActionId
	x.ActivityId = b.ActivityId
	x.ActivityName = b.ActivityName
	x.Actor = b.Actor
	x.Api = b.Api
	x.Attacks = b.Attacks
	x.Authorizations = b.Authorizations
	x.CategoryName = b.CategoryName
	x.CategoryUid = b.CategoryUid
	x.ClassName = b.ClassName
	x.ClassUid = b.ClassUid
	x.Cloud = b.Cloud
	x.Confidence = b.Confidence
	x.ConfidenceId = b.ConfidenceId
	x.ConfidenceScore = b.ConfidenceScore
	x.Count = b.Count
	x.Device = b.Device
	x.Disposition = b.Disposition
	x.DispositionId = b.DispositionId
	x.Duration = b.Duration
	x.EndTime = b.EndTime
	x.Enrichments = b.Enrichments
	x.FirewallRule = b.FirewallRule
	x.IsAlert = b.IsAlert
	x.Malware = b.Malware
	x.MalwareScanInfo = b.MalwareScanInfo
	x.Message = b.Message
	x.Metadata = b.Metadata
	x.Observables = b.Observables
	x.Osint = b.Osint
	x.Policy = b.Policy
	x.RawData = b.RawData
	x.RawDataSize = b.RawDataSize
	x.RiskDetails = b.RiskDetails
	x.RiskLevel = b.RiskLevel
	x.RiskLevelId = b.RiskLevelId
	x.RiskScore = b.RiskScore
	x.Severity = b.Severity
	x.SeverityId = b.SeverityId
	x.StartTime = b.StartTime
	x.Status = b.Status
	x.StatusCode = b.StatusCode
	x.StatusDetail = b.StatusDetail
	x.StatusId = b.StatusId
	x.Time = b.Time
	x.TimezoneOffset = b.TimezoneOffset
	x.TypeName = b.TypeName
	x.TypeUid = b.TypeUid
	x.Unmapped = b.Unmapped
	return m0
}

var File_ocsf_v1_5_0_events_other_other_proto protoreflect.FileDescriptor

const file_ocsf_v1_5_0_events_other_other_proto_rawDesc = "" +
	"\n" +
	"$ocsf/v1_5_0/events/other/other.proto\x12\x18ocsf.v1_5_0.events.other\x1a*ocsf/v1_5_0/events/other/enums/enums.proto\x1a!ocsf/v1_5_0/objects/objects.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc6\x13\n" +
	"\tBaseEvent\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12Q\n" +
	"\taction_id\x18\x02 \x01(\x0e24.ocsf.v1_5_0.events.other.enums.BASE_EVENT_ACTION_IDR\bactionId\x12W\n" +
	"\vactivity_id\x18\x03 \x01(\x0e26.ocsf.v1_5_0.events.other.enums.BASE_EVENT_ACTIVITY_IDR\n" +
	"activityId\x12#\n" +
	"\ractivity_name\x18\x04 \x01(\tR\factivityName\x120\n" +
	"\x05actor\x18\x05 \x01(\v2\x1a.ocsf.v1_5_0.objects.ActorR\x05actor\x12*\n" +
	"\x03api\x18\x06 \x01(\v2\x18.ocsf.v1_5_0.objects.ApiR\x03api\x125\n" +
	"\aattacks\x18\a \x03(\v2\x1b.ocsf.v1_5_0.objects.AttackR\aattacks\x12J\n" +
	"\x0eauthorizations\x18\b \x03(\v2\".ocsf.v1_5_0.objects.AuthorizationR\x0eauthorizations\x12#\n" +
	"\rcategory_name\x18\t \x01(\tR\fcategoryName\x12Z\n" +
	"\fcategory_uid\x18\n" +
	" \x01(\x0e27.ocsf.v1_5_0.events.other.enums.BASE_EVENT_CATEGORY_UIDR\vcategoryUid\x12\x1d\n" +
	"\n" +
	"class_name\x18\v \x01(\tR\tclassName\x12Q\n" +
	"\tclass_uid\x18\f \x01(\x0e24.ocsf.v1_5_0.events.other.enums.BASE_EVENT_CLASS_UIDR\bclassUid\x120\n" +
	"\x05cloud\x18\r \x01(\v2\x1a.ocsf.v1_5_0.objects.CloudR\x05cloud\x12\x1e\n" +
	"\n" +
	"confidence\x18\x0e \x01(\tR\n" +
	"confidence\x12]\n" +
	"\rconfidence_id\x18\x0f \x01(\x0e28.ocsf.v1_5_0.events.other.enums.BASE_EVENT_CONFIDENCE_IDR\fconfidenceId\x12)\n" +
	"\x10confidence_score\x18\x10 \x01(\x05R\x0fconfidenceScore\x12\x14\n" +
	"\x05count\x18\x11 \x01(\x05R\x05count\x123\n" +
	"\x06device\x18\x12 \x01(\v2\x1b.ocsf.v1_5_0.objects.DeviceR\x06device\x12 \n" +
	"\vdisposition\x18\x13 \x01(\tR\vdisposition\x12`\n" +
	"\x0edisposition_id\x18\x14 \x01(\x0e29.ocsf.v1_5_0.events.other.enums.BASE_EVENT_DISPOSITION_IDR\rdispositionId\x12\x1a\n" +
	"\bduration\x18\x15 \x01(\x03R\bduration\x12\x19\n" +
	"\bend_time\x18\x16 \x01(\x03R\aendTime\x12A\n" +
	"\venrichments\x18\x17 \x03(\v2\x1f.ocsf.v1_5_0.objects.EnrichmentR\venrichments\x12F\n" +
	"\rfirewall_rule\x18\x18 \x01(\v2!.ocsf.v1_5_0.objects.FirewallRuleR\ffirewallRule\x12\x19\n" +
	"\bis_alert\x18\x19 \x01(\bR\aisAlert\x126\n" +
	"\amalware\x18\x1a \x03(\v2\x1c.ocsf.v1_5_0.objects.MalwareR\amalware\x12P\n" +
	"\x11malware_scan_info\x18\x1b \x01(\v2$.ocsf.v1_5_0.objects.MalwareScanInfoR\x0fmalwareScanInfo\x12\x18\n" +
	"\amessage\x18\x1c \x01(\tR\amessage\x129\n" +
	"\bmetadata\x18\x1d \x01(\v2\x1d.ocsf.v1_5_0.objects.MetadataR\bmetadata\x12A\n" +
	"\vobservables\x18\x1e \x03(\v2\x1f.ocsf.v1_5_0.objects.ObservableR\vobservables\x120\n" +
	"\x05osint\x18\x1f \x03(\v2\x1a.ocsf.v1_5_0.objects.OsintR\x05osint\x123\n" +
	"\x06policy\x18  \x01(\v2\x1b.ocsf.v1_5_0.objects.PolicyR\x06policy\x12\x19\n" +
	"\braw_data\x18! \x01(\tR\arawData\x12\"\n" +
	"\rraw_data_size\x18\" \x01(\x03R\vrawDataSize\x12!\n" +
	"\frisk_details\x18# \x01(\tR\vriskDetails\x12\x1d\n" +
	"\n" +
	"risk_level\x18$ \x01(\tR\triskLevel\x12\\\n" +
	"\rrisk_level_id\x18% \x01(\x0e28.ocsf.v1_5_0.events.other.enums.BASE_EVENT_RISK_LEVEL_IDR\vriskLevelId\x12\x1d\n" +
	"\n" +
	"risk_score\x18& \x01(\x05R\triskScore\x12\x1a\n" +
	"\bseverity\x18' \x01(\tR\bseverity\x12W\n" +
	"\vseverity_id\x18( \x01(\x0e26.ocsf.v1_5_0.events.other.enums.BASE_EVENT_SEVERITY_IDR\n" +
	"severityId\x12\x1d\n" +
	"\n" +
	"start_time\x18) \x01(\x03R\tstartTime\x12\x16\n" +
	"\x06status\x18* \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18+ \x01(\tR\n" +
	"statusCode\x12#\n" +
	"\rstatus_detail\x18, \x01(\tR\fstatusDetail\x12Q\n" +
	"\tstatus_id\x18- \x01(\x0e24.ocsf.v1_5_0.events.other.enums.BASE_EVENT_STATUS_IDR\bstatusId\x12\x12\n" +
	"\x04time\x18. \x01(\x03R\x04time\x12'\n" +
	"\x0ftimezone_offset\x18/ \x01(\x05R\x0etimezoneOffset\x12\x1b\n" +
	"\ttype_name\x180 \x01(\tR\btypeName\x12\x19\n" +
	"\btype_uid\x181 \x01(\x03R\atypeUid\x123\n" +
	"\bunmapped\x182 \x01(\v2\x17.google.protobuf.StructR\bunmappedB\xe7\x01\n" +
	"\x1ccom.ocsf.v1_5_0.events.otherB\n" +
	"OtherProtoP\x01Z?github.com/valllabh/ocsf-schema-golang/ocsf/v1_5_0/events/other\xa2\x02\x04OVEO\xaa\x02\x16Ocsf.V150.Events.Other\xca\x02\x16Ocsf\\V150\\Events\\Other\xe2\x02\"Ocsf\\V150\\Events\\Other\\GPBMetadata\xea\x02\x19Ocsf::V150::Events::Otherb\x06proto3"

var file_ocsf_v1_5_0_events_other_other_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ocsf_v1_5_0_events_other_other_proto_goTypes = []any{
	(*BaseEvent)(nil),                    // 0: ocsf.v1_5_0.events.other.BaseEvent
	(enums.BASE_EVENT_ACTION_ID)(0),      // 1: ocsf.v1_5_0.events.other.enums.BASE_EVENT_ACTION_ID
	(enums.BASE_EVENT_ACTIVITY_ID)(0),    // 2: ocsf.v1_5_0.events.other.enums.BASE_EVENT_ACTIVITY_ID
	(*objects.Actor)(nil),                // 3: ocsf.v1_5_0.objects.Actor
	(*objects.Api)(nil),                  // 4: ocsf.v1_5_0.objects.Api
	(*objects.Attack)(nil),               // 5: ocsf.v1_5_0.objects.Attack
	(*objects.Authorization)(nil),        // 6: ocsf.v1_5_0.objects.Authorization
	(enums.BASE_EVENT_CATEGORY_UID)(0),   // 7: ocsf.v1_5_0.events.other.enums.BASE_EVENT_CATEGORY_UID
	(enums.BASE_EVENT_CLASS_UID)(0),      // 8: ocsf.v1_5_0.events.other.enums.BASE_EVENT_CLASS_UID
	(*objects.Cloud)(nil),                // 9: ocsf.v1_5_0.objects.Cloud
	(enums.BASE_EVENT_CONFIDENCE_ID)(0),  // 10: ocsf.v1_5_0.events.other.enums.BASE_EVENT_CONFIDENCE_ID
	(*objects.Device)(nil),               // 11: ocsf.v1_5_0.objects.Device
	(enums.BASE_EVENT_DISPOSITION_ID)(0), // 12: ocsf.v1_5_0.events.other.enums.BASE_EVENT_DISPOSITION_ID
	(*objects.Enrichment)(nil),           // 13: ocsf.v1_5_0.objects.Enrichment
	(*objects.FirewallRule)(nil),         // 14: ocsf.v1_5_0.objects.FirewallRule
	(*objects.Malware)(nil),              // 15: ocsf.v1_5_0.objects.Malware
	(*objects.MalwareScanInfo)(nil),      // 16: ocsf.v1_5_0.objects.MalwareScanInfo
	(*objects.Metadata)(nil),             // 17: ocsf.v1_5_0.objects.Metadata
	(*objects.Observable)(nil),           // 18: ocsf.v1_5_0.objects.Observable
	(*objects.Osint)(nil),                // 19: ocsf.v1_5_0.objects.Osint
	(*objects.Policy)(nil),               // 20: ocsf.v1_5_0.objects.Policy
	(enums.BASE_EVENT_RISK_LEVEL_ID)(0),  // 21: ocsf.v1_5_0.events.other.enums.BASE_EVENT_RISK_LEVEL_ID
	(enums.BASE_EVENT_SEVERITY_ID)(0),    // 22: ocsf.v1_5_0.events.other.enums.BASE_EVENT_SEVERITY_ID
	(enums.BASE_EVENT_STATUS_ID)(0),      // 23: ocsf.v1_5_0.events.other.enums.BASE_EVENT_STATUS_ID
	(*structpb.Struct)(nil),              // 24: google.protobuf.Struct
}
var file_ocsf_v1_5_0_events_other_other_proto_depIdxs = []int32{
	1,  // 0: ocsf.v1_5_0.events.other.BaseEvent.action_id:type_name -> ocsf.v1_5_0.events.other.enums.BASE_EVENT_ACTION_ID
	2,  // 1: ocsf.v1_5_0.events.other.BaseEvent.activity_id:type_name -> ocsf.v1_5_0.events.other.enums.BASE_EVENT_ACTIVITY_ID
	3,  // 2: ocsf.v1_5_0.events.other.BaseEvent.actor:type_name -> ocsf.v1_5_0.objects.Actor
	4,  // 3: ocsf.v1_5_0.events.other.BaseEvent.api:type_name -> ocsf.v1_5_0.objects.Api
	5,  // 4: ocsf.v1_5_0.events.other.BaseEvent.attacks:type_name -> ocsf.v1_5_0.objects.Attack
	6,  // 5: ocsf.v1_5_0.events.other.BaseEvent.authorizations:type_name -> ocsf.v1_5_0.objects.Authorization
	7,  // 6: ocsf.v1_5_0.events.other.BaseEvent.category_uid:type_name -> ocsf.v1_5_0.events.other.enums.BASE_EVENT_CATEGORY_UID
	8,  // 7: ocsf.v1_5_0.events.other.BaseEvent.class_uid:type_name -> ocsf.v1_5_0.events.other.enums.BASE_EVENT_CLASS_UID
	9,  // 8: ocsf.v1_5_0.events.other.BaseEvent.cloud:type_name -> ocsf.v1_5_0.objects.Cloud
	10, // 9: ocsf.v1_5_0.events.other.BaseEvent.confidence_id:type_name -> ocsf.v1_5_0.events.other.enums.BASE_EVENT_CONFIDENCE_ID
	11, // 10: ocsf.v1_5_0.events.other.BaseEvent.device:type_name -> ocsf.v1_5_0.objects.Device
	12, // 11: ocsf.v1_5_0.events.other.BaseEvent.disposition_id:type_name -> ocsf.v1_5_0.events.other.enums.BASE_EVENT_DISPOSITION_ID
	13, // 12: ocsf.v1_5_0.events.other.BaseEvent.enrichments:type_name -> ocsf.v1_5_0.objects.Enrichment
	14, // 13: ocsf.v1_5_0.events.other.BaseEvent.firewall_rule:type_name -> ocsf.v1_5_0.objects.FirewallRule
	15, // 14: ocsf.v1_5_0.events.other.BaseEvent.malware:type_name -> ocsf.v1_5_0.objects.Malware
	16, // 15: ocsf.v1_5_0.events.other.BaseEvent.malware_scan_info:type_name -> ocsf.v1_5_0.objects.MalwareScanInfo
	17, // 16: ocsf.v1_5_0.events.other.BaseEvent.metadata:type_name -> ocsf.v1_5_0.objects.Metadata
	18, // 17: ocsf.v1_5_0.events.other.BaseEvent.observables:type_name -> ocsf.v1_5_0.objects.Observable
	19, // 18: ocsf.v1_5_0.events.other.BaseEvent.osint:type_name -> ocsf.v1_5_0.objects.Osint
	20, // 19: ocsf.v1_5_0.events.other.BaseEvent.policy:type_name -> ocsf.v1_5_0.objects.Policy
	21, // 20: ocsf.v1_5_0.events.other.BaseEvent.risk_level_id:type_name -> ocsf.v1_5_0.events.other.enums.BASE_EVENT_RISK_LEVEL_ID
	22, // 21: ocsf.v1_5_0.events.other.BaseEvent.severity_id:type_name -> ocsf.v1_5_0.events.other.enums.BASE_EVENT_SEVERITY_ID
	23, // 22: ocsf.v1_5_0.events.other.BaseEvent.status_id:type_name -> ocsf.v1_5_0.events.other.enums.BASE_EVENT_STATUS_ID
	24, // 23: ocsf.v1_5_0.events.other.BaseEvent.unmapped:type_name -> google.protobuf.Struct
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_ocsf_v1_5_0_events_other_other_proto_init() }
func file_ocsf_v1_5_0_events_other_other_proto_init() {
	if File_ocsf_v1_5_0_events_other_other_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocsf_v1_5_0_events_other_other_proto_rawDesc), len(file_ocsf_v1_5_0_events_other_other_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocsf_v1_5_0_events_other_other_proto_goTypes,
		DependencyIndexes: file_ocsf_v1_5_0_events_other_other_proto_depIdxs,
		MessageInfos:      file_ocsf_v1_5_0_events_other_other_proto_msgTypes,
	}.Build()
	File_ocsf_v1_5_0_events_other_other_proto = out.File
	file_ocsf_v1_5_0_events_other_other_proto_goTypes = nil
	file_ocsf_v1_5_0_events_other_other_proto_depIdxs = nil
}
