syntax = "proto3";

package ocsf.v1_4_0.events.network;

option go_package = "/ocsf/v1_4_0/events/network";

option java_package = "com.your.project.generated.ocsf.v1_4_0.events.network";

option java_multiple_files = true;

import "ocsf/v1_4_0/events/network/enums/enums.proto";

import "ocsf/v1_4_0/objects/objects.proto";

import "google/protobuf/struct.proto";

// URL: https://schema.ocsf.io/1.4.0/classes/dhcp_activity
// Event: network
// Event UID: 4
message DhcpActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.DHCP_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.DHCP_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_4_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_4_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_4_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® Details; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_4_0.events.network.enums.DHCP_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_4_0.events.network.enums.DHCP_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_4_0.objects.Cloud cloud = 14; // Caption: Cloud; Profile: cloud;
	string confidence = 15; // Caption: Confidence; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.DHCP_ACTIVITY_CONFIDENCE_ID confidence_id = 16; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 17; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkConnectionInfo connection_info = 18; // Caption: Connection Info;
	int32 count = 19; // Caption: Count;
	ocsf.v1_4_0.objects.Device device = 20; // Caption: Device; Profile: host;
	string disposition = 21; // Caption: Disposition; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.DHCP_ACTIVITY_DISPOSITION_ID disposition_id = 22; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkEndpoint dst_endpoint = 23; // Caption: Destination Endpoint;
	int64 duration = 24; // Caption: Duration Milliseconds;
	int64 end_time = 25; // Caption: End Time;
	repeated ocsf.v1_4_0.objects.Enrichment enrichments = 26; // Caption: Enrichments;
	ocsf.v1_4_0.objects.FirewallRule firewall_rule = 27; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 28; // Caption: Alert; Profile: security_control;
	bool is_renewal = 29; // Caption: Renewal;
	repeated ocsf.v1_4_0.objects.Ja4Fingerprint ja4_fingerprint_list = 30; // Caption: JA4+ Fingerprints;
	int32 lease_dur = 31; // Caption: Lease Duration;
	ocsf.v1_4_0.objects.LoadBalancer load_balancer = 32; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_4_0.objects.Malware malware = 33; // Caption: Malware; Profile: security_control;
	string message = 34; // Caption: Message;
	ocsf.v1_4_0.objects.Metadata metadata = 35; // Caption: Metadata;
	repeated ocsf.v1_4_0.objects.Observable observables = 36; // Caption: Observables;
	repeated ocsf.v1_4_0.objects.Osint osint = 37; // Profile: osint; Caption: OSINT;
	ocsf.v1_4_0.objects.Policy policy = 38; // Caption: Policy; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkProxy proxy = 39; // Caption: Proxy;
	ocsf.v1_4_0.objects.NetworkConnectionInfo proxy_connection_info = 40; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkProxy proxy_endpoint = 41; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpRequest proxy_http_request = 42; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpResponse proxy_http_response = 43; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_4_0.objects.Tls proxy_tls = 44; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkTraffic proxy_traffic = 45; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 46; // Caption: Raw Data;
	ocsf.v1_4_0.objects.NetworkInterface relay = 47; // Caption: Relay;
	string risk_details = 48; // Caption: Risk Details; Profile: security_control;
	string risk_level = 49; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.DHCP_ACTIVITY_RISK_LEVEL_ID risk_level_id = 50; // Profile: security_control; Caption: Risk Level ID;
	int32 risk_score = 51; // Caption: Risk Score; Profile: security_control;
	string severity = 52; // Caption: Severity;
	ocsf.v1_4_0.events.network.enums.DHCP_ACTIVITY_SEVERITY_ID severity_id = 53; // Caption: Severity ID;
	ocsf.v1_4_0.objects.NetworkEndpoint src_endpoint = 54; // Caption: Source Endpoint;
	int64 start_time = 55; // Caption: Start Time;
	string status = 56; // Caption: Status;
	string status_code = 57; // Caption: Status Code;
	string status_detail = 58; // Caption: Status Detail;
	ocsf.v1_4_0.events.network.enums.DHCP_ACTIVITY_STATUS_ID status_id = 59; // Caption: Status ID;
	int64 time = 60; // Caption: Event Time;
	int32 timezone_offset = 61; // Caption: Timezone Offset;
	ocsf.v1_4_0.objects.Tls tls = 62; // Caption: TLS;
	ocsf.v1_4_0.objects.NetworkTraffic traffic = 63; // Caption: Traffic;
	string transaction_uid = 64; // Caption: Transaction UID;
	string type_name = 65; // Caption: Type Name;
	ocsf.v1_4_0.events.network.enums.DHCP_ACTIVITY_TYPE_UID type_uid = 66; // Caption: Type ID;
	google.protobuf.Struct unmapped = 67; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 3
// URL: https://schema.ocsf.io/1.4.0/classes/dns_activity
message DnsActivity {
	string action = 1; // Profile: security_control; Caption: Action;
	ocsf.v1_4_0.events.network.enums.DNS_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.DNS_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_4_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	repeated ocsf.v1_4_0.objects.DnsAnswer answers = 6; // Caption: DNS Answer;
	ocsf.v1_4_0.objects.Api api = 7; // Caption: API Details; Profile: cloud;
	string app_name = 8; // Caption: Application Name;
	repeated ocsf.v1_4_0.objects.Attack attacks = 9; // Caption: MITRE ATT&CK® Details; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Authorization authorizations = 10; // Caption: Authorization Information; Profile: security_control;
	string category_name = 11; // Caption: Category;
	ocsf.v1_4_0.events.network.enums.DNS_ACTIVITY_CATEGORY_UID category_uid = 12; // Caption: Category ID;
	string class_name = 13; // Caption: Class;
	ocsf.v1_4_0.events.network.enums.DNS_ACTIVITY_CLASS_UID class_uid = 14; // Caption: Class ID;
	ocsf.v1_4_0.objects.Cloud cloud = 15; // Caption: Cloud; Profile: cloud;
	string confidence = 16; // Caption: Confidence; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.DNS_ACTIVITY_CONFIDENCE_ID confidence_id = 17; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 18; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkConnectionInfo connection_info = 19; // Caption: Connection Info;
	int32 count = 20; // Caption: Count;
	ocsf.v1_4_0.objects.Device device = 21; // Caption: Device; Profile: host;
	string disposition = 22; // Caption: Disposition; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.DNS_ACTIVITY_DISPOSITION_ID disposition_id = 23; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkEndpoint dst_endpoint = 24; // Caption: Destination Endpoint;
	int64 duration = 25; // Caption: Duration Milliseconds;
	int64 end_time = 26; // Caption: End Time;
	repeated ocsf.v1_4_0.objects.Enrichment enrichments = 27; // Caption: Enrichments;
	ocsf.v1_4_0.objects.FirewallRule firewall_rule = 28; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 29; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Ja4Fingerprint ja4_fingerprint_list = 30; // Caption: JA4+ Fingerprints;
	ocsf.v1_4_0.objects.LoadBalancer load_balancer = 31; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_4_0.objects.Malware malware = 32; // Caption: Malware; Profile: security_control;
	string message = 33; // Caption: Message;
	ocsf.v1_4_0.objects.Metadata metadata = 34; // Caption: Metadata;
	repeated ocsf.v1_4_0.objects.Observable observables = 35; // Caption: Observables;
	repeated ocsf.v1_4_0.objects.Osint osint = 36; // Caption: OSINT; Profile: osint;
	ocsf.v1_4_0.objects.Policy policy = 37; // Caption: Policy; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkProxy proxy = 38; // Caption: Proxy;
	ocsf.v1_4_0.objects.NetworkConnectionInfo proxy_connection_info = 39; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkProxy proxy_endpoint = 40; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpRequest proxy_http_request = 41; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpResponse proxy_http_response = 42; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_4_0.objects.Tls proxy_tls = 43; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkTraffic proxy_traffic = 44; // Caption: Proxy Traffic; Profile: network_proxy;
	ocsf.v1_4_0.objects.DnsQuery query = 45; // Caption: DNS Query;
	int64 query_time = 46; // Caption: Query Time;
	string raw_data = 47; // Caption: Raw Data;
	string rcode = 48; // Caption: Response Code;
	ocsf.v1_4_0.events.network.enums.DNS_ACTIVITY_RCODE_ID rcode_id = 49; // Caption: Response Code ID;
	int64 response_time = 50; // Caption: Response Time;
	string risk_details = 51; // Caption: Risk Details; Profile: security_control;
	string risk_level = 52; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.DNS_ACTIVITY_RISK_LEVEL_ID risk_level_id = 53; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 54; // Caption: Risk Score; Profile: security_control;
	string severity = 55; // Caption: Severity;
	ocsf.v1_4_0.events.network.enums.DNS_ACTIVITY_SEVERITY_ID severity_id = 56; // Caption: Severity ID;
	ocsf.v1_4_0.objects.NetworkEndpoint src_endpoint = 57; // Caption: Source Endpoint;
	int64 start_time = 58; // Caption: Start Time;
	string status = 59; // Caption: Status;
	string status_code = 60; // Caption: Status Code;
	string status_detail = 61; // Caption: Status Detail;
	ocsf.v1_4_0.events.network.enums.DNS_ACTIVITY_STATUS_ID status_id = 62; // Caption: Status ID;
	int64 time = 63; // Caption: Event Time;
	int32 timezone_offset = 64; // Caption: Timezone Offset;
	ocsf.v1_4_0.objects.Tls tls = 65; // Caption: TLS;
	ocsf.v1_4_0.objects.NetworkTraffic traffic = 66; // Caption: Traffic;
	string type_name = 67; // Caption: Type Name;
	ocsf.v1_4_0.events.network.enums.DNS_ACTIVITY_TYPE_UID type_uid = 68; // Caption: Type ID;
	google.protobuf.Struct unmapped = 69; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 9
// URL: https://schema.ocsf.io/1.4.0/classes/email_activity
message EmailActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.EMAIL_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.EMAIL_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_4_0.objects.Actor actor = 5; // Profile: host; Caption: Actor;
	ocsf.v1_4_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	repeated ocsf.v1_4_0.objects.Attack attacks = 7; // Caption: MITRE ATT&CK® Details; Profile: security_control;
	int32 attempt = 8; // Caption: Attempt;
	repeated ocsf.v1_4_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string banner = 10; // Caption: Protocol Banner;
	string category_name = 11; // Caption: Category;
	ocsf.v1_4_0.events.network.enums.EMAIL_ACTIVITY_CATEGORY_UID category_uid = 12; // Caption: Category ID;
	string class_name = 13; // Caption: Class;
	ocsf.v1_4_0.events.network.enums.EMAIL_ACTIVITY_CLASS_UID class_uid = 14; // Caption: Class ID;
	ocsf.v1_4_0.objects.Cloud cloud = 15; // Caption: Cloud; Profile: cloud;
	string command = 16; // Caption: Command;
	string confidence = 17; // Caption: Confidence; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.EMAIL_ACTIVITY_CONFIDENCE_ID confidence_id = 18; // Profile: security_control; Caption: Confidence ID;
	int32 confidence_score = 19; // Caption: Confidence Score; Profile: security_control;
	int32 count = 20; // Caption: Count;
	ocsf.v1_4_0.objects.Device device = 21; // Caption: Device; Profile: host;
	string direction = 22; // Caption: Direction;
	ocsf.v1_4_0.events.network.enums.EMAIL_ACTIVITY_DIRECTION_ID direction_id = 23; // Caption: Direction ID;
	string disposition = 24; // Caption: Disposition; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.EMAIL_ACTIVITY_DISPOSITION_ID disposition_id = 25; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkEndpoint dst_endpoint = 26; // Caption: Destination Endpoint;
	int64 duration = 27; // Caption: Duration Milliseconds;
	ocsf.v1_4_0.objects.Email email = 28; // Caption: Email;
	ocsf.v1_4_0.objects.EmailAuth email_auth = 29; // Caption: Email Authentication;
	int64 end_time = 30; // Caption: End Time;
	repeated ocsf.v1_4_0.objects.Enrichment enrichments = 31; // Caption: Enrichments;
	ocsf.v1_4_0.objects.FirewallRule firewall_rule = 32; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 33; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Malware malware = 34; // Caption: Malware; Profile: security_control;
	string message = 35; // Caption: Message;
	string message_trace_uid = 36; // Caption: Message Trace UID;
	ocsf.v1_4_0.objects.Metadata metadata = 37; // Caption: Metadata;
	repeated ocsf.v1_4_0.objects.Observable observables = 38; // Caption: Observables;
	repeated ocsf.v1_4_0.objects.Osint osint = 39; // Caption: OSINT; Profile: osint;
	ocsf.v1_4_0.objects.Policy policy = 40; // Caption: Policy; Profile: security_control;
	string protocol_name = 41; // Caption: Protocol Name;
	string raw_data = 42; // Caption: Raw Data;
	string risk_details = 43; // Caption: Risk Details; Profile: security_control;
	string risk_level = 44; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.EMAIL_ACTIVITY_RISK_LEVEL_ID risk_level_id = 45; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 46; // Caption: Risk Score; Profile: security_control;
	string severity = 47; // Caption: Severity;
	ocsf.v1_4_0.events.network.enums.EMAIL_ACTIVITY_SEVERITY_ID severity_id = 48; // Caption: Severity ID;
	string smtp_hello = 49; // Caption: SMTP Hello;
	ocsf.v1_4_0.objects.NetworkEndpoint src_endpoint = 50; // Caption: Source Endpoint;
	int64 start_time = 51; // Caption: Start Time;
	string status = 52; // Caption: Status;
	string status_code = 53; // Caption: Status Code;
	string status_detail = 54; // Caption: Status Detail;
	ocsf.v1_4_0.events.network.enums.EMAIL_ACTIVITY_STATUS_ID status_id = 55; // Caption: Status ID;
	int64 time = 56; // Caption: Event Time;
	int32 timezone_offset = 57; // Caption: Timezone Offset;
	string type_name = 58; // Caption: Type Name;
	ocsf.v1_4_0.events.network.enums.EMAIL_ACTIVITY_TYPE_UID type_uid = 59; // Caption: Type ID;
	google.protobuf.Struct unmapped = 60; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 11
// URL: https://schema.ocsf.io/1.4.0/classes/email_file_activity
message EmailFileActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.EMAIL_FILE_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.EMAIL_FILE_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_4_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_4_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	repeated ocsf.v1_4_0.objects.Attack attacks = 7; // Caption: MITRE ATT&CK® Details; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Authorization authorizations = 8; // Caption: Authorization Information; Profile: security_control;
	string category_name = 9; // Caption: Category;
	ocsf.v1_4_0.events.network.enums.EMAIL_FILE_ACTIVITY_CATEGORY_UID category_uid = 10; // Caption: Category ID;
	string class_name = 11; // Caption: Class;
	ocsf.v1_4_0.events.network.enums.EMAIL_FILE_ACTIVITY_CLASS_UID class_uid = 12; // Caption: Class ID;
	ocsf.v1_4_0.objects.Cloud cloud = 13; // Caption: Cloud; Profile: cloud;
	string confidence = 14; // Caption: Confidence; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.EMAIL_FILE_ACTIVITY_CONFIDENCE_ID confidence_id = 15; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 16; // Profile: security_control; Caption: Confidence Score;
	int32 count = 17; // Caption: Count;
	ocsf.v1_4_0.objects.Device device = 18; // Caption: Device; Profile: host;
	string disposition = 19; // Caption: Disposition; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.EMAIL_FILE_ACTIVITY_DISPOSITION_ID disposition_id = 20; // Caption: Disposition ID; Profile: security_control;
	int64 duration = 21; // Caption: Duration Milliseconds;
	string email_uid = 22; // Caption: Email UID;
	int64 end_time = 23; // Caption: End Time;
	repeated ocsf.v1_4_0.objects.Enrichment enrichments = 24; // Caption: Enrichments;
	ocsf.v1_4_0.objects.File file = 25; // Caption: File;
	ocsf.v1_4_0.objects.FirewallRule firewall_rule = 26; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 27; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Malware malware = 28; // Caption: Malware; Profile: security_control;
	string message = 29; // Caption: Message;
	ocsf.v1_4_0.objects.Metadata metadata = 30; // Caption: Metadata;
	repeated ocsf.v1_4_0.objects.Observable observables = 31; // Caption: Observables;
	repeated ocsf.v1_4_0.objects.Osint osint = 32; // Caption: OSINT; Profile: osint;
	ocsf.v1_4_0.objects.Policy policy = 33; // Caption: Policy; Profile: security_control;
	string raw_data = 34; // Caption: Raw Data;
	string risk_details = 35; // Caption: Risk Details; Profile: security_control;
	string risk_level = 36; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.EMAIL_FILE_ACTIVITY_RISK_LEVEL_ID risk_level_id = 37; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 38; // Caption: Risk Score; Profile: security_control;
	string severity = 39; // Caption: Severity;
	ocsf.v1_4_0.events.network.enums.EMAIL_FILE_ACTIVITY_SEVERITY_ID severity_id = 40; // Caption: Severity ID;
	int64 start_time = 41; // Caption: Start Time;
	string status = 42; // Caption: Status;
	string status_code = 43; // Caption: Status Code;
	string status_detail = 44; // Caption: Status Detail;
	ocsf.v1_4_0.events.network.enums.EMAIL_FILE_ACTIVITY_STATUS_ID status_id = 45; // Caption: Status ID;
	int64 time = 46; // Caption: Event Time;
	int32 timezone_offset = 47; // Caption: Timezone Offset;
	string type_name = 48; // Caption: Type Name;
	ocsf.v1_4_0.events.network.enums.EMAIL_FILE_ACTIVITY_TYPE_UID type_uid = 49; // Caption: Type ID;
	google.protobuf.Struct unmapped = 50; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 12
// URL: https://schema.ocsf.io/1.4.0/classes/email_url_activity
message EmailUrlActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.EMAIL_URL_ACTIVITY_ACTION_ID action_id = 2; // Profile: security_control; Caption: Action ID;
	ocsf.v1_4_0.events.network.enums.EMAIL_URL_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_4_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_4_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	repeated ocsf.v1_4_0.objects.Attack attacks = 7; // Caption: MITRE ATT&CK® Details; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Authorization authorizations = 8; // Caption: Authorization Information; Profile: security_control;
	string category_name = 9; // Caption: Category;
	ocsf.v1_4_0.events.network.enums.EMAIL_URL_ACTIVITY_CATEGORY_UID category_uid = 10; // Caption: Category ID;
	string class_name = 11; // Caption: Class;
	ocsf.v1_4_0.events.network.enums.EMAIL_URL_ACTIVITY_CLASS_UID class_uid = 12; // Caption: Class ID;
	ocsf.v1_4_0.objects.Cloud cloud = 13; // Caption: Cloud; Profile: cloud;
	string confidence = 14; // Caption: Confidence; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.EMAIL_URL_ACTIVITY_CONFIDENCE_ID confidence_id = 15; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 16; // Caption: Confidence Score; Profile: security_control;
	int32 count = 17; // Caption: Count;
	ocsf.v1_4_0.objects.Device device = 18; // Caption: Device; Profile: host;
	string disposition = 19; // Profile: security_control; Caption: Disposition;
	ocsf.v1_4_0.events.network.enums.EMAIL_URL_ACTIVITY_DISPOSITION_ID disposition_id = 20; // Caption: Disposition ID; Profile: security_control;
	int64 duration = 21; // Caption: Duration Milliseconds;
	string email_uid = 22; // Caption: Email UID;
	int64 end_time = 23; // Caption: End Time;
	repeated ocsf.v1_4_0.objects.Enrichment enrichments = 24; // Caption: Enrichments;
	ocsf.v1_4_0.objects.FirewallRule firewall_rule = 25; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 26; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Malware malware = 27; // Caption: Malware; Profile: security_control;
	string message = 28; // Caption: Message;
	ocsf.v1_4_0.objects.Metadata metadata = 29; // Caption: Metadata;
	repeated ocsf.v1_4_0.objects.Observable observables = 30; // Caption: Observables;
	repeated ocsf.v1_4_0.objects.Osint osint = 31; // Profile: osint; Caption: OSINT;
	ocsf.v1_4_0.objects.Policy policy = 32; // Caption: Policy; Profile: security_control;
	string raw_data = 33; // Caption: Raw Data;
	string risk_details = 34; // Caption: Risk Details; Profile: security_control;
	string risk_level = 35; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.EMAIL_URL_ACTIVITY_RISK_LEVEL_ID risk_level_id = 36; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 37; // Caption: Risk Score; Profile: security_control;
	string severity = 38; // Caption: Severity;
	ocsf.v1_4_0.events.network.enums.EMAIL_URL_ACTIVITY_SEVERITY_ID severity_id = 39; // Caption: Severity ID;
	int64 start_time = 40; // Caption: Start Time;
	string status = 41; // Caption: Status;
	string status_code = 42; // Caption: Status Code;
	string status_detail = 43; // Caption: Status Detail;
	ocsf.v1_4_0.events.network.enums.EMAIL_URL_ACTIVITY_STATUS_ID status_id = 44; // Caption: Status ID;
	int64 time = 45; // Caption: Event Time;
	int32 timezone_offset = 46; // Caption: Timezone Offset;
	string type_name = 47; // Caption: Type Name;
	ocsf.v1_4_0.events.network.enums.EMAIL_URL_ACTIVITY_TYPE_UID type_uid = 48; // Caption: Type ID;
	google.protobuf.Struct unmapped = 49; // Caption: Unmapped Data;
	ocsf.v1_4_0.objects.Url url = 50; // Caption: URL;
}

// Event: network
// Event UID: 8
// URL: https://schema.ocsf.io/1.4.0/classes/ftp_activity
message FtpActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.FTP_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.FTP_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_4_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_4_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_4_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® Details; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Authorization authorizations = 9; // Profile: security_control; Caption: Authorization Information;
	string category_name = 10; // Caption: Category;
	ocsf.v1_4_0.events.network.enums.FTP_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_4_0.events.network.enums.FTP_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_4_0.objects.Cloud cloud = 14; // Caption: Cloud; Profile: cloud;
	repeated int32 codes = 15; // Caption: Response Codes;
	string command = 16; // Caption: Command;
	repeated string command_responses = 17; // Caption: Command Responses;
	string confidence = 18; // Caption: Confidence; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.FTP_ACTIVITY_CONFIDENCE_ID confidence_id = 19; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 20; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkConnectionInfo connection_info = 21; // Caption: Connection Info;
	int32 count = 22; // Caption: Count;
	ocsf.v1_4_0.objects.Device device = 23; // Caption: Device; Profile: host;
	string disposition = 24; // Caption: Disposition; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.FTP_ACTIVITY_DISPOSITION_ID disposition_id = 25; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkEndpoint dst_endpoint = 26; // Caption: Destination Endpoint;
	int64 duration = 27; // Caption: Duration Milliseconds;
	int64 end_time = 28; // Caption: End Time;
	repeated ocsf.v1_4_0.objects.Enrichment enrichments = 29; // Caption: Enrichments;
	ocsf.v1_4_0.objects.File file = 30; // Caption: File;
	ocsf.v1_4_0.objects.FirewallRule firewall_rule = 31; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 32; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Ja4Fingerprint ja4_fingerprint_list = 33; // Caption: JA4+ Fingerprints;
	ocsf.v1_4_0.objects.LoadBalancer load_balancer = 34; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_4_0.objects.Malware malware = 35; // Caption: Malware; Profile: security_control;
	string message = 36; // Caption: Message;
	ocsf.v1_4_0.objects.Metadata metadata = 37; // Caption: Metadata;
	string name = 38; // Caption: Name;
	repeated ocsf.v1_4_0.objects.Observable observables = 39; // Caption: Observables;
	repeated ocsf.v1_4_0.objects.Osint osint = 40; // Caption: OSINT; Profile: osint;
	ocsf.v1_4_0.objects.Policy policy = 41; // Caption: Policy; Profile: security_control;
	int32 port = 42; // Caption: Port;
	ocsf.v1_4_0.objects.NetworkProxy proxy = 43; // Caption: Proxy;
	ocsf.v1_4_0.objects.NetworkConnectionInfo proxy_connection_info = 44; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkProxy proxy_endpoint = 45; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpRequest proxy_http_request = 46; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpResponse proxy_http_response = 47; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_4_0.objects.Tls proxy_tls = 48; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkTraffic proxy_traffic = 49; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 50; // Caption: Raw Data;
	string risk_details = 51; // Caption: Risk Details; Profile: security_control;
	string risk_level = 52; // Profile: security_control; Caption: Risk Level;
	ocsf.v1_4_0.events.network.enums.FTP_ACTIVITY_RISK_LEVEL_ID risk_level_id = 53; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 54; // Caption: Risk Score; Profile: security_control;
	string severity = 55; // Caption: Severity;
	ocsf.v1_4_0.events.network.enums.FTP_ACTIVITY_SEVERITY_ID severity_id = 56; // Caption: Severity ID;
	ocsf.v1_4_0.objects.NetworkEndpoint src_endpoint = 57; // Caption: Source Endpoint;
	int64 start_time = 58; // Caption: Start Time;
	string status = 59; // Caption: Status;
	string status_code = 60; // Caption: Status Code;
	string status_detail = 61; // Caption: Status Detail;
	ocsf.v1_4_0.events.network.enums.FTP_ACTIVITY_STATUS_ID status_id = 62; // Caption: Status ID;
	int64 time = 63; // Caption: Event Time;
	int32 timezone_offset = 64; // Caption: Timezone Offset;
	ocsf.v1_4_0.objects.Tls tls = 65; // Caption: TLS;
	ocsf.v1_4_0.objects.NetworkTraffic traffic = 66; // Caption: Traffic;
	string type = 67; // Caption: Type;
	string type_name = 68; // Caption: Type Name;
	ocsf.v1_4_0.events.network.enums.FTP_ACTIVITY_TYPE_UID type_uid = 69; // Caption: Type ID;
	google.protobuf.Struct unmapped = 70; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 2
// URL: https://schema.ocsf.io/1.4.0/classes/http_activity
message HttpActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.HTTP_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.HTTP_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_4_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_4_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_4_0.objects.Attack attacks = 8; // Profile: security_control; Caption: MITRE ATT&CK® Details;
	repeated ocsf.v1_4_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_4_0.events.network.enums.HTTP_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_4_0.events.network.enums.HTTP_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_4_0.objects.Cloud cloud = 14; // Profile: cloud; Caption: Cloud;
	string confidence = 15; // Caption: Confidence; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.HTTP_ACTIVITY_CONFIDENCE_ID confidence_id = 16; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 17; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkConnectionInfo connection_info = 18; // Caption: Connection Info;
	int32 count = 19; // Caption: Count;
	ocsf.v1_4_0.objects.Device device = 20; // Caption: Device; Profile: host;
	string disposition = 21; // Caption: Disposition; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.HTTP_ACTIVITY_DISPOSITION_ID disposition_id = 22; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkEndpoint dst_endpoint = 23; // Caption: Destination Endpoint;
	int64 duration = 24; // Caption: Duration Milliseconds;
	int64 end_time = 25; // Caption: End Time;
	repeated ocsf.v1_4_0.objects.Enrichment enrichments = 26; // Caption: Enrichments;
	ocsf.v1_4_0.objects.File file = 27; // Caption: File;
	ocsf.v1_4_0.objects.FirewallRule firewall_rule = 28; // Caption: Firewall Rule; Profile: security_control;
	repeated ocsf.v1_4_0.objects.HttpCookie http_cookies = 29; // Caption: HTTP Cookies;
	ocsf.v1_4_0.objects.HttpRequest http_request = 30; // Caption: HTTP Request;
	ocsf.v1_4_0.objects.HttpResponse http_response = 31; // Caption: HTTP Response;
	int32 http_status = 32; // Caption: HTTP Status;
	bool is_alert = 33; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Ja4Fingerprint ja4_fingerprint_list = 34; // Caption: JA4+ Fingerprints;
	ocsf.v1_4_0.objects.LoadBalancer load_balancer = 35; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_4_0.objects.Malware malware = 36; // Caption: Malware; Profile: security_control;
	string message = 37; // Caption: Message;
	ocsf.v1_4_0.objects.Metadata metadata = 38; // Caption: Metadata;
	repeated ocsf.v1_4_0.objects.Observable observables = 39; // Caption: Observables;
	repeated ocsf.v1_4_0.objects.Osint osint = 40; // Caption: OSINT; Profile: osint;
	ocsf.v1_4_0.objects.Policy policy = 41; // Caption: Policy; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkProxy proxy = 42; // Caption: Proxy;
	ocsf.v1_4_0.objects.NetworkConnectionInfo proxy_connection_info = 43; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkProxy proxy_endpoint = 44; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpRequest proxy_http_request = 45; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpResponse proxy_http_response = 46; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_4_0.objects.Tls proxy_tls = 47; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkTraffic proxy_traffic = 48; // Profile: network_proxy; Caption: Proxy Traffic;
	string raw_data = 49; // Caption: Raw Data;
	string risk_details = 50; // Caption: Risk Details; Profile: security_control;
	string risk_level = 51; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.HTTP_ACTIVITY_RISK_LEVEL_ID risk_level_id = 52; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 53; // Profile: security_control; Caption: Risk Score;
	string severity = 54; // Caption: Severity;
	ocsf.v1_4_0.events.network.enums.HTTP_ACTIVITY_SEVERITY_ID severity_id = 55; // Caption: Severity ID;
	ocsf.v1_4_0.objects.NetworkEndpoint src_endpoint = 56; // Caption: Source Endpoint;
	int64 start_time = 57; // Caption: Start Time;
	string status = 58; // Caption: Status;
	string status_code = 59; // Caption: Status Code;
	string status_detail = 60; // Caption: Status Detail;
	ocsf.v1_4_0.events.network.enums.HTTP_ACTIVITY_STATUS_ID status_id = 61; // Caption: Status ID;
	int64 time = 62; // Caption: Event Time;
	int32 timezone_offset = 63; // Caption: Timezone Offset;
	ocsf.v1_4_0.objects.Tls tls = 64; // Caption: TLS;
	ocsf.v1_4_0.objects.Trace trace = 65; // Caption: Trace; Profile: trace;
	ocsf.v1_4_0.objects.NetworkTraffic traffic = 66; // Caption: Traffic;
	string type_name = 67; // Caption: Type Name;
	ocsf.v1_4_0.events.network.enums.HTTP_ACTIVITY_TYPE_UID type_uid = 68; // Caption: Type ID;
	google.protobuf.Struct unmapped = 69; // Caption: Unmapped Data;
}

// Event UID: 0
// URL: https://schema.ocsf.io/1.4.0/classes/network
// Event: network
message Network {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NETWORK_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NETWORK_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_4_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_4_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_4_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® Details; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_4_0.events.network.enums.NETWORK_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_4_0.events.network.enums.NETWORK_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_4_0.objects.Cloud cloud = 14; // Caption: Cloud; Profile: cloud;
	string confidence = 15; // Caption: Confidence; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NETWORK_CONFIDENCE_ID confidence_id = 16; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 17; // Profile: security_control; Caption: Confidence Score;
	ocsf.v1_4_0.objects.NetworkConnectionInfo connection_info = 18; // Caption: Connection Info;
	int32 count = 19; // Caption: Count;
	ocsf.v1_4_0.objects.Device device = 20; // Profile: host; Caption: Device;
	string disposition = 21; // Caption: Disposition; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NETWORK_DISPOSITION_ID disposition_id = 22; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkEndpoint dst_endpoint = 23; // Caption: Destination Endpoint;
	int64 duration = 24; // Caption: Duration Milliseconds;
	int64 end_time = 25; // Caption: End Time;
	repeated ocsf.v1_4_0.objects.Enrichment enrichments = 26; // Caption: Enrichments;
	ocsf.v1_4_0.objects.FirewallRule firewall_rule = 27; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 28; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Ja4Fingerprint ja4_fingerprint_list = 29; // Caption: JA4+ Fingerprints;
	ocsf.v1_4_0.objects.LoadBalancer load_balancer = 30; // Profile: load_balancer; Caption: Load Balancer;
	repeated ocsf.v1_4_0.objects.Malware malware = 31; // Profile: security_control; Caption: Malware;
	string message = 32; // Caption: Message;
	ocsf.v1_4_0.objects.Metadata metadata = 33; // Caption: Metadata;
	repeated ocsf.v1_4_0.objects.Observable observables = 34; // Caption: Observables;
	repeated ocsf.v1_4_0.objects.Osint osint = 35; // Caption: OSINT; Profile: osint;
	ocsf.v1_4_0.objects.Policy policy = 36; // Caption: Policy; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkProxy proxy = 37; // Caption: Proxy;
	ocsf.v1_4_0.objects.NetworkConnectionInfo proxy_connection_info = 38; // Profile: network_proxy; Caption: Proxy Connection Info;
	ocsf.v1_4_0.objects.NetworkProxy proxy_endpoint = 39; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpRequest proxy_http_request = 40; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpResponse proxy_http_response = 41; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_4_0.objects.Tls proxy_tls = 42; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkTraffic proxy_traffic = 43; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 44; // Caption: Raw Data;
	string risk_details = 45; // Caption: Risk Details; Profile: security_control;
	string risk_level = 46; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NETWORK_RISK_LEVEL_ID risk_level_id = 47; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 48; // Caption: Risk Score; Profile: security_control;
	string severity = 49; // Caption: Severity;
	ocsf.v1_4_0.events.network.enums.NETWORK_SEVERITY_ID severity_id = 50; // Caption: Severity ID;
	ocsf.v1_4_0.objects.NetworkEndpoint src_endpoint = 51; // Caption: Source Endpoint;
	int64 start_time = 52; // Caption: Start Time;
	string status = 53; // Caption: Status;
	string status_code = 54; // Caption: Status Code;
	string status_detail = 55; // Caption: Status Detail;
	ocsf.v1_4_0.events.network.enums.NETWORK_STATUS_ID status_id = 56; // Caption: Status ID;
	int64 time = 57; // Caption: Event Time;
	int32 timezone_offset = 58; // Caption: Timezone Offset;
	ocsf.v1_4_0.objects.Tls tls = 59; // Caption: TLS;
	ocsf.v1_4_0.objects.NetworkTraffic traffic = 60; // Caption: Traffic;
	string type_name = 61; // Caption: Type Name;
	ocsf.v1_4_0.events.network.enums.NETWORK_TYPE_UID type_uid = 62; // Caption: Type ID;
	google.protobuf.Struct unmapped = 63; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 1
// URL: https://schema.ocsf.io/1.4.0/classes/network_activity
message NetworkActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NETWORK_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NETWORK_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_4_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_4_0.objects.Api api = 6; // Profile: cloud; Caption: API Details;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_4_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® Details; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_4_0.events.network.enums.NETWORK_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_4_0.events.network.enums.NETWORK_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_4_0.objects.Cloud cloud = 14; // Caption: Cloud; Profile: cloud;
	string confidence = 15; // Profile: security_control; Caption: Confidence;
	ocsf.v1_4_0.events.network.enums.NETWORK_ACTIVITY_CONFIDENCE_ID confidence_id = 16; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 17; // Profile: security_control; Caption: Confidence Score;
	ocsf.v1_4_0.objects.NetworkConnectionInfo connection_info = 18; // Caption: Connection Info;
	int32 count = 19; // Caption: Count;
	ocsf.v1_4_0.objects.Device device = 20; // Caption: Device; Profile: host;
	string disposition = 21; // Caption: Disposition; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NETWORK_ACTIVITY_DISPOSITION_ID disposition_id = 22; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkEndpoint dst_endpoint = 23; // Caption: Destination Endpoint;
	int64 duration = 24; // Caption: Duration Milliseconds;
	int64 end_time = 25; // Caption: End Time;
	repeated ocsf.v1_4_0.objects.Enrichment enrichments = 26; // Caption: Enrichments;
	ocsf.v1_4_0.objects.FirewallRule firewall_rule = 27; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 28; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Ja4Fingerprint ja4_fingerprint_list = 29; // Caption: JA4+ Fingerprints;
	ocsf.v1_4_0.objects.LoadBalancer load_balancer = 30; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_4_0.objects.Malware malware = 31; // Caption: Malware; Profile: security_control;
	string message = 32; // Caption: Message;
	ocsf.v1_4_0.objects.Metadata metadata = 33; // Caption: Metadata;
	repeated ocsf.v1_4_0.objects.Observable observables = 34; // Caption: Observables;
	repeated ocsf.v1_4_0.objects.Osint osint = 35; // Caption: OSINT; Profile: osint;
	ocsf.v1_4_0.objects.Policy policy = 36; // Caption: Policy; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkProxy proxy = 37; // Caption: Proxy;
	ocsf.v1_4_0.objects.NetworkConnectionInfo proxy_connection_info = 38; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkProxy proxy_endpoint = 39; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpRequest proxy_http_request = 40; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpResponse proxy_http_response = 41; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_4_0.objects.Tls proxy_tls = 42; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkTraffic proxy_traffic = 43; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 44; // Caption: Raw Data;
	string risk_details = 45; // Profile: security_control; Caption: Risk Details;
	string risk_level = 46; // Profile: security_control; Caption: Risk Level;
	ocsf.v1_4_0.events.network.enums.NETWORK_ACTIVITY_RISK_LEVEL_ID risk_level_id = 47; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 48; // Caption: Risk Score; Profile: security_control;
	string severity = 49; // Caption: Severity;
	ocsf.v1_4_0.events.network.enums.NETWORK_ACTIVITY_SEVERITY_ID severity_id = 50; // Caption: Severity ID;
	ocsf.v1_4_0.objects.NetworkEndpoint src_endpoint = 51; // Caption: Source Endpoint;
	int64 start_time = 52; // Caption: Start Time;
	string status = 53; // Caption: Status;
	string status_code = 54; // Caption: Status Code;
	string status_detail = 55; // Caption: Status Detail;
	ocsf.v1_4_0.events.network.enums.NETWORK_ACTIVITY_STATUS_ID status_id = 56; // Caption: Status ID;
	int64 time = 57; // Caption: Event Time;
	int32 timezone_offset = 58; // Caption: Timezone Offset;
	ocsf.v1_4_0.objects.Tls tls = 59; // Caption: TLS;
	ocsf.v1_4_0.objects.NetworkTraffic traffic = 60; // Caption: Traffic;
	string type_name = 61; // Caption: Type Name;
	ocsf.v1_4_0.events.network.enums.NETWORK_ACTIVITY_TYPE_UID type_uid = 62; // Caption: Type ID;
	google.protobuf.Struct unmapped = 63; // Caption: Unmapped Data;
	ocsf.v1_4_0.objects.Url url = 64; // Caption: URL;
}

// Event: network
// Event UID: 10
// URL: https://schema.ocsf.io/1.4.0/classes/network_file_activity
message NetworkFileActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NETWORK_FILE_ACTIVITY_ACTION_ID action_id = 2; // Profile: security_control; Caption: Action ID;
	ocsf.v1_4_0.events.network.enums.NETWORK_FILE_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_4_0.objects.Actor actor = 5; // Caption: Actor;
	ocsf.v1_4_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_4_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® Details; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_4_0.events.network.enums.NETWORK_FILE_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_4_0.events.network.enums.NETWORK_FILE_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_4_0.objects.Cloud cloud = 14; // Caption: Cloud; Profile: cloud;
	string confidence = 15; // Caption: Confidence; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NETWORK_FILE_ACTIVITY_CONFIDENCE_ID confidence_id = 16; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 17; // Profile: security_control; Caption: Confidence Score;
	ocsf.v1_4_0.objects.NetworkConnectionInfo connection_info = 18; // Caption: Connection Info;
	int32 count = 19; // Caption: Count;
	ocsf.v1_4_0.objects.Device device = 20; // Profile: host; Caption: Device;
	string disposition = 21; // Caption: Disposition; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NETWORK_FILE_ACTIVITY_DISPOSITION_ID disposition_id = 22; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkEndpoint dst_endpoint = 23; // Caption: Destination Endpoint;
	int64 duration = 24; // Caption: Duration Milliseconds;
	int64 end_time = 25; // Caption: End Time;
	repeated ocsf.v1_4_0.objects.Enrichment enrichments = 26; // Caption: Enrichments;
	int64 expiration_time = 27; // Caption: Expiration Time;
	ocsf.v1_4_0.objects.File file = 28; // Caption: File;
	ocsf.v1_4_0.objects.FirewallRule firewall_rule = 29; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 30; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Ja4Fingerprint ja4_fingerprint_list = 31; // Caption: JA4+ Fingerprints;
	ocsf.v1_4_0.objects.LoadBalancer load_balancer = 32; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_4_0.objects.Malware malware = 33; // Caption: Malware; Profile: security_control;
	string message = 34; // Caption: Message;
	ocsf.v1_4_0.objects.Metadata metadata = 35; // Caption: Metadata;
	repeated ocsf.v1_4_0.objects.Observable observables = 36; // Caption: Observables;
	repeated ocsf.v1_4_0.objects.Osint osint = 37; // Caption: OSINT; Profile: osint;
	ocsf.v1_4_0.objects.Policy policy = 38; // Caption: Policy; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkProxy proxy = 39; // Caption: Proxy;
	ocsf.v1_4_0.objects.NetworkConnectionInfo proxy_connection_info = 40; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkProxy proxy_endpoint = 41; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpRequest proxy_http_request = 42; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpResponse proxy_http_response = 43; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_4_0.objects.Tls proxy_tls = 44; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkTraffic proxy_traffic = 45; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 46; // Caption: Raw Data;
	string risk_details = 47; // Caption: Risk Details; Profile: security_control;
	string risk_level = 48; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NETWORK_FILE_ACTIVITY_RISK_LEVEL_ID risk_level_id = 49; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 50; // Caption: Risk Score; Profile: security_control;
	string severity = 51; // Caption: Severity;
	ocsf.v1_4_0.events.network.enums.NETWORK_FILE_ACTIVITY_SEVERITY_ID severity_id = 52; // Caption: Severity ID;
	ocsf.v1_4_0.objects.NetworkEndpoint src_endpoint = 53; // Caption: Source Endpoint;
	int64 start_time = 54; // Caption: Start Time;
	string status = 55; // Caption: Status;
	string status_code = 56; // Caption: Status Code;
	string status_detail = 57; // Caption: Status Detail;
	ocsf.v1_4_0.events.network.enums.NETWORK_FILE_ACTIVITY_STATUS_ID status_id = 58; // Caption: Status ID;
	int64 time = 59; // Caption: Event Time;
	int32 timezone_offset = 60; // Caption: Timezone Offset;
	ocsf.v1_4_0.objects.Tls tls = 61; // Caption: TLS;
	ocsf.v1_4_0.objects.NetworkTraffic traffic = 62; // Caption: Traffic;
	string type_name = 63; // Caption: Type Name;
	ocsf.v1_4_0.events.network.enums.NETWORK_FILE_ACTIVITY_TYPE_UID type_uid = 64; // Caption: Type ID;
	google.protobuf.Struct unmapped = 65; // Caption: Unmapped Data;
}

// URL: https://schema.ocsf.io/1.4.0/classes/ntp_activity
// Event: network
// Event UID: 13
message NtpActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NTP_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NTP_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_4_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_4_0.objects.Api api = 6; // Profile: cloud; Caption: API Details;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_4_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® Details; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_4_0.events.network.enums.NTP_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_4_0.events.network.enums.NTP_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_4_0.objects.Cloud cloud = 14; // Caption: Cloud; Profile: cloud;
	string confidence = 15; // Profile: security_control; Caption: Confidence;
	ocsf.v1_4_0.events.network.enums.NTP_ACTIVITY_CONFIDENCE_ID confidence_id = 16; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 17; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkConnectionInfo connection_info = 18; // Caption: Connection Info;
	int32 count = 19; // Caption: Count;
	int32 delay = 20; // Caption: Root Delay;
	ocsf.v1_4_0.objects.Device device = 21; // Caption: Device; Profile: host;
	int32 dispersion = 22; // Caption: Root Dispersion;
	string disposition = 23; // Caption: Disposition; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NTP_ACTIVITY_DISPOSITION_ID disposition_id = 24; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkEndpoint dst_endpoint = 25; // Caption: Destination Endpoint;
	int64 duration = 26; // Caption: Duration Milliseconds;
	int64 end_time = 27; // Caption: End Time;
	repeated ocsf.v1_4_0.objects.Enrichment enrichments = 28; // Caption: Enrichments;
	ocsf.v1_4_0.objects.FirewallRule firewall_rule = 29; // Profile: security_control; Caption: Firewall Rule;
	bool is_alert = 30; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Ja4Fingerprint ja4_fingerprint_list = 31; // Caption: JA4+ Fingerprints;
	ocsf.v1_4_0.objects.LoadBalancer load_balancer = 32; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_4_0.objects.Malware malware = 33; // Caption: Malware; Profile: security_control;
	string message = 34; // Caption: Message;
	ocsf.v1_4_0.objects.Metadata metadata = 35; // Caption: Metadata;
	repeated ocsf.v1_4_0.objects.Observable observables = 36; // Caption: Observables;
	repeated ocsf.v1_4_0.objects.Osint osint = 37; // Caption: OSINT; Profile: osint;
	ocsf.v1_4_0.objects.Policy policy = 38; // Caption: Policy; Profile: security_control;
	int32 precision = 39; // Caption: Precision;
	ocsf.v1_4_0.objects.NetworkProxy proxy = 40; // Caption: Proxy;
	ocsf.v1_4_0.objects.NetworkConnectionInfo proxy_connection_info = 41; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkProxy proxy_endpoint = 42; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpRequest proxy_http_request = 43; // Profile: network_proxy; Caption: Proxy HTTP Request;
	ocsf.v1_4_0.objects.HttpResponse proxy_http_response = 44; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_4_0.objects.Tls proxy_tls = 45; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkTraffic proxy_traffic = 46; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 47; // Caption: Raw Data;
	string risk_details = 48; // Caption: Risk Details; Profile: security_control;
	string risk_level = 49; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.NTP_ACTIVITY_RISK_LEVEL_ID risk_level_id = 50; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 51; // Caption: Risk Score; Profile: security_control;
	string severity = 52; // Caption: Severity;
	ocsf.v1_4_0.events.network.enums.NTP_ACTIVITY_SEVERITY_ID severity_id = 53; // Caption: Severity ID;
	ocsf.v1_4_0.objects.NetworkEndpoint src_endpoint = 54; // Caption: Source Endpoint;
	int64 start_time = 55; // Caption: Start Time;
	string status = 56; // Caption: Status;
	string status_code = 57; // Caption: Status Code;
	string status_detail = 58; // Caption: Status Detail;
	ocsf.v1_4_0.events.network.enums.NTP_ACTIVITY_STATUS_ID status_id = 59; // Caption: Status ID;
	string stratum = 60; // Caption: Stratum;
	ocsf.v1_4_0.events.network.enums.NTP_ACTIVITY_STRATUM_ID stratum_id = 61; // Caption: Stratum ID;
	int64 time = 62; // Caption: Event Time;
	int32 timezone_offset = 63; // Caption: Timezone Offset;
	ocsf.v1_4_0.objects.Tls tls = 64; // Caption: TLS;
	ocsf.v1_4_0.objects.NetworkTraffic traffic = 65; // Caption: Traffic;
	string type_name = 66; // Caption: Type Name;
	ocsf.v1_4_0.events.network.enums.NTP_ACTIVITY_TYPE_UID type_uid = 67; // Caption: Type ID;
	google.protobuf.Struct unmapped = 68; // Caption: Unmapped Data;
	string version = 69; // Caption: Version;
}

// Event: network
// Event UID: 5
// URL: https://schema.ocsf.io/1.4.0/classes/rdp_activity
message RdpActivity {
	string action = 1; // Profile: security_control; Caption: Action;
	ocsf.v1_4_0.events.network.enums.RDP_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.RDP_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_4_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_4_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_4_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® Details; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Authorization authorizations = 9; // Profile: security_control; Caption: Authorization Information;
	repeated string capabilities = 10; // Caption: Capabilities;
	string category_name = 11; // Caption: Category;
	ocsf.v1_4_0.events.network.enums.RDP_ACTIVITY_CATEGORY_UID category_uid = 12; // Caption: Category ID;
	repeated string certificate_chain = 13; // Caption: Certificate Chain;
	string class_name = 14; // Caption: Class;
	ocsf.v1_4_0.events.network.enums.RDP_ACTIVITY_CLASS_UID class_uid = 15; // Caption: Class ID;
	ocsf.v1_4_0.objects.Cloud cloud = 16; // Caption: Cloud; Profile: cloud;
	string confidence = 17; // Caption: Confidence; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.RDP_ACTIVITY_CONFIDENCE_ID confidence_id = 18; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 19; // Profile: security_control; Caption: Confidence Score;
	ocsf.v1_4_0.objects.NetworkConnectionInfo connection_info = 20; // Caption: Connection Info;
	int32 count = 21; // Caption: Count;
	ocsf.v1_4_0.objects.Device device = 22; // Caption: Device;
	string disposition = 23; // Profile: security_control; Caption: Disposition;
	ocsf.v1_4_0.events.network.enums.RDP_ACTIVITY_DISPOSITION_ID disposition_id = 24; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkEndpoint dst_endpoint = 25; // Caption: Destination Endpoint;
	int64 duration = 26; // Caption: Duration Milliseconds;
	int64 end_time = 27; // Caption: End Time;
	repeated ocsf.v1_4_0.objects.Enrichment enrichments = 28; // Caption: Enrichments;
	ocsf.v1_4_0.objects.File file = 29; // Caption: File;
	ocsf.v1_4_0.objects.FirewallRule firewall_rule = 30; // Caption: Firewall Rule; Profile: security_control;
	string identifier_cookie = 31; // Caption: Identifier Cookie;
	bool is_alert = 32; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Ja4Fingerprint ja4_fingerprint_list = 33; // Caption: JA4+ Fingerprints;
	ocsf.v1_4_0.objects.KeyboardInfo keyboard_info = 34; // Caption: Keyboard Information;
	ocsf.v1_4_0.objects.LoadBalancer load_balancer = 35; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_4_0.objects.Malware malware = 36; // Profile: security_control; Caption: Malware;
	string message = 37; // Caption: Message;
	ocsf.v1_4_0.objects.Metadata metadata = 38; // Caption: Metadata;
	repeated ocsf.v1_4_0.objects.Observable observables = 39; // Caption: Observables;
	repeated ocsf.v1_4_0.objects.Osint osint = 40; // Caption: OSINT; Profile: osint;
	ocsf.v1_4_0.objects.Policy policy = 41; // Caption: Policy; Profile: security_control;
	string protocol_ver = 42; // Caption: Protocol Version;
	ocsf.v1_4_0.objects.NetworkProxy proxy = 43; // Caption: Proxy;
	ocsf.v1_4_0.objects.NetworkConnectionInfo proxy_connection_info = 44; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkProxy proxy_endpoint = 45; // Profile: network_proxy; Caption: Proxy Endpoint;
	ocsf.v1_4_0.objects.HttpRequest proxy_http_request = 46; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpResponse proxy_http_response = 47; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_4_0.objects.Tls proxy_tls = 48; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkTraffic proxy_traffic = 49; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 50; // Caption: Raw Data;
	ocsf.v1_4_0.objects.Display remote_display = 51; // Caption: Remote Display;
	ocsf.v1_4_0.objects.Request request = 52; // Caption: API Request Details;
	ocsf.v1_4_0.objects.Response response = 53; // Caption: API Response Details;
	string risk_details = 54; // Caption: Risk Details; Profile: security_control;
	string risk_level = 55; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.RDP_ACTIVITY_RISK_LEVEL_ID risk_level_id = 56; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 57; // Caption: Risk Score; Profile: security_control;
	string severity = 58; // Caption: Severity;
	ocsf.v1_4_0.events.network.enums.RDP_ACTIVITY_SEVERITY_ID severity_id = 59; // Caption: Severity ID;
	ocsf.v1_4_0.objects.NetworkEndpoint src_endpoint = 60; // Caption: Source Endpoint;
	int64 start_time = 61; // Caption: Start Time;
	string status = 62; // Caption: Status;
	string status_code = 63; // Caption: Status Code;
	string status_detail = 64; // Caption: Status Detail;
	ocsf.v1_4_0.events.network.enums.RDP_ACTIVITY_STATUS_ID status_id = 65; // Caption: Status ID;
	int64 time = 66; // Caption: Event Time;
	int32 timezone_offset = 67; // Caption: Timezone Offset;
	ocsf.v1_4_0.objects.Tls tls = 68; // Caption: TLS;
	ocsf.v1_4_0.objects.NetworkTraffic traffic = 69; // Caption: Traffic;
	string type_name = 70; // Caption: Type Name;
	ocsf.v1_4_0.events.network.enums.RDP_ACTIVITY_TYPE_UID type_uid = 71; // Caption: Type ID;
	google.protobuf.Struct unmapped = 72; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 6
// URL: https://schema.ocsf.io/1.4.0/classes/smb_activity
message SmbActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.SMB_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.SMB_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_4_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_4_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_4_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® Details; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_4_0.events.network.enums.SMB_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_4_0.events.network.enums.SMB_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	repeated string client_dialects = 14; // Caption: Client Dialects;
	ocsf.v1_4_0.objects.Cloud cloud = 15; // Caption: Cloud; Profile: cloud;
	string command = 16; // Caption: Command;
	string confidence = 17; // Caption: Confidence; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.SMB_ACTIVITY_CONFIDENCE_ID confidence_id = 18; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 19; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkConnectionInfo connection_info = 20; // Caption: Connection Info;
	int32 count = 21; // Caption: Count;
	ocsf.v1_4_0.objects.DceRpc dce_rpc = 22; // Caption: Distributed Computing Environment/Remote Procedure Call (DCE/RPC);
	ocsf.v1_4_0.objects.Device device = 23; // Caption: Device; Profile: host;
	string dialect = 24; // Caption: Dialect;
	string disposition = 25; // Profile: security_control; Caption: Disposition;
	ocsf.v1_4_0.events.network.enums.SMB_ACTIVITY_DISPOSITION_ID disposition_id = 26; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkEndpoint dst_endpoint = 27; // Caption: Destination Endpoint;
	int64 duration = 28; // Caption: Duration Milliseconds;
	int64 end_time = 29; // Caption: End Time;
	repeated ocsf.v1_4_0.objects.Enrichment enrichments = 30; // Caption: Enrichments;
	ocsf.v1_4_0.objects.File file = 31; // Caption: File;
	ocsf.v1_4_0.objects.FirewallRule firewall_rule = 32; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 33; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Ja4Fingerprint ja4_fingerprint_list = 34; // Caption: JA4+ Fingerprints;
	ocsf.v1_4_0.objects.LoadBalancer load_balancer = 35; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_4_0.objects.Malware malware = 36; // Caption: Malware; Profile: security_control;
	string message = 37; // Caption: Message;
	ocsf.v1_4_0.objects.Metadata metadata = 38; // Caption: Metadata;
	repeated ocsf.v1_4_0.objects.Observable observables = 39; // Caption: Observables;
	string open_type = 40; // Caption: Open Type;
	repeated ocsf.v1_4_0.objects.Osint osint = 41; // Caption: OSINT; Profile: osint;
	ocsf.v1_4_0.objects.Policy policy = 42; // Caption: Policy; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkProxy proxy = 43; // Caption: Proxy;
	ocsf.v1_4_0.objects.NetworkConnectionInfo proxy_connection_info = 44; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkProxy proxy_endpoint = 45; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpRequest proxy_http_request = 46; // Profile: network_proxy; Caption: Proxy HTTP Request;
	ocsf.v1_4_0.objects.HttpResponse proxy_http_response = 47; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_4_0.objects.Tls proxy_tls = 48; // Profile: network_proxy; Caption: Proxy TLS;
	ocsf.v1_4_0.objects.NetworkTraffic proxy_traffic = 49; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 50; // Caption: Raw Data;
	ocsf.v1_4_0.objects.Response response = 51; // Caption: API Response Details;
	string risk_details = 52; // Caption: Risk Details; Profile: security_control;
	string risk_level = 53; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.SMB_ACTIVITY_RISK_LEVEL_ID risk_level_id = 54; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 55; // Caption: Risk Score; Profile: security_control;
	string severity = 56; // Caption: Severity;
	ocsf.v1_4_0.events.network.enums.SMB_ACTIVITY_SEVERITY_ID severity_id = 57; // Caption: Severity ID;
	string share = 58; // Caption: Share;
	string share_type = 59; // Caption: Share Type;
	ocsf.v1_4_0.events.network.enums.SMB_ACTIVITY_SHARE_TYPE_ID share_type_id = 60; // Caption: Share Type ID;
	ocsf.v1_4_0.objects.NetworkEndpoint src_endpoint = 61; // Caption: Source Endpoint;
	int64 start_time = 62; // Caption: Start Time;
	string status = 63; // Caption: Status;
	string status_code = 64; // Caption: Status Code;
	string status_detail = 65; // Caption: Status Detail;
	ocsf.v1_4_0.events.network.enums.SMB_ACTIVITY_STATUS_ID status_id = 66; // Caption: Status ID;
	int64 time = 67; // Caption: Event Time;
	int32 timezone_offset = 68; // Caption: Timezone Offset;
	ocsf.v1_4_0.objects.Tls tls = 69; // Caption: TLS;
	ocsf.v1_4_0.objects.NetworkTraffic traffic = 70; // Caption: Traffic;
	string tree_uid = 71; // Caption: Tree UID;
	string type_name = 72; // Caption: Type Name;
	ocsf.v1_4_0.events.network.enums.SMB_ACTIVITY_TYPE_UID type_uid = 73; // Caption: Type ID;
	google.protobuf.Struct unmapped = 74; // Caption: Unmapped Data;
}

// Event: network
// Event UID: 7
// URL: https://schema.ocsf.io/1.4.0/classes/ssh_activity
message SshActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.SSH_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.SSH_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_4_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_4_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_4_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® Details; Profile: security_control;
	string auth_type = 9; // Caption: Authentication Type;
	ocsf.v1_4_0.events.network.enums.SSH_ACTIVITY_AUTH_TYPE_ID auth_type_id = 10; // Caption: Authentication Type ID;
	repeated ocsf.v1_4_0.objects.Authorization authorizations = 11; // Caption: Authorization Information; Profile: security_control;
	string category_name = 12; // Caption: Category;
	ocsf.v1_4_0.events.network.enums.SSH_ACTIVITY_CATEGORY_UID category_uid = 13; // Caption: Category ID;
	string class_name = 14; // Caption: Class;
	ocsf.v1_4_0.events.network.enums.SSH_ACTIVITY_CLASS_UID class_uid = 15; // Caption: Class ID;
	ocsf.v1_4_0.objects.Hassh client_hassh = 16; // Caption: Client HASSH;
	ocsf.v1_4_0.objects.Cloud cloud = 17; // Caption: Cloud; Profile: cloud;
	string confidence = 18; // Caption: Confidence; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.SSH_ACTIVITY_CONFIDENCE_ID confidence_id = 19; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 20; // Caption: Confidence Score; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkConnectionInfo connection_info = 21; // Caption: Connection Info;
	int32 count = 22; // Caption: Count;
	ocsf.v1_4_0.objects.Device device = 23; // Caption: Device; Profile: host;
	string disposition = 24; // Caption: Disposition; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.SSH_ACTIVITY_DISPOSITION_ID disposition_id = 25; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkEndpoint dst_endpoint = 26; // Caption: Destination Endpoint;
	int64 duration = 27; // Caption: Duration Milliseconds;
	int64 end_time = 28; // Caption: End Time;
	repeated ocsf.v1_4_0.objects.Enrichment enrichments = 29; // Caption: Enrichments;
	ocsf.v1_4_0.objects.File file = 30; // Caption: File;
	ocsf.v1_4_0.objects.FirewallRule firewall_rule = 31; // Profile: security_control; Caption: Firewall Rule;
	bool is_alert = 32; // Caption: Alert; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Ja4Fingerprint ja4_fingerprint_list = 33; // Caption: JA4+ Fingerprints;
	ocsf.v1_4_0.objects.LoadBalancer load_balancer = 34; // Caption: Load Balancer; Profile: load_balancer;
	repeated ocsf.v1_4_0.objects.Malware malware = 35; // Caption: Malware; Profile: security_control;
	string message = 36; // Caption: Message;
	ocsf.v1_4_0.objects.Metadata metadata = 37; // Caption: Metadata;
	repeated ocsf.v1_4_0.objects.Observable observables = 38; // Caption: Observables;
	repeated ocsf.v1_4_0.objects.Osint osint = 39; // Caption: OSINT; Profile: osint;
	ocsf.v1_4_0.objects.Policy policy = 40; // Caption: Policy; Profile: security_control;
	string protocol_ver = 41; // Caption: Protocol Version;
	ocsf.v1_4_0.objects.NetworkProxy proxy = 42; // Caption: Proxy;
	ocsf.v1_4_0.objects.NetworkConnectionInfo proxy_connection_info = 43; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkProxy proxy_endpoint = 44; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpRequest proxy_http_request = 45; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpResponse proxy_http_response = 46; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_4_0.objects.Tls proxy_tls = 47; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkTraffic proxy_traffic = 48; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 49; // Caption: Raw Data;
	string risk_details = 50; // Caption: Risk Details; Profile: security_control;
	string risk_level = 51; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.SSH_ACTIVITY_RISK_LEVEL_ID risk_level_id = 52; // Profile: security_control; Caption: Risk Level ID;
	int32 risk_score = 53; // Profile: security_control; Caption: Risk Score;
	ocsf.v1_4_0.objects.Hassh server_hassh = 54; // Caption: Server HASSH;
	string severity = 55; // Caption: Severity;
	ocsf.v1_4_0.events.network.enums.SSH_ACTIVITY_SEVERITY_ID severity_id = 56; // Caption: Severity ID;
	ocsf.v1_4_0.objects.NetworkEndpoint src_endpoint = 57; // Caption: Source Endpoint;
	int64 start_time = 58; // Caption: Start Time;
	string status = 59; // Caption: Status;
	string status_code = 60; // Caption: Status Code;
	string status_detail = 61; // Caption: Status Detail;
	ocsf.v1_4_0.events.network.enums.SSH_ACTIVITY_STATUS_ID status_id = 62; // Caption: Status ID;
	int64 time = 63; // Caption: Event Time;
	int32 timezone_offset = 64; // Caption: Timezone Offset;
	ocsf.v1_4_0.objects.Tls tls = 65; // Caption: TLS;
	ocsf.v1_4_0.objects.NetworkTraffic traffic = 66; // Caption: Traffic;
	string type_name = 67; // Caption: Type Name;
	ocsf.v1_4_0.events.network.enums.SSH_ACTIVITY_TYPE_UID type_uid = 68; // Caption: Type ID;
	google.protobuf.Struct unmapped = 69; // Caption: Unmapped Data;
}

// URL: https://schema.ocsf.io/1.4.0/classes/tunnel_activity
// Event: network
// Event UID: 14
message TunnelActivity {
	string action = 1; // Caption: Action; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.TUNNEL_ACTIVITY_ACTION_ID action_id = 2; // Caption: Action ID; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.TUNNEL_ACTIVITY_ACTIVITY_ID activity_id = 3; // Caption: Activity ID;
	string activity_name = 4; // Caption: Activity;
	ocsf.v1_4_0.objects.Actor actor = 5; // Caption: Actor; Profile: host;
	ocsf.v1_4_0.objects.Api api = 6; // Caption: API Details; Profile: cloud;
	string app_name = 7; // Caption: Application Name;
	repeated ocsf.v1_4_0.objects.Attack attacks = 8; // Caption: MITRE ATT&CK® Details; Profile: security_control;
	repeated ocsf.v1_4_0.objects.Authorization authorizations = 9; // Caption: Authorization Information; Profile: security_control;
	string category_name = 10; // Caption: Category;
	ocsf.v1_4_0.events.network.enums.TUNNEL_ACTIVITY_CATEGORY_UID category_uid = 11; // Caption: Category ID;
	string class_name = 12; // Caption: Class;
	ocsf.v1_4_0.events.network.enums.TUNNEL_ACTIVITY_CLASS_UID class_uid = 13; // Caption: Class ID;
	ocsf.v1_4_0.objects.Cloud cloud = 14; // Caption: Cloud; Profile: cloud;
	string confidence = 15; // Caption: Confidence; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.TUNNEL_ACTIVITY_CONFIDENCE_ID confidence_id = 16; // Caption: Confidence ID; Profile: security_control;
	int32 confidence_score = 17; // Profile: security_control; Caption: Confidence Score;
	ocsf.v1_4_0.objects.NetworkConnectionInfo connection_info = 18; // Caption: Connection Info;
	int32 count = 19; // Caption: Count;
	ocsf.v1_4_0.objects.Device device = 20; // Caption: Device;
	string disposition = 21; // Caption: Disposition; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.TUNNEL_ACTIVITY_DISPOSITION_ID disposition_id = 22; // Caption: Disposition ID; Profile: security_control;
	ocsf.v1_4_0.objects.NetworkEndpoint dst_endpoint = 23; // Caption: Destination Endpoint;
	int64 duration = 24; // Caption: Duration Milliseconds;
	int64 end_time = 25; // Caption: End Time;
	repeated ocsf.v1_4_0.objects.Enrichment enrichments = 26; // Caption: Enrichments;
	ocsf.v1_4_0.objects.FirewallRule firewall_rule = 27; // Caption: Firewall Rule; Profile: security_control;
	bool is_alert = 28; // Profile: security_control; Caption: Alert;
	repeated ocsf.v1_4_0.objects.Ja4Fingerprint ja4_fingerprint_list = 29; // Caption: JA4+ Fingerprints;
	ocsf.v1_4_0.objects.LoadBalancer load_balancer = 30; // Profile: load_balancer; Caption: Load Balancer;
	repeated ocsf.v1_4_0.objects.Malware malware = 31; // Caption: Malware; Profile: security_control;
	string message = 32; // Caption: Message;
	ocsf.v1_4_0.objects.Metadata metadata = 33; // Caption: Metadata;
	repeated ocsf.v1_4_0.objects.Observable observables = 34; // Caption: Observables;
	repeated ocsf.v1_4_0.objects.Osint osint = 35; // Caption: OSINT; Profile: osint;
	ocsf.v1_4_0.objects.Policy policy = 36; // Caption: Policy; Profile: security_control;
	string protocol_name = 37; // Caption: Protocol Name;
	ocsf.v1_4_0.objects.NetworkProxy proxy = 38; // Caption: Proxy;
	ocsf.v1_4_0.objects.NetworkConnectionInfo proxy_connection_info = 39; // Caption: Proxy Connection Info; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkProxy proxy_endpoint = 40; // Caption: Proxy Endpoint; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpRequest proxy_http_request = 41; // Caption: Proxy HTTP Request; Profile: network_proxy;
	ocsf.v1_4_0.objects.HttpResponse proxy_http_response = 42; // Caption: Proxy HTTP Response; Profile: network_proxy;
	ocsf.v1_4_0.objects.Tls proxy_tls = 43; // Caption: Proxy TLS; Profile: network_proxy;
	ocsf.v1_4_0.objects.NetworkTraffic proxy_traffic = 44; // Caption: Proxy Traffic; Profile: network_proxy;
	string raw_data = 45; // Caption: Raw Data;
	string risk_details = 46; // Caption: Risk Details; Profile: security_control;
	string risk_level = 47; // Caption: Risk Level; Profile: security_control;
	ocsf.v1_4_0.events.network.enums.TUNNEL_ACTIVITY_RISK_LEVEL_ID risk_level_id = 48; // Caption: Risk Level ID; Profile: security_control;
	int32 risk_score = 49; // Caption: Risk Score; Profile: security_control;
	ocsf.v1_4_0.objects.Session session = 50; // Caption: Session;
	string severity = 51; // Caption: Severity;
	ocsf.v1_4_0.events.network.enums.TUNNEL_ACTIVITY_SEVERITY_ID severity_id = 52; // Caption: Severity ID;
	ocsf.v1_4_0.objects.NetworkEndpoint src_endpoint = 53; // Caption: Source Endpoint;
	int64 start_time = 54; // Caption: Start Time;
	string status = 55; // Caption: Status;
	string status_code = 56; // Caption: Status Code;
	string status_detail = 57; // Caption: Status Detail;
	ocsf.v1_4_0.events.network.enums.TUNNEL_ACTIVITY_STATUS_ID status_id = 58; // Caption: Status ID;
	int64 time = 59; // Caption: Event Time;
	int32 timezone_offset = 60; // Caption: Timezone Offset;
	ocsf.v1_4_0.objects.Tls tls = 61; // Caption: TLS;
	ocsf.v1_4_0.objects.NetworkTraffic traffic = 62; // Caption: Traffic;
	ocsf.v1_4_0.objects.NetworkInterface tunnel_interface = 63; // Caption: Interface;
	string tunnel_type = 64; // Caption: Type;
	ocsf.v1_4_0.events.network.enums.TUNNEL_ACTIVITY_TUNNEL_TYPE_ID tunnel_type_id = 65; // Caption: Type;
	string type_name = 66; // Caption: Type Name;
	ocsf.v1_4_0.events.network.enums.TUNNEL_ACTIVITY_TYPE_UID type_uid = 67; // Caption: Type ID;
	google.protobuf.Struct unmapped = 68; // Caption: Unmapped Data;
	ocsf.v1_4_0.objects.User user = 69; // Caption: User;
}