// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: ocsf/v1_2_0/events/other/enums/enums.proto

//go:build !protoopaque

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BASE_EVENT_ACTIVITY_ID int32

const (
	BASE_EVENT_ACTIVITY_ID_BASE_EVENT_ACTIVITY_ID_UNKNOWN BASE_EVENT_ACTIVITY_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	BASE_EVENT_ACTIVITY_ID_BASE_EVENT_ACTIVITY_ID_OTHER   BASE_EVENT_ACTIVITY_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for BASE_EVENT_ACTIVITY_ID.
var (
	BASE_EVENT_ACTIVITY_ID_name = map[int32]string{
		0:  "BASE_EVENT_ACTIVITY_ID_UNKNOWN",
		99: "BASE_EVENT_ACTIVITY_ID_OTHER",
	}
	BASE_EVENT_ACTIVITY_ID_value = map[string]int32{
		"BASE_EVENT_ACTIVITY_ID_UNKNOWN": 0,
		"BASE_EVENT_ACTIVITY_ID_OTHER":   99,
	}
)

func (x BASE_EVENT_ACTIVITY_ID) Enum() *BASE_EVENT_ACTIVITY_ID {
	p := new(BASE_EVENT_ACTIVITY_ID)
	*p = x
	return p
}

func (x BASE_EVENT_ACTIVITY_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BASE_EVENT_ACTIVITY_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_2_0_events_other_enums_enums_proto_enumTypes[0].Descriptor()
}

func (BASE_EVENT_ACTIVITY_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_2_0_events_other_enums_enums_proto_enumTypes[0]
}

func (x BASE_EVENT_ACTIVITY_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type BASE_EVENT_CATEGORY_UID int32

const (
	BASE_EVENT_CATEGORY_UID_BASE_EVENT_CATEGORY_UID_UNCATEGORIZED BASE_EVENT_CATEGORY_UID = 0 // Type: OCSF_VALUE; EnumValue: 0;
)

// Enum value maps for BASE_EVENT_CATEGORY_UID.
var (
	BASE_EVENT_CATEGORY_UID_name = map[int32]string{
		0: "BASE_EVENT_CATEGORY_UID_UNCATEGORIZED",
	}
	BASE_EVENT_CATEGORY_UID_value = map[string]int32{
		"BASE_EVENT_CATEGORY_UID_UNCATEGORIZED": 0,
	}
)

func (x BASE_EVENT_CATEGORY_UID) Enum() *BASE_EVENT_CATEGORY_UID {
	p := new(BASE_EVENT_CATEGORY_UID)
	*p = x
	return p
}

func (x BASE_EVENT_CATEGORY_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BASE_EVENT_CATEGORY_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_2_0_events_other_enums_enums_proto_enumTypes[1].Descriptor()
}

func (BASE_EVENT_CATEGORY_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_2_0_events_other_enums_enums_proto_enumTypes[1]
}

func (x BASE_EVENT_CATEGORY_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type BASE_EVENT_CLASS_UID int32

const (
	BASE_EVENT_CLASS_UID_BASE_EVENT_CLASS_UID_BASE_EVENT BASE_EVENT_CLASS_UID = 0 // Type: OCSF_VALUE; EnumValue: 0;
)

// Enum value maps for BASE_EVENT_CLASS_UID.
var (
	BASE_EVENT_CLASS_UID_name = map[int32]string{
		0: "BASE_EVENT_CLASS_UID_BASE_EVENT",
	}
	BASE_EVENT_CLASS_UID_value = map[string]int32{
		"BASE_EVENT_CLASS_UID_BASE_EVENT": 0,
	}
)

func (x BASE_EVENT_CLASS_UID) Enum() *BASE_EVENT_CLASS_UID {
	p := new(BASE_EVENT_CLASS_UID)
	*p = x
	return p
}

func (x BASE_EVENT_CLASS_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BASE_EVENT_CLASS_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_2_0_events_other_enums_enums_proto_enumTypes[2].Descriptor()
}

func (BASE_EVENT_CLASS_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_2_0_events_other_enums_enums_proto_enumTypes[2]
}

func (x BASE_EVENT_CLASS_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type BASE_EVENT_SEVERITY_ID int32

const (
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_UNKNOWN       BASE_EVENT_SEVERITY_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_INFORMATIONAL BASE_EVENT_SEVERITY_ID = 1  // EnumValue: 1; Type: OCSF_VALUE;
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_LOW           BASE_EVENT_SEVERITY_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_MEDIUM        BASE_EVENT_SEVERITY_ID = 3  // Type: OCSF_VALUE; EnumValue: 3;
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_HIGH          BASE_EVENT_SEVERITY_ID = 4  // Type: OCSF_VALUE; EnumValue: 4;
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_CRITICAL      BASE_EVENT_SEVERITY_ID = 5  // Type: OCSF_VALUE; EnumValue: 5;
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_FATAL         BASE_EVENT_SEVERITY_ID = 6  // Type: OCSF_VALUE; EnumValue: 6;
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_OTHER         BASE_EVENT_SEVERITY_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for BASE_EVENT_SEVERITY_ID.
var (
	BASE_EVENT_SEVERITY_ID_name = map[int32]string{
		0:  "BASE_EVENT_SEVERITY_ID_UNKNOWN",
		1:  "BASE_EVENT_SEVERITY_ID_INFORMATIONAL",
		2:  "BASE_EVENT_SEVERITY_ID_LOW",
		3:  "BASE_EVENT_SEVERITY_ID_MEDIUM",
		4:  "BASE_EVENT_SEVERITY_ID_HIGH",
		5:  "BASE_EVENT_SEVERITY_ID_CRITICAL",
		6:  "BASE_EVENT_SEVERITY_ID_FATAL",
		99: "BASE_EVENT_SEVERITY_ID_OTHER",
	}
	BASE_EVENT_SEVERITY_ID_value = map[string]int32{
		"BASE_EVENT_SEVERITY_ID_UNKNOWN":       0,
		"BASE_EVENT_SEVERITY_ID_INFORMATIONAL": 1,
		"BASE_EVENT_SEVERITY_ID_LOW":           2,
		"BASE_EVENT_SEVERITY_ID_MEDIUM":        3,
		"BASE_EVENT_SEVERITY_ID_HIGH":          4,
		"BASE_EVENT_SEVERITY_ID_CRITICAL":      5,
		"BASE_EVENT_SEVERITY_ID_FATAL":         6,
		"BASE_EVENT_SEVERITY_ID_OTHER":         99,
	}
)

func (x BASE_EVENT_SEVERITY_ID) Enum() *BASE_EVENT_SEVERITY_ID {
	p := new(BASE_EVENT_SEVERITY_ID)
	*p = x
	return p
}

func (x BASE_EVENT_SEVERITY_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BASE_EVENT_SEVERITY_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_2_0_events_other_enums_enums_proto_enumTypes[3].Descriptor()
}

func (BASE_EVENT_SEVERITY_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_2_0_events_other_enums_enums_proto_enumTypes[3]
}

func (x BASE_EVENT_SEVERITY_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type BASE_EVENT_STATUS_ID int32

const (
	BASE_EVENT_STATUS_ID_BASE_EVENT_STATUS_ID_UNKNOWN BASE_EVENT_STATUS_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	BASE_EVENT_STATUS_ID_BASE_EVENT_STATUS_ID_SUCCESS BASE_EVENT_STATUS_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	BASE_EVENT_STATUS_ID_BASE_EVENT_STATUS_ID_FAILURE BASE_EVENT_STATUS_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	BASE_EVENT_STATUS_ID_BASE_EVENT_STATUS_ID_OTHER   BASE_EVENT_STATUS_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for BASE_EVENT_STATUS_ID.
var (
	BASE_EVENT_STATUS_ID_name = map[int32]string{
		0:  "BASE_EVENT_STATUS_ID_UNKNOWN",
		1:  "BASE_EVENT_STATUS_ID_SUCCESS",
		2:  "BASE_EVENT_STATUS_ID_FAILURE",
		99: "BASE_EVENT_STATUS_ID_OTHER",
	}
	BASE_EVENT_STATUS_ID_value = map[string]int32{
		"BASE_EVENT_STATUS_ID_UNKNOWN": 0,
		"BASE_EVENT_STATUS_ID_SUCCESS": 1,
		"BASE_EVENT_STATUS_ID_FAILURE": 2,
		"BASE_EVENT_STATUS_ID_OTHER":   99,
	}
)

func (x BASE_EVENT_STATUS_ID) Enum() *BASE_EVENT_STATUS_ID {
	p := new(BASE_EVENT_STATUS_ID)
	*p = x
	return p
}

func (x BASE_EVENT_STATUS_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BASE_EVENT_STATUS_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_2_0_events_other_enums_enums_proto_enumTypes[4].Descriptor()
}

func (BASE_EVENT_STATUS_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_2_0_events_other_enums_enums_proto_enumTypes[4]
}

func (x BASE_EVENT_STATUS_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_ocsf_v1_2_0_events_other_enums_enums_proto protoreflect.FileDescriptor

const file_ocsf_v1_2_0_events_other_enums_enums_proto_rawDesc = "" +
	"\n" +
	"*ocsf/v1_2_0/events/other/enums/enums.proto\x12\x1eocsf.v1_2_0.events.other.enums*^\n" +
	"\x16BASE_EVENT_ACTIVITY_ID\x12\"\n" +
	"\x1eBASE_EVENT_ACTIVITY_ID_UNKNOWN\x10\x00\x12 \n" +
	"\x1cBASE_EVENT_ACTIVITY_ID_OTHER\x10c*D\n" +
	"\x17BASE_EVENT_CATEGORY_UID\x12)\n" +
	"%BASE_EVENT_CATEGORY_UID_UNCATEGORIZED\x10\x00*;\n" +
	"\x14BASE_EVENT_CLASS_UID\x12#\n" +
	"\x1fBASE_EVENT_CLASS_UID_BASE_EVENT\x10\x00*\xb3\x02\n" +
	"\x16BASE_EVENT_SEVERITY_ID\x12\"\n" +
	"\x1eBASE_EVENT_SEVERITY_ID_UNKNOWN\x10\x00\x12(\n" +
	"$BASE_EVENT_SEVERITY_ID_INFORMATIONAL\x10\x01\x12\x1e\n" +
	"\x1aBASE_EVENT_SEVERITY_ID_LOW\x10\x02\x12!\n" +
	"\x1dBASE_EVENT_SEVERITY_ID_MEDIUM\x10\x03\x12\x1f\n" +
	"\x1bBASE_EVENT_SEVERITY_ID_HIGH\x10\x04\x12#\n" +
	"\x1fBASE_EVENT_SEVERITY_ID_CRITICAL\x10\x05\x12 \n" +
	"\x1cBASE_EVENT_SEVERITY_ID_FATAL\x10\x06\x12 \n" +
	"\x1cBASE_EVENT_SEVERITY_ID_OTHER\x10c*\x9c\x01\n" +
	"\x14BASE_EVENT_STATUS_ID\x12 \n" +
	"\x1cBASE_EVENT_STATUS_ID_UNKNOWN\x10\x00\x12 \n" +
	"\x1cBASE_EVENT_STATUS_ID_SUCCESS\x10\x01\x12 \n" +
	"\x1cBASE_EVENT_STATUS_ID_FAILURE\x10\x02\x12\x1e\n" +
	"\x1aBASE_EVENT_STATUS_ID_OTHER\x10cB\x8d\x02\n" +
	"\"com.ocsf.v1_2_0.events.other.enumsB\n" +
	"EnumsProtoP\x01ZEgithub.com/valllabh/ocsf-schema-golang/ocsf/v1_2_0/events/other/enums\xa2\x02\x05OVEOE\xaa\x02\x1cOcsf.V120.Events.Other.Enums\xca\x02\x1cOcsf\\V120\\Events\\Other\\Enums\xe2\x02(Ocsf\\V120\\Events\\Other\\Enums\\GPBMetadata\xea\x02 Ocsf::V120::Events::Other::Enumsb\x06proto3"

var file_ocsf_v1_2_0_events_other_enums_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_ocsf_v1_2_0_events_other_enums_enums_proto_goTypes = []any{
	(BASE_EVENT_ACTIVITY_ID)(0),  // 0: ocsf.v1_2_0.events.other.enums.BASE_EVENT_ACTIVITY_ID
	(BASE_EVENT_CATEGORY_UID)(0), // 1: ocsf.v1_2_0.events.other.enums.BASE_EVENT_CATEGORY_UID
	(BASE_EVENT_CLASS_UID)(0),    // 2: ocsf.v1_2_0.events.other.enums.BASE_EVENT_CLASS_UID
	(BASE_EVENT_SEVERITY_ID)(0),  // 3: ocsf.v1_2_0.events.other.enums.BASE_EVENT_SEVERITY_ID
	(BASE_EVENT_STATUS_ID)(0),    // 4: ocsf.v1_2_0.events.other.enums.BASE_EVENT_STATUS_ID
}
var file_ocsf_v1_2_0_events_other_enums_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ocsf_v1_2_0_events_other_enums_enums_proto_init() }
func file_ocsf_v1_2_0_events_other_enums_enums_proto_init() {
	if File_ocsf_v1_2_0_events_other_enums_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocsf_v1_2_0_events_other_enums_enums_proto_rawDesc), len(file_ocsf_v1_2_0_events_other_enums_enums_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocsf_v1_2_0_events_other_enums_enums_proto_goTypes,
		DependencyIndexes: file_ocsf_v1_2_0_events_other_enums_enums_proto_depIdxs,
		EnumInfos:         file_ocsf_v1_2_0_events_other_enums_enums_proto_enumTypes,
	}.Build()
	File_ocsf_v1_2_0_events_other_enums_enums_proto = out.File
	file_ocsf_v1_2_0_events_other_enums_enums_proto_goTypes = nil
	file_ocsf_v1_2_0_events_other_enums_enums_proto_depIdxs = nil
}
