// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: ocsf/v1_4_0/events/other/other.proto

//go:build protoopaque

package other

import (
	enums "github.com/valllabh/ocsf-schema-golang/ocsf/v1_4_0/events/other/enums"
	objects "github.com/valllabh/ocsf-schema-golang/ocsf/v1_4_0/objects"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event UID: 0
// URL: https://schema.ocsf.io/1.4.0/classes/base_event
// Event: other
type BaseEvent struct {
	state                      protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_Action          string                          `protobuf:"bytes,1,opt,name=action,proto3"`
	xxx_hidden_ActionId        enums.BASE_EVENT_ACTION_ID      `protobuf:"varint,2,opt,name=action_id,json=actionId,proto3,enum=ocsf.v1_4_0.events.other.enums.BASE_EVENT_ACTION_ID"`
	xxx_hidden_ActivityId      enums.BASE_EVENT_ACTIVITY_ID    `protobuf:"varint,3,opt,name=activity_id,json=activityId,proto3,enum=ocsf.v1_4_0.events.other.enums.BASE_EVENT_ACTIVITY_ID"`
	xxx_hidden_ActivityName    string                          `protobuf:"bytes,4,opt,name=activity_name,json=activityName,proto3"`
	xxx_hidden_Actor           *objects.Actor                  `protobuf:"bytes,5,opt,name=actor,proto3"`
	xxx_hidden_Api             *objects.Api                    `protobuf:"bytes,6,opt,name=api,proto3"`
	xxx_hidden_Attacks         *[]*objects.Attack              `protobuf:"bytes,7,rep,name=attacks,proto3"`
	xxx_hidden_Authorizations  *[]*objects.Authorization       `protobuf:"bytes,8,rep,name=authorizations,proto3"`
	xxx_hidden_CategoryName    string                          `protobuf:"bytes,9,opt,name=category_name,json=categoryName,proto3"`
	xxx_hidden_CategoryUid     enums.BASE_EVENT_CATEGORY_UID   `protobuf:"varint,10,opt,name=category_uid,json=categoryUid,proto3,enum=ocsf.v1_4_0.events.other.enums.BASE_EVENT_CATEGORY_UID"`
	xxx_hidden_ClassName       string                          `protobuf:"bytes,11,opt,name=class_name,json=className,proto3"`
	xxx_hidden_ClassUid        enums.BASE_EVENT_CLASS_UID      `protobuf:"varint,12,opt,name=class_uid,json=classUid,proto3,enum=ocsf.v1_4_0.events.other.enums.BASE_EVENT_CLASS_UID"`
	xxx_hidden_Cloud           *objects.Cloud                  `protobuf:"bytes,13,opt,name=cloud,proto3"`
	xxx_hidden_Confidence      string                          `protobuf:"bytes,14,opt,name=confidence,proto3"`
	xxx_hidden_ConfidenceId    enums.BASE_EVENT_CONFIDENCE_ID  `protobuf:"varint,15,opt,name=confidence_id,json=confidenceId,proto3,enum=ocsf.v1_4_0.events.other.enums.BASE_EVENT_CONFIDENCE_ID"`
	xxx_hidden_ConfidenceScore int32                           `protobuf:"varint,16,opt,name=confidence_score,json=confidenceScore,proto3"`
	xxx_hidden_Count           int32                           `protobuf:"varint,17,opt,name=count,proto3"`
	xxx_hidden_Device          *objects.Device                 `protobuf:"bytes,18,opt,name=device,proto3"`
	xxx_hidden_Disposition     string                          `protobuf:"bytes,19,opt,name=disposition,proto3"`
	xxx_hidden_DispositionId   enums.BASE_EVENT_DISPOSITION_ID `protobuf:"varint,20,opt,name=disposition_id,json=dispositionId,proto3,enum=ocsf.v1_4_0.events.other.enums.BASE_EVENT_DISPOSITION_ID"`
	xxx_hidden_Duration        int64                           `protobuf:"varint,21,opt,name=duration,proto3"`
	xxx_hidden_EndTime         int64                           `protobuf:"varint,22,opt,name=end_time,json=endTime,proto3"`
	xxx_hidden_Enrichments     *[]*objects.Enrichment          `protobuf:"bytes,23,rep,name=enrichments,proto3"`
	xxx_hidden_FirewallRule    *objects.FirewallRule           `protobuf:"bytes,24,opt,name=firewall_rule,json=firewallRule,proto3"`
	xxx_hidden_IsAlert         bool                            `protobuf:"varint,25,opt,name=is_alert,json=isAlert,proto3"`
	xxx_hidden_Malware         *[]*objects.Malware             `protobuf:"bytes,26,rep,name=malware,proto3"`
	xxx_hidden_Message         string                          `protobuf:"bytes,27,opt,name=message,proto3"`
	xxx_hidden_Metadata        *objects.Metadata               `protobuf:"bytes,28,opt,name=metadata,proto3"`
	xxx_hidden_Observables     *[]*objects.Observable          `protobuf:"bytes,29,rep,name=observables,proto3"`
	xxx_hidden_Osint           *[]*objects.Osint               `protobuf:"bytes,30,rep,name=osint,proto3"`
	xxx_hidden_Policy          *objects.Policy                 `protobuf:"bytes,31,opt,name=policy,proto3"`
	xxx_hidden_RawData         string                          `protobuf:"bytes,32,opt,name=raw_data,json=rawData,proto3"`
	xxx_hidden_RiskDetails     string                          `protobuf:"bytes,33,opt,name=risk_details,json=riskDetails,proto3"`
	xxx_hidden_RiskLevel       string                          `protobuf:"bytes,34,opt,name=risk_level,json=riskLevel,proto3"`
	xxx_hidden_RiskLevelId     enums.BASE_EVENT_RISK_LEVEL_ID  `protobuf:"varint,35,opt,name=risk_level_id,json=riskLevelId,proto3,enum=ocsf.v1_4_0.events.other.enums.BASE_EVENT_RISK_LEVEL_ID"`
	xxx_hidden_RiskScore       int32                           `protobuf:"varint,36,opt,name=risk_score,json=riskScore,proto3"`
	xxx_hidden_Severity        string                          `protobuf:"bytes,37,opt,name=severity,proto3"`
	xxx_hidden_SeverityId      enums.BASE_EVENT_SEVERITY_ID    `protobuf:"varint,38,opt,name=severity_id,json=severityId,proto3,enum=ocsf.v1_4_0.events.other.enums.BASE_EVENT_SEVERITY_ID"`
	xxx_hidden_StartTime       int64                           `protobuf:"varint,39,opt,name=start_time,json=startTime,proto3"`
	xxx_hidden_Status          string                          `protobuf:"bytes,40,opt,name=status,proto3"`
	xxx_hidden_StatusCode      string                          `protobuf:"bytes,41,opt,name=status_code,json=statusCode,proto3"`
	xxx_hidden_StatusDetail    string                          `protobuf:"bytes,42,opt,name=status_detail,json=statusDetail,proto3"`
	xxx_hidden_StatusId        enums.BASE_EVENT_STATUS_ID      `protobuf:"varint,43,opt,name=status_id,json=statusId,proto3,enum=ocsf.v1_4_0.events.other.enums.BASE_EVENT_STATUS_ID"`
	xxx_hidden_Time            int64                           `protobuf:"varint,44,opt,name=time,proto3"`
	xxx_hidden_TimezoneOffset  int32                           `protobuf:"varint,45,opt,name=timezone_offset,json=timezoneOffset,proto3"`
	xxx_hidden_TypeName        string                          `protobuf:"bytes,46,opt,name=type_name,json=typeName,proto3"`
	xxx_hidden_TypeUid         int64                           `protobuf:"varint,47,opt,name=type_uid,json=typeUid,proto3"`
	xxx_hidden_Unmapped        *structpb.Struct                `protobuf:"bytes,48,opt,name=unmapped,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *BaseEvent) Reset() {
	*x = BaseEvent{}
	mi := &file_ocsf_v1_4_0_events_other_other_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseEvent) ProtoMessage() {}

func (x *BaseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ocsf_v1_4_0_events_other_other_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BaseEvent) GetAction() string {
	if x != nil {
		return x.xxx_hidden_Action
	}
	return ""
}

func (x *BaseEvent) GetActionId() enums.BASE_EVENT_ACTION_ID {
	if x != nil {
		return x.xxx_hidden_ActionId
	}
	return enums.BASE_EVENT_ACTION_ID(0)
}

func (x *BaseEvent) GetActivityId() enums.BASE_EVENT_ACTIVITY_ID {
	if x != nil {
		return x.xxx_hidden_ActivityId
	}
	return enums.BASE_EVENT_ACTIVITY_ID(0)
}

func (x *BaseEvent) GetActivityName() string {
	if x != nil {
		return x.xxx_hidden_ActivityName
	}
	return ""
}

func (x *BaseEvent) GetActor() *objects.Actor {
	if x != nil {
		return x.xxx_hidden_Actor
	}
	return nil
}

func (x *BaseEvent) GetApi() *objects.Api {
	if x != nil {
		return x.xxx_hidden_Api
	}
	return nil
}

func (x *BaseEvent) GetAttacks() []*objects.Attack {
	if x != nil {
		if x.xxx_hidden_Attacks != nil {
			return *x.xxx_hidden_Attacks
		}
	}
	return nil
}

func (x *BaseEvent) GetAuthorizations() []*objects.Authorization {
	if x != nil {
		if x.xxx_hidden_Authorizations != nil {
			return *x.xxx_hidden_Authorizations
		}
	}
	return nil
}

func (x *BaseEvent) GetCategoryName() string {
	if x != nil {
		return x.xxx_hidden_CategoryName
	}
	return ""
}

func (x *BaseEvent) GetCategoryUid() enums.BASE_EVENT_CATEGORY_UID {
	if x != nil {
		return x.xxx_hidden_CategoryUid
	}
	return enums.BASE_EVENT_CATEGORY_UID(0)
}

func (x *BaseEvent) GetClassName() string {
	if x != nil {
		return x.xxx_hidden_ClassName
	}
	return ""
}

func (x *BaseEvent) GetClassUid() enums.BASE_EVENT_CLASS_UID {
	if x != nil {
		return x.xxx_hidden_ClassUid
	}
	return enums.BASE_EVENT_CLASS_UID(0)
}

func (x *BaseEvent) GetCloud() *objects.Cloud {
	if x != nil {
		return x.xxx_hidden_Cloud
	}
	return nil
}

func (x *BaseEvent) GetConfidence() string {
	if x != nil {
		return x.xxx_hidden_Confidence
	}
	return ""
}

func (x *BaseEvent) GetConfidenceId() enums.BASE_EVENT_CONFIDENCE_ID {
	if x != nil {
		return x.xxx_hidden_ConfidenceId
	}
	return enums.BASE_EVENT_CONFIDENCE_ID(0)
}

func (x *BaseEvent) GetConfidenceScore() int32 {
	if x != nil {
		return x.xxx_hidden_ConfidenceScore
	}
	return 0
}

func (x *BaseEvent) GetCount() int32 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *BaseEvent) GetDevice() *objects.Device {
	if x != nil {
		return x.xxx_hidden_Device
	}
	return nil
}

func (x *BaseEvent) GetDisposition() string {
	if x != nil {
		return x.xxx_hidden_Disposition
	}
	return ""
}

func (x *BaseEvent) GetDispositionId() enums.BASE_EVENT_DISPOSITION_ID {
	if x != nil {
		return x.xxx_hidden_DispositionId
	}
	return enums.BASE_EVENT_DISPOSITION_ID(0)
}

func (x *BaseEvent) GetDuration() int64 {
	if x != nil {
		return x.xxx_hidden_Duration
	}
	return 0
}

func (x *BaseEvent) GetEndTime() int64 {
	if x != nil {
		return x.xxx_hidden_EndTime
	}
	return 0
}

func (x *BaseEvent) GetEnrichments() []*objects.Enrichment {
	if x != nil {
		if x.xxx_hidden_Enrichments != nil {
			return *x.xxx_hidden_Enrichments
		}
	}
	return nil
}

func (x *BaseEvent) GetFirewallRule() *objects.FirewallRule {
	if x != nil {
		return x.xxx_hidden_FirewallRule
	}
	return nil
}

func (x *BaseEvent) GetIsAlert() bool {
	if x != nil {
		return x.xxx_hidden_IsAlert
	}
	return false
}

func (x *BaseEvent) GetMalware() []*objects.Malware {
	if x != nil {
		if x.xxx_hidden_Malware != nil {
			return *x.xxx_hidden_Malware
		}
	}
	return nil
}

func (x *BaseEvent) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *BaseEvent) GetMetadata() *objects.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *BaseEvent) GetObservables() []*objects.Observable {
	if x != nil {
		if x.xxx_hidden_Observables != nil {
			return *x.xxx_hidden_Observables
		}
	}
	return nil
}

func (x *BaseEvent) GetOsint() []*objects.Osint {
	if x != nil {
		if x.xxx_hidden_Osint != nil {
			return *x.xxx_hidden_Osint
		}
	}
	return nil
}

func (x *BaseEvent) GetPolicy() *objects.Policy {
	if x != nil {
		return x.xxx_hidden_Policy
	}
	return nil
}

func (x *BaseEvent) GetRawData() string {
	if x != nil {
		return x.xxx_hidden_RawData
	}
	return ""
}

func (x *BaseEvent) GetRiskDetails() string {
	if x != nil {
		return x.xxx_hidden_RiskDetails
	}
	return ""
}

func (x *BaseEvent) GetRiskLevel() string {
	if x != nil {
		return x.xxx_hidden_RiskLevel
	}
	return ""
}

func (x *BaseEvent) GetRiskLevelId() enums.BASE_EVENT_RISK_LEVEL_ID {
	if x != nil {
		return x.xxx_hidden_RiskLevelId
	}
	return enums.BASE_EVENT_RISK_LEVEL_ID(0)
}

func (x *BaseEvent) GetRiskScore() int32 {
	if x != nil {
		return x.xxx_hidden_RiskScore
	}
	return 0
}

func (x *BaseEvent) GetSeverity() string {
	if x != nil {
		return x.xxx_hidden_Severity
	}
	return ""
}

func (x *BaseEvent) GetSeverityId() enums.BASE_EVENT_SEVERITY_ID {
	if x != nil {
		return x.xxx_hidden_SeverityId
	}
	return enums.BASE_EVENT_SEVERITY_ID(0)
}

func (x *BaseEvent) GetStartTime() int64 {
	if x != nil {
		return x.xxx_hidden_StartTime
	}
	return 0
}

func (x *BaseEvent) GetStatus() string {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return ""
}

func (x *BaseEvent) GetStatusCode() string {
	if x != nil {
		return x.xxx_hidden_StatusCode
	}
	return ""
}

func (x *BaseEvent) GetStatusDetail() string {
	if x != nil {
		return x.xxx_hidden_StatusDetail
	}
	return ""
}

func (x *BaseEvent) GetStatusId() enums.BASE_EVENT_STATUS_ID {
	if x != nil {
		return x.xxx_hidden_StatusId
	}
	return enums.BASE_EVENT_STATUS_ID(0)
}

func (x *BaseEvent) GetTime() int64 {
	if x != nil {
		return x.xxx_hidden_Time
	}
	return 0
}

func (x *BaseEvent) GetTimezoneOffset() int32 {
	if x != nil {
		return x.xxx_hidden_TimezoneOffset
	}
	return 0
}

func (x *BaseEvent) GetTypeName() string {
	if x != nil {
		return x.xxx_hidden_TypeName
	}
	return ""
}

func (x *BaseEvent) GetTypeUid() int64 {
	if x != nil {
		return x.xxx_hidden_TypeUid
	}
	return 0
}

func (x *BaseEvent) GetUnmapped() *structpb.Struct {
	if x != nil {
		return x.xxx_hidden_Unmapped
	}
	return nil
}

func (x *BaseEvent) SetAction(v string) {
	x.xxx_hidden_Action = v
}

func (x *BaseEvent) SetActionId(v enums.BASE_EVENT_ACTION_ID) {
	x.xxx_hidden_ActionId = v
}

func (x *BaseEvent) SetActivityId(v enums.BASE_EVENT_ACTIVITY_ID) {
	x.xxx_hidden_ActivityId = v
}

func (x *BaseEvent) SetActivityName(v string) {
	x.xxx_hidden_ActivityName = v
}

func (x *BaseEvent) SetActor(v *objects.Actor) {
	x.xxx_hidden_Actor = v
}

func (x *BaseEvent) SetApi(v *objects.Api) {
	x.xxx_hidden_Api = v
}

func (x *BaseEvent) SetAttacks(v []*objects.Attack) {
	x.xxx_hidden_Attacks = &v
}

func (x *BaseEvent) SetAuthorizations(v []*objects.Authorization) {
	x.xxx_hidden_Authorizations = &v
}

func (x *BaseEvent) SetCategoryName(v string) {
	x.xxx_hidden_CategoryName = v
}

func (x *BaseEvent) SetCategoryUid(v enums.BASE_EVENT_CATEGORY_UID) {
	x.xxx_hidden_CategoryUid = v
}

func (x *BaseEvent) SetClassName(v string) {
	x.xxx_hidden_ClassName = v
}

func (x *BaseEvent) SetClassUid(v enums.BASE_EVENT_CLASS_UID) {
	x.xxx_hidden_ClassUid = v
}

func (x *BaseEvent) SetCloud(v *objects.Cloud) {
	x.xxx_hidden_Cloud = v
}

func (x *BaseEvent) SetConfidence(v string) {
	x.xxx_hidden_Confidence = v
}

func (x *BaseEvent) SetConfidenceId(v enums.BASE_EVENT_CONFIDENCE_ID) {
	x.xxx_hidden_ConfidenceId = v
}

func (x *BaseEvent) SetConfidenceScore(v int32) {
	x.xxx_hidden_ConfidenceScore = v
}

func (x *BaseEvent) SetCount(v int32) {
	x.xxx_hidden_Count = v
}

func (x *BaseEvent) SetDevice(v *objects.Device) {
	x.xxx_hidden_Device = v
}

func (x *BaseEvent) SetDisposition(v string) {
	x.xxx_hidden_Disposition = v
}

func (x *BaseEvent) SetDispositionId(v enums.BASE_EVENT_DISPOSITION_ID) {
	x.xxx_hidden_DispositionId = v
}

func (x *BaseEvent) SetDuration(v int64) {
	x.xxx_hidden_Duration = v
}

func (x *BaseEvent) SetEndTime(v int64) {
	x.xxx_hidden_EndTime = v
}

func (x *BaseEvent) SetEnrichments(v []*objects.Enrichment) {
	x.xxx_hidden_Enrichments = &v
}

func (x *BaseEvent) SetFirewallRule(v *objects.FirewallRule) {
	x.xxx_hidden_FirewallRule = v
}

func (x *BaseEvent) SetIsAlert(v bool) {
	x.xxx_hidden_IsAlert = v
}

func (x *BaseEvent) SetMalware(v []*objects.Malware) {
	x.xxx_hidden_Malware = &v
}

func (x *BaseEvent) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

func (x *BaseEvent) SetMetadata(v *objects.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *BaseEvent) SetObservables(v []*objects.Observable) {
	x.xxx_hidden_Observables = &v
}

func (x *BaseEvent) SetOsint(v []*objects.Osint) {
	x.xxx_hidden_Osint = &v
}

func (x *BaseEvent) SetPolicy(v *objects.Policy) {
	x.xxx_hidden_Policy = v
}

func (x *BaseEvent) SetRawData(v string) {
	x.xxx_hidden_RawData = v
}

func (x *BaseEvent) SetRiskDetails(v string) {
	x.xxx_hidden_RiskDetails = v
}

func (x *BaseEvent) SetRiskLevel(v string) {
	x.xxx_hidden_RiskLevel = v
}

func (x *BaseEvent) SetRiskLevelId(v enums.BASE_EVENT_RISK_LEVEL_ID) {
	x.xxx_hidden_RiskLevelId = v
}

func (x *BaseEvent) SetRiskScore(v int32) {
	x.xxx_hidden_RiskScore = v
}

func (x *BaseEvent) SetSeverity(v string) {
	x.xxx_hidden_Severity = v
}

func (x *BaseEvent) SetSeverityId(v enums.BASE_EVENT_SEVERITY_ID) {
	x.xxx_hidden_SeverityId = v
}

func (x *BaseEvent) SetStartTime(v int64) {
	x.xxx_hidden_StartTime = v
}

func (x *BaseEvent) SetStatus(v string) {
	x.xxx_hidden_Status = v
}

func (x *BaseEvent) SetStatusCode(v string) {
	x.xxx_hidden_StatusCode = v
}

func (x *BaseEvent) SetStatusDetail(v string) {
	x.xxx_hidden_StatusDetail = v
}

func (x *BaseEvent) SetStatusId(v enums.BASE_EVENT_STATUS_ID) {
	x.xxx_hidden_StatusId = v
}

func (x *BaseEvent) SetTime(v int64) {
	x.xxx_hidden_Time = v
}

func (x *BaseEvent) SetTimezoneOffset(v int32) {
	x.xxx_hidden_TimezoneOffset = v
}

func (x *BaseEvent) SetTypeName(v string) {
	x.xxx_hidden_TypeName = v
}

func (x *BaseEvent) SetTypeUid(v int64) {
	x.xxx_hidden_TypeUid = v
}

func (x *BaseEvent) SetUnmapped(v *structpb.Struct) {
	x.xxx_hidden_Unmapped = v
}

func (x *BaseEvent) HasActor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Actor != nil
}

func (x *BaseEvent) HasApi() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Api != nil
}

func (x *BaseEvent) HasCloud() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Cloud != nil
}

func (x *BaseEvent) HasDevice() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Device != nil
}

func (x *BaseEvent) HasFirewallRule() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FirewallRule != nil
}

func (x *BaseEvent) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *BaseEvent) HasPolicy() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Policy != nil
}

func (x *BaseEvent) HasUnmapped() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Unmapped != nil
}

func (x *BaseEvent) ClearActor() {
	x.xxx_hidden_Actor = nil
}

func (x *BaseEvent) ClearApi() {
	x.xxx_hidden_Api = nil
}

func (x *BaseEvent) ClearCloud() {
	x.xxx_hidden_Cloud = nil
}

func (x *BaseEvent) ClearDevice() {
	x.xxx_hidden_Device = nil
}

func (x *BaseEvent) ClearFirewallRule() {
	x.xxx_hidden_FirewallRule = nil
}

func (x *BaseEvent) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *BaseEvent) ClearPolicy() {
	x.xxx_hidden_Policy = nil
}

func (x *BaseEvent) ClearUnmapped() {
	x.xxx_hidden_Unmapped = nil
}

type BaseEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Action          string
	ActionId        enums.BASE_EVENT_ACTION_ID
	ActivityId      enums.BASE_EVENT_ACTIVITY_ID
	ActivityName    string
	Actor           *objects.Actor
	Api             *objects.Api
	Attacks         []*objects.Attack
	Authorizations  []*objects.Authorization
	CategoryName    string
	CategoryUid     enums.BASE_EVENT_CATEGORY_UID
	ClassName       string
	ClassUid        enums.BASE_EVENT_CLASS_UID
	Cloud           *objects.Cloud
	Confidence      string
	ConfidenceId    enums.BASE_EVENT_CONFIDENCE_ID
	ConfidenceScore int32
	Count           int32
	Device          *objects.Device
	Disposition     string
	DispositionId   enums.BASE_EVENT_DISPOSITION_ID
	Duration        int64
	EndTime         int64
	Enrichments     []*objects.Enrichment
	FirewallRule    *objects.FirewallRule
	IsAlert         bool
	Malware         []*objects.Malware
	Message         string
	Metadata        *objects.Metadata
	Observables     []*objects.Observable
	Osint           []*objects.Osint
	Policy          *objects.Policy
	RawData         string
	RiskDetails     string
	RiskLevel       string
	RiskLevelId     enums.BASE_EVENT_RISK_LEVEL_ID
	RiskScore       int32
	Severity        string
	SeverityId      enums.BASE_EVENT_SEVERITY_ID
	StartTime       int64
	Status          string
	StatusCode      string
	StatusDetail    string
	StatusId        enums.BASE_EVENT_STATUS_ID
	Time            int64
	TimezoneOffset  int32
	TypeName        string
	TypeUid         int64
	Unmapped        *structpb.Struct
}

func (b0 BaseEvent_builder) Build() *BaseEvent {
	m0 := &BaseEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Action = b.Action
	x.xxx_hidden_ActionId = b.ActionId
	x.xxx_hidden_ActivityId = b.ActivityId
	x.xxx_hidden_ActivityName = b.ActivityName
	x.xxx_hidden_Actor = b.Actor
	x.xxx_hidden_Api = b.Api
	x.xxx_hidden_Attacks = &b.Attacks
	x.xxx_hidden_Authorizations = &b.Authorizations
	x.xxx_hidden_CategoryName = b.CategoryName
	x.xxx_hidden_CategoryUid = b.CategoryUid
	x.xxx_hidden_ClassName = b.ClassName
	x.xxx_hidden_ClassUid = b.ClassUid
	x.xxx_hidden_Cloud = b.Cloud
	x.xxx_hidden_Confidence = b.Confidence
	x.xxx_hidden_ConfidenceId = b.ConfidenceId
	x.xxx_hidden_ConfidenceScore = b.ConfidenceScore
	x.xxx_hidden_Count = b.Count
	x.xxx_hidden_Device = b.Device
	x.xxx_hidden_Disposition = b.Disposition
	x.xxx_hidden_DispositionId = b.DispositionId
	x.xxx_hidden_Duration = b.Duration
	x.xxx_hidden_EndTime = b.EndTime
	x.xxx_hidden_Enrichments = &b.Enrichments
	x.xxx_hidden_FirewallRule = b.FirewallRule
	x.xxx_hidden_IsAlert = b.IsAlert
	x.xxx_hidden_Malware = &b.Malware
	x.xxx_hidden_Message = b.Message
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Observables = &b.Observables
	x.xxx_hidden_Osint = &b.Osint
	x.xxx_hidden_Policy = b.Policy
	x.xxx_hidden_RawData = b.RawData
	x.xxx_hidden_RiskDetails = b.RiskDetails
	x.xxx_hidden_RiskLevel = b.RiskLevel
	x.xxx_hidden_RiskLevelId = b.RiskLevelId
	x.xxx_hidden_RiskScore = b.RiskScore
	x.xxx_hidden_Severity = b.Severity
	x.xxx_hidden_SeverityId = b.SeverityId
	x.xxx_hidden_StartTime = b.StartTime
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_StatusCode = b.StatusCode
	x.xxx_hidden_StatusDetail = b.StatusDetail
	x.xxx_hidden_StatusId = b.StatusId
	x.xxx_hidden_Time = b.Time
	x.xxx_hidden_TimezoneOffset = b.TimezoneOffset
	x.xxx_hidden_TypeName = b.TypeName
	x.xxx_hidden_TypeUid = b.TypeUid
	x.xxx_hidden_Unmapped = b.Unmapped
	return m0
}

var File_ocsf_v1_4_0_events_other_other_proto protoreflect.FileDescriptor

const file_ocsf_v1_4_0_events_other_other_proto_rawDesc = "" +
	"\n" +
	"$ocsf/v1_4_0/events/other/other.proto\x12\x18ocsf.v1_4_0.events.other\x1a*ocsf/v1_4_0/events/other/enums/enums.proto\x1a!ocsf/v1_4_0/objects/objects.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xd0\x12\n" +
	"\tBaseEvent\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12Q\n" +
	"\taction_id\x18\x02 \x01(\x0e24.ocsf.v1_4_0.events.other.enums.BASE_EVENT_ACTION_IDR\bactionId\x12W\n" +
	"\vactivity_id\x18\x03 \x01(\x0e26.ocsf.v1_4_0.events.other.enums.BASE_EVENT_ACTIVITY_IDR\n" +
	"activityId\x12#\n" +
	"\ractivity_name\x18\x04 \x01(\tR\factivityName\x120\n" +
	"\x05actor\x18\x05 \x01(\v2\x1a.ocsf.v1_4_0.objects.ActorR\x05actor\x12*\n" +
	"\x03api\x18\x06 \x01(\v2\x18.ocsf.v1_4_0.objects.ApiR\x03api\x125\n" +
	"\aattacks\x18\a \x03(\v2\x1b.ocsf.v1_4_0.objects.AttackR\aattacks\x12J\n" +
	"\x0eauthorizations\x18\b \x03(\v2\".ocsf.v1_4_0.objects.AuthorizationR\x0eauthorizations\x12#\n" +
	"\rcategory_name\x18\t \x01(\tR\fcategoryName\x12Z\n" +
	"\fcategory_uid\x18\n" +
	" \x01(\x0e27.ocsf.v1_4_0.events.other.enums.BASE_EVENT_CATEGORY_UIDR\vcategoryUid\x12\x1d\n" +
	"\n" +
	"class_name\x18\v \x01(\tR\tclassName\x12Q\n" +
	"\tclass_uid\x18\f \x01(\x0e24.ocsf.v1_4_0.events.other.enums.BASE_EVENT_CLASS_UIDR\bclassUid\x120\n" +
	"\x05cloud\x18\r \x01(\v2\x1a.ocsf.v1_4_0.objects.CloudR\x05cloud\x12\x1e\n" +
	"\n" +
	"confidence\x18\x0e \x01(\tR\n" +
	"confidence\x12]\n" +
	"\rconfidence_id\x18\x0f \x01(\x0e28.ocsf.v1_4_0.events.other.enums.BASE_EVENT_CONFIDENCE_IDR\fconfidenceId\x12)\n" +
	"\x10confidence_score\x18\x10 \x01(\x05R\x0fconfidenceScore\x12\x14\n" +
	"\x05count\x18\x11 \x01(\x05R\x05count\x123\n" +
	"\x06device\x18\x12 \x01(\v2\x1b.ocsf.v1_4_0.objects.DeviceR\x06device\x12 \n" +
	"\vdisposition\x18\x13 \x01(\tR\vdisposition\x12`\n" +
	"\x0edisposition_id\x18\x14 \x01(\x0e29.ocsf.v1_4_0.events.other.enums.BASE_EVENT_DISPOSITION_IDR\rdispositionId\x12\x1a\n" +
	"\bduration\x18\x15 \x01(\x03R\bduration\x12\x19\n" +
	"\bend_time\x18\x16 \x01(\x03R\aendTime\x12A\n" +
	"\venrichments\x18\x17 \x03(\v2\x1f.ocsf.v1_4_0.objects.EnrichmentR\venrichments\x12F\n" +
	"\rfirewall_rule\x18\x18 \x01(\v2!.ocsf.v1_4_0.objects.FirewallRuleR\ffirewallRule\x12\x19\n" +
	"\bis_alert\x18\x19 \x01(\bR\aisAlert\x126\n" +
	"\amalware\x18\x1a \x03(\v2\x1c.ocsf.v1_4_0.objects.MalwareR\amalware\x12\x18\n" +
	"\amessage\x18\x1b \x01(\tR\amessage\x129\n" +
	"\bmetadata\x18\x1c \x01(\v2\x1d.ocsf.v1_4_0.objects.MetadataR\bmetadata\x12A\n" +
	"\vobservables\x18\x1d \x03(\v2\x1f.ocsf.v1_4_0.objects.ObservableR\vobservables\x120\n" +
	"\x05osint\x18\x1e \x03(\v2\x1a.ocsf.v1_4_0.objects.OsintR\x05osint\x123\n" +
	"\x06policy\x18\x1f \x01(\v2\x1b.ocsf.v1_4_0.objects.PolicyR\x06policy\x12\x19\n" +
	"\braw_data\x18  \x01(\tR\arawData\x12!\n" +
	"\frisk_details\x18! \x01(\tR\vriskDetails\x12\x1d\n" +
	"\n" +
	"risk_level\x18\" \x01(\tR\triskLevel\x12\\\n" +
	"\rrisk_level_id\x18# \x01(\x0e28.ocsf.v1_4_0.events.other.enums.BASE_EVENT_RISK_LEVEL_IDR\vriskLevelId\x12\x1d\n" +
	"\n" +
	"risk_score\x18$ \x01(\x05R\triskScore\x12\x1a\n" +
	"\bseverity\x18% \x01(\tR\bseverity\x12W\n" +
	"\vseverity_id\x18& \x01(\x0e26.ocsf.v1_4_0.events.other.enums.BASE_EVENT_SEVERITY_IDR\n" +
	"severityId\x12\x1d\n" +
	"\n" +
	"start_time\x18' \x01(\x03R\tstartTime\x12\x16\n" +
	"\x06status\x18( \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18) \x01(\tR\n" +
	"statusCode\x12#\n" +
	"\rstatus_detail\x18* \x01(\tR\fstatusDetail\x12Q\n" +
	"\tstatus_id\x18+ \x01(\x0e24.ocsf.v1_4_0.events.other.enums.BASE_EVENT_STATUS_IDR\bstatusId\x12\x12\n" +
	"\x04time\x18, \x01(\x03R\x04time\x12'\n" +
	"\x0ftimezone_offset\x18- \x01(\x05R\x0etimezoneOffset\x12\x1b\n" +
	"\ttype_name\x18. \x01(\tR\btypeName\x12\x19\n" +
	"\btype_uid\x18/ \x01(\x03R\atypeUid\x123\n" +
	"\bunmapped\x180 \x01(\v2\x17.google.protobuf.StructR\bunmappedB\xe7\x01\n" +
	"\x1ccom.ocsf.v1_4_0.events.otherB\n" +
	"OtherProtoP\x01Z?github.com/valllabh/ocsf-schema-golang/ocsf/v1_4_0/events/other\xa2\x02\x04OVEO\xaa\x02\x16Ocsf.V140.Events.Other\xca\x02\x16Ocsf\\V140\\Events\\Other\xe2\x02\"Ocsf\\V140\\Events\\Other\\GPBMetadata\xea\x02\x19Ocsf::V140::Events::Otherb\x06proto3"

var file_ocsf_v1_4_0_events_other_other_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ocsf_v1_4_0_events_other_other_proto_goTypes = []any{
	(*BaseEvent)(nil),                    // 0: ocsf.v1_4_0.events.other.BaseEvent
	(enums.BASE_EVENT_ACTION_ID)(0),      // 1: ocsf.v1_4_0.events.other.enums.BASE_EVENT_ACTION_ID
	(enums.BASE_EVENT_ACTIVITY_ID)(0),    // 2: ocsf.v1_4_0.events.other.enums.BASE_EVENT_ACTIVITY_ID
	(*objects.Actor)(nil),                // 3: ocsf.v1_4_0.objects.Actor
	(*objects.Api)(nil),                  // 4: ocsf.v1_4_0.objects.Api
	(*objects.Attack)(nil),               // 5: ocsf.v1_4_0.objects.Attack
	(*objects.Authorization)(nil),        // 6: ocsf.v1_4_0.objects.Authorization
	(enums.BASE_EVENT_CATEGORY_UID)(0),   // 7: ocsf.v1_4_0.events.other.enums.BASE_EVENT_CATEGORY_UID
	(enums.BASE_EVENT_CLASS_UID)(0),      // 8: ocsf.v1_4_0.events.other.enums.BASE_EVENT_CLASS_UID
	(*objects.Cloud)(nil),                // 9: ocsf.v1_4_0.objects.Cloud
	(enums.BASE_EVENT_CONFIDENCE_ID)(0),  // 10: ocsf.v1_4_0.events.other.enums.BASE_EVENT_CONFIDENCE_ID
	(*objects.Device)(nil),               // 11: ocsf.v1_4_0.objects.Device
	(enums.BASE_EVENT_DISPOSITION_ID)(0), // 12: ocsf.v1_4_0.events.other.enums.BASE_EVENT_DISPOSITION_ID
	(*objects.Enrichment)(nil),           // 13: ocsf.v1_4_0.objects.Enrichment
	(*objects.FirewallRule)(nil),         // 14: ocsf.v1_4_0.objects.FirewallRule
	(*objects.Malware)(nil),              // 15: ocsf.v1_4_0.objects.Malware
	(*objects.Metadata)(nil),             // 16: ocsf.v1_4_0.objects.Metadata
	(*objects.Observable)(nil),           // 17: ocsf.v1_4_0.objects.Observable
	(*objects.Osint)(nil),                // 18: ocsf.v1_4_0.objects.Osint
	(*objects.Policy)(nil),               // 19: ocsf.v1_4_0.objects.Policy
	(enums.BASE_EVENT_RISK_LEVEL_ID)(0),  // 20: ocsf.v1_4_0.events.other.enums.BASE_EVENT_RISK_LEVEL_ID
	(enums.BASE_EVENT_SEVERITY_ID)(0),    // 21: ocsf.v1_4_0.events.other.enums.BASE_EVENT_SEVERITY_ID
	(enums.BASE_EVENT_STATUS_ID)(0),      // 22: ocsf.v1_4_0.events.other.enums.BASE_EVENT_STATUS_ID
	(*structpb.Struct)(nil),              // 23: google.protobuf.Struct
}
var file_ocsf_v1_4_0_events_other_other_proto_depIdxs = []int32{
	1,  // 0: ocsf.v1_4_0.events.other.BaseEvent.action_id:type_name -> ocsf.v1_4_0.events.other.enums.BASE_EVENT_ACTION_ID
	2,  // 1: ocsf.v1_4_0.events.other.BaseEvent.activity_id:type_name -> ocsf.v1_4_0.events.other.enums.BASE_EVENT_ACTIVITY_ID
	3,  // 2: ocsf.v1_4_0.events.other.BaseEvent.actor:type_name -> ocsf.v1_4_0.objects.Actor
	4,  // 3: ocsf.v1_4_0.events.other.BaseEvent.api:type_name -> ocsf.v1_4_0.objects.Api
	5,  // 4: ocsf.v1_4_0.events.other.BaseEvent.attacks:type_name -> ocsf.v1_4_0.objects.Attack
	6,  // 5: ocsf.v1_4_0.events.other.BaseEvent.authorizations:type_name -> ocsf.v1_4_0.objects.Authorization
	7,  // 6: ocsf.v1_4_0.events.other.BaseEvent.category_uid:type_name -> ocsf.v1_4_0.events.other.enums.BASE_EVENT_CATEGORY_UID
	8,  // 7: ocsf.v1_4_0.events.other.BaseEvent.class_uid:type_name -> ocsf.v1_4_0.events.other.enums.BASE_EVENT_CLASS_UID
	9,  // 8: ocsf.v1_4_0.events.other.BaseEvent.cloud:type_name -> ocsf.v1_4_0.objects.Cloud
	10, // 9: ocsf.v1_4_0.events.other.BaseEvent.confidence_id:type_name -> ocsf.v1_4_0.events.other.enums.BASE_EVENT_CONFIDENCE_ID
	11, // 10: ocsf.v1_4_0.events.other.BaseEvent.device:type_name -> ocsf.v1_4_0.objects.Device
	12, // 11: ocsf.v1_4_0.events.other.BaseEvent.disposition_id:type_name -> ocsf.v1_4_0.events.other.enums.BASE_EVENT_DISPOSITION_ID
	13, // 12: ocsf.v1_4_0.events.other.BaseEvent.enrichments:type_name -> ocsf.v1_4_0.objects.Enrichment
	14, // 13: ocsf.v1_4_0.events.other.BaseEvent.firewall_rule:type_name -> ocsf.v1_4_0.objects.FirewallRule
	15, // 14: ocsf.v1_4_0.events.other.BaseEvent.malware:type_name -> ocsf.v1_4_0.objects.Malware
	16, // 15: ocsf.v1_4_0.events.other.BaseEvent.metadata:type_name -> ocsf.v1_4_0.objects.Metadata
	17, // 16: ocsf.v1_4_0.events.other.BaseEvent.observables:type_name -> ocsf.v1_4_0.objects.Observable
	18, // 17: ocsf.v1_4_0.events.other.BaseEvent.osint:type_name -> ocsf.v1_4_0.objects.Osint
	19, // 18: ocsf.v1_4_0.events.other.BaseEvent.policy:type_name -> ocsf.v1_4_0.objects.Policy
	20, // 19: ocsf.v1_4_0.events.other.BaseEvent.risk_level_id:type_name -> ocsf.v1_4_0.events.other.enums.BASE_EVENT_RISK_LEVEL_ID
	21, // 20: ocsf.v1_4_0.events.other.BaseEvent.severity_id:type_name -> ocsf.v1_4_0.events.other.enums.BASE_EVENT_SEVERITY_ID
	22, // 21: ocsf.v1_4_0.events.other.BaseEvent.status_id:type_name -> ocsf.v1_4_0.events.other.enums.BASE_EVENT_STATUS_ID
	23, // 22: ocsf.v1_4_0.events.other.BaseEvent.unmapped:type_name -> google.protobuf.Struct
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_ocsf_v1_4_0_events_other_other_proto_init() }
func file_ocsf_v1_4_0_events_other_other_proto_init() {
	if File_ocsf_v1_4_0_events_other_other_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocsf_v1_4_0_events_other_other_proto_rawDesc), len(file_ocsf_v1_4_0_events_other_other_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocsf_v1_4_0_events_other_other_proto_goTypes,
		DependencyIndexes: file_ocsf_v1_4_0_events_other_other_proto_depIdxs,
		MessageInfos:      file_ocsf_v1_4_0_events_other_other_proto_msgTypes,
	}.Build()
	File_ocsf_v1_4_0_events_other_other_proto = out.File
	file_ocsf_v1_4_0_events_other_other_proto_goTypes = nil
	file_ocsf_v1_4_0_events_other_other_proto_depIdxs = nil
}
