// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: ocsf/v1_4_0/events/other/enums/enums.proto

//go:build protoopaque

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BASE_EVENT_ACTION_ID int32

const (
	BASE_EVENT_ACTION_ID_BASE_EVENT_ACTION_ID_UNKNOWN  BASE_EVENT_ACTION_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	BASE_EVENT_ACTION_ID_BASE_EVENT_ACTION_ID_ALLOWED  BASE_EVENT_ACTION_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	BASE_EVENT_ACTION_ID_BASE_EVENT_ACTION_ID_DENIED   BASE_EVENT_ACTION_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	BASE_EVENT_ACTION_ID_BASE_EVENT_ACTION_ID_OBSERVED BASE_EVENT_ACTION_ID = 3  // Type: OCSF_VALUE; EnumValue: 3;
	BASE_EVENT_ACTION_ID_BASE_EVENT_ACTION_ID_MODIFIED BASE_EVENT_ACTION_ID = 4  // Type: OCSF_VALUE; EnumValue: 4;
	BASE_EVENT_ACTION_ID_BASE_EVENT_ACTION_ID_OTHER    BASE_EVENT_ACTION_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for BASE_EVENT_ACTION_ID.
var (
	BASE_EVENT_ACTION_ID_name = map[int32]string{
		0:  "BASE_EVENT_ACTION_ID_UNKNOWN",
		1:  "BASE_EVENT_ACTION_ID_ALLOWED",
		2:  "BASE_EVENT_ACTION_ID_DENIED",
		3:  "BASE_EVENT_ACTION_ID_OBSERVED",
		4:  "BASE_EVENT_ACTION_ID_MODIFIED",
		99: "BASE_EVENT_ACTION_ID_OTHER",
	}
	BASE_EVENT_ACTION_ID_value = map[string]int32{
		"BASE_EVENT_ACTION_ID_UNKNOWN":  0,
		"BASE_EVENT_ACTION_ID_ALLOWED":  1,
		"BASE_EVENT_ACTION_ID_DENIED":   2,
		"BASE_EVENT_ACTION_ID_OBSERVED": 3,
		"BASE_EVENT_ACTION_ID_MODIFIED": 4,
		"BASE_EVENT_ACTION_ID_OTHER":    99,
	}
)

func (x BASE_EVENT_ACTION_ID) Enum() *BASE_EVENT_ACTION_ID {
	p := new(BASE_EVENT_ACTION_ID)
	*p = x
	return p
}

func (x BASE_EVENT_ACTION_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BASE_EVENT_ACTION_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[0].Descriptor()
}

func (BASE_EVENT_ACTION_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[0]
}

func (x BASE_EVENT_ACTION_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type BASE_EVENT_ACTIVITY_ID int32

const (
	BASE_EVENT_ACTIVITY_ID_BASE_EVENT_ACTIVITY_ID_UNKNOWN BASE_EVENT_ACTIVITY_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	BASE_EVENT_ACTIVITY_ID_BASE_EVENT_ACTIVITY_ID_OTHER   BASE_EVENT_ACTIVITY_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for BASE_EVENT_ACTIVITY_ID.
var (
	BASE_EVENT_ACTIVITY_ID_name = map[int32]string{
		0:  "BASE_EVENT_ACTIVITY_ID_UNKNOWN",
		99: "BASE_EVENT_ACTIVITY_ID_OTHER",
	}
	BASE_EVENT_ACTIVITY_ID_value = map[string]int32{
		"BASE_EVENT_ACTIVITY_ID_UNKNOWN": 0,
		"BASE_EVENT_ACTIVITY_ID_OTHER":   99,
	}
)

func (x BASE_EVENT_ACTIVITY_ID) Enum() *BASE_EVENT_ACTIVITY_ID {
	p := new(BASE_EVENT_ACTIVITY_ID)
	*p = x
	return p
}

func (x BASE_EVENT_ACTIVITY_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BASE_EVENT_ACTIVITY_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[1].Descriptor()
}

func (BASE_EVENT_ACTIVITY_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[1]
}

func (x BASE_EVENT_ACTIVITY_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type BASE_EVENT_CATEGORY_UID int32

const (
	BASE_EVENT_CATEGORY_UID_BASE_EVENT_CATEGORY_UID_UNCATEGORIZED BASE_EVENT_CATEGORY_UID = 0 // Type: OCSF_VALUE; EnumValue: 0;
)

// Enum value maps for BASE_EVENT_CATEGORY_UID.
var (
	BASE_EVENT_CATEGORY_UID_name = map[int32]string{
		0: "BASE_EVENT_CATEGORY_UID_UNCATEGORIZED",
	}
	BASE_EVENT_CATEGORY_UID_value = map[string]int32{
		"BASE_EVENT_CATEGORY_UID_UNCATEGORIZED": 0,
	}
)

func (x BASE_EVENT_CATEGORY_UID) Enum() *BASE_EVENT_CATEGORY_UID {
	p := new(BASE_EVENT_CATEGORY_UID)
	*p = x
	return p
}

func (x BASE_EVENT_CATEGORY_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BASE_EVENT_CATEGORY_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[2].Descriptor()
}

func (BASE_EVENT_CATEGORY_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[2]
}

func (x BASE_EVENT_CATEGORY_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type BASE_EVENT_CLASS_UID int32

const (
	BASE_EVENT_CLASS_UID_BASE_EVENT_CLASS_UID_BASE_EVENT BASE_EVENT_CLASS_UID = 0 // Type: OCSF_VALUE; EnumValue: 0;
)

// Enum value maps for BASE_EVENT_CLASS_UID.
var (
	BASE_EVENT_CLASS_UID_name = map[int32]string{
		0: "BASE_EVENT_CLASS_UID_BASE_EVENT",
	}
	BASE_EVENT_CLASS_UID_value = map[string]int32{
		"BASE_EVENT_CLASS_UID_BASE_EVENT": 0,
	}
)

func (x BASE_EVENT_CLASS_UID) Enum() *BASE_EVENT_CLASS_UID {
	p := new(BASE_EVENT_CLASS_UID)
	*p = x
	return p
}

func (x BASE_EVENT_CLASS_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BASE_EVENT_CLASS_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[3].Descriptor()
}

func (BASE_EVENT_CLASS_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[3]
}

func (x BASE_EVENT_CLASS_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type BASE_EVENT_CONFIDENCE_ID int32

const (
	BASE_EVENT_CONFIDENCE_ID_BASE_EVENT_CONFIDENCE_ID_UNKNOWN BASE_EVENT_CONFIDENCE_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	BASE_EVENT_CONFIDENCE_ID_BASE_EVENT_CONFIDENCE_ID_LOW     BASE_EVENT_CONFIDENCE_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	BASE_EVENT_CONFIDENCE_ID_BASE_EVENT_CONFIDENCE_ID_MEDIUM  BASE_EVENT_CONFIDENCE_ID = 2  // EnumValue: 2; Type: OCSF_VALUE;
	BASE_EVENT_CONFIDENCE_ID_BASE_EVENT_CONFIDENCE_ID_HIGH    BASE_EVENT_CONFIDENCE_ID = 3  // Type: OCSF_VALUE; EnumValue: 3;
	BASE_EVENT_CONFIDENCE_ID_BASE_EVENT_CONFIDENCE_ID_OTHER   BASE_EVENT_CONFIDENCE_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for BASE_EVENT_CONFIDENCE_ID.
var (
	BASE_EVENT_CONFIDENCE_ID_name = map[int32]string{
		0:  "BASE_EVENT_CONFIDENCE_ID_UNKNOWN",
		1:  "BASE_EVENT_CONFIDENCE_ID_LOW",
		2:  "BASE_EVENT_CONFIDENCE_ID_MEDIUM",
		3:  "BASE_EVENT_CONFIDENCE_ID_HIGH",
		99: "BASE_EVENT_CONFIDENCE_ID_OTHER",
	}
	BASE_EVENT_CONFIDENCE_ID_value = map[string]int32{
		"BASE_EVENT_CONFIDENCE_ID_UNKNOWN": 0,
		"BASE_EVENT_CONFIDENCE_ID_LOW":     1,
		"BASE_EVENT_CONFIDENCE_ID_MEDIUM":  2,
		"BASE_EVENT_CONFIDENCE_ID_HIGH":    3,
		"BASE_EVENT_CONFIDENCE_ID_OTHER":   99,
	}
)

func (x BASE_EVENT_CONFIDENCE_ID) Enum() *BASE_EVENT_CONFIDENCE_ID {
	p := new(BASE_EVENT_CONFIDENCE_ID)
	*p = x
	return p
}

func (x BASE_EVENT_CONFIDENCE_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BASE_EVENT_CONFIDENCE_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[4].Descriptor()
}

func (BASE_EVENT_CONFIDENCE_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[4]
}

func (x BASE_EVENT_CONFIDENCE_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type BASE_EVENT_DISPOSITION_ID int32

const (
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_UNKNOWN             BASE_EVENT_DISPOSITION_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_ALLOWED             BASE_EVENT_DISPOSITION_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_BLOCKED             BASE_EVENT_DISPOSITION_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_QUARANTINED         BASE_EVENT_DISPOSITION_ID = 3  // Type: OCSF_VALUE; EnumValue: 3;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_ISOLATED            BASE_EVENT_DISPOSITION_ID = 4  // Type: OCSF_VALUE; EnumValue: 4;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_DELETED             BASE_EVENT_DISPOSITION_ID = 5  // Type: OCSF_VALUE; EnumValue: 5;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_DROPPED             BASE_EVENT_DISPOSITION_ID = 6  // Type: OCSF_VALUE; EnumValue: 6;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_CUSTOM_ACTION       BASE_EVENT_DISPOSITION_ID = 7  // Type: OCSF_VALUE; EnumValue: 7;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_APPROVED            BASE_EVENT_DISPOSITION_ID = 8  // Type: OCSF_VALUE; EnumValue: 8;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_RESTORED            BASE_EVENT_DISPOSITION_ID = 9  // EnumValue: 9; Type: OCSF_VALUE;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_EXONERATED          BASE_EVENT_DISPOSITION_ID = 10 // Type: OCSF_VALUE; EnumValue: 10;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_CORRECTED           BASE_EVENT_DISPOSITION_ID = 11 // Type: OCSF_VALUE; EnumValue: 11;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_PARTIALLY_CORRECTED BASE_EVENT_DISPOSITION_ID = 12 // Type: OCSF_VALUE; EnumValue: 12;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_UNCORRECTED         BASE_EVENT_DISPOSITION_ID = 13 // Type: OCSF_VALUE; EnumValue: 13;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_DELAYED             BASE_EVENT_DISPOSITION_ID = 14 // Type: OCSF_VALUE; EnumValue: 14;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_DETECTED            BASE_EVENT_DISPOSITION_ID = 15 // Type: OCSF_VALUE; EnumValue: 15;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_NO_ACTION           BASE_EVENT_DISPOSITION_ID = 16 // Type: OCSF_VALUE; EnumValue: 16;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_LOGGED              BASE_EVENT_DISPOSITION_ID = 17 // Type: OCSF_VALUE; EnumValue: 17;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_TAGGED              BASE_EVENT_DISPOSITION_ID = 18 // Type: OCSF_VALUE; EnumValue: 18;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_ALERT               BASE_EVENT_DISPOSITION_ID = 19 // Type: OCSF_VALUE; EnumValue: 19;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_COUNT               BASE_EVENT_DISPOSITION_ID = 20 // Type: OCSF_VALUE; EnumValue: 20;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_RESET               BASE_EVENT_DISPOSITION_ID = 21 // Type: OCSF_VALUE; EnumValue: 21;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_CAPTCHA             BASE_EVENT_DISPOSITION_ID = 22 // EnumValue: 22; Type: OCSF_VALUE;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_CHALLENGE           BASE_EVENT_DISPOSITION_ID = 23 // Type: OCSF_VALUE; EnumValue: 23;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_ACCESS_REVOKED      BASE_EVENT_DISPOSITION_ID = 24 // Type: OCSF_VALUE; EnumValue: 24;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_REJECTED            BASE_EVENT_DISPOSITION_ID = 25 // Type: OCSF_VALUE; EnumValue: 25;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_UNAUTHORIZED        BASE_EVENT_DISPOSITION_ID = 26 // Type: OCSF_VALUE; EnumValue: 26;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_ERROR               BASE_EVENT_DISPOSITION_ID = 27 // Type: OCSF_VALUE; EnumValue: 27;
	BASE_EVENT_DISPOSITION_ID_BASE_EVENT_DISPOSITION_ID_OTHER               BASE_EVENT_DISPOSITION_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for BASE_EVENT_DISPOSITION_ID.
var (
	BASE_EVENT_DISPOSITION_ID_name = map[int32]string{
		0:  "BASE_EVENT_DISPOSITION_ID_UNKNOWN",
		1:  "BASE_EVENT_DISPOSITION_ID_ALLOWED",
		2:  "BASE_EVENT_DISPOSITION_ID_BLOCKED",
		3:  "BASE_EVENT_DISPOSITION_ID_QUARANTINED",
		4:  "BASE_EVENT_DISPOSITION_ID_ISOLATED",
		5:  "BASE_EVENT_DISPOSITION_ID_DELETED",
		6:  "BASE_EVENT_DISPOSITION_ID_DROPPED",
		7:  "BASE_EVENT_DISPOSITION_ID_CUSTOM_ACTION",
		8:  "BASE_EVENT_DISPOSITION_ID_APPROVED",
		9:  "BASE_EVENT_DISPOSITION_ID_RESTORED",
		10: "BASE_EVENT_DISPOSITION_ID_EXONERATED",
		11: "BASE_EVENT_DISPOSITION_ID_CORRECTED",
		12: "BASE_EVENT_DISPOSITION_ID_PARTIALLY_CORRECTED",
		13: "BASE_EVENT_DISPOSITION_ID_UNCORRECTED",
		14: "BASE_EVENT_DISPOSITION_ID_DELAYED",
		15: "BASE_EVENT_DISPOSITION_ID_DETECTED",
		16: "BASE_EVENT_DISPOSITION_ID_NO_ACTION",
		17: "BASE_EVENT_DISPOSITION_ID_LOGGED",
		18: "BASE_EVENT_DISPOSITION_ID_TAGGED",
		19: "BASE_EVENT_DISPOSITION_ID_ALERT",
		20: "BASE_EVENT_DISPOSITION_ID_COUNT",
		21: "BASE_EVENT_DISPOSITION_ID_RESET",
		22: "BASE_EVENT_DISPOSITION_ID_CAPTCHA",
		23: "BASE_EVENT_DISPOSITION_ID_CHALLENGE",
		24: "BASE_EVENT_DISPOSITION_ID_ACCESS_REVOKED",
		25: "BASE_EVENT_DISPOSITION_ID_REJECTED",
		26: "BASE_EVENT_DISPOSITION_ID_UNAUTHORIZED",
		27: "BASE_EVENT_DISPOSITION_ID_ERROR",
		99: "BASE_EVENT_DISPOSITION_ID_OTHER",
	}
	BASE_EVENT_DISPOSITION_ID_value = map[string]int32{
		"BASE_EVENT_DISPOSITION_ID_UNKNOWN":             0,
		"BASE_EVENT_DISPOSITION_ID_ALLOWED":             1,
		"BASE_EVENT_DISPOSITION_ID_BLOCKED":             2,
		"BASE_EVENT_DISPOSITION_ID_QUARANTINED":         3,
		"BASE_EVENT_DISPOSITION_ID_ISOLATED":            4,
		"BASE_EVENT_DISPOSITION_ID_DELETED":             5,
		"BASE_EVENT_DISPOSITION_ID_DROPPED":             6,
		"BASE_EVENT_DISPOSITION_ID_CUSTOM_ACTION":       7,
		"BASE_EVENT_DISPOSITION_ID_APPROVED":            8,
		"BASE_EVENT_DISPOSITION_ID_RESTORED":            9,
		"BASE_EVENT_DISPOSITION_ID_EXONERATED":          10,
		"BASE_EVENT_DISPOSITION_ID_CORRECTED":           11,
		"BASE_EVENT_DISPOSITION_ID_PARTIALLY_CORRECTED": 12,
		"BASE_EVENT_DISPOSITION_ID_UNCORRECTED":         13,
		"BASE_EVENT_DISPOSITION_ID_DELAYED":             14,
		"BASE_EVENT_DISPOSITION_ID_DETECTED":            15,
		"BASE_EVENT_DISPOSITION_ID_NO_ACTION":           16,
		"BASE_EVENT_DISPOSITION_ID_LOGGED":              17,
		"BASE_EVENT_DISPOSITION_ID_TAGGED":              18,
		"BASE_EVENT_DISPOSITION_ID_ALERT":               19,
		"BASE_EVENT_DISPOSITION_ID_COUNT":               20,
		"BASE_EVENT_DISPOSITION_ID_RESET":               21,
		"BASE_EVENT_DISPOSITION_ID_CAPTCHA":             22,
		"BASE_EVENT_DISPOSITION_ID_CHALLENGE":           23,
		"BASE_EVENT_DISPOSITION_ID_ACCESS_REVOKED":      24,
		"BASE_EVENT_DISPOSITION_ID_REJECTED":            25,
		"BASE_EVENT_DISPOSITION_ID_UNAUTHORIZED":        26,
		"BASE_EVENT_DISPOSITION_ID_ERROR":               27,
		"BASE_EVENT_DISPOSITION_ID_OTHER":               99,
	}
)

func (x BASE_EVENT_DISPOSITION_ID) Enum() *BASE_EVENT_DISPOSITION_ID {
	p := new(BASE_EVENT_DISPOSITION_ID)
	*p = x
	return p
}

func (x BASE_EVENT_DISPOSITION_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BASE_EVENT_DISPOSITION_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[5].Descriptor()
}

func (BASE_EVENT_DISPOSITION_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[5]
}

func (x BASE_EVENT_DISPOSITION_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type BASE_EVENT_RISK_LEVEL_ID int32

const (
	BASE_EVENT_RISK_LEVEL_ID_BASE_EVENT_RISK_LEVEL_ID_INFO     BASE_EVENT_RISK_LEVEL_ID = 0  // EnumValue: 0; Type: OCSF_VALUE;
	BASE_EVENT_RISK_LEVEL_ID_BASE_EVENT_RISK_LEVEL_ID_LOW      BASE_EVENT_RISK_LEVEL_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	BASE_EVENT_RISK_LEVEL_ID_BASE_EVENT_RISK_LEVEL_ID_MEDIUM   BASE_EVENT_RISK_LEVEL_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	BASE_EVENT_RISK_LEVEL_ID_BASE_EVENT_RISK_LEVEL_ID_HIGH     BASE_EVENT_RISK_LEVEL_ID = 3  // Type: OCSF_VALUE; EnumValue: 3;
	BASE_EVENT_RISK_LEVEL_ID_BASE_EVENT_RISK_LEVEL_ID_CRITICAL BASE_EVENT_RISK_LEVEL_ID = 4  // Type: OCSF_VALUE; EnumValue: 4;
	BASE_EVENT_RISK_LEVEL_ID_BASE_EVENT_RISK_LEVEL_ID_OTHER    BASE_EVENT_RISK_LEVEL_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for BASE_EVENT_RISK_LEVEL_ID.
var (
	BASE_EVENT_RISK_LEVEL_ID_name = map[int32]string{
		0:  "BASE_EVENT_RISK_LEVEL_ID_INFO",
		1:  "BASE_EVENT_RISK_LEVEL_ID_LOW",
		2:  "BASE_EVENT_RISK_LEVEL_ID_MEDIUM",
		3:  "BASE_EVENT_RISK_LEVEL_ID_HIGH",
		4:  "BASE_EVENT_RISK_LEVEL_ID_CRITICAL",
		99: "BASE_EVENT_RISK_LEVEL_ID_OTHER",
	}
	BASE_EVENT_RISK_LEVEL_ID_value = map[string]int32{
		"BASE_EVENT_RISK_LEVEL_ID_INFO":     0,
		"BASE_EVENT_RISK_LEVEL_ID_LOW":      1,
		"BASE_EVENT_RISK_LEVEL_ID_MEDIUM":   2,
		"BASE_EVENT_RISK_LEVEL_ID_HIGH":     3,
		"BASE_EVENT_RISK_LEVEL_ID_CRITICAL": 4,
		"BASE_EVENT_RISK_LEVEL_ID_OTHER":    99,
	}
)

func (x BASE_EVENT_RISK_LEVEL_ID) Enum() *BASE_EVENT_RISK_LEVEL_ID {
	p := new(BASE_EVENT_RISK_LEVEL_ID)
	*p = x
	return p
}

func (x BASE_EVENT_RISK_LEVEL_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BASE_EVENT_RISK_LEVEL_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[6].Descriptor()
}

func (BASE_EVENT_RISK_LEVEL_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[6]
}

func (x BASE_EVENT_RISK_LEVEL_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type BASE_EVENT_SEVERITY_ID int32

const (
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_UNKNOWN       BASE_EVENT_SEVERITY_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_INFORMATIONAL BASE_EVENT_SEVERITY_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_LOW           BASE_EVENT_SEVERITY_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_MEDIUM        BASE_EVENT_SEVERITY_ID = 3  // Type: OCSF_VALUE; EnumValue: 3;
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_HIGH          BASE_EVENT_SEVERITY_ID = 4  // Type: OCSF_VALUE; EnumValue: 4;
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_CRITICAL      BASE_EVENT_SEVERITY_ID = 5  // Type: OCSF_VALUE; EnumValue: 5;
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_FATAL         BASE_EVENT_SEVERITY_ID = 6  // EnumValue: 6; Type: OCSF_VALUE;
	BASE_EVENT_SEVERITY_ID_BASE_EVENT_SEVERITY_ID_OTHER         BASE_EVENT_SEVERITY_ID = 99 // EnumValue: 99; Type: OCSF_VALUE;
)

// Enum value maps for BASE_EVENT_SEVERITY_ID.
var (
	BASE_EVENT_SEVERITY_ID_name = map[int32]string{
		0:  "BASE_EVENT_SEVERITY_ID_UNKNOWN",
		1:  "BASE_EVENT_SEVERITY_ID_INFORMATIONAL",
		2:  "BASE_EVENT_SEVERITY_ID_LOW",
		3:  "BASE_EVENT_SEVERITY_ID_MEDIUM",
		4:  "BASE_EVENT_SEVERITY_ID_HIGH",
		5:  "BASE_EVENT_SEVERITY_ID_CRITICAL",
		6:  "BASE_EVENT_SEVERITY_ID_FATAL",
		99: "BASE_EVENT_SEVERITY_ID_OTHER",
	}
	BASE_EVENT_SEVERITY_ID_value = map[string]int32{
		"BASE_EVENT_SEVERITY_ID_UNKNOWN":       0,
		"BASE_EVENT_SEVERITY_ID_INFORMATIONAL": 1,
		"BASE_EVENT_SEVERITY_ID_LOW":           2,
		"BASE_EVENT_SEVERITY_ID_MEDIUM":        3,
		"BASE_EVENT_SEVERITY_ID_HIGH":          4,
		"BASE_EVENT_SEVERITY_ID_CRITICAL":      5,
		"BASE_EVENT_SEVERITY_ID_FATAL":         6,
		"BASE_EVENT_SEVERITY_ID_OTHER":         99,
	}
)

func (x BASE_EVENT_SEVERITY_ID) Enum() *BASE_EVENT_SEVERITY_ID {
	p := new(BASE_EVENT_SEVERITY_ID)
	*p = x
	return p
}

func (x BASE_EVENT_SEVERITY_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BASE_EVENT_SEVERITY_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[7].Descriptor()
}

func (BASE_EVENT_SEVERITY_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[7]
}

func (x BASE_EVENT_SEVERITY_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type BASE_EVENT_STATUS_ID int32

const (
	BASE_EVENT_STATUS_ID_BASE_EVENT_STATUS_ID_UNKNOWN BASE_EVENT_STATUS_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	BASE_EVENT_STATUS_ID_BASE_EVENT_STATUS_ID_SUCCESS BASE_EVENT_STATUS_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	BASE_EVENT_STATUS_ID_BASE_EVENT_STATUS_ID_FAILURE BASE_EVENT_STATUS_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	BASE_EVENT_STATUS_ID_BASE_EVENT_STATUS_ID_OTHER   BASE_EVENT_STATUS_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for BASE_EVENT_STATUS_ID.
var (
	BASE_EVENT_STATUS_ID_name = map[int32]string{
		0:  "BASE_EVENT_STATUS_ID_UNKNOWN",
		1:  "BASE_EVENT_STATUS_ID_SUCCESS",
		2:  "BASE_EVENT_STATUS_ID_FAILURE",
		99: "BASE_EVENT_STATUS_ID_OTHER",
	}
	BASE_EVENT_STATUS_ID_value = map[string]int32{
		"BASE_EVENT_STATUS_ID_UNKNOWN": 0,
		"BASE_EVENT_STATUS_ID_SUCCESS": 1,
		"BASE_EVENT_STATUS_ID_FAILURE": 2,
		"BASE_EVENT_STATUS_ID_OTHER":   99,
	}
)

func (x BASE_EVENT_STATUS_ID) Enum() *BASE_EVENT_STATUS_ID {
	p := new(BASE_EVENT_STATUS_ID)
	*p = x
	return p
}

func (x BASE_EVENT_STATUS_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BASE_EVENT_STATUS_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[8].Descriptor()
}

func (BASE_EVENT_STATUS_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes[8]
}

func (x BASE_EVENT_STATUS_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_ocsf_v1_4_0_events_other_enums_enums_proto protoreflect.FileDescriptor

const file_ocsf_v1_4_0_events_other_enums_enums_proto_rawDesc = "" +
	"\n" +
	"*ocsf/v1_4_0/events/other/enums/enums.proto\x12\x1eocsf.v1_4_0.events.other.enums*\xe1\x01\n" +
	"\x14BASE_EVENT_ACTION_ID\x12 \n" +
	"\x1cBASE_EVENT_ACTION_ID_UNKNOWN\x10\x00\x12 \n" +
	"\x1cBASE_EVENT_ACTION_ID_ALLOWED\x10\x01\x12\x1f\n" +
	"\x1bBASE_EVENT_ACTION_ID_DENIED\x10\x02\x12!\n" +
	"\x1dBASE_EVENT_ACTION_ID_OBSERVED\x10\x03\x12!\n" +
	"\x1dBASE_EVENT_ACTION_ID_MODIFIED\x10\x04\x12\x1e\n" +
	"\x1aBASE_EVENT_ACTION_ID_OTHER\x10c*^\n" +
	"\x16BASE_EVENT_ACTIVITY_ID\x12\"\n" +
	"\x1eBASE_EVENT_ACTIVITY_ID_UNKNOWN\x10\x00\x12 \n" +
	"\x1cBASE_EVENT_ACTIVITY_ID_OTHER\x10c*D\n" +
	"\x17BASE_EVENT_CATEGORY_UID\x12)\n" +
	"%BASE_EVENT_CATEGORY_UID_UNCATEGORIZED\x10\x00*;\n" +
	"\x14BASE_EVENT_CLASS_UID\x12#\n" +
	"\x1fBASE_EVENT_CLASS_UID_BASE_EVENT\x10\x00*\xce\x01\n" +
	"\x18BASE_EVENT_CONFIDENCE_ID\x12$\n" +
	" BASE_EVENT_CONFIDENCE_ID_UNKNOWN\x10\x00\x12 \n" +
	"\x1cBASE_EVENT_CONFIDENCE_ID_LOW\x10\x01\x12#\n" +
	"\x1fBASE_EVENT_CONFIDENCE_ID_MEDIUM\x10\x02\x12!\n" +
	"\x1dBASE_EVENT_CONFIDENCE_ID_HIGH\x10\x03\x12\"\n" +
	"\x1eBASE_EVENT_CONFIDENCE_ID_OTHER\x10c*\xae\t\n" +
	"\x19BASE_EVENT_DISPOSITION_ID\x12%\n" +
	"!BASE_EVENT_DISPOSITION_ID_UNKNOWN\x10\x00\x12%\n" +
	"!BASE_EVENT_DISPOSITION_ID_ALLOWED\x10\x01\x12%\n" +
	"!BASE_EVENT_DISPOSITION_ID_BLOCKED\x10\x02\x12)\n" +
	"%BASE_EVENT_DISPOSITION_ID_QUARANTINED\x10\x03\x12&\n" +
	"\"BASE_EVENT_DISPOSITION_ID_ISOLATED\x10\x04\x12%\n" +
	"!BASE_EVENT_DISPOSITION_ID_DELETED\x10\x05\x12%\n" +
	"!BASE_EVENT_DISPOSITION_ID_DROPPED\x10\x06\x12+\n" +
	"'BASE_EVENT_DISPOSITION_ID_CUSTOM_ACTION\x10\a\x12&\n" +
	"\"BASE_EVENT_DISPOSITION_ID_APPROVED\x10\b\x12&\n" +
	"\"BASE_EVENT_DISPOSITION_ID_RESTORED\x10\t\x12(\n" +
	"$BASE_EVENT_DISPOSITION_ID_EXONERATED\x10\n" +
	"\x12'\n" +
	"#BASE_EVENT_DISPOSITION_ID_CORRECTED\x10\v\x121\n" +
	"-BASE_EVENT_DISPOSITION_ID_PARTIALLY_CORRECTED\x10\f\x12)\n" +
	"%BASE_EVENT_DISPOSITION_ID_UNCORRECTED\x10\r\x12%\n" +
	"!BASE_EVENT_DISPOSITION_ID_DELAYED\x10\x0e\x12&\n" +
	"\"BASE_EVENT_DISPOSITION_ID_DETECTED\x10\x0f\x12'\n" +
	"#BASE_EVENT_DISPOSITION_ID_NO_ACTION\x10\x10\x12$\n" +
	" BASE_EVENT_DISPOSITION_ID_LOGGED\x10\x11\x12$\n" +
	" BASE_EVENT_DISPOSITION_ID_TAGGED\x10\x12\x12#\n" +
	"\x1fBASE_EVENT_DISPOSITION_ID_ALERT\x10\x13\x12#\n" +
	"\x1fBASE_EVENT_DISPOSITION_ID_COUNT\x10\x14\x12#\n" +
	"\x1fBASE_EVENT_DISPOSITION_ID_RESET\x10\x15\x12%\n" +
	"!BASE_EVENT_DISPOSITION_ID_CAPTCHA\x10\x16\x12'\n" +
	"#BASE_EVENT_DISPOSITION_ID_CHALLENGE\x10\x17\x12,\n" +
	"(BASE_EVENT_DISPOSITION_ID_ACCESS_REVOKED\x10\x18\x12&\n" +
	"\"BASE_EVENT_DISPOSITION_ID_REJECTED\x10\x19\x12*\n" +
	"&BASE_EVENT_DISPOSITION_ID_UNAUTHORIZED\x10\x1a\x12#\n" +
	"\x1fBASE_EVENT_DISPOSITION_ID_ERROR\x10\x1b\x12#\n" +
	"\x1fBASE_EVENT_DISPOSITION_ID_OTHER\x10c*\xf2\x01\n" +
	"\x18BASE_EVENT_RISK_LEVEL_ID\x12!\n" +
	"\x1dBASE_EVENT_RISK_LEVEL_ID_INFO\x10\x00\x12 \n" +
	"\x1cBASE_EVENT_RISK_LEVEL_ID_LOW\x10\x01\x12#\n" +
	"\x1fBASE_EVENT_RISK_LEVEL_ID_MEDIUM\x10\x02\x12!\n" +
	"\x1dBASE_EVENT_RISK_LEVEL_ID_HIGH\x10\x03\x12%\n" +
	"!BASE_EVENT_RISK_LEVEL_ID_CRITICAL\x10\x04\x12\"\n" +
	"\x1eBASE_EVENT_RISK_LEVEL_ID_OTHER\x10c*\xb3\x02\n" +
	"\x16BASE_EVENT_SEVERITY_ID\x12\"\n" +
	"\x1eBASE_EVENT_SEVERITY_ID_UNKNOWN\x10\x00\x12(\n" +
	"$BASE_EVENT_SEVERITY_ID_INFORMATIONAL\x10\x01\x12\x1e\n" +
	"\x1aBASE_EVENT_SEVERITY_ID_LOW\x10\x02\x12!\n" +
	"\x1dBASE_EVENT_SEVERITY_ID_MEDIUM\x10\x03\x12\x1f\n" +
	"\x1bBASE_EVENT_SEVERITY_ID_HIGH\x10\x04\x12#\n" +
	"\x1fBASE_EVENT_SEVERITY_ID_CRITICAL\x10\x05\x12 \n" +
	"\x1cBASE_EVENT_SEVERITY_ID_FATAL\x10\x06\x12 \n" +
	"\x1cBASE_EVENT_SEVERITY_ID_OTHER\x10c*\x9c\x01\n" +
	"\x14BASE_EVENT_STATUS_ID\x12 \n" +
	"\x1cBASE_EVENT_STATUS_ID_UNKNOWN\x10\x00\x12 \n" +
	"\x1cBASE_EVENT_STATUS_ID_SUCCESS\x10\x01\x12 \n" +
	"\x1cBASE_EVENT_STATUS_ID_FAILURE\x10\x02\x12\x1e\n" +
	"\x1aBASE_EVENT_STATUS_ID_OTHER\x10cB\x8d\x02\n" +
	"\"com.ocsf.v1_4_0.events.other.enumsB\n" +
	"EnumsProtoP\x01ZEgithub.com/valllabh/ocsf-schema-golang/ocsf/v1_4_0/events/other/enums\xa2\x02\x05OVEOE\xaa\x02\x1cOcsf.V140.Events.Other.Enums\xca\x02\x1cOcsf\\V140\\Events\\Other\\Enums\xe2\x02(Ocsf\\V140\\Events\\Other\\Enums\\GPBMetadata\xea\x02 Ocsf::V140::Events::Other::Enumsb\x06proto3"

var file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_ocsf_v1_4_0_events_other_enums_enums_proto_goTypes = []any{
	(BASE_EVENT_ACTION_ID)(0),      // 0: ocsf.v1_4_0.events.other.enums.BASE_EVENT_ACTION_ID
	(BASE_EVENT_ACTIVITY_ID)(0),    // 1: ocsf.v1_4_0.events.other.enums.BASE_EVENT_ACTIVITY_ID
	(BASE_EVENT_CATEGORY_UID)(0),   // 2: ocsf.v1_4_0.events.other.enums.BASE_EVENT_CATEGORY_UID
	(BASE_EVENT_CLASS_UID)(0),      // 3: ocsf.v1_4_0.events.other.enums.BASE_EVENT_CLASS_UID
	(BASE_EVENT_CONFIDENCE_ID)(0),  // 4: ocsf.v1_4_0.events.other.enums.BASE_EVENT_CONFIDENCE_ID
	(BASE_EVENT_DISPOSITION_ID)(0), // 5: ocsf.v1_4_0.events.other.enums.BASE_EVENT_DISPOSITION_ID
	(BASE_EVENT_RISK_LEVEL_ID)(0),  // 6: ocsf.v1_4_0.events.other.enums.BASE_EVENT_RISK_LEVEL_ID
	(BASE_EVENT_SEVERITY_ID)(0),    // 7: ocsf.v1_4_0.events.other.enums.BASE_EVENT_SEVERITY_ID
	(BASE_EVENT_STATUS_ID)(0),      // 8: ocsf.v1_4_0.events.other.enums.BASE_EVENT_STATUS_ID
}
var file_ocsf_v1_4_0_events_other_enums_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ocsf_v1_4_0_events_other_enums_enums_proto_init() }
func file_ocsf_v1_4_0_events_other_enums_enums_proto_init() {
	if File_ocsf_v1_4_0_events_other_enums_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocsf_v1_4_0_events_other_enums_enums_proto_rawDesc), len(file_ocsf_v1_4_0_events_other_enums_enums_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocsf_v1_4_0_events_other_enums_enums_proto_goTypes,
		DependencyIndexes: file_ocsf_v1_4_0_events_other_enums_enums_proto_depIdxs,
		EnumInfos:         file_ocsf_v1_4_0_events_other_enums_enums_proto_enumTypes,
	}.Build()
	File_ocsf_v1_4_0_events_other_enums_enums_proto = out.File
	file_ocsf_v1_4_0_events_other_enums_enums_proto_goTypes = nil
	file_ocsf_v1_4_0_events_other_enums_enums_proto_depIdxs = nil
}
