// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: ocsf/v1_0_0/events/findings/enums/enums.proto

//go:build protoopaque

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FINDINGS_ACTIVITY_ID int32

const (
	FINDINGS_ACTIVITY_ID_FINDINGS_ACTIVITY_ID_UNKNOWN FINDINGS_ACTIVITY_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	FINDINGS_ACTIVITY_ID_FINDINGS_ACTIVITY_ID_CREATE  FINDINGS_ACTIVITY_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	FINDINGS_ACTIVITY_ID_FINDINGS_ACTIVITY_ID_UPDATE  FINDINGS_ACTIVITY_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	FINDINGS_ACTIVITY_ID_FINDINGS_ACTIVITY_ID_OTHER   FINDINGS_ACTIVITY_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for FINDINGS_ACTIVITY_ID.
var (
	FINDINGS_ACTIVITY_ID_name = map[int32]string{
		0:  "FINDINGS_ACTIVITY_ID_UNKNOWN",
		1:  "FINDINGS_ACTIVITY_ID_CREATE",
		2:  "FINDINGS_ACTIVITY_ID_UPDATE",
		99: "FINDINGS_ACTIVITY_ID_OTHER",
	}
	FINDINGS_ACTIVITY_ID_value = map[string]int32{
		"FINDINGS_ACTIVITY_ID_UNKNOWN": 0,
		"FINDINGS_ACTIVITY_ID_CREATE":  1,
		"FINDINGS_ACTIVITY_ID_UPDATE":  2,
		"FINDINGS_ACTIVITY_ID_OTHER":   99,
	}
)

func (x FINDINGS_ACTIVITY_ID) Enum() *FINDINGS_ACTIVITY_ID {
	p := new(FINDINGS_ACTIVITY_ID)
	*p = x
	return p
}

func (x FINDINGS_ACTIVITY_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FINDINGS_ACTIVITY_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[0].Descriptor()
}

func (FINDINGS_ACTIVITY_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[0]
}

func (x FINDINGS_ACTIVITY_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type FINDINGS_CATEGORY_UID int32

const (
	FINDINGS_CATEGORY_UID_FINDINGS_CATEGORY_UID_UNSPECIFIED FINDINGS_CATEGORY_UID = 0 // Type: NON_OCSF_VALUE;
	FINDINGS_CATEGORY_UID_FINDINGS_CATEGORY_UID_FINDINGS    FINDINGS_CATEGORY_UID = 2 // Type: OCSF_VALUE; EnumValue: 2;
)

// Enum value maps for FINDINGS_CATEGORY_UID.
var (
	FINDINGS_CATEGORY_UID_name = map[int32]string{
		0: "FINDINGS_CATEGORY_UID_UNSPECIFIED",
		2: "FINDINGS_CATEGORY_UID_FINDINGS",
	}
	FINDINGS_CATEGORY_UID_value = map[string]int32{
		"FINDINGS_CATEGORY_UID_UNSPECIFIED": 0,
		"FINDINGS_CATEGORY_UID_FINDINGS":    2,
	}
)

func (x FINDINGS_CATEGORY_UID) Enum() *FINDINGS_CATEGORY_UID {
	p := new(FINDINGS_CATEGORY_UID)
	*p = x
	return p
}

func (x FINDINGS_CATEGORY_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FINDINGS_CATEGORY_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[1].Descriptor()
}

func (FINDINGS_CATEGORY_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[1]
}

func (x FINDINGS_CATEGORY_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type FINDINGS_CLASS_UID int32

const (
	FINDINGS_CLASS_UID_FINDINGS_CLASS_UID_UNSPECIFIED FINDINGS_CLASS_UID = 0    // Type: NON_OCSF_VALUE;
	FINDINGS_CLASS_UID_FINDINGS_CLASS_UID_FINDINGS    FINDINGS_CLASS_UID = 2000 // Type: OCSF_VALUE; EnumValue: 2000;
)

// Enum value maps for FINDINGS_CLASS_UID.
var (
	FINDINGS_CLASS_UID_name = map[int32]string{
		0:    "FINDINGS_CLASS_UID_UNSPECIFIED",
		2000: "FINDINGS_CLASS_UID_FINDINGS",
	}
	FINDINGS_CLASS_UID_value = map[string]int32{
		"FINDINGS_CLASS_UID_UNSPECIFIED": 0,
		"FINDINGS_CLASS_UID_FINDINGS":    2000,
	}
)

func (x FINDINGS_CLASS_UID) Enum() *FINDINGS_CLASS_UID {
	p := new(FINDINGS_CLASS_UID)
	*p = x
	return p
}

func (x FINDINGS_CLASS_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FINDINGS_CLASS_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[2].Descriptor()
}

func (FINDINGS_CLASS_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[2]
}

func (x FINDINGS_CLASS_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type FINDINGS_SEVERITY_ID int32

const (
	FINDINGS_SEVERITY_ID_FINDINGS_SEVERITY_ID_UNKNOWN       FINDINGS_SEVERITY_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	FINDINGS_SEVERITY_ID_FINDINGS_SEVERITY_ID_INFORMATIONAL FINDINGS_SEVERITY_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	FINDINGS_SEVERITY_ID_FINDINGS_SEVERITY_ID_LOW           FINDINGS_SEVERITY_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	FINDINGS_SEVERITY_ID_FINDINGS_SEVERITY_ID_MEDIUM        FINDINGS_SEVERITY_ID = 3  // Type: OCSF_VALUE; EnumValue: 3;
	FINDINGS_SEVERITY_ID_FINDINGS_SEVERITY_ID_HIGH          FINDINGS_SEVERITY_ID = 4  // Type: OCSF_VALUE; EnumValue: 4;
	FINDINGS_SEVERITY_ID_FINDINGS_SEVERITY_ID_CRITICAL      FINDINGS_SEVERITY_ID = 5  // Type: OCSF_VALUE; EnumValue: 5;
	FINDINGS_SEVERITY_ID_FINDINGS_SEVERITY_ID_FATAL         FINDINGS_SEVERITY_ID = 6  // Type: OCSF_VALUE; EnumValue: 6;
	FINDINGS_SEVERITY_ID_FINDINGS_SEVERITY_ID_OTHER         FINDINGS_SEVERITY_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for FINDINGS_SEVERITY_ID.
var (
	FINDINGS_SEVERITY_ID_name = map[int32]string{
		0:  "FINDINGS_SEVERITY_ID_UNKNOWN",
		1:  "FINDINGS_SEVERITY_ID_INFORMATIONAL",
		2:  "FINDINGS_SEVERITY_ID_LOW",
		3:  "FINDINGS_SEVERITY_ID_MEDIUM",
		4:  "FINDINGS_SEVERITY_ID_HIGH",
		5:  "FINDINGS_SEVERITY_ID_CRITICAL",
		6:  "FINDINGS_SEVERITY_ID_FATAL",
		99: "FINDINGS_SEVERITY_ID_OTHER",
	}
	FINDINGS_SEVERITY_ID_value = map[string]int32{
		"FINDINGS_SEVERITY_ID_UNKNOWN":       0,
		"FINDINGS_SEVERITY_ID_INFORMATIONAL": 1,
		"FINDINGS_SEVERITY_ID_LOW":           2,
		"FINDINGS_SEVERITY_ID_MEDIUM":        3,
		"FINDINGS_SEVERITY_ID_HIGH":          4,
		"FINDINGS_SEVERITY_ID_CRITICAL":      5,
		"FINDINGS_SEVERITY_ID_FATAL":         6,
		"FINDINGS_SEVERITY_ID_OTHER":         99,
	}
)

func (x FINDINGS_SEVERITY_ID) Enum() *FINDINGS_SEVERITY_ID {
	p := new(FINDINGS_SEVERITY_ID)
	*p = x
	return p
}

func (x FINDINGS_SEVERITY_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FINDINGS_SEVERITY_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[3].Descriptor()
}

func (FINDINGS_SEVERITY_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[3]
}

func (x FINDINGS_SEVERITY_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type FINDINGS_STATUS_ID int32

const (
	FINDINGS_STATUS_ID_FINDINGS_STATUS_ID_UNKNOWN FINDINGS_STATUS_ID = 0  // EnumValue: 0; Type: OCSF_VALUE;
	FINDINGS_STATUS_ID_FINDINGS_STATUS_ID_SUCCESS FINDINGS_STATUS_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	FINDINGS_STATUS_ID_FINDINGS_STATUS_ID_FAILURE FINDINGS_STATUS_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	FINDINGS_STATUS_ID_FINDINGS_STATUS_ID_OTHER   FINDINGS_STATUS_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for FINDINGS_STATUS_ID.
var (
	FINDINGS_STATUS_ID_name = map[int32]string{
		0:  "FINDINGS_STATUS_ID_UNKNOWN",
		1:  "FINDINGS_STATUS_ID_SUCCESS",
		2:  "FINDINGS_STATUS_ID_FAILURE",
		99: "FINDINGS_STATUS_ID_OTHER",
	}
	FINDINGS_STATUS_ID_value = map[string]int32{
		"FINDINGS_STATUS_ID_UNKNOWN": 0,
		"FINDINGS_STATUS_ID_SUCCESS": 1,
		"FINDINGS_STATUS_ID_FAILURE": 2,
		"FINDINGS_STATUS_ID_OTHER":   99,
	}
)

func (x FINDINGS_STATUS_ID) Enum() *FINDINGS_STATUS_ID {
	p := new(FINDINGS_STATUS_ID)
	*p = x
	return p
}

func (x FINDINGS_STATUS_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FINDINGS_STATUS_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[4].Descriptor()
}

func (FINDINGS_STATUS_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[4]
}

func (x FINDINGS_STATUS_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type FINDINGS_TYPE_UID int32

const (
	FINDINGS_TYPE_UID_FINDINGS_TYPE_UID_UNSPECIFIED      FINDINGS_TYPE_UID = 0      // Type: NON_OCSF_VALUE;
	FINDINGS_TYPE_UID_FINDINGS_TYPE_UID_FINDINGS_UNKNOWN FINDINGS_TYPE_UID = 200000 // EnumValue: 200000; Type: OCSF_VALUE;
	FINDINGS_TYPE_UID_FINDINGS_TYPE_UID_FINDINGS_CREATE  FINDINGS_TYPE_UID = 200001 // Type: OCSF_VALUE; EnumValue: 200001;
	FINDINGS_TYPE_UID_FINDINGS_TYPE_UID_FINDINGS_UPDATE  FINDINGS_TYPE_UID = 200002 // Type: OCSF_VALUE; EnumValue: 200002;
	FINDINGS_TYPE_UID_FINDINGS_TYPE_UID_FINDINGS_OTHER   FINDINGS_TYPE_UID = 200099 // Type: OCSF_VALUE; EnumValue: 200099;
)

// Enum value maps for FINDINGS_TYPE_UID.
var (
	FINDINGS_TYPE_UID_name = map[int32]string{
		0:      "FINDINGS_TYPE_UID_UNSPECIFIED",
		200000: "FINDINGS_TYPE_UID_FINDINGS_UNKNOWN",
		200001: "FINDINGS_TYPE_UID_FINDINGS_CREATE",
		200002: "FINDINGS_TYPE_UID_FINDINGS_UPDATE",
		200099: "FINDINGS_TYPE_UID_FINDINGS_OTHER",
	}
	FINDINGS_TYPE_UID_value = map[string]int32{
		"FINDINGS_TYPE_UID_UNSPECIFIED":      0,
		"FINDINGS_TYPE_UID_FINDINGS_UNKNOWN": 200000,
		"FINDINGS_TYPE_UID_FINDINGS_CREATE":  200001,
		"FINDINGS_TYPE_UID_FINDINGS_UPDATE":  200002,
		"FINDINGS_TYPE_UID_FINDINGS_OTHER":   200099,
	}
)

func (x FINDINGS_TYPE_UID) Enum() *FINDINGS_TYPE_UID {
	p := new(FINDINGS_TYPE_UID)
	*p = x
	return p
}

func (x FINDINGS_TYPE_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FINDINGS_TYPE_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[5].Descriptor()
}

func (FINDINGS_TYPE_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[5]
}

func (x FINDINGS_TYPE_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SECURITY_FINDING_ACTIVITY_ID int32

const (
	SECURITY_FINDING_ACTIVITY_ID_SECURITY_FINDING_ACTIVITY_ID_UNKNOWN SECURITY_FINDING_ACTIVITY_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	SECURITY_FINDING_ACTIVITY_ID_SECURITY_FINDING_ACTIVITY_ID_CREATE  SECURITY_FINDING_ACTIVITY_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	SECURITY_FINDING_ACTIVITY_ID_SECURITY_FINDING_ACTIVITY_ID_UPDATE  SECURITY_FINDING_ACTIVITY_ID = 2  // EnumValue: 2; Type: OCSF_VALUE;
	SECURITY_FINDING_ACTIVITY_ID_SECURITY_FINDING_ACTIVITY_ID_OTHER   SECURITY_FINDING_ACTIVITY_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for SECURITY_FINDING_ACTIVITY_ID.
var (
	SECURITY_FINDING_ACTIVITY_ID_name = map[int32]string{
		0:  "SECURITY_FINDING_ACTIVITY_ID_UNKNOWN",
		1:  "SECURITY_FINDING_ACTIVITY_ID_CREATE",
		2:  "SECURITY_FINDING_ACTIVITY_ID_UPDATE",
		99: "SECURITY_FINDING_ACTIVITY_ID_OTHER",
	}
	SECURITY_FINDING_ACTIVITY_ID_value = map[string]int32{
		"SECURITY_FINDING_ACTIVITY_ID_UNKNOWN": 0,
		"SECURITY_FINDING_ACTIVITY_ID_CREATE":  1,
		"SECURITY_FINDING_ACTIVITY_ID_UPDATE":  2,
		"SECURITY_FINDING_ACTIVITY_ID_OTHER":   99,
	}
)

func (x SECURITY_FINDING_ACTIVITY_ID) Enum() *SECURITY_FINDING_ACTIVITY_ID {
	p := new(SECURITY_FINDING_ACTIVITY_ID)
	*p = x
	return p
}

func (x SECURITY_FINDING_ACTIVITY_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SECURITY_FINDING_ACTIVITY_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[6].Descriptor()
}

func (SECURITY_FINDING_ACTIVITY_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[6]
}

func (x SECURITY_FINDING_ACTIVITY_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SECURITY_FINDING_CATEGORY_UID int32

const (
	SECURITY_FINDING_CATEGORY_UID_SECURITY_FINDING_CATEGORY_UID_UNSPECIFIED SECURITY_FINDING_CATEGORY_UID = 0 // Type: NON_OCSF_VALUE;
	SECURITY_FINDING_CATEGORY_UID_SECURITY_FINDING_CATEGORY_UID_FINDINGS    SECURITY_FINDING_CATEGORY_UID = 2 // Type: OCSF_VALUE; EnumValue: 2;
)

// Enum value maps for SECURITY_FINDING_CATEGORY_UID.
var (
	SECURITY_FINDING_CATEGORY_UID_name = map[int32]string{
		0: "SECURITY_FINDING_CATEGORY_UID_UNSPECIFIED",
		2: "SECURITY_FINDING_CATEGORY_UID_FINDINGS",
	}
	SECURITY_FINDING_CATEGORY_UID_value = map[string]int32{
		"SECURITY_FINDING_CATEGORY_UID_UNSPECIFIED": 0,
		"SECURITY_FINDING_CATEGORY_UID_FINDINGS":    2,
	}
)

func (x SECURITY_FINDING_CATEGORY_UID) Enum() *SECURITY_FINDING_CATEGORY_UID {
	p := new(SECURITY_FINDING_CATEGORY_UID)
	*p = x
	return p
}

func (x SECURITY_FINDING_CATEGORY_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SECURITY_FINDING_CATEGORY_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[7].Descriptor()
}

func (SECURITY_FINDING_CATEGORY_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[7]
}

func (x SECURITY_FINDING_CATEGORY_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SECURITY_FINDING_CLASS_UID int32

const (
	SECURITY_FINDING_CLASS_UID_SECURITY_FINDING_CLASS_UID_UNSPECIFIED      SECURITY_FINDING_CLASS_UID = 0    // Type: NON_OCSF_VALUE;
	SECURITY_FINDING_CLASS_UID_SECURITY_FINDING_CLASS_UID_SECURITY_FINDING SECURITY_FINDING_CLASS_UID = 2001 // Type: OCSF_VALUE; EnumValue: 2001;
)

// Enum value maps for SECURITY_FINDING_CLASS_UID.
var (
	SECURITY_FINDING_CLASS_UID_name = map[int32]string{
		0:    "SECURITY_FINDING_CLASS_UID_UNSPECIFIED",
		2001: "SECURITY_FINDING_CLASS_UID_SECURITY_FINDING",
	}
	SECURITY_FINDING_CLASS_UID_value = map[string]int32{
		"SECURITY_FINDING_CLASS_UID_UNSPECIFIED":      0,
		"SECURITY_FINDING_CLASS_UID_SECURITY_FINDING": 2001,
	}
)

func (x SECURITY_FINDING_CLASS_UID) Enum() *SECURITY_FINDING_CLASS_UID {
	p := new(SECURITY_FINDING_CLASS_UID)
	*p = x
	return p
}

func (x SECURITY_FINDING_CLASS_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SECURITY_FINDING_CLASS_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[8].Descriptor()
}

func (SECURITY_FINDING_CLASS_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[8]
}

func (x SECURITY_FINDING_CLASS_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SECURITY_FINDING_CONFIDENCE_ID int32

const (
	SECURITY_FINDING_CONFIDENCE_ID_SECURITY_FINDING_CONFIDENCE_ID_UNKNOWN SECURITY_FINDING_CONFIDENCE_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	SECURITY_FINDING_CONFIDENCE_ID_SECURITY_FINDING_CONFIDENCE_ID_LOW     SECURITY_FINDING_CONFIDENCE_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	SECURITY_FINDING_CONFIDENCE_ID_SECURITY_FINDING_CONFIDENCE_ID_MEDIUM  SECURITY_FINDING_CONFIDENCE_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	SECURITY_FINDING_CONFIDENCE_ID_SECURITY_FINDING_CONFIDENCE_ID_HIGH    SECURITY_FINDING_CONFIDENCE_ID = 3  // Type: OCSF_VALUE; EnumValue: 3;
	SECURITY_FINDING_CONFIDENCE_ID_SECURITY_FINDING_CONFIDENCE_ID_OTHER   SECURITY_FINDING_CONFIDENCE_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for SECURITY_FINDING_CONFIDENCE_ID.
var (
	SECURITY_FINDING_CONFIDENCE_ID_name = map[int32]string{
		0:  "SECURITY_FINDING_CONFIDENCE_ID_UNKNOWN",
		1:  "SECURITY_FINDING_CONFIDENCE_ID_LOW",
		2:  "SECURITY_FINDING_CONFIDENCE_ID_MEDIUM",
		3:  "SECURITY_FINDING_CONFIDENCE_ID_HIGH",
		99: "SECURITY_FINDING_CONFIDENCE_ID_OTHER",
	}
	SECURITY_FINDING_CONFIDENCE_ID_value = map[string]int32{
		"SECURITY_FINDING_CONFIDENCE_ID_UNKNOWN": 0,
		"SECURITY_FINDING_CONFIDENCE_ID_LOW":     1,
		"SECURITY_FINDING_CONFIDENCE_ID_MEDIUM":  2,
		"SECURITY_FINDING_CONFIDENCE_ID_HIGH":    3,
		"SECURITY_FINDING_CONFIDENCE_ID_OTHER":   99,
	}
)

func (x SECURITY_FINDING_CONFIDENCE_ID) Enum() *SECURITY_FINDING_CONFIDENCE_ID {
	p := new(SECURITY_FINDING_CONFIDENCE_ID)
	*p = x
	return p
}

func (x SECURITY_FINDING_CONFIDENCE_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SECURITY_FINDING_CONFIDENCE_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[9].Descriptor()
}

func (SECURITY_FINDING_CONFIDENCE_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[9]
}

func (x SECURITY_FINDING_CONFIDENCE_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SECURITY_FINDING_IMPACT_ID int32

const (
	SECURITY_FINDING_IMPACT_ID_SECURITY_FINDING_IMPACT_ID_UNKNOWN  SECURITY_FINDING_IMPACT_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	SECURITY_FINDING_IMPACT_ID_SECURITY_FINDING_IMPACT_ID_LOW      SECURITY_FINDING_IMPACT_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	SECURITY_FINDING_IMPACT_ID_SECURITY_FINDING_IMPACT_ID_MEDIUM   SECURITY_FINDING_IMPACT_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	SECURITY_FINDING_IMPACT_ID_SECURITY_FINDING_IMPACT_ID_HIGH     SECURITY_FINDING_IMPACT_ID = 3  // Type: OCSF_VALUE; EnumValue: 3;
	SECURITY_FINDING_IMPACT_ID_SECURITY_FINDING_IMPACT_ID_CRITICAL SECURITY_FINDING_IMPACT_ID = 4  // Type: OCSF_VALUE; EnumValue: 4;
	SECURITY_FINDING_IMPACT_ID_SECURITY_FINDING_IMPACT_ID_OTHER    SECURITY_FINDING_IMPACT_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for SECURITY_FINDING_IMPACT_ID.
var (
	SECURITY_FINDING_IMPACT_ID_name = map[int32]string{
		0:  "SECURITY_FINDING_IMPACT_ID_UNKNOWN",
		1:  "SECURITY_FINDING_IMPACT_ID_LOW",
		2:  "SECURITY_FINDING_IMPACT_ID_MEDIUM",
		3:  "SECURITY_FINDING_IMPACT_ID_HIGH",
		4:  "SECURITY_FINDING_IMPACT_ID_CRITICAL",
		99: "SECURITY_FINDING_IMPACT_ID_OTHER",
	}
	SECURITY_FINDING_IMPACT_ID_value = map[string]int32{
		"SECURITY_FINDING_IMPACT_ID_UNKNOWN":  0,
		"SECURITY_FINDING_IMPACT_ID_LOW":      1,
		"SECURITY_FINDING_IMPACT_ID_MEDIUM":   2,
		"SECURITY_FINDING_IMPACT_ID_HIGH":     3,
		"SECURITY_FINDING_IMPACT_ID_CRITICAL": 4,
		"SECURITY_FINDING_IMPACT_ID_OTHER":    99,
	}
)

func (x SECURITY_FINDING_IMPACT_ID) Enum() *SECURITY_FINDING_IMPACT_ID {
	p := new(SECURITY_FINDING_IMPACT_ID)
	*p = x
	return p
}

func (x SECURITY_FINDING_IMPACT_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SECURITY_FINDING_IMPACT_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[10].Descriptor()
}

func (SECURITY_FINDING_IMPACT_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[10]
}

func (x SECURITY_FINDING_IMPACT_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SECURITY_FINDING_RISK_LEVEL_ID int32

const (
	SECURITY_FINDING_RISK_LEVEL_ID_SECURITY_FINDING_RISK_LEVEL_ID_INFO     SECURITY_FINDING_RISK_LEVEL_ID = 0 // Type: OCSF_VALUE; EnumValue: 0;
	SECURITY_FINDING_RISK_LEVEL_ID_SECURITY_FINDING_RISK_LEVEL_ID_LOW      SECURITY_FINDING_RISK_LEVEL_ID = 1 // Type: OCSF_VALUE; EnumValue: 1;
	SECURITY_FINDING_RISK_LEVEL_ID_SECURITY_FINDING_RISK_LEVEL_ID_MEDIUM   SECURITY_FINDING_RISK_LEVEL_ID = 2 // Type: OCSF_VALUE; EnumValue: 2;
	SECURITY_FINDING_RISK_LEVEL_ID_SECURITY_FINDING_RISK_LEVEL_ID_HIGH     SECURITY_FINDING_RISK_LEVEL_ID = 3 // Type: OCSF_VALUE; EnumValue: 3;
	SECURITY_FINDING_RISK_LEVEL_ID_SECURITY_FINDING_RISK_LEVEL_ID_CRITICAL SECURITY_FINDING_RISK_LEVEL_ID = 4 // Type: OCSF_VALUE; EnumValue: 4;
)

// Enum value maps for SECURITY_FINDING_RISK_LEVEL_ID.
var (
	SECURITY_FINDING_RISK_LEVEL_ID_name = map[int32]string{
		0: "SECURITY_FINDING_RISK_LEVEL_ID_INFO",
		1: "SECURITY_FINDING_RISK_LEVEL_ID_LOW",
		2: "SECURITY_FINDING_RISK_LEVEL_ID_MEDIUM",
		3: "SECURITY_FINDING_RISK_LEVEL_ID_HIGH",
		4: "SECURITY_FINDING_RISK_LEVEL_ID_CRITICAL",
	}
	SECURITY_FINDING_RISK_LEVEL_ID_value = map[string]int32{
		"SECURITY_FINDING_RISK_LEVEL_ID_INFO":     0,
		"SECURITY_FINDING_RISK_LEVEL_ID_LOW":      1,
		"SECURITY_FINDING_RISK_LEVEL_ID_MEDIUM":   2,
		"SECURITY_FINDING_RISK_LEVEL_ID_HIGH":     3,
		"SECURITY_FINDING_RISK_LEVEL_ID_CRITICAL": 4,
	}
)

func (x SECURITY_FINDING_RISK_LEVEL_ID) Enum() *SECURITY_FINDING_RISK_LEVEL_ID {
	p := new(SECURITY_FINDING_RISK_LEVEL_ID)
	*p = x
	return p
}

func (x SECURITY_FINDING_RISK_LEVEL_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SECURITY_FINDING_RISK_LEVEL_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[11].Descriptor()
}

func (SECURITY_FINDING_RISK_LEVEL_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[11]
}

func (x SECURITY_FINDING_RISK_LEVEL_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SECURITY_FINDING_SEVERITY_ID int32

const (
	SECURITY_FINDING_SEVERITY_ID_SECURITY_FINDING_SEVERITY_ID_UNKNOWN       SECURITY_FINDING_SEVERITY_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	SECURITY_FINDING_SEVERITY_ID_SECURITY_FINDING_SEVERITY_ID_INFORMATIONAL SECURITY_FINDING_SEVERITY_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	SECURITY_FINDING_SEVERITY_ID_SECURITY_FINDING_SEVERITY_ID_LOW           SECURITY_FINDING_SEVERITY_ID = 2  // EnumValue: 2; Type: OCSF_VALUE;
	SECURITY_FINDING_SEVERITY_ID_SECURITY_FINDING_SEVERITY_ID_MEDIUM        SECURITY_FINDING_SEVERITY_ID = 3  // Type: OCSF_VALUE; EnumValue: 3;
	SECURITY_FINDING_SEVERITY_ID_SECURITY_FINDING_SEVERITY_ID_HIGH          SECURITY_FINDING_SEVERITY_ID = 4  // Type: OCSF_VALUE; EnumValue: 4;
	SECURITY_FINDING_SEVERITY_ID_SECURITY_FINDING_SEVERITY_ID_CRITICAL      SECURITY_FINDING_SEVERITY_ID = 5  // Type: OCSF_VALUE; EnumValue: 5;
	SECURITY_FINDING_SEVERITY_ID_SECURITY_FINDING_SEVERITY_ID_FATAL         SECURITY_FINDING_SEVERITY_ID = 6  // Type: OCSF_VALUE; EnumValue: 6;
	SECURITY_FINDING_SEVERITY_ID_SECURITY_FINDING_SEVERITY_ID_OTHER         SECURITY_FINDING_SEVERITY_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for SECURITY_FINDING_SEVERITY_ID.
var (
	SECURITY_FINDING_SEVERITY_ID_name = map[int32]string{
		0:  "SECURITY_FINDING_SEVERITY_ID_UNKNOWN",
		1:  "SECURITY_FINDING_SEVERITY_ID_INFORMATIONAL",
		2:  "SECURITY_FINDING_SEVERITY_ID_LOW",
		3:  "SECURITY_FINDING_SEVERITY_ID_MEDIUM",
		4:  "SECURITY_FINDING_SEVERITY_ID_HIGH",
		5:  "SECURITY_FINDING_SEVERITY_ID_CRITICAL",
		6:  "SECURITY_FINDING_SEVERITY_ID_FATAL",
		99: "SECURITY_FINDING_SEVERITY_ID_OTHER",
	}
	SECURITY_FINDING_SEVERITY_ID_value = map[string]int32{
		"SECURITY_FINDING_SEVERITY_ID_UNKNOWN":       0,
		"SECURITY_FINDING_SEVERITY_ID_INFORMATIONAL": 1,
		"SECURITY_FINDING_SEVERITY_ID_LOW":           2,
		"SECURITY_FINDING_SEVERITY_ID_MEDIUM":        3,
		"SECURITY_FINDING_SEVERITY_ID_HIGH":          4,
		"SECURITY_FINDING_SEVERITY_ID_CRITICAL":      5,
		"SECURITY_FINDING_SEVERITY_ID_FATAL":         6,
		"SECURITY_FINDING_SEVERITY_ID_OTHER":         99,
	}
)

func (x SECURITY_FINDING_SEVERITY_ID) Enum() *SECURITY_FINDING_SEVERITY_ID {
	p := new(SECURITY_FINDING_SEVERITY_ID)
	*p = x
	return p
}

func (x SECURITY_FINDING_SEVERITY_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SECURITY_FINDING_SEVERITY_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[12].Descriptor()
}

func (SECURITY_FINDING_SEVERITY_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[12]
}

func (x SECURITY_FINDING_SEVERITY_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SECURITY_FINDING_STATE_ID int32

const (
	SECURITY_FINDING_STATE_ID_SECURITY_FINDING_STATE_ID_UNKNOWN     SECURITY_FINDING_STATE_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	SECURITY_FINDING_STATE_ID_SECURITY_FINDING_STATE_ID_NEW         SECURITY_FINDING_STATE_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	SECURITY_FINDING_STATE_ID_SECURITY_FINDING_STATE_ID_IN_PROGRESS SECURITY_FINDING_STATE_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	SECURITY_FINDING_STATE_ID_SECURITY_FINDING_STATE_ID_SUPPRESSED  SECURITY_FINDING_STATE_ID = 3  // Type: OCSF_VALUE; EnumValue: 3;
	SECURITY_FINDING_STATE_ID_SECURITY_FINDING_STATE_ID_RESOLVED    SECURITY_FINDING_STATE_ID = 4  // Type: OCSF_VALUE; EnumValue: 4;
	SECURITY_FINDING_STATE_ID_SECURITY_FINDING_STATE_ID_OTHER       SECURITY_FINDING_STATE_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for SECURITY_FINDING_STATE_ID.
var (
	SECURITY_FINDING_STATE_ID_name = map[int32]string{
		0:  "SECURITY_FINDING_STATE_ID_UNKNOWN",
		1:  "SECURITY_FINDING_STATE_ID_NEW",
		2:  "SECURITY_FINDING_STATE_ID_IN_PROGRESS",
		3:  "SECURITY_FINDING_STATE_ID_SUPPRESSED",
		4:  "SECURITY_FINDING_STATE_ID_RESOLVED",
		99: "SECURITY_FINDING_STATE_ID_OTHER",
	}
	SECURITY_FINDING_STATE_ID_value = map[string]int32{
		"SECURITY_FINDING_STATE_ID_UNKNOWN":     0,
		"SECURITY_FINDING_STATE_ID_NEW":         1,
		"SECURITY_FINDING_STATE_ID_IN_PROGRESS": 2,
		"SECURITY_FINDING_STATE_ID_SUPPRESSED":  3,
		"SECURITY_FINDING_STATE_ID_RESOLVED":    4,
		"SECURITY_FINDING_STATE_ID_OTHER":       99,
	}
)

func (x SECURITY_FINDING_STATE_ID) Enum() *SECURITY_FINDING_STATE_ID {
	p := new(SECURITY_FINDING_STATE_ID)
	*p = x
	return p
}

func (x SECURITY_FINDING_STATE_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SECURITY_FINDING_STATE_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[13].Descriptor()
}

func (SECURITY_FINDING_STATE_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[13]
}

func (x SECURITY_FINDING_STATE_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SECURITY_FINDING_STATUS_ID int32

const (
	SECURITY_FINDING_STATUS_ID_SECURITY_FINDING_STATUS_ID_UNKNOWN SECURITY_FINDING_STATUS_ID = 0  // Type: OCSF_VALUE; EnumValue: 0;
	SECURITY_FINDING_STATUS_ID_SECURITY_FINDING_STATUS_ID_SUCCESS SECURITY_FINDING_STATUS_ID = 1  // Type: OCSF_VALUE; EnumValue: 1;
	SECURITY_FINDING_STATUS_ID_SECURITY_FINDING_STATUS_ID_FAILURE SECURITY_FINDING_STATUS_ID = 2  // Type: OCSF_VALUE; EnumValue: 2;
	SECURITY_FINDING_STATUS_ID_SECURITY_FINDING_STATUS_ID_OTHER   SECURITY_FINDING_STATUS_ID = 99 // Type: OCSF_VALUE; EnumValue: 99;
)

// Enum value maps for SECURITY_FINDING_STATUS_ID.
var (
	SECURITY_FINDING_STATUS_ID_name = map[int32]string{
		0:  "SECURITY_FINDING_STATUS_ID_UNKNOWN",
		1:  "SECURITY_FINDING_STATUS_ID_SUCCESS",
		2:  "SECURITY_FINDING_STATUS_ID_FAILURE",
		99: "SECURITY_FINDING_STATUS_ID_OTHER",
	}
	SECURITY_FINDING_STATUS_ID_value = map[string]int32{
		"SECURITY_FINDING_STATUS_ID_UNKNOWN": 0,
		"SECURITY_FINDING_STATUS_ID_SUCCESS": 1,
		"SECURITY_FINDING_STATUS_ID_FAILURE": 2,
		"SECURITY_FINDING_STATUS_ID_OTHER":   99,
	}
)

func (x SECURITY_FINDING_STATUS_ID) Enum() *SECURITY_FINDING_STATUS_ID {
	p := new(SECURITY_FINDING_STATUS_ID)
	*p = x
	return p
}

func (x SECURITY_FINDING_STATUS_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SECURITY_FINDING_STATUS_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[14].Descriptor()
}

func (SECURITY_FINDING_STATUS_ID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[14]
}

func (x SECURITY_FINDING_STATUS_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SECURITY_FINDING_TYPE_UID int32

const (
	SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_TYPE_UID_UNSPECIFIED              SECURITY_FINDING_TYPE_UID = 0      // Type: NON_OCSF_VALUE;
	SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_UNKNOWN SECURITY_FINDING_TYPE_UID = 200100 // Type: OCSF_VALUE; EnumValue: 200100;
	SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_CREATE  SECURITY_FINDING_TYPE_UID = 200101 // Type: OCSF_VALUE; EnumValue: 200101;
	SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_UPDATE  SECURITY_FINDING_TYPE_UID = 200102 // Type: OCSF_VALUE; EnumValue: 200102;
	SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_OTHER   SECURITY_FINDING_TYPE_UID = 200199 // EnumValue: 200199; Type: OCSF_VALUE;
)

// Enum value maps for SECURITY_FINDING_TYPE_UID.
var (
	SECURITY_FINDING_TYPE_UID_name = map[int32]string{
		0:      "SECURITY_FINDING_TYPE_UID_UNSPECIFIED",
		200100: "SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_UNKNOWN",
		200101: "SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_CREATE",
		200102: "SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_UPDATE",
		200199: "SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_OTHER",
	}
	SECURITY_FINDING_TYPE_UID_value = map[string]int32{
		"SECURITY_FINDING_TYPE_UID_UNSPECIFIED":              0,
		"SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_UNKNOWN": 200100,
		"SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_CREATE":  200101,
		"SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_UPDATE":  200102,
		"SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_OTHER":   200199,
	}
)

func (x SECURITY_FINDING_TYPE_UID) Enum() *SECURITY_FINDING_TYPE_UID {
	p := new(SECURITY_FINDING_TYPE_UID)
	*p = x
	return p
}

func (x SECURITY_FINDING_TYPE_UID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SECURITY_FINDING_TYPE_UID) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[15].Descriptor()
}

func (SECURITY_FINDING_TYPE_UID) Type() protoreflect.EnumType {
	return &file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes[15]
}

func (x SECURITY_FINDING_TYPE_UID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_ocsf_v1_0_0_events_findings_enums_enums_proto protoreflect.FileDescriptor

const file_ocsf_v1_0_0_events_findings_enums_enums_proto_rawDesc = "" +
	"\n" +
	"-ocsf/v1_0_0/events/findings/enums/enums.proto\x12!ocsf.v1_0_0.events.findings.enums*\x9a\x01\n" +
	"\x14FINDINGS_ACTIVITY_ID\x12 \n" +
	"\x1cFINDINGS_ACTIVITY_ID_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bFINDINGS_ACTIVITY_ID_CREATE\x10\x01\x12\x1f\n" +
	"\x1bFINDINGS_ACTIVITY_ID_UPDATE\x10\x02\x12\x1e\n" +
	"\x1aFINDINGS_ACTIVITY_ID_OTHER\x10c*b\n" +
	"\x15FINDINGS_CATEGORY_UID\x12%\n" +
	"!FINDINGS_CATEGORY_UID_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eFINDINGS_CATEGORY_UID_FINDINGS\x10\x02*Z\n" +
	"\x12FINDINGS_CLASS_UID\x12\"\n" +
	"\x1eFINDINGS_CLASS_UID_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1bFINDINGS_CLASS_UID_FINDINGS\x10\xd0\x0f*\xa1\x02\n" +
	"\x14FINDINGS_SEVERITY_ID\x12 \n" +
	"\x1cFINDINGS_SEVERITY_ID_UNKNOWN\x10\x00\x12&\n" +
	"\"FINDINGS_SEVERITY_ID_INFORMATIONAL\x10\x01\x12\x1c\n" +
	"\x18FINDINGS_SEVERITY_ID_LOW\x10\x02\x12\x1f\n" +
	"\x1bFINDINGS_SEVERITY_ID_MEDIUM\x10\x03\x12\x1d\n" +
	"\x19FINDINGS_SEVERITY_ID_HIGH\x10\x04\x12!\n" +
	"\x1dFINDINGS_SEVERITY_ID_CRITICAL\x10\x05\x12\x1e\n" +
	"\x1aFINDINGS_SEVERITY_ID_FATAL\x10\x06\x12\x1e\n" +
	"\x1aFINDINGS_SEVERITY_ID_OTHER\x10c*\x92\x01\n" +
	"\x12FINDINGS_STATUS_ID\x12\x1e\n" +
	"\x1aFINDINGS_STATUS_ID_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aFINDINGS_STATUS_ID_SUCCESS\x10\x01\x12\x1e\n" +
	"\x1aFINDINGS_STATUS_ID_FAILURE\x10\x02\x12\x1c\n" +
	"\x18FINDINGS_STATUS_ID_OTHER\x10c*\xda\x01\n" +
	"\x11FINDINGS_TYPE_UID\x12!\n" +
	"\x1dFINDINGS_TYPE_UID_UNSPECIFIED\x10\x00\x12(\n" +
	"\"FINDINGS_TYPE_UID_FINDINGS_UNKNOWN\x10\xc0\x9a\f\x12'\n" +
	"!FINDINGS_TYPE_UID_FINDINGS_CREATE\x10\xc1\x9a\f\x12'\n" +
	"!FINDINGS_TYPE_UID_FINDINGS_UPDATE\x10\u009a\f\x12&\n" +
	" FINDINGS_TYPE_UID_FINDINGS_OTHER\x10\xa3\x9b\f*\xc2\x01\n" +
	"\x1cSECURITY_FINDING_ACTIVITY_ID\x12(\n" +
	"$SECURITY_FINDING_ACTIVITY_ID_UNKNOWN\x10\x00\x12'\n" +
	"#SECURITY_FINDING_ACTIVITY_ID_CREATE\x10\x01\x12'\n" +
	"#SECURITY_FINDING_ACTIVITY_ID_UPDATE\x10\x02\x12&\n" +
	"\"SECURITY_FINDING_ACTIVITY_ID_OTHER\x10c*z\n" +
	"\x1dSECURITY_FINDING_CATEGORY_UID\x12-\n" +
	")SECURITY_FINDING_CATEGORY_UID_UNSPECIFIED\x10\x00\x12*\n" +
	"&SECURITY_FINDING_CATEGORY_UID_FINDINGS\x10\x02*z\n" +
	"\x1aSECURITY_FINDING_CLASS_UID\x12*\n" +
	"&SECURITY_FINDING_CLASS_UID_UNSPECIFIED\x10\x00\x120\n" +
	"+SECURITY_FINDING_CLASS_UID_SECURITY_FINDING\x10\xd1\x0f*\xf2\x01\n" +
	"\x1eSECURITY_FINDING_CONFIDENCE_ID\x12*\n" +
	"&SECURITY_FINDING_CONFIDENCE_ID_UNKNOWN\x10\x00\x12&\n" +
	"\"SECURITY_FINDING_CONFIDENCE_ID_LOW\x10\x01\x12)\n" +
	"%SECURITY_FINDING_CONFIDENCE_ID_MEDIUM\x10\x02\x12'\n" +
	"#SECURITY_FINDING_CONFIDENCE_ID_HIGH\x10\x03\x12(\n" +
	"$SECURITY_FINDING_CONFIDENCE_ID_OTHER\x10c*\x83\x02\n" +
	"\x1aSECURITY_FINDING_IMPACT_ID\x12&\n" +
	"\"SECURITY_FINDING_IMPACT_ID_UNKNOWN\x10\x00\x12\"\n" +
	"\x1eSECURITY_FINDING_IMPACT_ID_LOW\x10\x01\x12%\n" +
	"!SECURITY_FINDING_IMPACT_ID_MEDIUM\x10\x02\x12#\n" +
	"\x1fSECURITY_FINDING_IMPACT_ID_HIGH\x10\x03\x12'\n" +
	"#SECURITY_FINDING_IMPACT_ID_CRITICAL\x10\x04\x12$\n" +
	" SECURITY_FINDING_IMPACT_ID_OTHER\x10c*\xf2\x01\n" +
	"\x1eSECURITY_FINDING_RISK_LEVEL_ID\x12'\n" +
	"#SECURITY_FINDING_RISK_LEVEL_ID_INFO\x10\x00\x12&\n" +
	"\"SECURITY_FINDING_RISK_LEVEL_ID_LOW\x10\x01\x12)\n" +
	"%SECURITY_FINDING_RISK_LEVEL_ID_MEDIUM\x10\x02\x12'\n" +
	"#SECURITY_FINDING_RISK_LEVEL_ID_HIGH\x10\x03\x12+\n" +
	"'SECURITY_FINDING_RISK_LEVEL_ID_CRITICAL\x10\x04*\xe9\x02\n" +
	"\x1cSECURITY_FINDING_SEVERITY_ID\x12(\n" +
	"$SECURITY_FINDING_SEVERITY_ID_UNKNOWN\x10\x00\x12.\n" +
	"*SECURITY_FINDING_SEVERITY_ID_INFORMATIONAL\x10\x01\x12$\n" +
	" SECURITY_FINDING_SEVERITY_ID_LOW\x10\x02\x12'\n" +
	"#SECURITY_FINDING_SEVERITY_ID_MEDIUM\x10\x03\x12%\n" +
	"!SECURITY_FINDING_SEVERITY_ID_HIGH\x10\x04\x12)\n" +
	"%SECURITY_FINDING_SEVERITY_ID_CRITICAL\x10\x05\x12&\n" +
	"\"SECURITY_FINDING_SEVERITY_ID_FATAL\x10\x06\x12&\n" +
	"\"SECURITY_FINDING_SEVERITY_ID_OTHER\x10c*\x87\x02\n" +
	"\x19SECURITY_FINDING_STATE_ID\x12%\n" +
	"!SECURITY_FINDING_STATE_ID_UNKNOWN\x10\x00\x12!\n" +
	"\x1dSECURITY_FINDING_STATE_ID_NEW\x10\x01\x12)\n" +
	"%SECURITY_FINDING_STATE_ID_IN_PROGRESS\x10\x02\x12(\n" +
	"$SECURITY_FINDING_STATE_ID_SUPPRESSED\x10\x03\x12&\n" +
	"\"SECURITY_FINDING_STATE_ID_RESOLVED\x10\x04\x12#\n" +
	"\x1fSECURITY_FINDING_STATE_ID_OTHER\x10c*\xba\x01\n" +
	"\x1aSECURITY_FINDING_STATUS_ID\x12&\n" +
	"\"SECURITY_FINDING_STATUS_ID_UNKNOWN\x10\x00\x12&\n" +
	"\"SECURITY_FINDING_STATUS_ID_SUCCESS\x10\x01\x12&\n" +
	"\"SECURITY_FINDING_STATUS_ID_FAILURE\x10\x02\x12$\n" +
	" SECURITY_FINDING_STATUS_ID_OTHER\x10c*\xaa\x02\n" +
	"\x19SECURITY_FINDING_TYPE_UID\x12)\n" +
	"%SECURITY_FINDING_TYPE_UID_UNSPECIFIED\x10\x00\x128\n" +
	"2SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_UNKNOWN\x10\xa4\x9b\f\x127\n" +
	"1SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_CREATE\x10\xa5\x9b\f\x127\n" +
	"1SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_UPDATE\x10\xa6\x9b\f\x126\n" +
	"0SECURITY_FINDING_TYPE_UID_SECURITY_FINDING_OTHER\x10\x87\x9c\fB\x9f\x02\n" +
	"%com.ocsf.v1_0_0.events.findings.enumsB\n" +
	"EnumsProtoP\x01ZHgithub.com/valllabh/ocsf-schema-golang/ocsf/v1_0_0/events/findings/enums\xa2\x02\x05OVEFE\xaa\x02\x1fOcsf.V100.Events.Findings.Enums\xca\x02\x1fOcsf\\V100\\Events\\Findings\\Enums\xe2\x02+Ocsf\\V100\\Events\\Findings\\Enums\\GPBMetadata\xea\x02#Ocsf::V100::Events::Findings::Enumsb\x06proto3"

var file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 16)
var file_ocsf_v1_0_0_events_findings_enums_enums_proto_goTypes = []any{
	(FINDINGS_ACTIVITY_ID)(0),           // 0: ocsf.v1_0_0.events.findings.enums.FINDINGS_ACTIVITY_ID
	(FINDINGS_CATEGORY_UID)(0),          // 1: ocsf.v1_0_0.events.findings.enums.FINDINGS_CATEGORY_UID
	(FINDINGS_CLASS_UID)(0),             // 2: ocsf.v1_0_0.events.findings.enums.FINDINGS_CLASS_UID
	(FINDINGS_SEVERITY_ID)(0),           // 3: ocsf.v1_0_0.events.findings.enums.FINDINGS_SEVERITY_ID
	(FINDINGS_STATUS_ID)(0),             // 4: ocsf.v1_0_0.events.findings.enums.FINDINGS_STATUS_ID
	(FINDINGS_TYPE_UID)(0),              // 5: ocsf.v1_0_0.events.findings.enums.FINDINGS_TYPE_UID
	(SECURITY_FINDING_ACTIVITY_ID)(0),   // 6: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_ACTIVITY_ID
	(SECURITY_FINDING_CATEGORY_UID)(0),  // 7: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_CATEGORY_UID
	(SECURITY_FINDING_CLASS_UID)(0),     // 8: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_CLASS_UID
	(SECURITY_FINDING_CONFIDENCE_ID)(0), // 9: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_CONFIDENCE_ID
	(SECURITY_FINDING_IMPACT_ID)(0),     // 10: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_IMPACT_ID
	(SECURITY_FINDING_RISK_LEVEL_ID)(0), // 11: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_RISK_LEVEL_ID
	(SECURITY_FINDING_SEVERITY_ID)(0),   // 12: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_SEVERITY_ID
	(SECURITY_FINDING_STATE_ID)(0),      // 13: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_STATE_ID
	(SECURITY_FINDING_STATUS_ID)(0),     // 14: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_STATUS_ID
	(SECURITY_FINDING_TYPE_UID)(0),      // 15: ocsf.v1_0_0.events.findings.enums.SECURITY_FINDING_TYPE_UID
}
var file_ocsf_v1_0_0_events_findings_enums_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ocsf_v1_0_0_events_findings_enums_enums_proto_init() }
func file_ocsf_v1_0_0_events_findings_enums_enums_proto_init() {
	if File_ocsf_v1_0_0_events_findings_enums_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocsf_v1_0_0_events_findings_enums_enums_proto_rawDesc), len(file_ocsf_v1_0_0_events_findings_enums_enums_proto_rawDesc)),
			NumEnums:      16,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocsf_v1_0_0_events_findings_enums_enums_proto_goTypes,
		DependencyIndexes: file_ocsf_v1_0_0_events_findings_enums_enums_proto_depIdxs,
		EnumInfos:         file_ocsf_v1_0_0_events_findings_enums_enums_proto_enumTypes,
	}.Build()
	File_ocsf_v1_0_0_events_findings_enums_enums_proto = out.File
	file_ocsf_v1_0_0_events_findings_enums_enums_proto_goTypes = nil
	file_ocsf_v1_0_0_events_findings_enums_enums_proto_depIdxs = nil
}
